### ISSUE TITLE
setup.py

### ISSUE THREAD

**Issue by necrose99** [Veil-Framework/Veil#10]
**setup.py , setup.cfg ** **py-distutils is more distro agnostic** , so it might be best to add them time permitting , thus veil evasion , catapult etc, can be put to correct folders etc.  recompiled if libraries update etc. 
as well weather its Debian related , RPM related Gentoo related , arch related, bsd, 
it should package , as well could use pip install for bleeding edge,  also might make testing and maintenance easier, as well as a common deploy.... 
**basic modules setup and dependencies.  ie py-distutils**.  for future release would also make ease plus if it borks theirs a log to go through per module.  as well its easier to package more frequently on many distributions including kahli 

https://github.com/necrose99/necromancy-overlay/blob/master/net-analyzer/veil-evasion/veil-evasion-2.21.1.1.ebuild this uses , Gentoo's python installer functions ,  however  setup.py etc missing. 
writing in the distdir to /var..... build... sandbox , then getting to put into /usr/bin/? or basic defacto path is a slight mess, can wrap the deb file to unpack to correct dirs however can be a bit of a mess, esp due to library updates.  also a pain with the security sandbox for prep of packages, however better to comply with Security policies... 

**CISSP/CCNA CCNA Security** , Passed Security+  been a bit busy. 
however in that repo is a set of script templates for a **secure-nuke**, repo'visn x32 or x64 (testing)  despite being geared for Gentoo  or related (@Sabayon, Spike-pentesting Google chrome-os, @Pentoo) , IE user wine... they should be rather universal using **Wine**/**Winetricks**/**wget** and a .veil-wine-x??  wouldn't want to break user's real main wine...   anyhow feel free to abscond with them, if you like. https://github.com/necrose99/necromancy-overlay/app-emulation/veil-wine/
these should , add many of the packages and a few other useful's to a instance of wine
and if needed having a self-destruction script could be useful to clean up sensitive client pen-test data  post report time ..
anyhow back to the fun 8 domains of CISSP...  
hopefully I will find time to fix the wine scripts I have some time.

**Comment by ChrisTruncer** [comment]
Thanks for the info.  For now, I'm using this to track active bugs, so I will close this topic, but not lock it so we can look into it and talk about this.

Thanks!

**Comment by necrose99** [comment]
gentoo Ebuilds , can do debian_unpack,rpm etc  , no problem just frowned on when possible ,by the Gentoo Q/A devs . just for now as well laptop gpu fan decided to crap out.  hopefully , Once I test for CISSP , and pass the SOB my free time will actuality Improve.  as will ability to work on graduate classes again. 

hopefully in time  I can on a Forked Branch get setup.py and cfg to work per veil item reliably work 
pass note to user's " you'll need to edit xyz???.conf or file/s "  call it done. 
however setup.py will set up each veil-item , then do the usual. symlink /usr/bin/  veil-sub units ie catapult setup.py will just place in /usr/bin/veil/catapult or something , sym to /usr/bin 
push the fork back with branch , so as not to disturb things currently working , however once passes muster can be used. 

fix my bash scripts to run reliably , perhaps python-ize it ,  if disto = debian/Kahli  do A 
else A_2 ie wine-tricks and wget into ...  ./veil-wine , or some method that any-other disto can patch the functions , if not , then wget and wine tricks works the majority of the time. 
one can script out whole wine builds for prefix's for a specific windows game ,
