### ISSUE TITLE
Error Unable to create output file

### ISSUE THREAD

**Issue by groundzero7** [Veil-Framework/Veil#101]
## OS Used - all info (architecture, linux flavor, etc)
Kali Linux x86_64 GNU/Linux

## How did you install Veil? (Apt, Clone from Github, etc.)
git clone from Github

## Did you run the setup script?
yes

## Pastebin link to error you are encountering (include console actions you took prior to error)

[!] ERROR: Unable to create output file.
## Expected behavior
To create the compiled file

## Any additional info you want to tell me
Thank You!

**Comment by ChrisTruncer** [comment]
You did not give me the information I need. I have no way to recreate this based on the information you provided

**Comment by groundzero7** [comment]
I was using go/meterpreter/reverse_https and set Processors to 1 and Sleep to 5.

**Comment by ChrisTruncer** [comment]
With that info, I was able to re-create it. I just pushed a fix for this. Thanks for letting me know!
