### ISSUE TITLE
./Veil.py gives errors

### ISSUE THREAD

**Issue by DatOpb** [Veil-Framework/Veil#102]
## Veil version
3.0

## OS Used - all info (architecture, linux flavor, etc)

kali 2017.1 
## How did you install Veil? (Apt, Clone from Github, etc.)

git clone
## Did you run the setup script?

yes
## Pastebin link to error you are encountering (include console actions you took prior to error)

https://pastebin.com/sPhb9NT4
## Any additional info you want to tell me
installed this twice on 2 new images after updating aswell giving the same error

**Comment by usama7628674** [comment]
I ran veil using the command python3 Veil.py and it ran successfully.I selected use command and it showed me 2 tools one is Evasion and the other one is Ordnance.When I select any one of the tool it 
goes back to the main menu screen.Please tell me how to solve this issue.Images are following

![screenshot from 2017-08-13 07-37-25](https://user-images.githubusercontent.com/29252277/29245654-899dbaec-7ffa-11e7-8058-010ea1dfb762.png)


![screenshot from 2017-08-13 07-37-56](https://user-images.githubusercontent.com/29252277/29245655-911be60e-7ffa-11e7-99f6-63b3e2eea83b.png)



![screenshot from 2017-08-13 07-38-24](https://user-images.githubusercontent.com/29252277/29245656-98bb6c90-7ffa-11e7-8d57-d442e0f30ee8.png)

**Comment by ChrisTruncer** [comment]
3.0 also is not the latest version. Please use the latest version and then retry if you have an issue.
