### ISSUE TITLE
Veil Evasion Error 100 Failed to Install Wine

### ISSUE THREAD

**Issue by Adarsh777** [Veil-Framework/Veil#104]
## Veil version
Version 3

## OS Used - all info (architecture, linux flavor, etc)
Kali Linux 2017

## How did you install Veil? (Apt, Clone from Github, etc.)
git clone

## Did you run the setup script?
yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
![error](https://user-images.githubusercontent.com/20425116/29315372-9aa3c768-81e0-11e7-981d-d5d6a4d3f8eb.png)

## Any additional info you want to tell me
When i try to install it gives me error attached above. i.e Failed to install Wine Exit code 100.
Please help me.

**Comment by usama7628674** [comment]
@Adarsh777.          
Open resource monitor and look for service packagekit and end task it.After that try install it again.

**Comment by Adarsh777** [comment]
After Ending packagekit service then getting this error.
![erro 2](https://user-images.githubusercontent.com/20425116/29318333-3193ab28-81ed-11e7-8d26-d0cc5c4e4b42.png)

**Comment by ChrisTruncer** [comment]
apt is running at the same time you are trying to setup Veil. Please look at the error messages, because it says exactly that.

**Comment by laeverne101** [comment]
Hello Chris, I couldn't help but notice you said apt is running at the same time you are trying to setup veil, it's the installation of veil that prompted that apt task in the first place so how do I prevent apt from running concurrently. I'm new to all these and I've been trying to install veil for days now and I always end up with the same error. Please help

**Comment by laeverne101** [comment]
My bad I didn't look at the first image properly, my issue doesn't lie in the first image. It is the same as the second one, sorry for that

**Comment by Alireza77r** [comment]
Im 4 setup this version,but just error 100
