### ISSUE TITLE
PowerShell UTCCHECK Logic Error

### ISSUE THREAD

**Issue by assistedjay** [Veil-Framework/Veil#105]
## Veil version
3.1.3

## OS Used - all info (architecture, linux flavor, etc)
Linux Kali 4.9.0 - 64 bit

## How did you install Veil? (Apt, Clone from Github, etc.)
Clone from GitHub

## Did you run the setup script?
Yes

## Expected behavior
Tested on modules:
powershell/meterpreter/rev_tcp.py
powershell/meterpreter/rev_https.py

Setting the UTCCHECK flag to TRUE should "check that system isn't using UTC time zone." 

Decoding the output provides the following:

--SNIP--
$ItQgXdVuiev = [System.TimeZone]::CurrentTimeZone.StandardName
$Jvoreh = [System.TimeZone]::CurrentTimeZone.DaylightName
if ($ItQgXdVuiev -eq "Coordinated Universal Time" -or $Jvoreh -eq "Coordinated Universal Time") {
try{$s = New-Object System.Net.Sockets.Socket ([System.Net.Sockets.AddressFamily]::InterNetwork, [System.Net.Sockets.SocketType]::Stream, [System.Net.Sockets.ProtocolType]::Tcp)
--SNIP--

The use of "-eq" appears to be validating the machine is running UTC, instead of validating it is not. My payload worked as intended changing the "-eq" to "-ne" for a machine in EST. 

## Any additional info you want to tell me

I only verified the two powershell modules mentioned. I did not check logic for anything else.

**Comment by ChrisTruncer** [comment]
Thanks for reporting this, checking into it.

**Comment by ChrisTruncer** [comment]
merged this in, thanks for reporting it!
