### ISSUE TITLE
Options not working

### ISSUE THREAD

**Issue by vendforce** [Veil-Framework/Veil#106]
## Did you run the setup script? yes

when I run python Veil.py I get the option screen and I select use and there is two options 
1) Evasion
2) Ordnance

when I try to choose either 1,2 it just goes back to main screen no errors , nothing it just returns to main menu 

I've set the config.py with the right paths and reinstalled using setup.py -c and still the same

**Comment by usama7628674** [comment]
It happened to me also a couple of weeks ago but it's very simple and I figured it out myself.Use the following commands to fix it

just type _use_ and it will show you 2 tools Evasion and Ordnance to use them just write

_use Evasion_ or _use Ordnance_ and it will jump to another page.Just use right commands

**Comment by vendforce** [comment]
thanks usama7628674 

I tried using the menu options i.e typing 1 then typing Evasion I never thought  to type 'use Evasion'

thanks again for your response

**Comment by chezis45** [comment]
Thank you so much!

**Comment by TheCyberMonster** [comment]
options are not selecting and the numbering for the options is also not displayed (showing [i] insted of options numbering) 
![Screenshot from 2019-07-14 10-58-17](https://user-images.githubusercontent.com/40531762/61179760-105d5c00-a627-11e9-844c-027c30ee2bbe.png)
When i try to select even in the main menu as 1 or 2 it redirects to the main menu again
