### ISSUE TITLE
19/36 antiviruses detect it as a trojan from nodistribute :(

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [Veil-Framework/Veil#107]
## Veil version
Latest

## OS Used - all info (architecture, linux flavor, etc)
Kali rolling

## How did you install Veil? (Apt, Clone from Github, etc.)
clone from github

## Did you run the setup script?
yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
http://nodistribute.com/result/N4xvFzc9B3ymQgMjutbEedo

## Expected behavior
it should be clean

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
This says please don't submit online.

:/

Please use non-defaults.

**Comment by ThatNerdyPikachu** [comment]
@ChrisTruncer what do u mean by non defaults? also, this doesnt submit anything, dont worry

**Comment by ChrisTruncer** [comment]
Again, you aren't supposed to submit anything to ANY online scanner.... :/

**Comment by ThatNerdyPikachu** [comment]
@ChrisTruncer k, sorry :(
