### ISSUE TITLE
cant install veil framework

### ISSUE THREAD

**Issue by ahmedmunir** [Veil-Framework/Veil#108]
## Veil version
3.0

## OS Used - all info (architecture, linux flavor, etc)
kali linux 2017 - 64bit OS

## How did you install Veil? (Apt, Clone from Github, etc.)
clone from github

## Did you run the setup script?
yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
it stuck at this stage for along time and nothing changed 
[*] Adding x86 architecture to x86_64 system for Wine
https://pastebin.com/gHfEcaGZ

## Expected behavior
it supposed to begin to install programs and packages like python but no thing changed for a long time

## Any additional info you want to tell me
i updated & upgraded my kali and here is my repository links
deb http://http.kali.org/kali kali-rolling main contrib non-free
deb-src http://http.kali.org/kali kali main non-free contrib

deb http://old.kali.org/kali sana main non-free contrib

deb http://old.kali.org/kali moto main non-free contrib

## Security updates
##deb http://security.kali.org/kali-security kali/updates main contrib non-free

**Comment by ahmedmunir** [comment]
by the way 
i use kali linux on Virtual box not as main machine

**Comment by ChrisTruncer** [comment]
This is a problem with your VM. Please fix it or try a clean Kali VM

**Comment by ChrisTruncer** [comment]
A clean VM will work
