### ISSUE TITLE
Meterpreter doesn't give complete list of options

### ISSUE THREAD

**Issue by derek7467** [Veil-Framework/Veil#110]
## Veil version
Veil 3

## OS Used - all info (architecture, linux flavor, etc)
Kali 64

## How did you install Veil? (Apt, Clone from Github, etc.)
Clone

## Did you run the setup script?
Yea

## Pastebin link to error you are encountering (include console actions you took prior to error)
I'm attempting to run this payload (python/meter prefer/reverse_tcp) remotely and here's what happens.  When I click the exe remotely I get a session but most of the meterpreter options are not listed like shell, hashdump, webcam stuff...Etc. When I run the same exe but on the LAN I get all the meter prefer options no problem. What gives?  Why does this work on the LAN but not fully over the WAN?

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
I can't speak to why that's happening, but unfortunately it isn't a Veil issue. If you're receiving your callback, then Veil did what it is supposed to do. It in no way impacts the loading of functionality within Meterpreter.

**Comment by derek7467** [comment]
I agree with you after more thought. The wan computer was connected to a Comcast wifi so I think it's blocking some of the traffic. Going to try a true wan home router. Thanks.
