### ISSUE TITLE
setup.sh awk FS

### ISSUE THREAD

**Issue by RobQ** [Veil-Framework/Veil#111]
## Veil version
3.1.4

## OS Used - all info (architecture, linux flavor, etc)
CentOS 7

## How did you install Veil? (Apt, Clone from Github, etc.)
git clone

## Did you run the setup script?
./setup.sh -c

## Pastebin link to error you are encountering (include console actions you took prior to error)
 [ERROR] Unable to determine OS information. Exiting...

The field separator on awk calls should be ["=]+ to handle quoted and unquoted values in /etc/os-release.
$ egrep '^ID=' /tmp/os-release
ID="centos"
ID=ubuntu
$ awk -F '["=]+' '/^ID=/ {print $2}' /tmp/os-release
centos
ubuntu

Likewise for VERSION_ID.

Still dies later (after yum install epel-release dng) due to wine differences.  Is CentOS a known dead end?

**Comment by ChrisTruncer** [comment]
I personally don't support CentOS, although its support has been added by members of the community via pull requests. If you want to patch it and submit a pull request, please feel free (assuming it maintains existing support and doesn't break any other distros).

**Comment by ChrisTruncer** [comment]
Closing due to not hearing back.
