### ISSUE TITLE
Issue with PyCrypto

### ISSUE THREAD

**Issue by By3xec** [Veil-Framework/Veil#114]
## Veil version
Veil 3.0

## OS Used - all info (architecture, linux flavor, etc)
Debian 9 but I have the same issue with Kali-rolling

## How did you install Veil? (Apt, Clone from Github, etc.)
Clone from Github

## Did you run the setup script?
I ran It but I can't install PyCrypto

## Pastebin link to error you are encountering (include console actions you took prior to error)
When I run : Python3 Veil.py
https://pastebin.com/YjrzucX8

When I run the setup (PyCrypto part)
https://pastebin.com/9TsYuNzg

## Any additional info you want to tell me

I tried to install PyCryo manualy with the setup.py and with the exec file wich is here "Veil/config" but I always have the same issue.

**Comment by ChrisTruncer** [comment]
I just tested this on Debian and was able to install fine. Please run ./setup.sh -c from the setup folder.

**Comment by By3xec** [comment]
I tried but the error still there :
https://pastebin.com/sSxuWMpa
(It's the pastebin from the begining of the install this time)
ps : I made an upgrade to Kali linux
pps : I had this trouble with 2 others computers

**Comment by ChrisTruncer** [comment]
I just installed this on a clean Debian 9 and clean Kali (latest version) VM, and both installed fine. I'm inclined to think that it is an issue with your system/VMs

**Comment by By3xec** [comment]
Hum ok.
Maybe It's a system issue. But I tried It from an OVH VPS, and 2 Kali laptop (they are not virtualized). I have the same error but not same system.


Thank you for your help.
I'll try some others things to solve the issue.

(I googled this issue and It seems I'm not the only one which had this trouble)

**Comment by ChrisTruncer** [comment]
This is he first I have heard if anyone having this issue. If you can give me a way to recreate the issue, I would be more than happy to look into it.

**Comment by By3xec** [comment]
Maybe the second : 
https://github.com/Veil-Framework/Veil/issues/13

I tried to run "pip3 install pycrypto" (You told him to do that)
and I'have this result : 
https://pastebin.com/8LNp5fRr

I'll try on a clean Kali install.
But I already tried on a clean Debian (I reset my VPS)


PS : for information, I saw that : https://github.com/dlitz/pycrypto/issues/238

**Comment by By3xec** [comment]
I successfuly install PyCrypto. 
There was differents Python versions on the system. I remove them all and just reinstall Python3

Thank you for your help.

**Comment by sjosephrw** [comment]
Try this
apt-get install python3-crypto
