### ISSUE TITLE
Install.sh continues on apt-get failure

### ISSUE THREAD

**Issue by vladionescu** [Veil-Framework/Veil#12]
When running `Install.sh -c` while another process has the apt lock (long-running `apt-get upgrade` in the background) the script notes a failure but does not exit, printing further errors as it goes then finally exiting with `0`, indicating success.

If this is intended behavior, please tell me and ignore :)

![](http://i.imgur.com/CSP9iLY.png)

**Comment by ChrisTruncer** [comment]
Hey Vlad :)

I am undecided on the proper way to detect this.  Based off of some quick research, it looks like I could probably use aptdcon to detect the current usage of apt, but that would require some testing on my end to make sure the setup package works perfect in that case.  I am unfortunately going to be traveling the the next little bit and won't have the easiest way to download a new ISO and look into this.  So for now I am going to leave this responsibility for the user to detect and make sure that they aren't running apt simultaneously somewhere else.

With that said, in the future I will look into this and try to figure out the best way to handle this situation.  Thanks for reporting it.

**Comment by vladionescu** [comment]
Hey Chris :)

That's fair. If you accept pull requests, I might be able to help sometime
soon.

**Comment by ChrisTruncer** [comment]
Absolutely on the pull requests :)


-----------------------------------------------------------------------------------------
Christopher Truncer
@christruncer

On May 11, 2016 at 10:19:48 PM, Vlad Ionescu (notifications@github.com) wrote:

Hey Chris :)

That's fair. If you accept pull requests, I might be able to help sometime
soon.

**Comment by vladionescu** [comment]
There is an active PR to help others who run into this #13
