### ISSUE TITLE
Setup behind proxy

### ISSUE THREAD

**Issue by jonas2k** [Veil-Framework/Veil#123]
Hi Chris,

enhancement: I just set up Veil on another Kali box and since I'm behind a proxy in a corporate environment, I got a hard time to download all dependencies, especially the python modules via wine and python.exe.

https://github.com/Veil-Framework/Veil/blob/327d433fd4fbe116830ece5338e5a168974fcaa4/setup/setup.sh#L394-L396

Just wanted to let you know, that I had to add "--proxy=[HOST]:[PORT]" to the pip commands to successfully download everything. Maybe it's possible to adapt the setup script accordingly. Keep up the good work!

Regards,

Jonas

**Comment by ChrisTruncer** [comment]
Thanks for the info. I think it would add a lot of complexity to the setup script if people needed extra parameters, etc. for the setup script, I really appreciate you making this issue. With you providing the answer, if anyone searches for this, they will know how to fix it.

Thanks for providing that info!
