### ISSUE TITLE
Run ./Veil.py fails due ImportError: No module called 'Crypto' 

### ISSUE THREAD

**Issue by cunhajcesar** [Veil-Framework/Veil#125]
## Veil version
Veil 3.0

## OS Used - all info (architecture, linux flavor, etc)
Kali Linux 2017.2
Kali Linux 2017.1
Kali Linux 2016.2
Kali Linux 2016.1
Using clean install on standalone machine
Using clean install on VirtualBox

Issue occurs in all listed above 

## How did you install Veil? (Apt, Clone from Github, etc.)

Clone from Github

## Did you run the setup script?

cd /opt
git clone https://github.com/Veil-Framework/Veil.git
cd /Veil
cd /setup
./setup.sh
Next Next Next Finish....
![2017-10-03 3](https://user-images.githubusercontent.com/4603350/31168402-94115520-a8cb-11e7-8f80-44e2d2d52e0a.png)

## Any additional info you want to tell me

All done in fresh install Kali without run any update or upgrade

**Comment by cunhajcesar** [comment]
I solved this issue bye run 'apt install python3-crypto'

Thanks

**Comment by tingoose** [comment]
Was searching on how to slove this for the past 3 hours, finally worked. Thanks @cunhajcesar .

**Comment by cunhajcesar** [comment]
My pleasure.
I'm glad to help you.


Em 4 de out de 2017 7:46 AM, "tingoose" <notifications@github.com> escreveu:

**Comment by ChrisTruncer** [comment]
Fixed in setup script too
