### ISSUE TITLE
Can't Install Veil  3.0

### ISSUE THREAD

**Issue by ghanteyyy** [Veil-Framework/Veil#127]
## Veil version
    3.0

## OS Used - all info (architecture, Linux flavor, etc)
Kali Linux 2017.2

## How did you install Veil? (Apt, Clone from Github, etc.)
Clone from Github

## Did you run the setup script?
Yes, Multiple times I tried but the same result == Failed to install dependencies... Exit code: 100

## Pastebin link to error you are encountering (include console actions you took prior to error)

There was issues installing the following:
Failed to install dependencies... Exit code: 100

## Expected behavior
The installation goes to the end but says failed to install dependencies.... Exit code:100

## Any additional info you want to tell me

I have tried more than 5 times and also reinstalled the Kali Linux
 more than two times but there was no effect. The error occurred when I ran the setup each time.

![screenshot from 2017-10-06 19-35-21](https://user-images.githubusercontent.com/22255426/31281392-d54133d8-aa9e-11e7-8933-96c063d20718.png)
![screenshot from 2017-10-06 19-35-28](https://user-images.githubusercontent.com/22255426/31281391-d53bb890-aa9e-11e7-80ae-85080b7dba83.png)
![screenshot from 2017-10-06 19-37-13](https://user-images.githubusercontent.com/22255426/31281390-d53a9f1e-aa9e-11e7-82aa-65629eba58a2.png)

**Comment by ChrisTruncer** [comment]
3.0 is not the latest version. Please get the latest version of Veil and try again.

**Comment by ghanteyyy** [comment]
I had cloned from this link
                                             https://github.com/Veil-Framework/Veil.git

Isn't it a latest version?

**Comment by ChrisTruncer** [comment]
Please try getting the latest version and trying again. I mentioned in another issue that I literally just downloaded Kali and installed Veil without an issue
