### ISSUE TITLE
payload issue

### ISSUE THREAD

**Issue by 7r09** [Veil-Framework/Veil#128]
what is this issue
i can type my own payload or enter doesn't works 

![screenshot at 2017-10-10 10-05-07](https://user-images.githubusercontent.com/27410678/31390713-9442e1b8-ada2-11e7-9d70-679e690194c7.png)

**Comment by ChrisTruncer** [comment]
Please for github issues fill out the requested information

**Comment by ChrisTruncer** [comment]
I just installed this on Kali, with a clean image, and it works without a problem. Please for future issues provide all the required information, and steps to recreate the issue. At the moment, I cannot recreate this problem.
