### ISSUE TITLE
Kali x32 Installation Failure

### ISSUE THREAD

**Issue by michael-bey** [Veil-Framework/Veil#13]
## Veil version
3.0, newest

## OS Used - all info (architecture, linux flavor, etc)
Kali 2.0 rolling -  i386

## Pastebin link to error you are encountering (include console actions you took prior to error)
Running the installer via ./setup.sh -c and the default values accept runs through, but fails when Veil is started.
```
Traceback (most recent call last):
  File "./Veil.py", line 87, in <module>
    the_conductor = orchestra.Conductor(args)
  File "/opt/Veil/lib/common/orchestra.py", line 23, in __init__
    self.load_tools(cli_stuff)
  File "/opt/Veil/lib/common/orchestra.py", line 67, in load_tools
    command_line_object)
  File "Tools/Evasion/Tool.py", line 39, in __init__
    self.load_payloads(cli_options)
  File "Tools/Evasion/Tool.py", line 240, in load_payloads
    name.replace("/", ".").rstrip('.py'), name)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "Tools/Evasion/payloads/auxiliary/pyinstaller_wrapper.py", line 11, in <module>
    from Tools.Evasion.evasion_common import encryption
  File "/opt/Veil/Tools/Evasion/evasion_common/encryption.py", line 8, in <module>
    from Crypto.Cipher import ARC4
ImportError: No module named 'Crypto'
```

**Comment by ChrisTruncer** [comment]
Run "pip3 install pycrypto", that should fix it for you. I swore I have that in the install process, but now I need to check...

Thanks for letting me know.

**Comment by ChrisTruncer** [comment]
Well, I just checked and that line is in there:

https://github.com/Veil-Framework/Veil/blob/master/setup/setup.sh#L345

Not sure why it wouldn't have worked, but please let me know if that pip3 install command fixed this for you.

**Comment by ChrisTruncer** [comment]
Any feedback? Able to get up and going?

**Comment by ChrisTruncer** [comment]
closing due to not hearing anything back

**Comment by santhosprabahar** [comment]
Hey man, i have the same error and i tried installing pycrypto like you said with pip3 but it says Requirement already satisfied. i dont know what to do..pls help me

**Comment by ChrisTruncer** [comment]
I need more information than that. Please open a new GitHub issue and post everything that is asked for so I can help troubleshoot.

**Comment by santhosprabahar** [comment]
I just removed wine and reinstalled it works fine now thanks for the reply
though appreciate it man

On 07-Jun-2017 4:55 PM, "ChrisTruncer" <notifications@github.com> wrote:

I need more information than that. Please open a new GitHub issue and post
everything that is asked for so I can help troubleshoot.

> On Jun 7, 2017, at 2:01 AM, santhosprabahar <notifications@github.com>
wrote:
>
> Hey man, i have the same error and i tried installing pycrypto like you
said with pip3 but it says Requirement already satisfied. i dont know what
to do..pls help me
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Veil-Framework/Veil/issues/13#issuecomment-306766577>,
or mute the thread

**Comment by tarunsinghtomar** [comment]
Hello Chris, evn i am getting the same error as benichmt1.
i even tried to install the module pycrypto but it dint help.
I am still getting the same error.
Can you guide me?

**Comment by sjosephrw** [comment]
Try this
apt-get install python3-crypto
