### ISSUE TITLE
What are err:ole and err:mscoree ?

### ISSUE THREAD

**Issue by GypsyCosmonaut** [Veil-Framework/Veil#131]
## Veil version
Veil 3.0

## OS Used - all info (architecture, linux flavor, etc)
Official Kali Linux VMWare 64 bit image (Kali Linux 64 bit VM) available for direct download at this link https://www.offensive-security.com/kali-linux-vmware-virtualbox-image-download/

## How did you install Veil? (Apt, Clone from Github, etc.)
git clone https://github.com/Veil-Framework/Veil.git
cd Veil/setup
./setup.sh -c

## Did you run the setup script?
yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
https://pastebin.com/9kNvTDBb

## Expected behavior
I expect that there would not be any error presented to me

## Any additional info you want to tell me
As mentioned in the installation, I also tried 'rm -rf /root/.config/wine/veil' and then tried './setup.sh -c' again but these errors persist.

What are these errors?

Are these errors okay ?

**Comment by ChrisTruncer** [comment]
These should not cause any problems, Veil still works.
