### ISSUE TITLE
can go further than 2tools loaded? I CAN CHOOSE EVASION OR ORDNANCE

### ISSUE THREAD

**Issue by X0R1972** [Veil-Framework/Veil#133]
## Did you run the setup script? yes

![aaaagftztzi](https://user-images.githubusercontent.com/24534204/32031841-dd32b336-ba03-11e7-92d8-609d1339bc21.PNG)

)i dont now why i can choose EVASION AND ORDNANCE.;it returns to main menu
I have last python installed python 3.6

**Comment by xp4xbox** [comment]
type `use Evasion` or `use Ordnance`

**Comment by X0R1972** [comment]
thank you very much ..
