### ISSUE TITLE
How to install in Windows?

### ISSUE THREAD

**Issue by akiraaisha** [Veil-Framework/Veil#134]
## Veil version: 
2017-01-24

## OS Used - all info (architecture, linux flavor, etc): 
Windows 7

## How did you install Veil? (Apt, Clone from Github, etc.)
Clone from Git

## Did you run the setup script?
![image](https://user-images.githubusercontent.com/6212018/32136267-0ecd72ce-bc3d-11e7-9c8d-c803b36f28cd.png)

**Comment by xp4xbox** [comment]
Its only for linux.

**Comment by ChrisTruncer** [comment]
As @xp4xbox said, it's for Linux
