### ISSUE TITLE
List payloads not working

### ISSUE THREAD

**Issue by leebaird** [Veil-Framework/Veil#136]
## Veil version
3.1.4

## OS Used - all info (architecture, linux flavor, etc)
Kali

## How did you install Veil? (Apt, Clone from Github, etc.)
GitHub

## Did you run the setup script?
Yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
list
1
Brings me back to the main menu.

## Expected behavior
List all of the payloads available.

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
you need to select the tool you want to use.

Please provide a pastebin link for your console where you were interacting with Veil.

**Comment by leebaird** [comment]
My Bad.
