### ISSUE TITLE
Unpacking Veil Dependencies takes forever

### ISSUE THREAD

**Issue by X3eRo0** [Veil-Framework/Veil#137]
## Veil version
Latest one I just did it on my PC yesterday 11/11/2017
## OS Used - all info (architecture, linux flavor, etc)
Kali 2017.2

## How did you install Veil? (Apt, Clone from Github, etc.)

Github
## Did you run the setup script?

Yes 
## Pastebin link to error you are encountering (include console actions you took prior to error)

No error but it takes forever to unpack veil dependencies it gets stuck at 33%
## Expected behavior
Proper unpacking and installing wine environment

## Any additional info you want to tell me
It worked earlier but I have to stop the installation at wine configuration due to some reason so I had to interrupt in the process where it was downloading something but veildependencies already downloaded successfully. After that it takes literally forever to proceed from cloning veildependencies.  I can't even do it manually

**Comment by ChrisTruncer** [comment]
That is going to be an issue with your computer or network connection. All it does is clone down the repo containing the required files.

**Comment by X3eRo0** [comment]
But earlier it worked but after the installation interruption I did this happened.
I have core i5 6th gen 3 GHz processor 8 gigs of RAM and a GTX 750ti this is happening just with veil

**Comment by ChrisTruncer** [comment]
The issue you are having has absolutely nothing to do with Veil but with git on your system cloning down the dependencies.

**Comment by X3eRo0** [comment]
I will try and report

**Comment by X3eRo0** [comment]
I got it working anyway I just deleted old junk of veil files and then did everything from the start and it worked

**Comment by Thamizhpathi** [comment]
i was in strugle in install the veil framework in kali linux


 [i] Can't find WINE profile?   Run: /home/kali/Veil/config/config/setup.sh --force --silent
 [>] Please enter the directory of Veil's WINE profile (e.g. /var/lib/veil/wine/)
how to solvethis please explain
