### ISSUE TITLE
Booting Up Problem Afte Installing Veil 3.0

### ISSUE THREAD

**Issue by Kounisd123** [Veil-Framework/Veil#138]
## Veil version
Veil 3.0

## OS Used - all info (architecture, linux flavor, etc)
Kali Linux 2.0 2017.2 
USB 3.0
I did apt-get update and upgrade then installed Veil

## How did you install Veil? (Apt, Clone from Github, etc.)
Cloned from github

## Did you run the setup script?
Yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
The error isn't of Veil itself but after it is installed it won't let me boot up persistent again after I shutdown and reboot. It keeps on going on about the Mouse USB plugged in writing the same thing over and over again. But won't ever actually boot. I can boot into non persistence though.

## Expected behavior
To be able to boot up after downloading.

## Any additional info you want to tell me
Thanks!

**Comment by ChrisTruncer** [comment]
Hi,

Veil doesn’t modify anything with how your VM boots. None of its additions would do anything to impact that.

**Comment by ChrisTruncer** [comment]
If you can give any additional way to recreate this, I'll check it out, but as mentioned, Veil doesn't modify your system's boot process

**Comment by Kounisd123** [comment]
@ChrisTruncer All I do to recreate what happens is create Kali on my USB 3, do apt-get update and apt-get upgrade after making it persistent and after that I clone veil and go through the setup. After Veil works fine but when i try to boot up again in persistence it gets stuck in the process and doesn't boot up. It still boots up just the live version. Also, I've tried doing apt-get update and upgrade and everything works fine. I know Veil doesn't bother with the boot process but for some reason when I install it I can't boot into persistence again. My friend has the same problem as me. We both use USB's to boot into Kali.

**Comment by ChrisTruncer** [comment]
I wish I knew how to help, but since Veil doesn’t modify anything with your system booting, I’m not sure what to say.
