### ISSUE TITLE
unmet dependencies  of  libgnome-vfs2.0-cil

### ISSUE THREAD

**Issue by sidjad** [Veil-Framework/Veil#14]
I am using Ubuntu 16.04 x64 arch & trying to install Veil-evasion but found some dependence  error 
The following packages have unmet dependencies:
 monodevelop : Depends: libgnome-vfs2.0-cil (>= 2.24.0) but it is not going to be installed
               Depends: libgnome2.24-cil (>= 2.24.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
 [ERROR] Failed To Install Dependencies... Exit Code: 100.

**Comment by ChrisTruncer** [comment]
Duplicate, closing
