### ISSUE TITLE
Veil fails to start after fresh install

### ISSUE THREAD

**Issue by hittersinfo** [Veil-Framework/Veil#140]
## Veil version
3.1.1-0kali2

## OS Used - all info (architecture, linux flavor, etc)
KaliLinux.2017.2.amd64
(although veil says it detects Kali Linux 2017.3 x86_64

## How did you install Veil? (Apt, Clone from Github, etc.)
apt-get update
apt-get upgrade -y
apt-get install veil -y
veil

## Did you run the setup script?
no, I just typed veil after using apt-get

## Pastebin link to error you are encountering (include console actions you took prior to error)
https://pastebin.com/BdFVeBqt

## Expected behavior
for veil to start

## Any additional info you want to tell me
It starts and works normally when i clone it from github.

**Comment by ChrisTruncer** [comment]
Don’t install Veil from apt, just install it from GitHub
