### ISSUE TITLE
Multiple errors

### ISSUE THREAD

**Issue by 43r0ncyb3r** [Veil-Framework/Veil#141]
## Veil version
Veil 3.0

## OS Used - all info (architecture, linux flavor, etc)
Linux 43r0ncyb3r 4.13.0-kali1-amd64 #1 SMP Debian 4.13.10-1kali2 (2017-11-08) x86_64 GNU/Linux

## How did you install Veil? (Apt, Clone from Github, etc.)
APT-get

## Did you run the setup script?
Yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
https://pastebin.com/tW9xe9T4

## Expected behavior
To working?

## Any additional info you want to tell me
-

**Comment by ChrisTruncer** [comment]
Please search for similar issues to not create duplicates which have already been answered.

Also, I've stated that you need to install via git cloning the repo and not via apt. Please remove and install via git clone.
