### ISSUE TITLE
How to completely remove Veil?

### ISSUE THREAD

**Issue by linyostorovoltos** [Veil-Framework/Veil#146]
## How did you install Veil? (Apt, Clone from Github, etc.)
Clone from github

## Did you run the setup script?
Yes

## Expected behavior
I'd like a script like "remove.sh"

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
Right now there isn't an automated means to do so. You can delete the wine environment it makes, uninstall the packages (from the setup script), and delete the folder for Veil.
