### ISSUE TITLE
py2exe problem

### ISSUE THREAD

**Issue by mny123** [Veil-Framework/Veil#147]
## Veil version
newest version

## OS Used - all info (architecture, linux flavor, etc)
kali-linux 2017.3

## How did you install Veil? (Apt, Clone from Github, etc.)
github

## Did you run the setup script?
yes, as recommended

## Pastebin link to error you are encountering (include console actions you took prior to error)
runme.bat

## Expected behavior
executable exe

## Any additional info you want to tell me
In my kali-linux 2017.3, I've downloaded and installed Veil-Framework in the newest version via github, according to your installation guide without any errors, except the fact, that AutoIt gave me the message „Could not load wine-gecko, HTML rendering will be disabled“.

As recommended, I've created in your Veil-Framework my payload (python_inject/aes_encrypt and ordnance rev_tcp) with py2exe. I got the files runme.bat, myfile.py, setup.py and myfile.rc without any problems.

Following your discription on github, I first downloaded and installed on my windows vista Python 3.3 for 32bit by double-click the msi-installer.exe. Than I downloaded and installed the correspondig files for pywin32, pycrypto and py2exe by double-click the exe-packages. I made sure, that every package was installed in my Python 3.3 path.

After that, I inserted the files runme.bat, myfile.py and setup.py in my Python 3.3 directory and started the runme.bat by double-click. As expected, I received the myfile.exe in my Python 3.3 directory. This file I transferred to a windows xp machine on my network.

After running myfile.exe on that machine a window popped up with the message, that myfile.exe has detected a problem and must be quit.

What's my mistake? Related to my problem, I couldn't find something in the closed issues.

Maybe it helps you to answer my question, if I run the runme.bat the cmd gives me the message, that there are two missing modules: Crypto.Util.py21compat and readline. Should this causes my problem, how can I fix it?

**Comment by ChrisTruncer** [comment]
Is pycrypto installed in windows and it’s respective Python?

**Comment by mny123** [comment]
Yes, it is installed, because I can see in my Python33 Folder in C: the Removepycrypto.exe. And yes, it is respective Python, because the package is pycrypto-2.6.win32-py3.3.exe.
 
 
-----Ursprüngliche Nachricht-----
 Von: "ChrisTruncer" [notifications@github.com]
 Gesendet: Sa. 16.12.2017 20:29
 An: "Veil-Framework/Veil" [Veil@noreply.github.com]
 Kopie: "mny123" [alexander.schiemann1@freenet.de],  "Author" [author@noreply.github.com]
 Betreff: Re: [Veil-Framework/Veil] py2exe problem (#147)

Is pycrypto installed in windows and it’s respective Python?
 
 > On Dec 16, 2017, at 10:36 AM, mny123  wrote:
 > 
 > Veil version
 > 
 > newest version
 > 
 > OS Used - all info (architecture, linux flavor, etc)
 > 
 > kali-linux 2017.3
 > 
 > How did you install Veil? (Apt, Clone from Github, etc.)
 > 
 > github
 > 
 > Did you run the setup script?
 > 
 > yes, as recommended
 > 
 > Pastebin link to error you are encountering (include console actions you took prior to error)
 > 
 > runme.bat
 > 
 > Expected behavior
 > 
 > executable exe
 > 
 > Any additional info you want to tell me
 > 
 > In my kali-linux 2017.3, I've downloaded and installed Veil-Framework in the newest version via github, according to your installation guide without any errors, except the fact, that AutoIt gave me the message „Could not load wine-gecko, HTML rendering will be disabled“.
 > 
 > As recommended, I've created in your Veil-Framework my payload (python_inject/aes_encrypt and ordnance rev_tcp) with py2exe. I got the files runme.bat, myfile.py, setup.py and myfile.rc without any problems.
 > 
 > Following your discription on github, I first downloaded and installed on my windows vista Python 3.3 for 32bit by double-click the msi-installer.exe. Than I downloaded and installed the correspondig files for pywin32, pycrypto and py2exe by double-click the exe-packages. I made sure, that every package was installed in my Python 3.3 path.
 > 
 > After that, I inserted the files runme.bat, myfile.py and setup.py in my Python 3.3 directory and started the runme.bat by double-click. As expected, I received the myfile.exe in my Python 3.3 directory. This file I transferred to a windows xp machine on my network.
 > 
 > After running myfile.exe on that machine a window popped up with the message, that myfile.exe has detected a problem and must be quit.
 > 
 > What's my mistake? Related to my problem, I couldn't find something in the closed issues.
 > 
 > Maybe it helps you to answer my question, if I run the runme.bat the cmd gives me the message, that there are two missing modules: Crypto.Util.py21compat and readline. Should this causes my problem, how can I fix it?
 > 
 > —
 > You are receiving this because you are subscribed to this thread.
 > Reply to this email directly, view it on GitHub, or mute the thread.
 > 
—
You are receiving this because you authored the thread
Reply to this email directly, view it on GitHub, or mute the thread.
-----Ursprüngliche Nachricht Ende-----

Sichern Sie sich mit freenet Mail start 20 GB Cloud-Speicher zusätzlich zu Ihrem werbefreien Postfach sowie höchste Sicherheitsstandards.
https://email.freenet.de/start/index.html

**Comment by xp4xbox** [comment]
Personally I never use the batch file for building to exe since I see no purpose I just use the setup.py.

**Comment by mny123** [comment]
I tried that, but without success. Maybe my py2exe command-line for a single .exe, not a dist folder, is wrong. What command-line do You use exactly to build Your single .exe?
 
 
-----Ursprüngliche Nachricht-----
 Von: "xp4xbox" [notifications@github.com]
 Gesendet: So. 17.12.2017 14:14
 An: "Veil-Framework/Veil" [Veil@noreply.github.com]
 Kopie: "mny123" [alexander.schiemann1@freenet.de],  "Author" [author@noreply.github.com]
 Betreff: Re: [Veil-Framework/Veil] py2exe problem (#147)

Personally I never use the batch file for building to exe since I see no purpose I just use the setup.py.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
-----Ursprüngliche Nachricht Ende-----

Sichern Sie sich mit freenet Mail start 20 GB Cloud-Speicher zusätzlich zu Ihrem werbefreien Postfach sowie höchste Sicherheitsstandards.
https://email.freenet.de/start/index.html

**Comment by xp4xbox** [comment]
I used
Python setup.py py2exe

**Comment by mny123** [comment]
The same command-line I used in cmd within Python 3.3 too. But the resulting .exe only works on the vista machine, on wich I've created the .exe. On another vista machine or a xp machine a window poppes up with the message, that myfile.exe has detected a problem and must be quit. What's my mistake?

By the way, in Your framework You use Python 3.4.4, but here on the github page You gives the advice to use Python 3.3. Is it possible, that this causes my problem?

**Comment by xp4xbox** [comment]
You have to use 3.3 because it is the last supported version for pycrypto. If there is an error, be sure you have installed all of the correct modules. 

Last time I used it, it worked, but I havent updated Veil in a while. Il try it out,

Also, right next to the .exe there should be a log file. Could you write it here?

**Comment by xp4xbox** [comment]
I just tested it out, and it works for me with that exact payload. I am using windows 7. Maybe its something related to win vista?

**Comment by mny123** [comment]
Ok, it must be a vista related problem. Does py2exe only work in windows 7 or even higher?

**Comment by xp4xbox** [comment]
Should work on all os, what is the output of the log file?

**Comment by mny123** [comment]
This ist the output of the log file taken from my vista machine, in which I've not created the .exe. In my xp machine the same modul causes the problem.

**Comment by mny123** [comment]
The attachment is the output of the log file taken from my vista machine, in which I've not created the .exe. In my xp machine the same modul causes the problem.
 
-----Ursprüngliche Nachricht-----
 Von: "xp4xbox" [notifications@github.com]
 Gesendet: Mi. 20.12.2017 16:45
 An: "Veil-Framework/Veil" [Veil@noreply.github.com]
 Kopie: "mny123" [alexanderschiemann1@freenet.de],  "Author" [author@noreply.github.com]
 Betreff: Re: [Veil-Framework/Veil] py2exe problem (#147)

Should work on all os, what is the output of the log file?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
-----Ursprüngliche Nachricht Ende-----

Sichern Sie sich mit freenet Mail start 20 GB Cloud-Speicher zusätzlich zu Ihrem werbefreien Postfach sowie höchste Sicherheitsstandards.
https://email.freenet.de/start/index.html

  Problemereignisname:	APPCRASH
  Anwendungsname:	test1.exe
  Anwendungsversion:	0.0.0.0
  Anwendungszeitstempel:	54467a4a
  Fehlermodulname:	MSVCR100.dll
  Fehlermodulversion:	10.0.40219.325
  Fehlermodulzeitstempel:	4df2be1e
  Ausnahmecode:	c0000005
  Ausnahmeoffset:	00002b84
  Betriebsystemversion:	6.0.6002.2.2.0.256.6
  Gebietsschema-ID:	1031
  Zusatzinformation 1:	06aa
  Zusatzinformation 2:	b74632f4e5a36cb48eda13818afd1da9
  Zusatzinformation 3:	655f
  Zusatzinformation 4:	dcd2926b30c1b4c286cadc43366dc301


Protokollname: Application
Quelle:        Application Error
Datum:         21.12.2017 05:23:19
Ereignis-ID:   1000
Aufgabenkategorie:(100)
Ebene:         Fehler
Schl�sselw�rter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      LH-R91LNAC448IH
Beschreibung:
Fehlerhafte Anwendung test1.exe, Version 0.0.0.0, Zeitstempel 0x54467a4a, fehlerhaftes Modul MSVCR100.dll, Version 10.0.40219.325, Zeitstempel 0x4df2be1e, Ausnahmecode 0xc0000005, Fehleroffset 0x00002b84, Prozess-ID 0x7dc, Anwendungsstartzeit 01d37a1369688c60.
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-12-21T04:23:19.000Z" />
    <EventRecordID>20301</EventRecordID>
    <Channel>Application</Channel>
    <Computer>LH-R91LNAC448IH</Computer>
    <Security />
  </System>
  <EventData>
    <Data>test1.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>54467a4a</Data>
    <Data>MSVCR100.dll</Data>
    <Data>10.0.40219.325</Data>
    <Data>4df2be1e</Data>
    <Data>c0000005</Data>
    <Data>00002b84</Data>
    <Data>7dc</Data>
    <Data>01d37a1369688c60</Data>
  </EventData>
</Event>

**Comment by xp4xbox** [comment]
Ok that seems like a os error rather than a python error.

**Comment by mny123** [comment]
In the internet I wrote, that Python 3.3.5 is compatible with windows xp. So I will give my good old, stable xp a try and report the result.

**Comment by mny123** [comment]
In the internet there was the information, that Python 3.3.5 is compatible with windows xp. So I will give my good old, stable xp a try and report the result.

**Comment by mny123** [comment]
Yes Sir, you're right! I've tested creating the .exe in my xp machine with the runme.bat and the command-line. The two resulting .exes runs without any problems on my xp machine and my vista machine. I've a connection back from both machines to my kali-linux machine via .rc file in msfconsole.

Thank you very much for your quick responses, your patience and your help! You're doing a great job. Keep on working!
