### ISSUE TITLE
 No module named 'Crypto'

### ISSUE THREAD

**Issue by modernhacker75** [Veil-Framework/Veil#150]
## Veil version
3

## OS Used - all info (architecture, linux flavor, etc)

kali linux 2017.3
## How did you install Veil? (Apt, Clone from Github, etc.)

clone from github
## Did you run the setup script?
yeah i did

## Pastebin link to error you are encountering (include console actions you took prior to error)
After installation i run ./Veil.py but it gives the  error :  No module named 'Crypto'

## Expected behavior
it should have opened the main menu

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
Are you running the latest version of Veil? You just have 3 listed. Also, are you using python3?

**Comment by modernhacker75** [comment]
the problem was solved !

**Comment by ChrisTruncer** [comment]
You didn’t provide any information on how you solved it. Can you please give that info?

**Comment by ChrisTruncer** [comment]
Please provide information on how to solve your issue so others can learn from it if they encounter the same issue.

**Comment by modernhacker75** [comment]
this solved my problem 
~pip install pycrypto

**Comment by aditya2305** [comment]
> this solved my problem
> ~pip install pycrypto

This didn't do anything
