### ISSUE TITLE
Compllete uninstallation

### ISSUE THREAD

**Issue by Jinovas** [Veil-Framework/Veil#154]
## Veil version
3.0

## OS Used - all info (architecture, linux flavor, etc)
Kali

## How did you install Veil? (Apt, Clone from Github, etc.)
Github

## Did you run the setup script?
Yes

## Any additional info you want to tell me

For whatever reason Veil just does not work after install. So I tried uninstaling it but I could not uninstall it via package manager because it doesn't see it. So I looked online and several online sources said to just delete the "/root.config/wine/veil" directory. But now I notice theres a ton of other things in my desktop applications menu that i have no clue where they cane from. Something about "autlt" and several ruby gem based links that do not work.

Any help to figure out whats going on and how to remove this completely would be much appreciated.

**Comment by ChrisTruncer** [comment]
Hi there,

Veil doesn't currently have an uninstall script. You can delete the wine directory (like you referenced above), the /etc/veil directory, and the directory veil is installed in. For your desktop, I would just look at their file location and delete those manually.
