### ISSUE TITLE
help me..

### ISSUE THREAD

**Issue by ayanamida** [Veil-Framework/Veil#155]
## Veil version
 3.0

## OS Used - all info (architecture, linux flavor, etc)

kali 4.14.0-kali3-amd64

## How did you install Veil? (Apt, Clone from Github, etc.)
gitclone

## Did you run the setup script?

./setup.sh -c
## Pastebin link to error you are encountering (include console actions you took prior to error)
help me..

Can not use Pwnstaller (obfuscated Pyinstaller loader) in veil 3.0?

veil3.0 does not have a Pwnstaller?

help me
## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
Do you see pwnstaller as an option?
