### ISSUE TITLE
Windows Defender

### ISSUE THREAD

**Issue by vigilante09** [Veil-Framework/Veil#156]
hello I have just started to use veil evasion but when I try to execute the exe file in my Windows virtual machine it is detected by Windows Defender. Is it because of me or is there something to do different about my vm?

**Comment by ChrisTruncer** [comment]
Please look into using different options the payloads have to help them bypass detection.

**Comment by vigilante09** [comment]
<img width="779" alt="ekran resmi 2018-01-17 00 38 41" src="https://user-images.githubusercontent.com/35505385/35013615-fa68f328-fb1e-11e7-8fa9-a866dc24b1ec.png">
isnt it enough what else can I change ?

**Comment by ChrisTruncer** [comment]
There is more, plus C# is fairly well caught. You could modify the template that is currently in Veil. The reason the templates are there are so you can have a base to start with, and modify as needed.
