### ISSUE TITLE
Veil 3.0 error runing in kali linux

### ISSUE THREAD

**Issue by D33pOnion** [Veil-Framework/Veil#157]
## Veil version
3.1.4  (from the changelog file)

## OS Used - all info (architecture, linux flavor, etc)
uname -a:
Linux kali 4.14.0-kali3-amd64 #1 SMP Debian 4.14.13-1kali1 (2018-01-25) x86_64 GNU/Linux

## How did you install Veil? (Apt, Clone from Github, etc.)
Installed from [https://github.com/Veil-Framework/Veil](url) and `Download ZIP`

## Did you run the setup script?
**When I run the setup script:**
[https://mega.nz/#F!hGgHXL5R!o6ZYzQTUrFt0ojnzeXTdBA](url)
(copy and paste link)

## Any additional info you want to tell me
installed to `/opt/Veil-master`

What must I do ?

**Comment by ChrisTruncer** [comment]
Run veil.py

**Comment by D33pOnion** [comment]
When I run:
`root@kali:/opt/Veil-master# ./Veil.py`
Traceback (most recent call last):
  File "./Veil.py", line 87, in <module>
    the_conductor = orchestra.Conductor(args)
  File "/opt/Veil-master/lib/common/orchestra.py", line 23, in __init__
    self.load_tools(cli_stuff)
  File "/opt/Veil-master/lib/common/orchestra.py", line 67, in load_tools
    command_line_object)
  File "Tools/Evasion/Tool.py", line 41, in __init__
    self.load_payloads(cli_options)
  File "Tools/Evasion/Tool.py", line 242, in load_payloads
    name.replace("/", ".").rstrip('.py'), name)
  File "/usr/local/lib/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "Tools/Evasion/payloads/auxiliary/pyinstaller_wrapper.py", line 11, in <module>
    from Tools.Evasion.evasion_common import encryption
  File "/opt/Veil-master/Tools/Evasion/evasion_common/encryption.py", line 8, in <module>
    from Crypto.Cipher import ARC4
ImportError: No module named 'Crypto'
root@kali:/opt/Veil-master#

**Comment by ChrisTruncer** [comment]
You need to install the dependencies, run the setup script to automate it.

**Comment by D33pOnion** [comment]
How can I fix this?

**Comment by ChrisTruncer** [comment]
Sorry, if you’re unwilling to read the instructions that come with the tool, my support stops at that point.

**Comment by ghost** [comment]
I tried to install from the command line.

apt -y install veil
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package veil

I downloaded the github version.

I ran setup.sh but most things as it did in the past do not install correctly. Python, ruby and the first 2 dependencies do not install or are not there to be installed. 

root@kali:~/Veil/config# ./setup.sh --force --silent
 ==========================================================================
                 Veil (Setup Script) | [Updated]: 2018-05-08
 ==========================================================================
     [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
 ==========================================================================

                 os = kali
          osversion = 2018.2
       osmajversion = 2018
               arch = x86_64
           trueuser = root
   userprimarygroup = root
        userhomedir = /root
            rootdir = /root/Veil
            veildir = /var/lib/veil
          outputdir = /var/lib/veil/output
    dependenciesdir = /var/lib/veil/setup-dependencies
            winedir = /var/lib/veil/wine
          winedrive = /var/lib/veil/wine/drive_c
            gempath = Z:\var\lib\veil\wine\drive_c\Ruby187\bin\gem

 [I] Kali Linux 2018.2 x86_64 detected...

 [I] Silent Mode: Enabled
 [I]  Force Mode: Enabled


 [?] Are you sure you wish to install Veil?

     Continue with installation? ([y]es/[s]ilent/[N]o): S



 [*] Initializing package installation



 [*] Installing dependencies

 [*] Updating APT

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package mono-mcs
 [ERROR] Failed with installing dependencies (1): 0



 [*] Installing Python's pycrypto (via apt)...

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python3-crypto is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-crypto' has no installation candidate
 [ERROR] Failed with installing dependencies (6): 0

Reading package lists... Done
Building dependency tree       
Reading state information... Done
metasploit-framework is already the newest version (4.17.3-0kali1).
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.


 [*] Pulling down binary dependencies

 [*] Empty folder... git cloning

Cloning into '/var/lib/veil/setup-dependencies'...
remote: Counting objects: 12, done.
remote: Total 12 (delta 0), reused 0 (delta 0), pack-reused 12
Unpacking objects: 100% (12/12), done.
Checking out files: 100% (10/10), done.


 [*] Installing Wine

 [*] Already have x86 architecture added...



 [*] Installing Wine 32-bit and 64-bit binaries (via APT)

E: Unable to correct problems, you have held broken packages.
 [ERROR] Failed with installing wine (2): 0



 [*] [ALERT]: Existing Veil Wine environment detected at: /var/lib/veil/wine

     Do you want to nuke it? ([y]es/[N]o): Y

 [*] Deleting existing Veil Wine environment...

 [*] Creating new Veil Wine environment in: /var/lib/veil/wine

 [*] Initializing Veil's Wine environment...

it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
wine: '/var/lib/veil/wine' is a 32-bit installation, it cannot support 64-bit applications.
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
wine: '/var/lib/veil/wine' is a 32-bit installation, it cannot support 64-bit applications.
 [*] Veil Wine environment successfully created!



 [*] Finished package installation



 [*] Initializing (OS + Wine) Python dependencies installation...



 [*] Installing (Wine) Python...

 [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)

it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
0012:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0012:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0012:err:ole:get_local_server_stream Failed: 80004002
0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
0014:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0014:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0014:err:ole:get_local_server_stream Failed: 80004002
Could not load wine-gecko. HTML rendering will be disabled.
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/var/lib/veil/wine' has been updated.
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
0009:err:msi:create_temp_binary failed to load dll L"C:\\users\\root\\Temp\\msi9e18.tmp" (193)
002f:err:msi:ACTION_CallDllFunction failed to load dll L"C:\\users\\root\\Temp\\msi9e18.tmp" (193)
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
wine: Bad EXE format for C:\Python34\python.exe.
0009:err:msi:execute_command unable to execute command 193


 [*] Installing (Wine) Python dependencies...



 [*] Installing (Wine) Python's pywin32-220.win32-py3.4.exe...

 [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)

warning [pywin32-220.win32-py3.4.exe]:  192288 extra bytes at beginning or within zipfile
  (attempting to process anyway)
cp: target '/var/lib/veil/wine/drive_c/Python34/Scripts/' is not a directory
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
wine: Bad EXE format for C:\Python34\python.exe.


 [*] Installing (Wine) Python's pycrypto-2.6.1.win32-py3.4.exe...

 [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)

warning [pycrypto-2.6.1.win32-py3.4.exe]:  191515 extra bytes at beginning or within zipfile
  (attempting to process anyway)


 [*] Installing (OS) Python's PyInstaller (via TAR)



 [*] Installing (Wine) Python's PIP pefile

it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
wine: Bad EXE format for C:\Python34\python.exe.
 [ERROR] Failed to run (wine) Python pip... Exit code: 193

it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
wine: Bad EXE format for C:\Python34\python.exe.
 [ERROR] Failed to run (wine) Python pip future... Exit code: 193

it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
wine: Bad EXE format for C:\Python34\python.exe.
 [ERROR] Failed to run (wine) Python pip pefile... Exit code: 193



 [*] Finished (Wine + OS) Python dependencies installation



 [*] Initializing (Wine) Ruby installation...



 [*] Installing (Wine) Ruby & dependencies

 [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)

it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
wine: Bad EXE format for Z:\var\lib\veil\setup-dependencies\rubyinstaller-1.8.7-p371.exe.
 [ERROR] Failed to install (Wine) Ruby.exe... Exit code: 193



 [*] Installing (Wine) Ruby OCRA gem...

it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"

Z:\var\lib\veil\setup-dependencies>Z:\var\lib\veil\wine\drive_c\Ruby187\bin\gem install --force --local ocra-1.3.6.gem 
Can't recognize 'Z:\var\lib\veil\wine\drive_c\Ruby187\bin\gem install --force --local ocra-1.3.6.gem' as an internal or external command, or batch script.
 [ERROR] Failed to run (wine) Ruby OCRA.. Exit code: 49



 [*] Extracting (Wine) Ruby dependencies...



 [*] Finished Ruby installation



 [*] Initializing Go installation...



 [*] Installing Go x86_64 (via TAR)



 [*] Finished Go installation



 [*] Initializing AutoIT installation...



 [*] Installing (Wine) AutoIT

 [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)

it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
wine: Bad EXE format for Z:\var\lib\veil\setup-dependencies\autoit-v3-setup.exe.
 [ERROR] Failed to run (wine) AutoIT.. Exit code: 193



 [*] Finished AutoIT installation



 [*] Updating Veil configuration...


 Veil Configuration:
 [*] OPERATING_SYSTEM = Kali
 [*] TERMINAL_CLEAR = false
 [*] VEIL_PATH = /root/Veil/
 [*] WINEPREFIX = /var/lib/veil/wine/
 [*] TEMP_PATH = /tmp/
 [*] METASPLOIT_PATH = /usr/share/metasploit-framework/
 [*] MSFVENOM_PATH = /usr/bin/
 [*] MSFVENOM_OPTIONS = 
 [*] PYINSTALLER_PATH = /var/lib/veil/PyInstaller-3.2.1/
 [*] GOLANG_PATH = /var/lib/veil/go/



 Veil-Evasion Configuration:
 [*] PAYLOAD_SOURCE_PATH = /var/lib/veil/output/source/
 [*] PAYLOAD_COMPILED_PATH = /var/lib/veil/output/compiled/
 [*] HANDLER_PATH = /var/lib/veil/output/handlers/
 [*] HASH_LIST = /var/lib/veil/output/hashes.txt
 [I] Path Created: '/var/lib/veil/output/handlers/
 [I] Path Created: '/var/lib/veil/output/source/
 [I] Path Created: '/var/lib/veil/output/compiled/
 [I] Path '/etc/veil/' Created
 [I] Configuration File Written To: '/etc/veil/settings.py'



 [*] Ensuring this account (root) owns veil output directory (/var/lib/veil/output)...

 [*] Ensuring this account (root) has correct ownership of /var/lib/veil/wine



 [*] Finished Veil configuration...



 [*] Finished environment checks

 [ERROR] There was issues installing the following:

 
Failed with installing dependencies (1): 0
Failed with installing dependencies (6): 0
Failed with installing wine (2): 0
Failed to run (wine) Python pip... Exit code: 193
Failed to run (wine) Python pip future... Exit code: 193
Failed to run (wine) Python pip pefile... Exit code: 193
Failed to install (Wine) Ruby.exe... Exit code: 193
Failed to run (wine) Ruby OCRA.. Exit code: 49
Failed to run (wine) AutoIT.. Exit code: 193



 [I] If you have any errors running Veil, run: './Veil.py --setup' and select the nuke the wine folder option



 [I] Done!

root@kali:~/Veil/config#

**Comment by usamakarim5** [comment]
> I tried to install from the command line.
> 
> apt -y install veil
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> E: Unable to locate package veil
> 
> I downloaded the github version.
> 
> I ran setup.sh but most things as it did in the past do not install correctly. Python, ruby and the first 2 dependencies do not install or are not there to be installed.
> # root@kali:~/Veil/config# ./setup.sh --force --silent
> 
> ```
>              Veil (Setup Script) | [Updated]: 2018-05-08
> ```
> 
> # ==========================================================================
> [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
> 
> ```
>              os = kali
>       osversion = 2018.2
>    osmajversion = 2018
>            arch = x86_64
>        trueuser = root
> ```
> 
> userprimarygroup = root
> userhomedir = /root
> rootdir = /root/Veil
> veildir = /var/lib/veil
> outputdir = /var/lib/veil/output
> dependenciesdir = /var/lib/veil/setup-dependencies
> winedir = /var/lib/veil/wine
> winedrive = /var/lib/veil/wine/drive_c
> gempath = Z:\var\lib\veil\wine\drive_c\Ruby187\bin\gem
> 
> [I] Kali Linux 2018.2 x86_64 detected...
> 
> [I] Silent Mode: Enabled
> [I] Force Mode: Enabled
> 
> [?] Are you sure you wish to install Veil?
> 
> ```
>  Continue with installation? ([y]es/[s]ilent/[N]o): S
> ```
> 
> [*] Initializing package installation
> 
> [*] Installing dependencies
> 
> [*] Updating APT
> 
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> E: Unable to locate package mono-mcs
> [ERROR] Failed with installing dependencies (1): 0
> 
> [*] Installing Python's pycrypto (via apt)...
> 
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Package python3-crypto is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'python3-crypto' has no installation candidate
> [ERROR] Failed with installing dependencies (6): 0
> 
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> metasploit-framework is already the newest version (4.17.3-0kali1).
> 0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
> 
> [*] Pulling down binary dependencies
> 
> [*] Empty folder... git cloning
> 
> Cloning into '/var/lib/veil/setup-dependencies'...
> remote: Counting objects: 12, done.
> remote: Total 12 (delta 0), reused 0 (delta 0), pack-reused 12
> Unpacking objects: 100% (12/12), done.
> Checking out files: 100% (10/10), done.
> 
> [*] Installing Wine
> 
> [*] Already have x86 architecture added...
> 
> [*] Installing Wine 32-bit and 64-bit binaries (via APT)
> 
> E: Unable to correct problems, you have held broken packages.
> [ERROR] Failed with installing wine (2): 0
> 
> [*] [ALERT]: Existing Veil Wine environment detected at: /var/lib/veil/wine
> 
> ```
>  Do you want to nuke it? ([y]es/[N]o): Y
> ```
> 
> [*] Deleting existing Veil Wine environment...
> 
> [*] Creating new Veil Wine environment in: /var/lib/veil/wine
> 
> [*] Initializing Veil's Wine environment...
> 
> it looks like wine32 is missing, you should install it.
> as root, please execute "apt-get install wine32"
> wine: '/var/lib/veil/wine' is a 32-bit installation, it cannot support 64-bit applications.
> it looks like wine32 is missing, you should install it.
> as root, please execute "apt-get install wine32"
> wine: '/var/lib/veil/wine' is a 32-bit installation, it cannot support 64-bit applications.
> [*] Veil Wine environment successfully created!
> 
> [*] Finished package installation
> 
> [*] Initializing (OS + Wine) Python dependencies installation...
> 
> [*] Installing (Wine) Python...
> 
> [*] Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)
> 
> it looks like wine32 is missing, you should install it.
> as root, please execute "apt-get install wine32"
> 0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
> 0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
> 0012:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
> 0012:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
> 0012:err:ole:get_local_server_stream Failed: 80004002
> 0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
> 0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
> 0014:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
> 0014:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
> 0014:err:ole:get_local_server_stream Failed: 80004002
> Could not load wine-gecko. HTML rendering will be disabled.
> it looks like wine32 is missing, you should install it.
> as root, please execute "apt-get install wine32"
> Could not load wine-gecko. HTML rendering will be disabled.
> wine: configuration in '/var/lib/veil/wine' has been updated.
> 0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
> 0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
> 0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
> 0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
> 0009:err:msi:create_temp_binary failed to load dll L"C:\users\root\Temp\msi9e18.tmp" (193)
> 002f:err:msi:ACTION_CallDllFunction failed to load dll L"C:\users\root\Temp\msi9e18.tmp" (193)
> it looks like wine32 is missing, you should install it.
> as root, please execute "apt-get install wine32"
> wine: Bad EXE format for C:\Python34\python.exe.
> 0009:err:msi:execute_command unable to execute command 193
> 
> [*] Installing (Wine) Python dependencies...
> 
> [*] Installing (Wine) Python's pywin32-220.win32-py3.4.exe...
> 
> [*] Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)
> 
> warning [pywin32-220.win32-py3.4.exe]: 192288 extra bytes at beginning or within zipfile
> (attempting to process anyway)
> cp: target '/var/lib/veil/wine/drive_c/Python34/Scripts/' is not a directory
> it looks like wine32 is missing, you should install it.
> as root, please execute "apt-get install wine32"
> it looks like wine32 is missing, you should install it.
> as root, please execute "apt-get install wine32"
> wine: Bad EXE format for C:\Python34\python.exe.
> 
> [*] Installing (Wine) Python's pycrypto-2.6.1.win32-py3.4.exe...
> 
> [*] Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)
> 
> warning [pycrypto-2.6.1.win32-py3.4.exe]: 191515 extra bytes at beginning or within zipfile
> (attempting to process anyway)
> 
> [*] Installing (OS) Python's PyInstaller (via TAR)
> 
> [*] Installing (Wine) Python's PIP pefile
> 
> it looks like wine32 is missing, you should install it.
> as root, please execute "apt-get install wine32"
> it looks like wine32 is missing, you should install it.
> as root, please execute "apt-get install wine32"
> wine: Bad EXE format for C:\Python34\python.exe.
> [ERROR] Failed to run (wine) Python pip... Exit code: 193
> 
> it looks like wine32 is missing, you should install it.
> as root, please execute "apt-get install wine32"
> it looks like wine32 is missing, you should install it.
> as root, please execute "apt-get install wine32"
> wine: Bad EXE format for C:\Python34\python.exe.
> [ERROR] Failed to run (wine) Python pip future... Exit code: 193
> 
> it looks like wine32 is missing, you should install it.
> as root, please execute "apt-get install wine32"
> it looks like wine32 is missing, you should install it.
> as root, please execute "apt-get install wine32"
> wine: Bad EXE format for C:\Python34\python.exe.
> [ERROR] Failed to run (wine) Python pip pefile... Exit code: 193
> 
> [*] Finished (Wine + OS) Python dependencies installation
> 
> [*] Initializing (Wine) Ruby installation...
> 
> [*] Installing (Wine) Ruby & dependencies
> 
> [*] Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)
> 
> it looks like wine32 is missing, you should install it.
> as root, please execute "apt-get install wine32"
> it looks like wine32 is missing, you should install it.
> as root, please execute "apt-get install wine32"
> wine: Bad EXE format for Z:\var\lib\veil\setup-dependencies\rubyinstaller-1.8.7-p371.exe.
> [ERROR] Failed to install (Wine) Ruby.exe... Exit code: 193
> 
> [*] Installing (Wine) Ruby OCRA gem...
> 
> it looks like wine32 is missing, you should install it.
> as root, please execute "apt-get install wine32"
> 
> Z:\var\lib\veil\setup-dependencies>Z:\var\lib\veil\wine\drive_c\Ruby187\bin\gem install --force --local ocra-1.3.6.gem
> Can't recognize 'Z:\var\lib\veil\wine\drive_c\Ruby187\bin\gem install --force --local ocra-1.3.6.gem' as an internal or external command, or batch script.
> [ERROR] Failed to run (wine) Ruby OCRA.. Exit code: 49
> 
> [*] Extracting (Wine) Ruby dependencies...
> 
> [*] Finished Ruby installation
> 
> [*] Initializing Go installation...
> 
> [*] Installing Go x86_64 (via TAR)
> 
> [*] Finished Go installation
> 
> [*] Initializing AutoIT installation...
> 
> [*] Installing (Wine) AutoIT
> 
> [*] Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)
> 
> it looks like wine32 is missing, you should install it.
> as root, please execute "apt-get install wine32"
> it looks like wine32 is missing, you should install it.
> as root, please execute "apt-get install wine32"
> wine: Bad EXE format for Z:\var\lib\veil\setup-dependencies\autoit-v3-setup.exe.
> [ERROR] Failed to run (wine) AutoIT.. Exit code: 193
> 
> [*] Finished AutoIT installation
> 
> [*] Updating Veil configuration...
> 
> Veil Configuration:
> [_] OPERATING_SYSTEM = Kali [_] TERMINAL_CLEAR = false
> [_] VEIL_PATH = /root/Veil/ [_] WINEPREFIX = /var/lib/veil/wine/
> [_] TEMP_PATH = /tmp/ [_] METASPLOIT_PATH = /usr/share/metasploit-framework/
> [_] MSFVENOM_PATH = /usr/bin/ [_] MSFVENOM_OPTIONS =
> [_] PYINSTALLER_PATH = /var/lib/veil/PyInstaller-3.2.1/ [_] GOLANG_PATH = /var/lib/veil/go/
> 
> Veil-Evasion Configuration:
> [_] PAYLOAD_SOURCE_PATH = /var/lib/veil/output/source/ [_] PAYLOAD_COMPILED_PATH = /var/lib/veil/output/compiled/
> [_] HANDLER_PATH = /var/lib/veil/output/handlers/ [_] HASH_LIST = /var/lib/veil/output/hashes.txt
> [I] Path Created: '/var/lib/veil/output/handlers/
> [I] Path Created: '/var/lib/veil/output/source/
> [I] Path Created: '/var/lib/veil/output/compiled/
> [I] Path '/etc/veil/' Created
> [I] Configuration File Written To: '/etc/veil/settings.py'
> 
> [*] Ensuring this account (root) owns veil output directory (/var/lib/veil/output)...
> 
> [*] Ensuring this account (root) has correct ownership of /var/lib/veil/wine
> 
> [*] Finished Veil configuration...
> 
> [*] Finished environment checks
> 
> [ERROR] There was issues installing the following:
> 
> Failed with installing dependencies (1): 0
> Failed with installing dependencies (6): 0
> Failed with installing wine (2): 0
> Failed to run (wine) Python pip... Exit code: 193
> Failed to run (wine) Python pip future... Exit code: 193
> Failed to run (wine) Python pip pefile... Exit code: 193
> Failed to install (Wine) Ruby.exe... Exit code: 193
> Failed to run (wine) Ruby OCRA.. Exit code: 49
> Failed to run (wine) AutoIT.. Exit code: 193
> 
> [I] If you have any errors running Veil, run: './Veil.py --setup' and select the nuke the wine folder option
> 
> [I] Done!
> 
> root@kali:~/Veil/config#

I don't still you having this issue or not. But i was facing the same issue you had. For this you have to install Veil via Git Clone 
--> apt-get -y install git
--> git clone git clone https://github.com/Veil-Framework/Veil.git
--> cd Veil
--> cd config
--> ./setup.sh --silent --force
when everything Done and same issue occur then Run the following Commands
--> pip install pycrypto
it will install the python crypto. Because above while installing python crypto in Veil. it shows error. So we need to install it manually.

**Comment by nabiljaved** [comment]
After cloning Veil The first issue I faced was Wine was not Installed , I saw that my virtual space hard drive assigned for Virtual Box had been full , I increased it and then Kali kept asking username and password for Login. I got fed up deleted the machine and reinstall Kali and cloned veil again . However this time,  I assigned Virtual space 30 GB instead of 16GB. Moving forward, Wine installed successfully . But , when I ran ./Veil.py another Error Showed Up ; Crypto not found . Then , I thought why not to install Pyhton3- crypto . Again , another Error Showed up . "Python3-crypto" has no installation candidate. It was such a disappointment. Nevertheless, I sudo apt-get update and upgrade . Oh boy ! it took a hell of a time. Afterwards, I again ran ./setup.sh -- silent --force and then ./Veil.Py . But the Error remained the same Crypto not found. So, I Googled and install python3-pip and later sudo install pycrypto. Having done that , ran ./Veil.py again and Volia ! It worked 😳. Maybe I am a newbie on Kali . Nevertheless, the experiences are great . Hope it helps 😊

**Comment by Idlefase** [comment]
@D33pOnion the best way to use veil is to use apt. This will install the libs needed for it with and (if needed) the kali policy.

After that you need to setup veil. Follow the info for that are at the kali linux tool docs. Make sure to run that as ROOT. 

It can come in handy to have run sudo msfdb init beforehand and to make sure that the postgresql service is running at the moment. ( in case you might have run in the past: sudo systemctl stop postgresql).

Suc6 m8.

**Comment by MusabPalaz** [comment]
Try these codes for no module named "Crypto" problem;

1) pip3 uninstall pycrypto
2) pip3 install pycryptodome
3) python3 Veil.py
it will work.
