### ISSUE TITLE
problem to add custom payload raw

### ISSUE THREAD

**Issue by HanseSecure** [Veil-Framework/Veil#159]
Got the same problem as descriped here:
https://github.com/Veil-Framework/Veil/issues/67

Setup: recent Kali 64Bit in Virtualbox

Any suggestions?

**Comment by ChrisTruncer** [comment]
When the github issue asks for information, if you don't provide it it makes helping to solve a problem harder. Please provide the requested information.

I just tested this on my system and did not encounter a problem. If this is a problem, please recreate a new issue and provide all the requested information that is already present to help repeat the issue on my side.
