### ISSUE TITLE
error installing python 

### ISSUE THREAD

**Issue by sharkmoos** [Veil-Framework/Veil#16]
when I install this framework I can't install python, the window pops up but the 'next' button fails to work and I have to exit the window thereby canceling the download 

[I] Kali Linux "2016.1" x86_64 detected...

 [?] Are you sure you wish to install Veil-Evasion?

```
 Continue with installation? ([y]/[s]ilent/[N]o): y
```

 [*] Initializing package installation

 [*] Adding x86 architecture to x86_64 system for Wine

 [*] Installing Wine 32-bit and 64-bit binaries
E: Package 'wine32' has no installation candidate
 [ERROR] Failed to install Wine... Exit code: 100

 [_] Creating new Veil Wine environment in: /root/.config/wine/veil
 [_] Initializing Veil's Wine environment...
it looks like multiarch needs to be enabled.  as root, please
execute "dpkg --add-architecture i386 && apt-get update &&
apt-get install wine32"
wine: WINEARCH set to win32 but '/root/.config/wine/veil' is a 64-bit installation.
 [*] Veil Wine environment successfully created!

 [*] Installing dependencies
Reading package lists... Done
Building dependency tree  
Reading state information... Done
E: Unable to locate package mingw-w64
E: Unable to locate package monodoc-browser
E: Unable to locate package monodevelop
E: Unable to locate package mono-mcs
E: Unable to locate package golang
 [ERROR] Failed to install dependencies... Exit code: 100

Reading package lists... Done
Building dependency tree  
Reading state information... Done
metasploit-framework is already the newest version (4.11.5-2016010401-0kali1).
metasploit-framework set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

 [*] Installing Capstone dependencies...
Reading package lists... Done
Building dependency tree  
Reading state information... Done
python-capstone is already the newest version (3.0.4-0.2).
python-capstone set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

 [*] Initializing Python dependencies installation...

 [_] Installing Python's SymmetricJSONRPC...
 [_] Installing SymmetricJSONRPC dependency (via Repository)
Reading package lists... Done
Building dependency tree  
Reading state information... Done
E: Unable to locate package python-symmetric-jsonrpc
 [ERROR] Failed to install SymmetricJSONRPC... Exit code: 100

 [*] Initializing (Wine) Python dependencies installation...

 [*] Preparing (Wine) Python directories...

 [_] Installing (Wine) Python...
 [_] Next -> Next -> Next -> Finished! ...Overwrite if prompt. Use default values.
Could not load wine-gecko. HTML rendering will be disabled.
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/root/.config/wine/veil' has been updated.
 [ERROR] Failed to install (Wine) Python 2.7.5... Exit code: 66

ls

 [*] Installing (Wine) Python dependencies...

 [_] Installing (Wine) Python's pywin32-219.win32-py2.7.exe...
 [_] Next -> Next -> Next -> Finished! ...Overwrite if prompt. Use default values.
wine: Bad EXE format for Z:\root\Veil\Veil-Evasion\setup\pywin32-219.win32-py2.7.exe.
 [ERROR] Failed to install pywin32-219.win32-py2.7.exe... Exit code: 193

 [_] Installing (Wine) Python's pycrypto-2.6.win32-py2.7.exe...
 [_] Next -> Next -> Next -> Finished! ...Overwrite if prompt. Use default values.
./iwine: Bad EXE format for Z:\root\Veil\Veil-Evasion\setup\pycrypto-2.6.win32-py2.7.exe.
 [ERROR] Failed to install pycrypto-2.6.win32-py2.7.exe... Exit code: 193

 [*] Installing Python's PyInstaller

 [*] Installing Python's PEFile (For PyInstaller)
wine: cannot find '/root/.config/wine/veil/drive_c/Python27/python.exe'

 [*] Installing Python's Futures (For PyInstaller)
nwine: cannot find '/root/.config/wine/veil/drive_c/Python27/python.exe'

 [*] Installing Python's setup  tools
wine: cannot find '/root/.config/wine/veil/drive_c/Python27/python.exe'

 [*] Initializing (Wine) Ruby dependencies installation...

 [_] Installing (Wine) Ruby & dependencies
 [_] Next -> Next -> Next -> Finished! ...Overwrite if prompt. Use default values.
stallwine: Bad EXE format for Z:\root\Veil\Veil-Evasion\setup\rubyinstaller-1.8.7-p371.exe.
 [ERROR] Failed to install (Wine) Ruby.exe... Exit code: 193

 [*] Installing (Wine) Ruby OCRA gem...
wine: cannot find '/root/.config/wine/veil/drive_c/Ruby187/bin/ruby.exe'
 [ERROR] Failed to install (Wine) Ruby OCRA Gem... Exit code: 2

 [*] Extracting (Wine) Ruby dependencies...

 [*] Initializing Go dependencies installation...

E: No packages found
./setup.sh: line 542: [: : integer expression expected
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Package gccgo-5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libgcc-5-dev cpp-5 gcc-5

E: Package 'gccgo-5' has no installation candidate
update-alternatives: error: no alternatives for go

 [*] Installing Go x86_64 (via TAR)
- [ERROR] Bad hash for go153x64.tar.gz!
  
  [*] Updating Veil-Framework configuration...
  
  Veil-Framework configuration:
  
  [_] OPERATING_SYSTEM = Kali
  [_] TERMINAL_CLEAR = clear
  [_] WINEPREFIX = /root/.config/wine/veil/
  [_] TEMP_DIR = /tmp/
  [_] MSFVENOM_OPTIONS = 
  [_] METASPLOIT_PATH = /usr/share/metasploit-framework/
  [_] MSFVENOM_PATH = /usr/bin/
  [_] PYINSTALLER_PATH = /opt/veil/PyInstaller-3.2/
  
  [_] VEIL_EVASION_PATH = /root/Veil/Veil-Evasion/
  [_] PAYLOAD_SOURCE_PATH = /usr/share/veil-output/source/
  [_] Path '/usr/share/veil-output/source/' Created
  [_] PAYLOAD_COMPILED_PATH = /usr/share/veil-output/compiled/
  [_] Path '/usr/share/veil-output/compiled/' Created
  [_] Path '/usr/share/veil-output/handlers/' Created
  [_] GENERATE_HANDLER_SCRIPT = True
  [_] HANDLER_PATH = /usr/share/veil-output/handlers/
  [*] HASH_LIST = /usr/share/veil-output/hashes.txt
  
  [_] VEIL_CATAPULT_PATH = /root/Veil/Veil-Catapult/
  [_] Path '/usr/share/veil-output/catapult/' Created
  [*] CATAPULT_RESOURCE_PATH = /usr/share/veil-output/catapult/
  
  [*] Path '/etc/veil/' Created
  Configuration File Written To '/etc/veil/settings.py'
  
  [_] Ensuring this account (root) owns veil output directory (/usr/share/veil-output)...
  [_] Ensuring this account (root) has correct ownership of /root/.config/wine/veil
  There was issues installing the following:

Failed to install Wine... Exit code: 100
Failed to install dependencies... Exit code: 100
Failed to install SymmetricJSONRPC... Exit code: 100
Failed to install (Wine) Python 2.7.5... Exit code: 66
Failed to install pywin32-219.win32-py2.7.exe... Exit code: 193
Failed to install pycrypto-2.6.win32-py2.7.exe... Exit code: 193
Failed to install (Wine) Ruby.exe... Exit code: 193
Failed to install (Wine) Ruby OCRA Gem... Exit code: 2
Bad hash for go153x64.tar.gz!

**Comment by N-Komodo** [comment]
Try using Kali 32-bit instead of 64-bit.

**Comment by ChrisTruncer** [comment]
Sorry, I'm really not sure the best thing to tell you.  I am able to install Python and click on the button.  Please also use the provided template for submitting issues.

Thanks
