### ISSUE TITLE
Veil not working after accidentally removing python3 - how to revert

### ISSUE THREAD

**Issue by oqawasmi** [Veil-Framework/Veil#160]
## Veil version
3

## OS Used - all info (architecture, linux flavor, etc)
Kali Linux 2017.3 , 686

## How did you install Veil? (Apt, Clone from Github, etc.)
Clone

## Did you run the setup script?
Yes

## Pastebin link to error you are encountering (include console actions you took prior to error)

Main menu choice: use 2
free(): invalid pointer
Aborted

I accidentally removed Python3, I then had the error 
..File root/Veil/lib/common/orchestra.py line 10 in module import readline
readline module didn't exist obviously, so I installed it using pip3 install --user readline
after doing so, I receivethe above error when I select any option

## Expected behavior
when I type in use 2, it should go to Veil Evasion

## Any additional info you want to tell me
Please helo

**Comment by ChrisTruncer** [comment]
reinstall python 3 and Veil's dependencies. This isn't a Veil issue, unfortunately. Worst case, do a rebuild

**Comment by oqawasmi** [comment]
Thanks Chris, do you mean reinstall Kali.. worst case ?
