### ISSUE TITLE
No protocol specified - Veil install

### ISSUE THREAD

**Issue by keviiin38** [Veil-Framework/Veil#161]
## Veil version
3.0

## OS Used - all info (architecture, linux flavor, etc)
ParrotOS

## How did you install Veil? (Apt, Clone from Github, etc.)
git clone

## Did you run the setup script?
yes with the `sudo ./setup.sh -c`

## Pastebin link to error you are encountering (include console actions you took prior to error)
`Reading profile /etc/firejail/wine.profile`
`Reading profile /etc/firejail/disable-common.inc`
`Reading profile /etc/firejail/disable-devel.inc`
`Reading profile /etc/firejail/disable-programs.inc`
`Warning: noroot option is not available`
`Parent pid 4336, child pid 4337`
`The new log directory is /proc/4337/root/var/log`
`Child process initialized in 42.13 ms`
`No protocol specified
`

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
Hi there,

It looks like firejail is causing Veil some problems. I’ve never used that, and I don’t support parrotOS as I’ve never used it.

If someone that uses parrot wants to hop in and give some info though, that’s fine by me.  Hope it gets working for you.
