### ISSUE TITLE
Multiple Veil errors upon clone install. None of the tools will list, or show in info.

### ISSUE THREAD

**Issue by l3onCloud** [Veil-Framework/Veil#165]
## Veil version

Veil 3.1.4

## OS Used - all info (architecture, linux flavor, etc)

Kali Linux 2018.1 vbox image from Offensive Security website 
Kali Linux 2018.1 .iso non VM on a newly formatted SSD
4.14.0-kali3-amd64 

- Clean install, ran apt-get update && apt-get upgrade then rebooted VM before I did the Veil install

also made sure I ran this command per the release info about Kali 2018.1:

wget -q -O - https://archive.kali.org/archive-key.asc | apt-key add
then ran 
apt-get update

made sure that sources.list had the correct sources listed.

## How did you install Veil? (Apt, Clone from Github, etc.)
cloned from github in the /opt dir.... never installed this via apt-get install

git clone https://github.com/Veil-Framework/Veil.git

## Did you run the setup script?
cloned fro Github into the /root/opt directory and ran the 
./setup.py -c after I cd into setup.

## Pastebin link to error you are encountering (include console actions you took prior to error)

![wine error](https://user-images.githubusercontent.com/32713693/36311868-aed75582-12fa-11e8-846d-93b2be96f9ed.png)

![veil error1](https://user-images.githubusercontent.com/32713693/36311878-b974eb80-12fa-11e8-9102-aa9d2897c473.png)

![veil error3](https://user-images.githubusercontent.com/32713693/36311889-c240027c-12fa-11e8-8424-527da378a978.png)

I try to list tools and select either 1 or 2 but none of the tools show up it revert back to the prior screen

![veil tools don t list_no_info](https://user-images.githubusercontent.com/32713693/36311895-c94b6e1c-12fa-11e8-936b-ff4e5862ed88.png)

## Expected behavior

Script should run ./Veil.py with all the options as it did when I had Kali 2016.x and Kali 2017.x installed.

## Any additional info you want to tell me

OMG PEBKAC issue, I figured it out. Please close this out, I apologize.

**Comment by rdrzaz** [comment]
OMG PEBKAC issue I figured it out. Please close this out, I apologize.
