### ISSUE TITLE
Unable to create output file

### ISSUE THREAD

**Issue by KrisKnez** [Veil-Framework/Veil#166]
## Veil version
3.1.4

## OS Used - all info (architecture, linux flavor, etc)
Kali Linux 2018.1 x86_64
Non-live version with a user that is not root.

## How did you install Veil? (Apt, Clone from Github, etc.)
git clone

## Did you run the setup script?
I did

## Pastebin link to error you are encountering (include console actions you took prior to error)
I did
./Veil.py
use 1
use 28
set LHOST 127.0.0.1
generate
veil5.exe
1

## Error behavior
Unable to create output file

## Any additional info you want to tell me
I've tried running it with
sudo ./Veil.py
and
sudo su & ./Veil.py
but still the same error occurrs.

**Comment by ChrisTruncer** [comment]
Can you try running as root and seeing if it works that way? I run Veil as a non-root user and am able to run it.

**Comment by ChrisTruncer** [comment]
Closing since I don't have any additional info. Please add more detail if you can and I will try to recreate it.

**Comment by attakercyebr** [comment]
Hello friends
I am after installing the software
In Kali Linux, I get this error when I make a file
please guide me
 [!] ERROR: Unable to create output file.

 [!] Internal error #2. Unable to generate output. Please run /root/Veil-Evasion/config/update.py manually

 [>] Press any key to return to the main menu.

**Comment by syamrag** [comment]
Same here.But some payloads are working and some are bot working. I tryied 	go/meterpreter/rev_https and got the same error but o/meterpreter/rev_tcp is working
