### ISSUE TITLE
Unable to determine OS Information

### ISSUE THREAD

**Issue by SA0-XDZ03** [Veil-Framework/Veil#168]
## Veil version
Veil 3.8

## OS Used - all info (architecture, linux flavor, etc)
Centos 7

## How did you install Veil? (Apt, Clone from Github, etc.)
Clone from Github

## Did you run the setup script?
Yes! Couldn't install as the setup.sh shows unable to determine OS information

## Expected behavior
Unable to install Veil3.0 in Centos 7

## Any additional info you want to tell me
I am very new to centos 7 and tried installing Veil 3.0. And error saying, unable to determine OS is shown.

**Comment by ChrisTruncer** [comment]
Hi there,

Cent isn’t a supported distribution, so unfortunately it won’t work on there. If you are wanting to use it, please check out Debian for example.
