### ISSUE TITLE
Error generating payload

### ISSUE THREAD

**Issue by loneferret** [Veil-Framework/Veil#17]
Hello,
So using Kali Rolling 64bit, generating a meterpreter bind shell, and getting this:
 [?] How would you like to create your payload executable?

     1 - Pyinstaller (default)
 [>] Please enter the number of your choice: 1
cp: cannot create regular file '/opt/pyinstaller-2.0//PyInstaller/bootloader/Windows-32bit/runw.exe': No such file or directory
Traceback (most recent call last):
  File "./Veil-Evasion.py", line 339, in <module>
    controller.MainMenu(args=args)
  File "/root/Veil/Veil-Evasion/modules/common/controller.py", line 885, in MainMenu
    self.outputFileName = self.PayloadMenu(self.payload, args=args)
  File "/root/Veil/Veil-Evasion/modules/common/controller.py", line 806, in PayloadMenu
    return self.OutputMenu(payload, payloadCode, args=args)
  File "/root/Veil/Veil-Evasion/modules/common/controller.py", line 612, in OutputMenu
    supportfiles.supportingFiles(self.payload, OutputFileName, {})
  File "/root/Veil/Veil-Evasion/modules/common/supportfiles.py", line 129, in supportingFiles
    and not os.path.isfile(settings.WINEPREFIX + 'drive_c/Python27/python.exe')):
AttributeError: 'module' object has no attribute 'WINEPREFIX'

Was hoping to not have to spin up a 32bit VM, hopefully there's a fix
Thanks

**Comment by ChrisTruncer** [comment]
Can you try running the update.py script?  Veil-Evasion just needs the WINEPREFIX variable added to the settings file, and the update.py script will handle that.  You should not need to use a 32 bit VM.

**Comment by loneferret** [comment]
Well ran the update.py script.. now getting this:
=========================================================================
 Veil-Evasion | [Version]: 2.28.2
=========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
=========================================================================


 [!] ERROR: Can't find python.exe in /root/.config/wine/veil/drive_c/Python27/
 [!] ERROR: Make sure the python.exe binary exists before using PyInstaller.


Maybe I screwed something up at my end. I'll double back, and see if I missed something 
thanks

**Comment by ChrisTruncer** [comment]
If it helps, this is the value in my settings.py file
WINEPREFIX="/home/flynn/.config/wine/veil/"

If you're on Kali, it is likely
WINEPREFIX="/root/.config/wine/veil/"

**Comment by ChrisTruncer** [comment]
Were you able to get this working?

**Comment by loneferret** [comment]
Yeah.. just didn't update which was odd.

**Comment by ChrisTruncer** [comment]
Ok, thanks, just wanted to verify it was working for you before I closed this!
