### ISSUE TITLE
Still 0 tools, ran update.py in /config

### ISSUE THREAD

**Issue by jake-thewoz** [Veil-Framework/Veil#172]
## Veil version
3.0

## OS Used - all info (architecture, linux flavor, etc)
Rolling Kali, last updated today. Running on VMware, graphical install. I update and upgrade practically every day.

## How did you install Veil? (Apt, Clone from Github, etc.)
Exactly as instructed- cloned from github

## Did you run the setup script?
yup

## Pastebin link to error you are encountering (include console actions you took prior to error)
I'm not sure what the most useful thing to look at is. I've looked at my /etc/veil/settings.py, and it seems to make sense. When I run /config/update.py, it looks similarly to everyone else's.

## Expected behavior
more than 0 tools available

## Any additional info you want to tell me
Would it be wise to start over with a fresh install of Kali? I feel like there's something somewhere I'm doing wrong. My Python is 2.7.14+

Thanks for your help. I've really, really tried to fix this without asking, but I'm at a loss... :/

**Comment by ChrisTruncer** [comment]
You need to use Python 3. But I test this on clean Kali VMs and it loads the tools up.

**Comment by jake-thewoz** [comment]
Ah, yeah I figured Python might have something to do with it. Last week I was trying to get an old outdated tool to run, and had to load some older Python versions.

I'm running a new graphical install of Kali now, so it's taking a minute. I'll close this as soon as I verify it's running. Thanks!

**Comment by ChrisTruncer** [comment]
No prob!

**Comment by jake-thewoz** [comment]
I'm up and running. I had a hiccup, because I used a Kali VM with too little space (20gb). I had to restart with more space. It might be nice to mention the size of Veil somewhere- I didn't realize how big it really was! Thanks again.
