### ISSUE TITLE
No matter how I did, pyinstaller went wrong

### ISSUE THREAD

**Issue by ZTR05** [Veil-Framework/Veil#173]
## Veil version
3.14

## OS Used - all info (architecture, linux flavor, etc)
kali 2018.1 on VMware

## How did you install Veil? (Apt, Clone from Github, etc.)
Clone of course

## Did you run the setup script?
Yup

## Pastebin link to error you are encountering (include console actions you took prior to error)
Traceback (most recent call last):
  File "/opt/veil/PyInstaller-3.2.1//pyinstaller.py", line 14, in <module>
    from PyInstaller.__main__ import run
  File "Z:\opt\veil\PyInstaller-3.2.1\PyInstaller\__main__.py", line 21, in <module>
    import PyInstaller.building.build_main
  File "Z:\opt\veil\PyInstaller-3.2.1\PyInstaller\building\build_main.py", line 34, in <module>
    from .api import PYZ, EXE, COLLECT, MERGE
  File "Z:\opt\veil\PyInstaller-3.2.1\PyInstaller\building\api.py", line 38, in <module>
    from PyInstaller.utils.win32 import winmanifest, icon, versioninfo, winresource
  File "Z:\opt\veil\PyInstaller-3.2.1\PyInstaller\utils\win32\versioninfo.py", line 18, in <module>
    from ...lib import pefile
  File "Z:\opt\veil\PyInstaller-3.2.1\PyInstaller\lib\pefile.py", line 26, in <module>
    from past.builtins import cmp, long
ImportError: No module named 'past'

The installation of Veil is successful
I have already installed the application in your setup.sh
So I think I cannot give you More information
One more is The payload is generated by Cobalt Strke 3.8 using "Veil"
Please Help Me Dude
## Expected behavior
Ruby BE MORE GOOD

## Any additional info you want to tell me
RUBY'S PAYLOAD IS BEST!!!

**Comment by ZTR05** [comment]
Oh, By the way, I am A chinese user
Need I to use VPN for your installation?
Thx

**Comment by ChrisTruncer** [comment]
Please stop opening the same issue. I literally just installed Veil on a clean install without your error. I need additional steps to recreate this, or it is likely isolated to your machine.

**Comment by ZTR05** [comment]
Ok, I will give you some additional steps
Get kali linux from kali.org of VMware
Set language Chinese
sudo ./setup.sh -c
Then Follow your tips
During The installation you will see some red characters of pip is old and cannot get the newest version
Then cd Veil
./Veil.py
use 1
use 29
generate
4
/root/payload.txt(generated by Cobalt Strike v3.8)
1
and is The ERROR TIME
