### ISSUE TITLE
## Veil Evasion 3.0

### ISSUE THREAD

**Issue by UberByte** [Veil-Framework/Veil#174]
Veil 3.0

OS Used - Kali Linux

How did you install Veil? git clone

Did you run the setup script? YES

https://pastebin.com/BNXazy8W

This has worked properly before fresh install

any information in regards to total obliteration of this annoying issue would be extremely helpful.

**Comment by ChrisTruncer** [comment]
That I believe always shows, and shouldn’t impact Veil running.

**Comment by UberByte** [comment]
Thank you very much, literally just solved this issue by attempting Veil. appreciate the feedback! @ChrisTruncer
