### ISSUE TITLE
OS check does not respect --silent 

### ISSUE THREAD

**Issue by killswitch-GUI** [Veil-Framework/Veil#175]
## Veil version
3.0

## OS Used - all info (architecture, linux flavor, etc)
xUbuntu

## How did you install Veil? (Apt, Clone from Github, etc.)
git

## Did you run the setup script?
yes

## Pastebin link to error you are encountering (include console actions you took prior to error)

```
test@XUBUTUN:~/Veil/setup$ sudo ./setup.sh --silent --clean
 ==========================================================================
                  Veil (Setup Script) | [Updated]: 2017-01-24
 ==========================================================================
  [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
 ==========================================================================

 [I] Ubuntu 16 x86_64 detected...


 [!] NON-KALI Users: Before you begin the install, make sure that you have
     the Metasploit-Framework installed before you proceed!

```
## Expected behavior
If passing the silent flag for automated unattended installs this check does not respect the silent flag. Think this could be added?

**Comment by ChrisTruncer** [comment]
Just pushed a fix for it, should be set now. Thanks!

**Comment by killswitch-GUI** [comment]
Awesome thanks @ChrisTruncer !
