### ISSUE TITLE
[!] ERROR: Unable to create output file.

### ISSUE THREAD

**Issue by darenharlan** [Veil-Framework/Veil#176]
## Veil version
3.1.4

## OS Used - all info (architecture, linux flavor, etc)
Linux Mint 18.2 Sonya MATE 64-bit

## How did you install Veil? (Apt, Clone from Github, etc.)
`apt-get -y install git`
`git clone https://github.com/Veil-Framework/Veil-Evasion.git`
`cd Veil-Evasion/`
`cd setup`
`./setup.sh -c`

## Did you run the setup script?
Yes.

## Pastebin link to error you are encountering (include console actions you took prior to error)
I run:
`./Veil.py`

I used:
`use evasion`
`use python/meterpreter/rev_tcp.py`
`set LHOST 192.168.0.7`
`set LPORT 443`
`generate`
`backdoor`
`PyInstaller (1)`

Then, I get this error:
`[!] ERROR: Unable to create output file.`

## Expected behavior
executable generated

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
Veil-Evasion isn't supported. Please use the Veil 3.0 repo (this one)

**Comment by darenharlan** [comment]
I installed using:
`git clone https://github.com/Veil-Framework/Veil.git`

But when I run, I see:
`[Version]: 3.1.4`

Where can I download the Veil 3.0 ?
