### ISSUE TITLE
err:menubuilder:InvokeShellLinker

### ISSUE THREAD

**Issue by darenharlan** [Veil-Framework/Veil#178]
## Veil version
3.0

## OS Used - all info (architecture, linux flavor, etc)
Linux Mint 18.2 Sonya MATE 64-bit

## How did you install Veil? (Apt, Clone from Github, etc.)
`apt-get -y install git`
`git clone https://github.com/Veil-Framework/Veil.git`
`cd Veil/`
`cd setup`
`sudo ./setup.sh -c`

## Did you run the setup script?
Yes, but when I run, I get the follow problem: 

[>] Please enter the path of your metasploit installation: err:menubuilder:InvokeShellLinker failed to extract icon from L"C:\\Program Files (x86)\\AutoIt3\\SciTE\\SciTE.exe"

## Pastebin link to error you are encountering (include console actions you took prior to error)
[>] Please enter the path of your metasploit installation: err:menubuilder:InvokeShellLinker failed to extract icon from L"C:\\Program Files (x86)\\AutoIt3\\SciTE\\SciTE.exe"
err:menubuilder:InvokeShellLinker failed to build the menu
err:menubuilder:InvokeShellLinker failed to extract icon from L"C:\\Program Files (x86)\\AutoIt3\\AU3Info.exe"
err:menubuilder:InvokeShellLinker failed to build the menu
err:menubuilder:InvokeShellLinker failed to extract icon from L"C:\\Program Files (x86)\\AutoIt3\\Aut2Exe\\Aut2Exe_x64.exe"
err:menubuilder:InvokeShellLinker failed to build the menu
err:menubuilder:InvokeShellLinker failed to extract icon from L"C:\\Program Files (x86)\\AutoIt3\\Extras"
err:menubuilder:InvokeShellLinker failed to build the menu
err:menubuilder:InvokeShellLinker failed to extract icon from L"C:\\Program Files (x86)\\AutoIt3\\AutoIt.chm"
err:menubuilder:InvokeShellLinker failed to build the menu
err:menubuilder:InvokeShellLinker failed to extract icon from L"C:\\Program Files (x86)\\AutoIt3\\AutoItX\\ActiveX\\VBScript"
err:menubuilder:InvokeShellLinker failed to build the menu
err:menubuilder:InvokeShellLinker failed to extract icon from L"C:\\Program Files (x86)\\AutoIt3\\AutoIt v3 Website.url"
err:menubuilder:InvokeShellLinker failed to build the menu
err:menubuilder:InvokeShellLinker failed to extract icon from L"C:\\Program Files (x86)\\AutoIt3\\Examples"
err:menubuilder:InvokeShellLinker failed to extract icon from L"C:\\Program Files (x86)\\AutoIt3\\Aut2Exe\\Aut2Exe.exe"
err:menubuilder:InvokeShellLinker failed to build the menu
err:menubuilder:InvokeShellLinker failed to build the menu
err:menubuilder:InvokeShellLinker failed to extract icon from L"C:\\Program Files (x86)\\AutoIt3\\AutoIt3_x64.exe"
err:menubuilder:InvokeShellLinker failed to extract icon from L"C:\\Program Files (x86)\\AutoIt3\\AutoIt3_x64.exe"
err:menubuilder:InvokeShellLinker failed to build the menu
err:menubuilder:InvokeShellLinker failed to build the menu
err:menubuilder:InvokeShellLinker failed to extract icon from L"C:\\Program Files (x86)\\AutoIt3\\AutoIt3.exe"
err:menubuilder:InvokeShellLinker failed to build the menu
err:menubuilder:InvokeShellLinker failed to extract icon from L"C:\\Program Files (x86)\\AutoIt3\\AU3Info_x64.exe"
err:menubuilder:InvokeShellLinker failed to build the menu
err:menubuilder:InvokeShellLinker failed to extract icon from L"C:\\Program Files (x86)\\AutoIt3\\AutoItX\\AutoItX.chm"
err:menubuilder:InvokeShellLinker failed to build the menu

## Expected behavior
Could be installed.
## Any additional info you want to tell me
I already have the metasploit installed on my computer;

**Comment by ChrisTruncer** [comment]
Can you comment about this? Was it actually not an issue and payloads generates correctly?

**Comment by darenharlan** [comment]
I installed Veil using:
`https://github.com/Veil-Framework/Veil.git`

Then I executed :
`cd Veil/`
`cd setup/`
`./setup.sh -c`

But I received this error ^, so I was execute `./Veil.py`, and this is output:  (version 3.1.4)
![captura de tela em 2018-03-20 15-55-20](https://user-images.githubusercontent.com/37000884/37676636-37f1a258-2c57-11e8-9755-a72c92e0f5d8.png)
