### ISSUE TITLE
LHOST problem

### ISSUE THREAD

**Issue by shouyou2016** [Veil-Framework/Veil#18]
## Veil version
3.0

## OS Used - all info (architecture, linux flavor, etc)
Kali linux VM Win10

## Pastebin link to error you are encountering (include console actions you took prior to error)
http://pastebin.com/4NZBAhKy

## Expected behavior
i want to creat msfvenom with a no-ip domain so that i can deal  with dynamic ip address and since i updated Veil Evasion to Veil 3.0 it is no longer working and requires only numbers or else it will not work

## Any additional info you want to tell me
i am still newbie and i am lerning so if i am doing it wrong then please tell my how to creat payload working over wan using veil 
PS : so sorry for my horrible english

**Comment by ChrisTruncer** [comment]
A reverse_tcp payload will not accept a domain name. It will resolve the IP and hardcode the IP, it doesn't code in the domain name

**Comment by ChrisTruncer** [comment]
I just merged in a fix for this, but again, I want to point out, even if you give that specific payload a domain name, it will hard code the ip, not the domain
