### ISSUE TITLE
Setup Issue

### ISSUE THREAD

**Issue by HannanBeiken** [Veil-Framework/Veil#180]
## Veil version
Veil 3.0

## OS Used - all info (architecture, linux flavor, etc)
Parrot 3.11 x64

## How did you install Veil? (Apt, Clone from Github, etc.)
Clone from GitHub

## Did you run the setup script?
./setup.sh (I am root)

## Pastebin link to error you are encountering (include console actions you took prior to error)
https://pastebin.com/sY2vCPci

## Expected behavior
Finish setup and run perfectly

## Any additional info you want to tell me
I ran the script, Went through it, and it got stuck at a part that took a lot of time doing nothing.

**Comment by ChrisTruncer** [comment]
Hi there,

I will close this because I don't support ParrotOS. However, I would try running setup.sh with the -c flag. I would also potentially remove the PyInstaller directory to have Veil install it again (or just delete this at least /opt/veil/PyInstaller-3.2.1/pyinstaller.py).
