### ISSUE TITLE
Veil3 launch issue

### ISSUE THREAD

**Issue by rnbaidya** [Veil-Framework/Veil#183]
Traceback (most recent call last):
  File "./Veil.py", line 7, in <module>
    from lib.common import orchestra
  File "/opt/Veil/lib/common/orchestra.py", line 10, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'
 
facing this when it launch. Please suggest how to solve it.

**Comment by ChrisTruncer** [comment]
Please run the setup script

**Comment by ChrisTruncer** [comment]
Please provide all the information requested when submitting an issue or I can't help effectively.
