### ISSUE TITLE
Could not load gecko

### ISSUE THREAD

**Issue by kdenaeem** [Veil-Framework/Veil#184]
## Veil version
Latest Version

## OS Used - all info (architecture, linux flavor, etc)
Latest Debain, Kali Linux x64

## How did you install Veil? (Apt, Clone from Github, etc.)
Cloned from github

## Did you run the setup script?
Yes I did ./setup.sh -c

## Pastebin link to error you are encountering (include console actions you took prior to error)
`` Could not load wine-gecko. HTML rendering will be disabled.
004e:err:mshtml:create_document_object Failed to init Gecko, returning CLASS_E_CLASSNOTAVAILABLE

Also some other errors 
`` [*] Ensuring this account (root) owns veil output directory (/usr/share/veil-output)...
 [*] Ensuring this account (root) has correct ownership of /root/.config/wine/veil
  There was issues installing the following:

 
Failed to install Wine... Exit code: 100
Failed to install dependencies... Exit code: 100
Failed to install dependencies (Metasploit-Framework)... Exit code: 100
``
``

## Expected behavior
I expected it to download veil

## Any additional info you want to tell me
Wine kept repeating that it was not responding, I pressed the wait option and carried on.
Also I have reinstalled and installed Veil about 3 times. I chose not to nuke current Wine profile because it would take longer and I already had a wine profile

**Comment by usama7628674** [comment]
@CodingAlien Make a backup of .wine directory and then delete the original one from root folder then run `winecfg` command.It will create automatically for you and try to install wine using apt-get method.

**Comment by ChrisTruncer** [comment]
Please delete the current wine environment and reinstall.

**Comment by kdenaeem** [comment]
I tried uninstalling wine and reinstalling still it doesn't work although something else pops up and it says ``wine: Unhandled page fault on read access to 0x7f38ec30 at address 0x7fc3dcf7 (thread 0031), starting debugger...``
but I still get 
There was issues installing the following:

 
``Failed to install Wine... Exit code: 100
Failed to install dependencies... Exit code: 100
Failed to install dependencies (Metasploit-Framework)... Exit code: 100
``
and the error 
``Could not load wine-gecko. HTML rendering will be disabled.
004e:err:mshtml:create_document_object Failed to init Gecko, returning CLASS_E_CLASSNOTAVAILABLE
``

**Comment by kdenaeem** [comment]
as in uninstalling wine you guys mean doing ``rm -rf /root/.config/wine/veil`` 
right? Or the whole thing?

**Comment by CodingAlien** [comment]
Tried installing it for the 5th time it worked!
Thanks guys but how do I open it? It says [I] Done!
but I cannot find an application named veil. I would expect it to come up with the veil gui and ``please enter your command`` but nothing it happening?

**Comment by kdenaeem** [comment]
Thanks a lot uninstalling win ``apt-get remove wine`` and reinstalling worked

**Comment by ChrisTruncer** [comment]
Closing since the issue appears to be resolved
