### ISSUE TITLE
python importerror

### ISSUE THREAD

**Issue by xznhj8129** [Veil-Framework/Veil#185]
## Veil version
3.0

## OS Used - all info (architecture, linux flavor, etc)
Linux Mint 18.3 Sylvia x86_64

## How did you install Veil? (Apt, Clone from Github, etc.)
clone

## Did you run the setup script?
yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
https://pastebin.com/1paLpzmb
ImportError: No module named 'context_locals'`

## Expected behavior
no error?

**Comment by ChrisTruncer** [comment]
That looks to be an error within Python itself, vs something in Veil’s code. It can’t seem to find the context_locals library/module. Can you look to see if this is correct? I don’t really support Mint (primarily Debian or Kali Linux), but may try to look into this. 

Also, you put down you are using version 3.0, versus 3.1.5. Are you sure you are using the correct version?

**Comment by xznhj8129** [comment]
Me neither, i've looked for any clue as to what this is but there is no result anywhere for this; i'm the first to experience it apparently. I am using whatever version is on the git repo right now, and it says 3.0.

**Comment by ChrisTruncer** [comment]
I have a Linux Mint system, and when I run ./Veil.py, I am presented with the main menu screen of Veil.

**Comment by ChrisTruncer** [comment]
closing since I haven't heard back
