### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by dufywihi** [Veil-Framework/Veil#187]
@ChrisTruncer
 
Hey, I tried (literally) 20 different payload types with many different options. Every single one was immediately detected by a fully patched Windows 10 VM only running Windows Defender. Is Veil still a viable option for creating undetectable payloads?

Can you clarify what you mean when [you say](https://github.com/Veil-Framework/Veil/issues/156):

> "You could modify the template that is currently in Veil."

And when [you say](https://github.com/Veil-Framework/Veil/issues/107):

> "Please use non-defaults."

What templates and what non-defaults are you referring to?

**Comment by ChrisTruncer** [comment]
Yes Veil still works, I use it on pen tests. There is a template that each payload is made from. You could look into modifying the templates to bypass additional AVs. The default values are related to the options you can set with each payload. Don’t just use the default ones. Customize it to your target.

**Comment by dufywihi** [comment]
Thanks for replying. Is [this](https://github.com/Veil-Framework/Veil/blob/master/tools/evasion/payloads/template.py) one of the templates? Can you provide a quick/simple example of modifying the default values to help bypass detection? Which values, exactly?

**Comment by ChrisTruncer** [comment]
I unfortunately do not have the time to cover every option. Please experiment with them and see what works best.

That is a base template, but not what Veil uses. Please look in the language specific folders within Veil to see the templates.
