### ISSUE TITLE
No module named 'tool'

### ISSUE THREAD

**Issue by Jared-Harrington-Gibbs** [Veil-Framework/Veil#188]
## Veil version
Veil 3.0 (fresh git pull)

## OS Used - all info (architecture, linux flavor, etc)
`Linux kali 4.14.0-kali3-amd64 \#1 SMP Debian 4.14.17-1kali1 (2018-02-16) x86_64 GNU/Linux`

## How did you install Veil? (Apt, Clone from Github, etc.)
`git clone https://github.com/Veil-Framework/Veil.git`

## Did you run the setup script?
Yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
https://pastebin.com/8XmpF8nc

## Expected behavior
Installer Starts

### Note 1
Veil works if I don't update and clean kali.

### Note 2
I installed kali from the offensive security OVA

### Note 3
I am using vmware workstation 12 for virtualization

**Comment by leesoh** [comment]
I had the same issue when I didn't run `update-config.py` from `config/`

**Comment by g0tmi1k** [comment]
I believe once #189 is merged in, this should be fixed.

@leesoh is also correct, re-running: `cd ./config/; ./update-config.py` *should* also fix it.

**Comment by Jared-Harrington-Gibbs** [comment]
Hey, @leesoh and @g0tmi1k 

I had already run update-config.py twice before posting this issue.
I will check if the issue persists after the merging of #189.
