### ISSUE TITLE
Pyinstaller

### ISSUE THREAD

**Issue by yesiboot** [Veil-Framework/Veil#190]
I have the following problem when creating a pioneer someone can help me please.
How do I solve the problem? I have not been able so far
or how could I eliminate veil if I did not solve the problem to reinstall again

 How would you like to create your payload executable?

     1 - Pyinstaller (default)
     2 - Py2Exe

 [>] Please enter the number of your choice: 1
cp: cannot create regular file '/opt/veil/PyInstaller-3.2.1//PyInstaller/bootloader/Windows-32bit/runw.exe': No such file or directory
fixme:winediag:start_process Wine Staging 2.4 is a testing version containing experimental patches.
fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
C:\Python34\python.exe: can't open file '/opt/veil/PyInstaller-3.2.1//pyinstaller.py': [Errno 2] No such file or directory
fixme:msvcrt:__clean_type_info_names_internal (0x1e2932cc) stub

===============================================================================
                                   Veil-Evasion
===============================================================================
      [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
===============================================================================

 [!] ERROR: Unable to create output file.
 [*] Source code written to: /opt/veil/output/source/test.py
 [*] Metasploit RC file written to: /opt/veil/output/handlers/test.rc

**Comment by yesiboot** [comment]
my version of linux is linux mint sonya 18.2

**Comment by g0tmi1k** [comment]
I believe once #189 is merged in, this should be fixed.

- - - 

Edit: Merged! Could you update Veil and re-test with v3.1.6

**Comment by ChrisTruncer** [comment]
Let us know!

**Comment by ChrisTruncer** [comment]
Closing due to no response
