### ISSUE TITLE
Wine Package on Ubuntu 17.10

### ISSUE THREAD

**Issue by leesoh** [Veil-Framework/Veil#192]
## Veil version
3.0

## OS Used - all info (architecture, linux flavor, etc)
Ubuntu 17.10

## How did you install Veil? (Apt, Clone from Github, etc.)
Clone fom Github

## Did you run the setup script?
Yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
Ran `update-config.py`, then ran `./Veil.py --setup`. Got the following errors: https://pastebin.com/8anpUHAA

## Expected behavior
Seamless installation.

## Any additional info you want to tell me
I did a bit of digging around and it seems like wine-stable includes wine and wine64. I tried installing the package manually and rerunning setup, but got a bunch of these errors: https://pastebin.com/tNj6eq4A

I'll poke around at this when I get some cycles. Throwing it up here in case anyone else runs into the same.

**Comment by g0tmi1k** [comment]
So the package name in Ubuntu 17.10 (Artful Aardvark) isn't "wine"?  ~ https://packages.ubuntu.com/search?suite=artful&keywords=wine

What is it then?

**Comment by leesoh** [comment]
![image](https://user-images.githubusercontent.com/1276654/38686790-6b6513b2-3e32-11e8-92e9-7fe286b98ed6.png)

**Comment by leesoh** [comment]
Just tested with `wine-stable` and generated a CS, PyInstaller, and Ruby payload with no issues. #193 should fix it.

**Comment by leesoh** [comment]
This changed in artful: https://packages.ubuntu.com/search?keywords=wine

Will fix and submit PR hopefully by end of weekend.

**Comment by leesoh** [comment]
I'm going to hold off on making any changes until @g0tmi1k is finished with #189

**Comment by ChrisTruncer** [comment]
Thanks, once we get that merged in, I’ll look to get this merged after

**Comment by anasamsha5** [comment]
Same with kali linux
What is the soluotion?

**Comment by g0tmi1k** [comment]
@anasamsha5 as stated above, wait until #189 is merged in. 
Else as you are using Kali, switch to `apt install veil` .
- - -
Edit Merged!

**Comment by leesoh** [comment]
PR #201 is in!

**Comment by ChrisTruncer** [comment]
Closing since this is merged in
