### ISSUE TITLE
 Internal error #2. Unable to generate output.

### ISSUE THREAD

**Issue by slavadba** [Veil-Framework/Veil#194]
## Veil version
2.28.2

## OS Used - all info (architecture, linux flavor, etc)
Linux kali 4.14.0-kali3-amd64 #1 SMP Debian 4.14.12-2kali1 (2018-01-08) x86_64 GNU/Linux

## How did you install Veil? (Apt, Clone from Github, etc.)
git clone https://github.com/Veil-Framework/Veil-Evasion

## Did you run the setup script?
yes:
/root/Veil-Evasion/setup/setup.sh -c

## Pastebin link to error you are encountering (include console actions you took prior to error)
.
.
 [?] How would you like to create your payload executable?

     1 - Pyinstaller (default)
     2 - Pwnstaller (obfuscated Pyinstaller loader)
     3 - Py2Exe

 [>] Please enter the number of your choice: 1
Traceback (most recent call last):
  File "/opt/veil/PyInstaller-3.2//pyinstaller.py", line 14, in <module>
    from PyInstaller.__main__ import run
  File "Z:\opt\veil\PyInstaller-3.2\PyInstaller\__main__.py", line 21, in <module>
    import PyInstaller.building.build_main
  File "Z:\opt\veil\PyInstaller-3.2\PyInstaller\building\build_main.py", line 32, in <module>
    from ..depend import bindepend
  File "Z:\opt\veil\PyInstaller-3.2\PyInstaller\depend\bindepend.py", line 26, in <module>
    from . import dylib, utils
  File "Z:\opt\veil\PyInstaller-3.2\PyInstaller\depend\utils.py", line 25, in <module>
    from ..lib.modulegraph import modulegraph
  File "Z:\opt\veil\PyInstaller-3.2\PyInstaller\lib\modulegraph\modulegraph.py", line 12, in <module>
    import pkg_resources
ImportError: No module named pkg_resources
=========================================================================
 Veil-Evasion | [Version]: 2.28.2
=========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
=========================================================================

 [!] ERROR: Unable to create output file.

 [!] Internal error #2. Unable to generate output. Please run /root/Veil-Evasion/config/update.py manually

 [>] Press any key to return to the main menu.

## Expected behavior
generate payload. 

## Any additional info you want to tell me
I run /root/Veil-Evasion/config/update.py but error its still the same. I also check permissions on directories:

root@kali:/mnt/disk_C/Users/РЎР»Р°РІР°/Desktop/HACK THE PLANET/Veil# ls -la /usr/share/veil-output/source/
total 16
drwxr-xr-x 2 root root 2048 Apr  8 17:54 .
drwxr-xr-x 6 root root 2048 Apr  8 17:08 ..
-rw-r--r-- 1 root root 2865 Apr  8 17:54 after_winbind_install.py
-rw-r--r-- 1 root root 2783 Apr  8 17:15 veilaes1.py
-rw-r--r-- 1 root root 2890 Apr  8 17:08 veilaes.py
root@kali:/mnt/disk_C/Users/РЎР»Р°РІР°/Desktop/HACK THE PLANET/Veil#
root@kali:/mnt/disk_C/Users/РЎР»Р°РІР°/Desktop/HACK THE PLANET/Veil# ls -la /usr/share/veil-output/compiled/
total 4
drwxr-xr-x 2 root root 2048 Apr  8 16:55 .
drwxr-xr-x 6 root root 2048 Apr  8 17:08 ..
root@kali:/mnt/disk_C/Users/РЎР»Р°РІР°/Desktop/HACK THE PLANET/Veil#

**Comment by ChrisTruncer** [comment]
Veil-Evasion is not supported, that’s why there are no issues allowed for it. Please use Veil instead.

**Comment by shankavinvisr** [comment]
Veil-Evasion | [Version]: 2.28.2
=========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
=========================================================================

 [!] ERROR: Unable to create output file.

 [!] Internal error #2. Unable to generate output. Please run /root/Veil-Evasion/config/update.py manually

 [>] Press any key to return to the main menu.
