### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by anasamsha5** [Veil-Framework/Veil#196]
## OS Used - all info (architecture, linux flavor, etc)
MacOS high Sierra

## How did you install Veil? (Apt, Clone from Github, etc.)
Clone from Github
## Did you run the setup script?
Yes 

## Pastebin link to error you are encountering (include console actions you took prior to error)
https://pastebin.com/jfV76dPv
## Expected behavior

To be installed
## Any additional info you want to tell me(Wine) Python 3.4.4... Exit code: 2
Failed to install pywin32-220.win32-py3.4.exe... Exit code: 2
Failed to install pycrypto-2.6.1.win32-py3.4.exe... Exit code: 2
Bad hash for PyInstaller.tar.gz!
Failed to install (Wine) Ruby.exe... Exit code: 2
Bad hash for go153x64.tar.gz!

**Comment by g0tmi1k** [comment]
It looks like the `git clone` command failed for some reason - the one used to pull down the setup files.
I suggest re-running the `setup.sh` with `--force` flag.
- - - 

Edit: Could you update Veil and re-test with v3.1.6?

**Comment by ChrisTruncer** [comment]
closing due to no response. Please create a new issue if this still is a problem
