### ISSUE TITLE
Unable to create output file

### ISSUE THREAD

**Issue by krishnenduash** [Veil-Framework/Veil#198]
## Veil version
![kalilinux 2013 march-2018-04-21-01-00-35](https://user-images.githubusercontent.com/30100922/39058526-7055a1ec-44ff-11e8-93c7-6d5c5d1ef947.png)

## OS Used - all info (architecture, linux flavor, etc)
kali1 (2018-03-21) x86_64 GNU/Linux

## How did you install Veil? (Apt, Clone from Github, etc.)
apt

## Did you run the setup script?
yes

## Expected behavior

![kalilinux 2013 march-2018-04-21-00-56-30](https://user-images.githubusercontent.com/30100922/39058546-7fe460f8-44ff-11e8-8ae7-7a6ba98f2bcc.png)

**Comment by erron403** [comment]
This error show because GOROOT or GOPATH is no found.
check for using:-
     go env GOROOT
     go env GOPATH

the outfile.py contain path:-
     GOROOT=/usr/local/go  which are may be different in your os.
this bug in veil.

**Comment by g0tmi1k** [comment]
Could you update Veil and re-test with v3.1.6?

**Comment by lori8816** [comment]
I have a similar problem
![kail](https://user-images.githubusercontent.com/37245968/39151962-074e026c-4747-11e8-8212-11df58c4505c.jpg)

**Comment by ChrisTruncer** [comment]
Please don’t hijack threads and use the latest version of Veil.

**Comment by ChrisTruncer** [comment]
closing due to no response

**Comment by attakercyebr** [comment]
[!] ERROR: Unable to create output file.

 [!] Internal error #2. Unable to generate output. Please run /root/Veil-Evasion/config/update.py manually
