### ISSUE TITLE
error auxuliary/macro_converter

### ISSUE THREAD

**Issue by gearcapitan** [Veil-Framework/Veil#2]
![kali 2016-2017-03-03-10-02-34](https://cloud.githubusercontent.com/assets/13740942/23558297/aa67a666-fff8-11e6-977e-f098fd7143ff.png)

**Comment by ChrisTruncer** [comment]
There's nothing in here

**Comment by ChrisTruncer** [comment]
Thanks for reporting this, I'll check it out and push a fix

**Comment by ChrisTruncer** [comment]
This should now be fixed.  Thanks for reporting the issue
