### ISSUE TITLE
Veil 3.0 is breaking Kali linux

### ISSUE THREAD

**Issue by HGC0DE** [Veil-Framework/Veil#20]
## Veil version
3.0

## OS Used - all info (architecture, linux flavor, etc)
Kali Linux 2016.2

## Issue
After I installed Veil by running setup.sh, when ever I would restart or shutdown the box  would never be able to log back in. I would be able to put in the username and password but it would just restart the process.

**Comment by ChrisTruncer** [comment]
Veil doesn't do anything to modify how the system boots

**Comment by HGC0DE** [comment]
The system would work fine until i would install Veil. Could Wine have anything to do with it?

**Comment by ChrisTruncer** [comment]
No, wine is already on Kali

**Comment by HGC0DE** [comment]
Then what could the probelm be?

**Comment by ChrisTruncer** [comment]
I can't really tell you the answer to that, I'm not sure. But Veil doesn't mess with anything in your system's startup

**Comment by michael-bey** [comment]
I have noticed this issue in previous versions of Veil as well - the problem has something to do with Wine32. 

See:
https://superuser.com/questions/1085636/what-to-do-wine32-installation-breaks-my-kali-guest-and-prevent-login
http://unix.stackexchange.com/questions/292620/kali-stuck-at-log-in-screen-after-i-installed-veil-evasion

**Comment by ChrisTruncer** [comment]
thanks for posting that info!

**Comment by Blcktape** [comment]
I am experiencing the same issue here myself, even with the above resources i could not get it fixed.
I tryed the following:
```
apt-get remove wine
apt-mark hold libgl1-mesa-dri
apt-get install wine
```
and then
```
apt-get -y install git
git clone https://github.com/Veil-Framework/Veil.git
cd Veil/
cd setup
sudo ./setup.sh -c
```
Also tryed the following after breaking my installation:
`apt-get install kali-Linux-all`

but nothing seem to work.
I am using the stock image: Kali-Linux-2016.2-vm-amd64 on VMware Workstation

**Comment by attackercan** [comment]
Also have same issue here - Veil broke Kali Linux, and I can't log in after reboot.
It seems that we're all using same image (`Kali-Linux-2016.2-vm-amd64` on VMWare).

Is it in your power to alert users of the same image to prevent from installing Veil from git sources, untill the issue gets fixed?

Current issue should be definately re-opened and investigated.

**Comment by attackercan** [comment]
I just did `apt-get update && apt-get dist-upgrade` and logged in.
This can be a solution.

**Comment by ChrisTruncer** [comment]
Veil doesn't break Kali, there's nothing it installs or modifies that breaks authentication, booting the OS, etc. I also have always stated that the best way to install Veil is to clone from github. The package in kali's repos is old, and that's beyond my control.

**Comment by ChrisTruncer** [comment]
If doing an apt-get update && apt-get dist-upgrade worked, then that shows that Veil did not break your system.

**Comment by tomesh365** [comment]
Sir ...i don't know what but veil has something to do with startup of kali linux .....i use linux and windows with dual boot ...but after installing veil using GitHub and installation of all necessary files for veil ....i restart my pc and then linux become unavailable....it happenes everytime....i installed linux for a no. Of times but can't fix it ...now I installed linux 2020.1 it still gives the issue....so what m i supposed to do ?again reinstalling linux for my rest of life?

**Comment by tomsey0** [comment]
after successful completion of the installation of veil framework when i reboot the system the kali linux got breakand could not boot up .....bu via recovery mode i login and saw the files were properly there ....so i did
apt-get update
apt-get upgrade and it took approximately 900 mib of data to download and install some files and then it worked fine as it was working earlier.
