### ISSUE TITLE
Review dependencies

### ISSUE THREAD

**Issue by ChrisTruncer** [Veil-Framework/Veil#200]
## Veil version
Current version

## OS Used - all info (architecture, linux flavor, etc)
All

## How did you install Veil? (Apt, Clone from Github, etc.)
Clone

## Did you run the setup script?
Yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
N/A

## Expected behavior
Check dependencies to see what can be removed.

## Any additional info you want to tell me
n/a

**Comment by sphereict** [comment]
Hi
All the payloads in Veil are detected in windows 10 I tried each and everyone.

Would be great if we could bypass AV in windows 10 

Looking forward to your reply.
Sincerely.
G

**Comment by g0tmi1k** [comment]
@sphereict Very off-topic for this issue.
You should make a new issue up - rather than hijack

**Comment by pieterhouwen** [comment]
Veil version

Current version
OS Used - all info (architecture, linux flavor, etc)

Kali Linux 2018.2
How did you install Veil? (Apt, Clone from Github, etc.)

Both clone and apt
Did you run the setup script?

Yes
Pastebin link to error you are encountering (include console actions you took prior to error)

https://pastebin.com/5G6GdWUV (please read until the end)
Expected behavior

Update dependencies so veil actually runs.
Any additional info you want to tell me

I've installed both lib and common in pip and pip3 didn't seem to help.

**Comment by ChrisTruncer** [comment]
Please look at the readme and run the command that it shows to run and install Veil

**Comment by pieterhouwen** [comment]
**root@supersecretkali:/opt/BypassAV/Veil# nano README.md 
root@supersecretkali:/opt/BypassAV/Veil# /usr/share/veil/config/setup.sh --force --silent
 ==========================================================================
                 Veil (Setup Script) | [Updated]: 2018-05-08
 ==========================================================================
     [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
 ==========================================================================

                 os = kali
          osversion = 2018.2
       osmajversion = 2018
               arch = x86_64
           trueuser = root
   userprimarygroup = root
        userhomedir = /root
            rootdir = /usr/share/veil
            veildir = /var/lib/veil
          outputdir = /var/lib/veil/output
    dependenciesdir = /var/lib/veil/setup-dependencies
            winedir = /var/lib/veil/wine
          winedrive = /var/lib/veil/wine/drive_c
            gempath = Z:\var\lib\veil\wine\drive_c\Ruby187\bin\gem

 [I] Kali Linux 2018.2 x86_64 detected...

 [I] Silent Mode: Enabled
 [I]  Force Mode: Enabled


 [?] Are you sure you wish to install Veil?

     Continue with installation? ([y]es/[s]ilent/[N]o): S



 [*] Initializing package installation



 [*] Pulling down binary dependencies

 [*] Empty folder... git cloning

Cloning into '/var/lib/veil/setup-dependencies'...
remote: Counting objects: 12, done.
remote: Total 12 (delta 0), reused 0 (delta 0), pack-reused 12
Unpacking objects: 100% (12/12), done.


 [*] Installing Wine

 [*] Already have x86 architecture added...



 [*] Installing Wine 32-bit and 64-bit binaries (via APT)



 [*] [ALERT]: Existing Veil Wine environment detected at: /var/lib/veil/wine

     Do you want to nuke it? ([y]es/[N]o): Y

 [*] Deleting existing Veil Wine environment...

 [*] Creating new Veil Wine environment in: /var/lib/veil/wine

 [*] Initializing Veil's Wine environment...

0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
0012:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0012:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0012:err:ole:get_local_server_stream Failed: 80004002
0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
0014:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0014:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0014:err:ole:get_local_server_stream Failed: 80004002
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/var/lib/veil/wine' has been updated.
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/var/lib/veil/wine' has been updated.
 [*] Veil Wine environment successfully created!



 [*] Finished package installation



 [*] Initializing (OS + Wine) Python dependencies installation...



 [*] Installing (Wine) Python...

 [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)

000f:err:service:process_send_command receiving command result timed out
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
Ignoring indexes: https://pypi.python.org/simple
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
0014:err:service:process_send_command receiving command result timed out
0029:err:plugplay:handle_bus_relations Failed to load driver L"WineHID"
Successfully installed pip-7.1.2 setuptools-18.2


 [*] Installing (Wine) Python dependencies...



 [*] Installing (Wine) Python's pywin32-220.win32-py3.4.exe...

 [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)

warning [pywin32-220.win32-py3.4.exe]:  192288 extra bytes at beginning or within zipfile
  (attempting to process anyway)
000f:err:service:process_send_command receiving command result timed out


 [*] Installing (Wine) Python's pycrypto-2.6.1.win32-py3.4.exe...

 [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)

warning [pycrypto-2.6.1.win32-py3.4.exe]:  191515 extra bytes at beginning or within zipfile
  (attempting to process anyway)


 [*] Installing (OS) Python's PyInstaller (via TAR)



 [*] Installing (Wine) Python's PIP pefile

Collecting pip
  Downloading https://files.pythonhosted.org/packages/5f/25/e52d3f31441505a5f3af41213346e5b6c221c9e086a166f3703d2ddaf940/pip-18.0-py2.py3-none-any.whl (1.3MB)
    100% |################################| 1.3MB 312kB/s 
Installing collected packages: pip
  Found existing installation: pip 7.1.2
    Uninstalling pip-7.1.2:
      Successfully uninstalled pip-7.1.2
Successfully installed pip-18.0
0015:err:service:process_send_command receiving command result timed out
002a:err:plugplay:handle_bus_relations Failed to load driver L"WineHID"
Collecting future
  Downloading https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz (824kB)
    100% |████████████████████████████████| 829kB 4.1MB/s ta 0:00:01
Installing collected packages: future
  Running setup.py install for future ... done
Successfully installed future-0.16.0
Collecting pefile
  Downloading https://files.pythonhosted.org/packages/7e/9b/f99171190f04cd23768547dd34533b4016bd582842f53cd9fe9585a74c74/pefile-2017.11.5.tar.gz (61kB)
    100% |████████████████████████████████| 71kB 1.2MB/s ta 0:00:01
Requirement already satisfied: future in c:\python34\lib\site-packages (from pefile) (0.16.0)
Installing collected packages: pefile
  Running setup.py install for pefile ... done
Successfully installed pefile-2017.11.5


 [*] Finished (Wine + OS) Python dependencies installation



 [*] Initializing (Wine) Ruby installation...



 [*] Installing (Wine) Ruby & dependencies

 [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)

000f:err:service:process_send_command receiving command result timed out


 [*] Installing (Wine) Ruby OCRA gem...


Z:\var\lib\veil\setup-dependencies>Z:\var\lib\veil\wine\drive_c\Ruby187\bin\gem install --force --local ocra-1.3.6.gem 
Successfully installed ocra-1.3.6
1 gem installed
Installing ri documentation for ocra-1.3.6...
Installing RDoc documentation for ocra-1.3.6...


 [*] Extracting (Wine) Ruby dependencies...



 [*] Finished Ruby installation



 [*] Initializing Go installation...



 [*] Installing Go x86_64 (via TAR)



 [*] Finished Go installation



 [*] Initializing AutoIT installation...



 [*] Installing (Wine) AutoIT

 [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)

0014:err:service:process_send_command receiving command result timed out
002a:err:plugplay:handle_bus_relations Failed to load driver L"WineHID"
000f:err:service:process_send_command receiving command result timed out


 [*] Finished AutoIT installation



 [*] Updating Veil configuration...

 [*] Detected current Veil settings. Removing...


 Veil Configuration:
 [*] OPERATING_SYSTEM = Kali
 [*] TERMINAL_CLEAR = false
 [*] VEIL_PATH = /usr/share/veil/
 [*] WINEPREFIX = /var/lib/veil/wine/
 [*] TEMP_PATH = /tmp/
 [*] METASPLOIT_PATH = /usr/share/metasploit-framework/
 [*] MSFVENOM_PATH = /usr/bin/
 [*] MSFVENOM_OPTIONS = 
 [*] PYINSTALLER_PATH = /var/lib/veil/PyInstaller-3.2.1/
 [*] GOLANG_PATH = /var/lib/veil/go/



 Veil-Evasion Configuration:
 [*] PAYLOAD_SOURCE_PATH = /var/lib/veil/output/source/
 [*] PAYLOAD_COMPILED_PATH = /var/lib/veil/output/compiled/
 [*] HANDLER_PATH = /var/lib/veil/output/handlers/
 [*] HASH_LIST = /var/lib/veil/output/hashes.txt
 [I] Path '/etc/veil/' Created
 [I] Configuration File Written To: '/etc/veil/settings.py'



 [*] Ensuring this account (root) owns veil output directory (/var/lib/veil/output)...

 [*] Ensuring this account (root) has correct ownership of /var/lib/veil/wine



 [*] Finished Veil configuration...



 [*] Finished environment checks



 [I] If you have any errors running Veil, run: './Veil.py --setup' and select the nuke the wine folder option



 [I] Done!

root@supersecretkali:/opt/BypassAV/Veil# 0014:err:service:process_send_command receiving command result timed out
002a:err:plugplay:handle_bus_relations Failed to load driver L"WineHID"

root@supersecretkali:/opt/BypassAV/Veil# veil
Traceback (most recent call last):
  File "./Veil.py", line 16, in <module>
    from lib.common import helpers
ModuleNotFoundError: No module named 'lib.common'
root@supersecretkali:/opt/BypassAV/Veil# 
**

**Comment by pieterhouwen** [comment]
It's the same when i type veil and python3 Veil.py

**Comment by ChrisTruncer** [comment]
@pieterhouwen - the point of this github issue was to look at reducing the dependencies required for Veil, not for the issue you are encountering. Please create a separate issue to discuss this.

With that said, I also just installed Veil on a clean instance of Kali and I did not run into any issues. I ran via the command in the readme and it installed and started immediately.
