### ISSUE TITLE
Can't find the WINE profile for AuotIT v3

### ISSUE THREAD

**Issue by lowssy** [Veil-Framework/Veil#204]
I try to install Veil and all are fine but when it finish and i run "./Veil.py" the next message appear:
>$ [!] ERROR #2-3: Can't find the WINE profile for AuotIT v3 (/var/lib/veil/wine//drive_c/Program Files/AutoIt3/Aut2Exe/Aut2exe.exe).   Run: /home/$USER/Veil/config/setup.sh --force --silent

The commands that i used to install it are:
>$ git clone https://github.com/Veil-Framework/Veil.git
>$ cd Veil
>$ ./config/setup.sh
I execute them without root.
And if i execute them with root it remains freeze.

Veil version: Current version
OS: Ubuntu 16.04
Yes, i run the setup.sh script

I already executed the command:
>$ ./config/setup.sh --force --silent

In the AutoIt installation i put:
>$ Use native x86 tools by default(recommended for compatibility)

I searched that directory (.../AutoIt3/Aut2Exe/) and i found that this directory was not in (.../drive_c/Program Files/), was in (.../drive_c/Program Files (x86)/...), so ¿i need to copy it into Program Files or i installed him bad?

Please help me :cry: 
I can't continue :disappointed:
Sorry if my english is bad :laughing:

**Comment by ChrisTruncer** [comment]
Please provide the information requested when creating an issue.

**Comment by lowssy** [comment]
Sorry, i already put the information 😆

**Comment by usama7628674** [comment]
@ChrisTruncer Same here.
![image](https://user-images.githubusercontent.com/29252277/39670511-d3ddfdaa-511f-11e8-854e-df80277be53c.png)

installed it using apt-get method
using kali-linux 2018.2
veil version  3.1.7
 Use native x86 tools by default(recommended for compatibility)
Autoit3 folder does exist in program files(x86) but not in program files.
I copied autoit3 folder from program files(x86) to program files and then veil was working fine.

**Comment by lowssy** [comment]
Thank you 😃

**Comment by ChrisTruncer** [comment]
I just installed Veil on a clean install of Kali via apt, and I was successfully able to generate an AutoIt payload and did not have the above error.

Can you please retry on a clean Kali vm?

**Comment by usama7628674** [comment]
@ChrisTruncer It's not about installation.The pic that I posted above was error that occurred straight after installation of veil.The necessary solution that I did was copied autoit3 folder from program files(x86) to program files and then veil was working fine.

**Comment by ChrisTruncer** [comment]
I think something happened during your install process though because that’s not where Veil installs AutoIt. Once you moved it, it was in the correct location and then started working.

**Comment by usama7628674** [comment]
> I think something happened during your install process though because that’s not where Veil installs AutoIt

@ChrisTruncer I don't think so autoit3 setup default points to program files(x86) folder so I just installed it there.

**Comment by ChrisTruncer** [comment]
I can confirm it is something isolated to your install process/environment. I have installed Veil on a clean Kali VM using the process outlined in the README, and I did not need to move any Auto IT directory. It also was not in the Program Files(x86) folder (there wasn't one in the first place).

**Comment by john-kyuhae-lee** [comment]
@ChrisTruncer Ran into the same issue. I had the same setup as @NIGHTMARE06. Ubuntu 16.04, not Kali to emphasize. I was able to resolve this with the same solution by copying AutoIt3 from Program Files (x86) to Program Files. Not a big problem, but to let you know it does happen. Thanks!

**Comment by alexverboon** [comment]
had the same issue, solution from @usama7628674 worked for me as well.

**Comment by Ahmed7fathi** [comment]
same as @alexverboon i copied the autoit3 directory and its working fine 
i think there's problem with installation

**Comment by ChrisTruncer** [comment]
This appears to only be limited to a small number of people. I am testing this on Kali, and I am not running into the issue. Veil installs fine and has no problem generating AutoIt binaries. I do appreciate the heads up in case anyone else does run into this issue.

**Comment by TSeeker1000** [comment]
Thank you all.  Experienced this issue, and fix above worked fine.

**Comment by jeffmcjunkin** [comment]
Confirmed on Ubuntu 16.04.5. To give an easy copy-pastable fix for others, the below fixed the issue after following the normal setup instructions:
`cp -R '/var/lib/veil/wine/drive_c/Program Files (x86)/AutoIt3' '/var/lib/veil/wine/drive_c/Program Files/'`

For a Metasploit install made by https://github.com/trustedsec/ptf, here's my entire install script:
```
sudo git clone https://github.com/Veil-Framework/Veil --depth=1 /opt/veil
pushd /opt/veil
cd config
echo "/opt/metasploit-framework/bin/" | sudo ./setup.sh -s
# Fix for https://github.com/Veil-Framework/Veil/issues/204
cp -R '/var/lib/veil/wine/drive_c/Program Files (x86)/AutoIt3' '/var/lib/veil/wine/drive_c/Program Files/'
popd
```

**Comment by memir2012** [comment]
thansk for answer. i run it

**Comment by bigj75024** [comment]
> 
> 
> @ChrisTruncer Same here.
> ![image](https://user-images.githubusercontent.com/29252277/39670511-d3ddfdaa-511f-11e8-854e-df80277be53c.png)
> 
> installed it using apt-get method
> using kali-linux 2018.2
> veil version 3.1.7
> Use native x86 tools by default(recommended for compatibility)
> Autoit3 folder does exist in program files(x86) but not in program files.
> I copied autoit3 folder from program files(x86) to program files and then veil was working fine.

Worked great! Thanks for the tip!

**Comment by 1captainnemo1** [comment]
Simply fire this command :cp -R '/var/lib/veil/wine/drive_c/Program Files (x86)/AutoIt3' '/var/lib/veil/wine/drive_c/Program Files/'
Thats will resolve th issue 
the next will free up 32 megs of drive space that AutoIt3 is occupying in the programfiles(x86) folder... for the HDD cleanup nazis : cd "/var/lib/veil/wine/drive_c/Program Files (x86)" followed by rm -R AutoIt3 
reboot
should work fine

**Comment by AhmetPayaslioglu** [comment]
> Confirmed on Ubuntu 16.04.5. To give an easy copy-pastable fix for others, the below fixed the issue after following the normal setup instructions:
> `cp -R '/var/lib/veil/wine/drive_c/Program Files (x86)/AutoIt3' '/var/lib/veil/wine/drive_c/Program Files/'`
> 
> For a Metasploit install made by https://github.com/trustedsec/ptf, here's my entire install script:
> 
> ```
> sudo git clone https://github.com/Veil-Framework/Veil --depth=1 /opt/veil
> pushd /opt/veil
> cd config
> echo "/opt/metasploit-framework/bin/" | sudo ./setup.sh -s
> # Fix for https://github.com/Veil-Framework/Veil/issues/204
> cp -R '/var/lib/veil/wine/drive_c/Program Files (x86)/AutoIt3' '/var/lib/veil/wine/drive_c/Program Files/'
> popd
> ```

Thanks for answer . I did.

**Comment by abarracu** [comment]
Hi all, I have a similar problem of you but on ParrotOs but.. my AutoIt installation path seems already good `/var/lib/veil/wine/drive_c/Program Files/AutoIt3/` . Do you have some advices? Thanks

**Comment by EvilzCoder** [comment]
bash /usr/share/veil/config/setup.sh --force --silent

Specially works fine for me.

**Comment by techno39** [comment]
> Simply fire this command :cp -R '/var/lib/veil/wine/drive_c/Program Files (x86)/AutoIt3' '/var/lib/veil/wine/drive_c/Program Files/'
> Thats will resolve th issue
> the next will free up 32 megs of drive space that AutoIt3 is occupying in the programfiles(x86) folder... for the HDD cleanup nazis : cd "/var/lib/veil/wine/drive_c/Program Files (x86)" followed by rm -R AutoIt3
> reboot
> should work fine

thanks it work for me

**Comment by techno39** [comment]
Simply fire this command :cp -R '/var/lib/veil/wine/drive_c/Program Files (x86)/AutoIt3' '/var/lib/veil/wine/drive_c/Program Files/'

**Comment by andrealine** [comment]
Can't Find Autolt3 file in Program Files(x86) SO What Can I  DO Now

**Comment by VortexVoltGIT** [comment]
Hey this may be too late but you may want to try
First Uninstall your current Veil
`$ sudo apt-get autoremove Veil`

Then we must git clone it,
`$ git clone https://github.com/Veil-Framework/Veil.git`
We have to direct our system to the directory
`$ cd Veil`
This runs the veil setup in force mode, silent mode
`$ ./config/setup.sh --force --silent`

I had the same issue as you so I did it in force and silent mode

**Comment by andrealine** [comment]
Actually I Did It On My Own.
It Take Me Total 1 Day To Find Out Solution
I Just Download AuotIT v3 And Install It Using Wine  In The Directory Which
Was Shown In The Error. And eventually It Worked.

**Comment by andrealine** [comment]
And Thanks For Response

**Comment by pavankumar5460** [comment]
Please someone Help Me ...Iam Getting this Error while installing Veil in kali

 [i] Can't find WINE profile?   Run: /home/kali/Desktop/Veil/config/config/setup.sh --force --silent
 [>] Please enter the directory of Veil's WINE profile (e.g. /var/lib/veil/wine/): 

please
help me

**Comment by aelmosalamy** [comment]
Same issue happened with me when installing Veil on a fresh Kali using all the default installation options. Worked directly after moving AutoIt3 from Program Files (x86) to Program Files.
