### ISSUE TITLE
go/meterpreter/rev_https.py not generating executable when setting MINPROCS option

### ISSUE THREAD

**Issue by pachulo** [Veil-Framework/Veil#208]
## Veil version
3.1.7

## OS Used - all info (architecture, linux flavor, etc)
Ubuntu 16.04

## How did you install Veil? (Apt, Clone from Github, etc.)
I'm using this Docker container: https://github.com/mattias-ohlsson/docker-veil

`docker run -it -v /tmp/veil-output:/var/lib/veil/output mattiasohlsson/veil
`
## Did you run the setup script?
No.

## Pastebin link to error you are encountering (include console actions you took prior to error)

```
Veil>: use 1
Veil>: use go/meterpreter/rev_https.py
[go/meterpreter/rev_https>>]: set MINPROCS 1

...

[!] ERROR: Unable to create output file.
[*] Source code written to: /var/lib/veil/output/source/payload17.go

```

## Expected behavior
The option MINPROCS should be setable.

## Any additional info you want to tell me
When I set MINPROCS to X (or don't touch it) the generation works OK.

**Comment by ChrisTruncer** [comment]
You will have to supply that to the maintainer of that docker image. I appreciate you creating the image and the fix though, in case other people have the same issue. Thanks for taking the time to do that.

**Comment by ChrisTruncer** [comment]
I will double check though to see if this impacts the regular code base too, and not just the docket image.

**Comment by ChrisTruncer** [comment]
This issue should ow be fixed, thanks for reporting it!
