### ISSUE TITLE
Jumping Back to Main Menu

### ISSUE THREAD

**Issue by okiwoki** [Veil-Framework/Veil#21]
## Veil version

3.0

## OS Used - all info (architecture, linux flavor, etc)

Kali Rolling 2016.2 (x64)

## Expected behavior

List options for module, should there also be more modules with Veil 3.0 installed instead of just 2?

## Any additional info you want to tell me

I just finished git cloning and running setup.sh to install Veil but it shows that there's only two tools loaded (Evasion and Ordnance). When I choose the menu option "use" and select "1" or "2" to select them, I'm just dropped back into the main menu.

I attempted to re-run update.py in the config directory and I'm getting the same results.

**Comment by ChrisTruncer** [comment]
There are only two main tools in Veil, Evasion and Ordnance. Within each of those tools are tool specific modules. There will only show 2 modules at the main menu. Typing "use 1" or use 2" or "use Evasion" etc. will get you into the tool you want to use.
