### ISSUE TITLE
Veil won't run even after update

### ISSUE THREAD

**Issue by ZeR0AbSoLu** [Veil-Framework/Veil#210]
## Veil version
3.1.9-0kali1

## OS Used - all info (architecture, linux flavor, etc)
Kali 2018.2 xfce and gnome desktop 

## How did you install Veil? (Apt, Clone from Github, etc.)
Apt and clone (tried both)

## Did you run the setup script?
yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
after running veil i instantly obtain this
https://pastebin.com/2yiWwDGr

## Any additional info you want to tell me
happens since 2 weeks each time after any apt-get dist-upgrade

**Comment by ChrisTruncer** [comment]
I can't seem to recreate this. I have Veil installed on a VM with xfce as well, and it runs.  Worst case, please re-run the update script at /usr/share/veil/config/update.py

**Comment by ZeR0AbSoLu** [comment]
Ok thanks i try this and i let you know

**Comment by ZeR0AbSoLu** [comment]
Thank you it resolved the problem , but why does this happens each time i do a dist-upgrade ? is it a problem which come from me ?  because I got this problem in 3 different setup

**Comment by ChrisTruncer** [comment]
I think it is something isolated to your VMs. I can't recreate this, and I've not had any other users encounter the same issue. If you can find a repeatable way to encounter this, please let me know and I will review it on my end.

**Comment by ZeR0AbSoLu** [comment]
Ok thank you , i'll let you know , even if it happens not only in my VM's.
Congratulations for your work by the way !
