### ISSUE TITLE
Directory of the metasploit framework

### ISSUE THREAD

**Issue by blackdedz** [Veil-Framework/Veil#211]
When i install Veil at the end of all the process that happend. 
Idk what to do...

Please enter the directory of the Metasploit Framework (e.g. /opt/metasploit-framework/embedded/framework/):

**Comment by divyesh-01** [comment]
select the path where you have installed metasploit-framework , if by default path is not working

**Comment by divyesh-01** [comment]
> When i install Veil at the end of all the process that happend.
> Idk what to do...
> 
> Please enter the directory of the Metasploit Framework (e.g. /opt/metasploit-framework/embedded/framework/):



select the path where you have installed metasploit-framework , if by default path is not working
--
