### ISSUE TITLE
 Updating Veil configuration

### ISSUE THREAD

**Issue by blackdedz** [Veil-Framework/Veil#213]
## Veil version

3.1.X

## OS Used - all info (architecture, linux flavor, etc)

ParrotOS

## How did you install Veil? (Apt, Clone from Github, etc.)

Clone for github

## Did you run the setup script?

yes, sudo ./setup.sh 

## Pastebin link to error you are encountering (include console actions you took prior to error)

![screenshot at 2018-05-21 01-41-46](https://user-images.githubusercontent.com/38926886/40292260-ce66e7d0-5c8f-11e8-8787-256ba67db682.png)

## Expected behavior

install it :) 

## Any additional info you want to tell me

anything, what should i do ?

**Comment by ChrisTruncer** [comment]
The message on the screen is telling you exactly what you need to do. Please enter the directory of the Metasploit Framework on your local system.

**Comment by blackdedz** [comment]
How can i do it? im new in this... ><

**Comment by blackdedz** [comment]
Well i did it, but now request that: " Please enter the directory of msfvenom (e.g. /usr/bin/): " and i complete it with the directory "/usr/bin/msfvenom/", but nothing happend what should i do  ?
