### ISSUE TITLE
Updating Veil

### ISSUE THREAD

**Issue by blackdedz** [Veil-Framework/Veil#214]
## Veil version

3

## OS Used - all info (architecture, linux flavor, etc)

parrotOS

## How did you install Veil? (Apt, Clone from Github, etc.)

clone

## Did you run the setup script?

Yes

## Pastebin link to error you are encountering (include console actions you took prior to error)

![screenshot at 2018-05-23 02-24-07](https://user-images.githubusercontent.com/38926886/40406914-1dab2768-5e28-11e8-9be4-3a68a6dc4f0e.png)

## Expected behavior

update it :<

## Any additional info you want to tell me

i try all the directorys, but nothing happend

**Comment by ChrisTruncer** [comment]
It says to enter the directory of msfvenom, not the path to the directory. Please review the on-console requests. You should put in /usr/bin
