### ISSUE TITLE
Setup Problem of Kali Linux Azure Deployement

### ISSUE THREAD

**Issue by t00lc00l** [Veil-Framework/Veil#215]
I've tried to install latest version of the Veil through  git.

I deployed Kali Linux in Azure portal and after I deploy it I ran the
`apt-get update && apt-get upgrade && apt-get dist-upgrade`

After that I followed the steps in  README for installation from Github for Kali Linux. However I get that errors at the end of the installation process.

```............... 
skipped
...............
Failed to install (Wine) Ruby.exe... Exit code: 1
Failed to run (wine) Ruby OCRA.. Exit code: 49
...........
```

Then ran the `Veil.py --setup` because I get errors above and it says:

```
[!] ERROR #2-3: Can't find the WINE profile for Ruby v1.8.7 (/var/lib/veil/wine//drive_c/Ruby187/bin/ruby.exe).   Run: /root/Veil/config/setup.sh --force --silent
```

When I follow what it says there which is `Veil/config/setup.sh --force --silent`, it still doesn't install the Veil.

How can I solve this problem?

**Comment by ChrisTruncer** [comment]
I wish I could help here, but I don't currently have an Azure VM to deploy and test. I'm testing on local Kali and it doesn't seem to encounter the error. Any chance to redeploy a different VM instance and try again?

**Comment by ChrisTruncer** [comment]
Checking in one more time

**Comment by swarleysez** [comment]
I've encountered the same issues on AWS with the available Kali instance.  It has been an issue across multiple instances.

![image](https://user-images.githubusercontent.com/31361532/40849176-3d2e826a-658f-11e8-9c41-696ab10d7629.png)

However, installing on my VMware Workstation Kali VM, it installs without errors.

![image](https://user-images.githubusercontent.com/31361532/40849251-67987236-658f-11e8-9b80-2a1bd57c52d3.png)

**Comment by The-legend3** [comment]
Having the same issue on Ubuntu. Any updates?

**Comment by christinashver** [comment]
I have the same issue on Kali VM on my workstation player. Any updates?

**Comment by ChrisTruncer** [comment]
@The-legend3 - you did not provide any information that I can use to troubleshoot. I need version information, how you installed it, etc.

To everyone else, I'm sorry, but I'm currently unable to test this as I do not have an Azure VM deployed. I have verified that it is working on Kali in a VM (and it appears the reporter has above as well).

If you have azure infrastructure that you would like me to test in, just let me know.

**Comment by TheOffender** [comment]
I ran into this issue on a headless kali instance. Problem was $DISPLAY environmental variable was not set, so Wine could not finish installation of Ruby.exe, and thus could not install OCRA gem. 2 potential fixes - install veil through a desktop environment like gnome or, in the case of a headless server, ssh -X root@kali, which will set the display and allow wine to install ruby.exe correctly.
