### ISSUE TITLE
Veil-Pillage Installation

### ISSUE THREAD

**Issue by rajiv2790** [Veil-Framework/Veil#217]
## Veil version
3.1.11

## OS Used - all info (architecture, linux flavor, etc)
Kali Rolling 2018 x64

## How did you install Veil? (Apt, Clone from Github, etc.)
Cloned from Github 

## Did you run the setup script?
Yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
Veil-Pillage tool not installed

## Expected behavior
Veil-Pillage tool present

## Any additional info you want to tell me
Veil-Pillage documentation says that on running update.sh in Veil directory, it should automatically pull the required files. However, there is no update.sh in Veil directory.

**Comment by ChrisTruncer** [comment]
Veil-Pillage isn't supported anymore, and this isn't the same tool either.
