### ISSUE TITLE
Please Delete

### ISSUE THREAD

**Issue by darkarp** [Veil-Framework/Veil#220]
Please Delete. I've fixed my own error.

**Comment by darkarp** [comment]
It seems like the problem has to do with the X session, however there is one, but wine has errors creating Windows. No errors happen with Wine outside of veil config script However. 

I understand you don't have an Amazon EC2 to test on, I can give you credentials to mine, free for your testing.

**Comment by ChrisTruncer** [comment]
So it looks like you closed this issue, did you get everything working?
