### ISSUE TITLE
Error while install Veli on Kali 2018.1

### ISSUE THREAD

**Issue by Frenzyvn** [Veil-Framework/Veil#221]
## Veil version
Installed version using APT 

## OS Used - all info (architecture, linux flavor, etc)
Kali 2018.1

## How did you install Veil? (Apt, Clone from Github, etc.)
Apt

## Did you run the setup script?
Yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
xrandr:xrandr12_init_modes Failed to get primary CRTC info.

## Expected behavior
I don't know.

## Any additional info you want to tell me
Please support, thanks.

**Comment by ChrisTruncer** [comment]
Can you provide more information? I don't have any way to try to re-create this issue from the information provided.

Thanks

**Comment by ChrisTruncer** [comment]
Wanted to check in one more time on this

**Comment by Frenzyvn** [comment]
Hi Veli,

This error came while I used apt to install Veli, but when I try to run, no
problems happened. I think your can close this issue. Thanks for your
product.
