### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by omerbadawy11** [Veil-Framework/Veil#224]
## Veil version
Latest

## OS Used - all info (architecture, linux flavor, etc)

Kali 2018.1
## How did you install Veil? (Apt, Clone from Github, etc.)

apt-get install veil, also tried to clone from git
## Did you run the setup script?
yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
root@anon:~/Veil# apt --fix-broken install -f
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
  dh-python libfile-copy-recursive-perl libfreerdp-cache1.1
  libfreerdp-client1.1 libfreerdp-codec1.1 libfreerdp-common1.1.0
  libfreerdp-core1.1 libfreerdp-crypto1.1 libfreerdp-gdi1.1
  libfreerdp-locale1.1 libfreerdp-primitives1.1 libfreerdp-utils1.1
  libgcr-3-common libjs-excanvas libtcl8.5 libtk8.5 libtxc-dxtn-s2tc
  libwinpr-crt0.1 libwinpr-crypto0.1 libwinpr-dsparse0.1
  libwinpr-environment0.1 libwinpr-file0.1 libwinpr-handle0.1 libwinpr-heap0.1
  libwinpr-input0.1 libwinpr-interlocked0.1 libwinpr-library0.1
  libwinpr-path0.1 libwinpr-pool0.1 libwinpr-registry0.1 libwinpr-rpc0.1
  libwinpr-sspi0.1 libwinpr-synch0.1 libwinpr-sysinfo0.1 libwinpr-thread0.1
  libwinpr-utils0.1 libxfont1 multiarch-support python-unicodecsv
  python3-argcomplete python3-argh python3-construct python3-cssutils
  python3-feedparser python3-flask python3-html2text python3-itsdangerous
  python3-jsbeautifier python3-pathtools python3-pyinotify python3-simplejson
  python3-watchdog python3-werkzeug ruby2.3 tk8.5
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  binutils-mingw-w64-x86-64 libmono-security4.0-cil
  libmono-system-security4.0-cil libmono-system-xml4.0-cil mono-4.0-gac
  mono-gac mono-runtime-common
The following NEW packages will be installed:
  binutils-mingw-w64-x86-64 libmono-security4.0-cil
  libmono-system-security4.0-cil libmono-system-xml4.0-cil mono-4.0-gac
  mono-gac mono-runtime-common
0 upgraded, 7 newly installed, 0 to remove and 422 not upgraded.
34 not fully installed or removed.
Need to get 0 B/4,143 kB of archives.
After this operation, 30.8 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
E: Invalid archive signature
E: Internal error, could not locate member control.tar.{zstlz4gzxzbz2lzma}
E: Prior errors apply to /var/cache/apt/archives/libmono-system-security4.0-cil_4.6.2.7+dfsg-1_all.deb
E: Invalid archive signature
E: Internal error, could not locate member control.tar.{zstlz4gzxzbz2lzma}
E: Prior errors apply to /var/cache/apt/archives/libmono-security4.0-cil_4.6.2.7+dfsg-1_all.deb
E: Invalid archive signature
E: Internal error, could not locate member control.tar.{zstlz4gzxzbz2lzma}
E: Prior errors apply to /var/cache/apt/archives/mono-4.0-gac_4.6.2.7+dfsg-1_all.deb
E: Invalid archive signature
E: Internal error, could not locate member control.tar.{zstlz4gzxzbz2lzma}
E: Prior errors apply to /var/cache/apt/archives/mono-gac_4.6.2.7+dfsg-1_all.deb
E: Invalid archive signature
E: Internal error, could not locate member control.tar.{zstlz4gzxzbz2lzma}
E: Prior errors apply to /var/cache/apt/archives/mono-runtime-common_4.6.2.7+dfsg-1_amd64.deb
E: Prior errors apply to /var/cache/apt/archives/binutils-mingw-w64-x86-64_2.30-13+8.1_amd64.deb
debconf: apt-extracttemplates failed: No such file or directory
(Reading database ... 359280 files and directories currently installed.)
Preparing to unpack .../0-libmono-system-xml4.0-cil_4.6.2.7+dfsg-1_all.deb ...
Unpacking libmono-system-xml4.0-cil (4.6.2.7+dfsg-1) ...
dpkg-deb (subprocess): decompressing archive member: lzma error: compressed data is corrupt
dpkg-deb: error: <decompress> subprocess returned error exit status 2
dpkg: error processing archive /tmp/apt-dpkg-install-XREl2V/0-libmono-system-xml4.0-cil_4.6.2.7+dfsg-1_all.deb (--unpack):
 cannot copy extracted data for './usr/lib/mono/gac/System.Xml/4.0.0.0__b77a5c561934e089/System.Xml.dll' to '/usr/lib/mono/gac/System.Xml/4.0.0.0__b77a5c561934e089/System.Xml.dll.dpkg-new': unexpected end of file or stream
dpkg-deb: error: '/tmp/apt-dpkg-install-XREl2V/1-libmono-system-security4.0-cil_4.6.2.7+dfsg-1_all.deb' is not a Debian format archive
dpkg: error processing archive /tmp/apt-dpkg-install-XREl2V/1-libmono-system-security4.0-cil_4.6.2.7+dfsg-1_all.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
dpkg-deb: error: '/tmp/apt-dpkg-install-XREl2V/2-libmono-security4.0-cil_4.6.2.7+dfsg-1_all.deb' is not a Debian format archive
dpkg: error processing archive /tmp/apt-dpkg-install-XREl2V/2-libmono-security4.0-cil_4.6.2.7+dfsg-1_all.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
dpkg-deb: error: '/tmp/apt-dpkg-install-XREl2V/3-mono-4.0-gac_4.6.2.7+dfsg-1_all.deb' is not a Debian format archive
dpkg: error processing archive /tmp/apt-dpkg-install-XREl2V/3-mono-4.0-gac_4.6.2.7+dfsg-1_all.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
dpkg-deb: error: '/tmp/apt-dpkg-install-XREl2V/4-mono-gac_4.6.2.7+dfsg-1_all.deb' is not a Debian format archive
dpkg: error processing archive /tmp/apt-dpkg-install-XREl2V/4-mono-gac_4.6.2.7+dfsg-1_all.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
dpkg-deb: error: '/tmp/apt-dpkg-install-XREl2V/5-mono-runtime-common_4.6.2.7+dfsg-1_amd64.deb' is not a Debian format archive
dpkg: error processing archive /tmp/apt-dpkg-install-XREl2V/5-mono-runtime-common_4.6.2.7+dfsg-1_amd64.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
Preparing to unpack .../6-binutils-mingw-w64-x86-64_2.30-13+8.1_amd64.deb ...
Unpacking binutils-mingw-w64-x86-64 (2.30-13+8.1) ...
dpkg-deb (subprocess): decompressing archive member: lzma error: compressed data is corrupt
dpkg-deb: error: <decompress> subprocess returned error exit status 2
dpkg: error processing archive /tmp/apt-dpkg-install-XREl2V/6-binutils-mingw-w64-x86-64_2.30-13+8.1_amd64.deb (--unpack):
 cannot copy extracted data for './usr/bin/x86_64-w64-mingw32-strip' to '/usr/bin/x86_64-w64-mingw32-strip.dpkg-new': unexpected end of file or stream
Errors were encountered while processing:
 /tmp/apt-dpkg-install-XREl2V/0-libmono-system-xml4.0-cil_4.6.2.7+dfsg-1_all.deb
 /tmp/apt-dpkg-install-XREl2V/1-libmono-system-security4.0-cil_4.6.2.7+dfsg-1_all.deb
 /tmp/apt-dpkg-install-XREl2V/2-libmono-security4.0-cil_4.6.2.7+dfsg-1_all.deb
 /tmp/apt-dpkg-install-XREl2V/3-mono-4.0-gac_4.6.2.7+dfsg-1_all.deb
 /tmp/apt-dpkg-install-XREl2V/4-mono-gac_4.6.2.7+dfsg-1_all.deb
 /tmp/apt-dpkg-install-XREl2V/5-mono-runtime-common_4.6.2.7+dfsg-1_amd64.deb
 /tmp/apt-dpkg-install-XREl2V/6-binutils-mingw-w64-x86-64_2.30-13+8.1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

## Expected behavior
installation to successfully work

## Any additional info you want to tell me
nope

**Comment by ChrisTruncer** [comment]
I can’t do anything at the moment with this info. If you git Clone and install, will that work? Have you tried that on a clean system?

**Comment by omerbadawy11** [comment]
Yes, I have tried on a clean system, keeps getting repeated.

**Comment by omerbadawy11** [comment]
root@anon:~# apt --fix-broken install -f
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
  dh-python libfile-copy-recursive-perl libfreerdp-cache1.1
  libfreerdp-client1.1 libfreerdp-codec1.1 libfreerdp-common1.1.0
  libfreerdp-core1.1 libfreerdp-crypto1.1 libfreerdp-gdi1.1
  libfreerdp-locale1.1 libfreerdp-primitives1.1 libfreerdp-utils1.1
  libgcr-3-common libjs-excanvas libtcl8.5 libtk8.5 libtxc-dxtn-s2tc
  libwinpr-crt0.1 libwinpr-crypto0.1 libwinpr-dsparse0.1
  libwinpr-environment0.1 libwinpr-file0.1 libwinpr-handle0.1 libwinpr-heap0.1
  libwinpr-input0.1 libwinpr-interlocked0.1 libwinpr-library0.1
  libwinpr-path0.1 libwinpr-pool0.1 libwinpr-registry0.1 libwinpr-rpc0.1
  libwinpr-sspi0.1 libwinpr-synch0.1 libwinpr-sysinfo0.1 libwinpr-thread0.1
  libwinpr-utils0.1 libxfont1 multiarch-support python-unicodecsv
  python3-argcomplete python3-argh python3-construct python3-cssutils
  python3-feedparser python3-flask python3-html2text python3-itsdangerous
  python3-jsbeautifier python3-pathtools python3-pyinotify python3-simplejson
  python3-watchdog python3-werkzeug ruby2.3 tk8.5
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  binutils-mingw-w64-x86-64 libmono-security4.0-cil
  libmono-system-security4.0-cil libmono-system-xml4.0-cil mono-4.0-gac
  mono-gac mono-runtime-common
The following NEW packages will be installed:
  binutils-mingw-w64-x86-64 libmono-security4.0-cil
  libmono-system-security4.0-cil libmono-system-xml4.0-cil mono-4.0-gac
  mono-gac mono-runtime-common
0 upgraded, 7 newly installed, 0 to remove and 440 not upgraded.
34 not fully installed or removed.
Need to get 0 B/4,143 kB of archives.
After this operation, 30.8 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
E: Invalid archive signature
E: Internal error, could not locate member control.tar.{zstlz4gzxzbz2lzma}
E: Prior errors apply to /var/cache/apt/archives/libmono-system-security4.0-cil_4.6.2.7+dfsg-1_all.deb
E: Invalid archive signature
E: Internal error, could not locate member control.tar.{zstlz4gzxzbz2lzma}
E: Prior errors apply to /var/cache/apt/archives/libmono-security4.0-cil_4.6.2.7+dfsg-1_all.deb
E: Invalid archive signature
E: Internal error, could not locate member control.tar.{zstlz4gzxzbz2lzma}
E: Prior errors apply to /var/cache/apt/archives/mono-4.0-gac_4.6.2.7+dfsg-1_all.deb
E: Invalid archive signature
E: Internal error, could not locate member control.tar.{zstlz4gzxzbz2lzma}
E: Prior errors apply to /var/cache/apt/archives/mono-gac_4.6.2.7+dfsg-1_all.deb
E: Invalid archive signature
E: Internal error, could not locate member control.tar.{zstlz4gzxzbz2lzma}
E: Prior errors apply to /var/cache/apt/archives/mono-runtime-common_4.6.2.7+dfsg-1_amd64.deb
E: Prior errors apply to /var/cache/apt/archives/binutils-mingw-w64-x86-64_2.30-13+8.1_amd64.deb
debconf: apt-extracttemplates failed: No such file or directory
(Reading database ... 359280 files and directories currently installed.)
Preparing to unpack .../0-libmono-system-xml4.0-cil_4.6.2.7+dfsg-1_all.deb ...
Unpacking libmono-system-xml4.0-cil (4.6.2.7+dfsg-1) ...
dpkg-deb (subprocess): decompressing archive member: lzma error: compressed data is corrupt
dpkg-deb: error: <decompress> subprocess returned error exit status 2
dpkg: error processing archive /tmp/apt-dpkg-install-B651k2/0-libmono-system-xml4.0-cil_4.6.2.7+dfsg-1_all.deb (--unpack):
 cannot copy extracted data for './usr/lib/mono/gac/System.Xml/4.0.0.0__b77a5c561934e089/System.Xml.dll' to '/usr/lib/mono/gac/System.Xml/4.0.0.0__b77a5c561934e089/System.Xml.dll.dpkg-new': unexpected end of file or stream
dpkg-deb: error: '/tmp/apt-dpkg-install-B651k2/1-libmono-system-security4.0-cil_4.6.2.7+dfsg-1_all.deb' is not a Debian format archive
dpkg: error processing archive /tmp/apt-dpkg-install-B651k2/1-libmono-system-security4.0-cil_4.6.2.7+dfsg-1_all.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
dpkg-deb: error: '/tmp/apt-dpkg-install-B651k2/2-libmono-security4.0-cil_4.6.2.7+dfsg-1_all.deb' is not a Debian format archive
dpkg: error processing archive /tmp/apt-dpkg-install-B651k2/2-libmono-security4.0-cil_4.6.2.7+dfsg-1_all.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
dpkg-deb: error: '/tmp/apt-dpkg-install-B651k2/3-mono-4.0-gac_4.6.2.7+dfsg-1_all.deb' is not a Debian format archive
dpkg: error processing archive /tmp/apt-dpkg-install-B651k2/3-mono-4.0-gac_4.6.2.7+dfsg-1_all.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
dpkg-deb: error: '/tmp/apt-dpkg-install-B651k2/4-mono-gac_4.6.2.7+dfsg-1_all.deb' is not a Debian format archive
dpkg: error processing archive /tmp/apt-dpkg-install-B651k2/4-mono-gac_4.6.2.7+dfsg-1_all.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
dpkg-deb: error: '/tmp/apt-dpkg-install-B651k2/5-mono-runtime-common_4.6.2.7+dfsg-1_amd64.deb' is not a Debian format archive
dpkg: error processing archive /tmp/apt-dpkg-install-B651k2/5-mono-runtime-common_4.6.2.7+dfsg-1_amd64.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
Preparing to unpack .../6-binutils-mingw-w64-x86-64_2.30-13+8.1_amd64.deb ...
Unpacking binutils-mingw-w64-x86-64 (2.30-13+8.1) ...
dpkg-deb (subprocess): decompressing archive member: lzma error: compressed data is corrupt
dpkg-deb: error: <decompress> subprocess returned error exit status 2
dpkg: error processing archive /tmp/apt-dpkg-install-B651k2/6-binutils-mingw-w64-x86-64_2.30-13+8.1_amd64.deb (--unpack):
 cannot copy extracted data for './usr/bin/x86_64-w64-mingw32-strip' to '/usr/bin/x86_64-w64-mingw32-strip.dpkg-new': unexpected end of file or stream
Errors were encountered while processing:
 /tmp/apt-dpkg-install-B651k2/0-libmono-system-xml4.0-cil_4.6.2.7+dfsg-1_all.deb
 /tmp/apt-dpkg-install-B651k2/1-libmono-system-security4.0-cil_4.6.2.7+dfsg-1_all.deb
 /tmp/apt-dpkg-install-B651k2/2-libmono-security4.0-cil_4.6.2.7+dfsg-1_all.deb
 /tmp/apt-dpkg-install-B651k2/3-mono-4.0-gac_4.6.2.7+dfsg-1_all.deb
 /tmp/apt-dpkg-install-B651k2/4-mono-gac_4.6.2.7+dfsg-1_all.deb
 /tmp/apt-dpkg-install-B651k2/5-mono-runtime-common_4.6.2.7+dfsg-1_amd64.deb
 /tmp/apt-dpkg-install-B651k2/6-binutils-mingw-w64-x86-64_2.30-13+8.1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by ChrisTruncer** [comment]
You’re getting invalid signatures. Please try on a different VM possibly, or change your mirrors.

To be honest, it’s a bit easier to install by cloning from Github.

**Comment by omerbadawy11** [comment]
i tried to clone, same issue for some reason, i wish there's a way to avoid using a different VM.

**Comment by ChrisTruncer** [comment]
This appears to be something isolated to your system and/or the mirrors you are using. I am able to install this on the Kali VM I have.

**Comment by omerbadawy11** [comment]
after doing : 
apt-get remove --purge mono-runtime-sgen mono-runtime-common mono-mcs libmono-i18n-west4.0-cil libmono-system-xml4.0-cil libmono-system-xml4.0-cil libmono-security4.0-cil libmono-system4.0-cil libmono-system-security4.0-cil libmono-system-configuration4.0-cil libmono-csharp4.0c-cil libmono-system-xml4.0-cil binutils-mingw-w64-x86-64 gcc-mingw-w64-x86-64 libmono-security4.0-cil ca-certificates-mono g++-mingw-w64-x86-64 gcc-mingw-w64 libmono-microsoft-csharp4.0-cil libmono-posix4.0-cil libmono-system-core4.0-cil mono-runtime g++-mingw-w64 libmono-corlib4.5-cil libmono-i18n4.0-cil mingw-w64 && apt-get autoremove && apt-get install -f
it installed normally, thanks.
