### ISSUE TITLE
Setup erro

### ISSUE THREAD

**Issue by b00tx** [Veil-Framework/Veil#227]
[I] Parrot Security 4.1 x86_64 detected...

 [I] Silent Mode: Enabled
 [I]  Force Mode: Enabled

 [?] Are you sure you wish to install Veil?

     Continue with installation? ([y]es/[s]ilent/[N]o): S

 [*] Initializing package installation

 [*] Pulling down binary dependencies

 [*] Empty folder... git cloning

Cloning into '/var/lib/veil/setup-dependencies'...
remote: Counting objects: 12, done.
remote: Total 12 (delta 0), reused 0 (delta 0), pack-reused 12
Unpacking objects: 100% (12/12), done.

 [*] Installing Wine

 [*] Already have x86 architecture added...

 [*] Installing Wine 32-bit and 64-bit binaries (via APT)

E: O pacote 'wine32' não tem candidato para instalação
 [ERROR] Failed with installing wine (2): 0

 [*] [ALERT]: Existing Veil Wine environment detected at: /var/lib/veil/wine

     Do you want to nuke it? ([y]es/[N]o): Y

 [*] Deleting existing Veil Wine environment...

 [*] Creating new Veil Wine environment in: /var/lib/veil/wine

 [*] Initializing Veil's Wine environment...

it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
wine: '/var/lib/veil/wine' is a 32-bit installation, it cannot support 64-bit applications.
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
wine: '/var/lib/veil/wine' is a 32-bit installation, it cannot support 64-bit applications.
 [*] Veil Wine environment successfully created!

 [*] Finished package installation

 [*] Initializing (OS + Wine) Python dependencies installation...

 [*] Installing (Wine) Python...

 [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)

it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
0012:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0012:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0012:err:ole:get_local_server_stream Failed: 80004002
0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
0014:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0014:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0014:err:ole:get_local_server_stream Failed: 80004002
Could not load wine-gecko. HTML rendering will be disabled.
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/var/lib/veil/wine' has been updated.
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
0009:err:msi:create_temp_binary failed to load dll L"C:\\users\\root\\Temp\\msi43de.tmp" (193)
002f:err:msi:ACTION_CallDllFunction failed to load dll L"C:\\users\\root\\Temp\\msi43de.tmp" (193)
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
wine: Formato EXE impróprio para C:\Python34\python.exe.
0009:err:msi:execute_command unable to execute command 193

 [*] Installing (Wine) Python dependencies...

 [*] Installing (Wine) Python's pywin32-220.win32-py3.4.exe...

 [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)

warning [pywin32-220.win32-py3.4.exe]:  192288 extra bytes at beginning or within zipfile
  (attempting to process anyway)
cp: o alvo '/var/lib/veil/wine/drive_c/Python34/Scripts/' não é um diretório
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
wine: Formato EXE impróprio para C:\Python34\python.exe.

 [*] Installing (Wine) Python's pycrypto-2.6.1.win32-py3.4.exe...

 [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)

warning [pycrypto-2.6.1.win32-py3.4.exe]:  191515 extra bytes at beginning or within zipfile
  (attempting to process anyway)

 [*] Installing (OS) Python's PyInstaller (via TAR)

 [*] Installing (Wine) Python's PIP pefile

it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
wine: Formato EXE impróprio para C:\Python34\python.exe.
 [ERROR] Failed to run (wine) Python pip... Exit code: 193

it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
wine: Formato EXE impróprio para C:\Python34\python.exe.
 [ERROR] Failed to run (wine) Python pip future... Exit code: 193

it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
wine: Formato EXE impróprio para C:\Python34\python.exe.
 [ERROR] Failed to run (wine) Python pip pefile... Exit code: 193

 [*] Finished (Wine + OS) Python dependencies installation

 [*] Initializing (Wine) Ruby installation...

 [*] Installing (Wine) Ruby & dependencies

 [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)

it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
wine: Formato EXE impróprio para Z:\var\lib\veil\setup-dependencies\rubyinstaller-1.8.7-p371.exe.
 [ERROR] Failed to install (Wine) Ruby.exe... Exit code: 193

 [*] Installing (Wine) Ruby OCRA gem...

it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"

Z:\var\lib\veil\setup-dependencies>Z:\var\lib\veil\wine\drive_c\Ruby187\bin\gem install --force --local ocra-1.3.6.gem 
Não é possível reconhecer 'Z:\var\lib\veil\wine\drive_c\Ruby187\bin\gem install --force --local ocra-1.3.6.gem' como um comando interno, externo ou arquivo de lotes.
 [ERROR] Failed to run (wine) Ruby OCRA.. Exit code: 49

 [*] Extracting (Wine) Ruby dependencies...

 [*] Finished Ruby installation

 [*] Initializing Go installation...

 [*] Installing Go x86_64 (via TAR)

 [*] Finished Go installation

 [*] Initializing AutoIT installation...

 [*] Installing (Wine) AutoIT

 [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)

it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
wine: Formato EXE impróprio para Z:\var\lib\veil\setup-dependencies\autoit-v3-setup.exe.
 [ERROR] Failed to run (wine) AutoIT.. Exit code: 193

 [*] Finished AutoIT installation

 [*] Updating Veil configuration...

 [*] Detected current Veil settings. Removing...

 Veil Configuration:
 [*] OPERATING_SYSTEM = Linux
 [*] TERMINAL_CLEAR = clear
 [*] VEIL_PATH = /usr/share/veil/
 [*] WINEPREFIX = /var/lib/veil/wine/
 [*] TEMP_PATH = /tmp/
 [*] METASPLOIT_PATH = /opt/metasploit-framework/embedded/framework/
 [*] MSFVENOM_PATH = /usr/local/bin/
 [*] MSFVENOM_OPTIONS = 
 [*] PYINSTALLER_PATH = /var/lib/veil/PyInstaller-3.2.1/
 [*] GOLANG_PATH = /var/lib/veil/go/

 Veil-Evasion Configuration:
 [*] PAYLOAD_SOURCE_PATH = /var/lib/veil/output/source/
 [*] PAYLOAD_COMPILED_PATH = /var/lib/veil/output/compiled/
 [*] HANDLER_PATH = /var/lib/veil/output/handlers/
 [*] HASH_LIST = /var/lib/veil/output/hashes.txt
 [I] Path '/etc/veil/' Created
 [I] Configuration File Written To: '/etc/veil/settings.py'

 [*] Ensuring this account (root) owns veil output directory (/var/lib/veil/output)...

 [*] Ensuring this account (root) has correct ownership of /var/lib/veil/wine

 [*] Finished Veil configuration...

 [*] Finished environment checks

 [ERROR] There was issues installing the following:

 
Failed with installing wine (2): 0
Failed to run (wine) Python pip... Exit code: 193
Failed to run (wine) Python pip future... Exit code: 193
Failed to run (wine) Python pip pefile... Exit code: 193
Failed to install (Wine) Ruby.exe... Exit code: 193
Failed to run (wine) Ruby OCRA.. Exit code: 49
Failed to run (wine) AutoIT.. Exit code: 193

 [I] If you have any errors running Veil, run: './Veil.py --setup' and select the nuke the wine folder option

**Comment by ChrisTruncer** [comment]
Do you have a pull request that fixes the parrot OS install? I don’t support Parrot OS at this time, but if you had a fix I’m happy to merge it.

**Comment by ChrisTruncer** [comment]
Closing due to no response

**Comment by serdaromer** [comment]
[*] Ensuring this account (root) owns veil output directory (/var/lib/veil/output)...

 [*] Ensuring this account (root) has correct ownership of /var/lib/veil/wine



 [*] Finished Veil configuration...



 [*] Finished environment checks

 [ERROR] There was issues installing the following:

 
Failed with installing wine (2): 0



 [I] If you have any errors running Veil, run: './Veil.py --setup' and select the nuke the wine folder option



 [I] Done!

**Comment by serdaromer** [comment]
[*] Ensuring this account (root) owns veil output directory (/var/lib/veil/output)...

 [*] Ensuring this account (root) has correct ownership of /var/lib/veil/wine



 [*] Finished Veil configuration...



 [*] Finished environment checks

 [ERROR] There was issues installing the following:

 
Failed with installing wine (2): 0



 [I] If you have any errors running Veil, run: './Veil.py --setup' and select the nuke the wine folder option



 [I] Done!
