### ISSUE TITLE
No module named lib.common

### ISSUE THREAD

**Issue by pieterhouwen** [Veil-Framework/Veil#228]
## Veil version
2018-05-08

## OS Used - all info (architecture, linux flavor, etc)
Kali Linux 2018.2

## How did you install Veil? (Apt, Clone from Github, etc.)
Both

## Did you run the setup script?
Yes, the buitlin script when starting Veil and the file specified in the README.

## Pastebin link to error you are encountering (include console actions you took prior to error)
https://pastebin.com/5xHemUs9

## Expected behavior
Run

## Any additional info you want to tell me
I've removed Veil with apt-get purge veil and reinstalled it, but to no aVeil (pun intended).
Would you be so kind as to provide me with your sources.list? Maybe I'm using an old repository.

**Comment by ChrisTruncer** [comment]
Can you please try on a clean VM, and try just installing via git cloning the repo and following instructions in the README? That is how I currently install it and don’t run into this error.

**Comment by ChrisTruncer** [comment]
Closing due to no response
