### ISSUE TITLE
ERROR #2-3: Can't find the WINE profile for Ruby v1.8.7 (SOLUTION)

### ISSUE THREAD

**Issue by Anaphylaxis** [Veil-Framework/Veil#230]
## Veil version
2018.3

## OS Used - all info (architecture, linux flavor, etc)
Kali Linux latest

## How did you install Veil? (Apt, Clone from Github, etc.)
both apt, and git clone

## Did you run the setup script?
Yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
apt install veil -y
https://pastebin.com/YbN5xxSL

## Expected behavior
Launch veil

## Any additional info you want to tell me
Happened on my x64 Kali Linux that was very lightly used, and happens on a brand new x86 virtual machine that has only had bleeding edge added, and "apt update -y && apt upgrade -y"

### EDIT ###
Fixed -- this can't be run headless.

**Comment by ViruTyagi** [comment]
I am having the same error. Can anyone Help?

**Comment by shivankar-madaan** [comment]
@ViruTyagi did you try `apt-get install wine32` and then
`/root/config/setup.sh --force --silent`

It worked for me

**Comment by alxprogrmz** [comment]
I am having the same error.  Can't find the WINE profile for Ruby v1.8.7 I installed veil through apt-get. I followed the instructions but to no avail. How to fix this problem.

**Comment by Anaphylaxis** [comment]
@alxprogrmz Did you see my edit? This can't be run headless -- try without SSH and actually on the machine/VM.

**Comment by dsx12** [comment]
What about windows subsystem for linux? It's not installing on kali's subsystem either.

**Comment by ChrisTruncer** [comment]
Veil was developed when there was no subsystem for linux, so it doesn’t support it (that I know of). If you’d like, I’d be more than happy to see a pull request with the support.


----------------------------------------------------------------
Christopher Truncer
Co-Founder & Red Team Lead
[justlogoword]
Phone: 703-594-1340
E-Mail: CTruncer@fortynorthsecurity.com<mailto:CTruncer@fortynorthsecurity.com>
Website: https://www.fortynorthsecurity.com<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.fortynorthsecurity.com%2F&data=02%7C01%7Cchris%40fortynorthsecurity.com%7C8ab99d535c354aa3867a08d65fa8df84%7C13e7061fe89b41a78b92ac403c961ded%7C1%7C0%7C636801576266012597&sdata=XaljkT%2FptnQqhx%2FS502%2BqQ9pgOK%2BD2ex8WbFKXPzbfg%3D&reserved=0>

**Comment by dsx12** [comment]
Thanks if you could that would be awesome because most penetration testers/hackers are moving over to windows/mac and ssh into their linux systems or use subsystem to get the best of both worlds. It would indeed make out jobs a lot easier lol.

**Comment by ChrisTruncer** [comment]
At this point in time I am not able to add this. If you would like to add this support, I would be happy to review it.

Also, I wouldn’t necessarily agree all hackers are moving to using that. I and many others I know primarily use linux in VMs.


________________________________

**Comment by dsx12** [comment]
I think the linux subsystem is more productive though, unless you run into these typical errors. I suppose I was just referring to the community I am in. Sure I'll see what I can do.

**Comment by dsx12** [comment]
Off Subject: How long do you predict veil will be undetectable?

**Comment by Anaphylaxis** [comment]
> I think the linux subsystem is more productive though

I don't.
> How long do you predict veil will be undetectable?

It's not.

**Comment by ChrisTruncer** [comment]
I'm going to lock this since we're going pretty far off topic. Veil can be undetectable, you just have to test against the AV you are going against, or use any of the built in functionality to help change how it works.
