### ISSUE TITLE
Wondows Defender 

### ISSUE THREAD

**Issue by 8L4NK** [Veil-Framework/Veil#231]
## Veil version
3.1
And 3.0

## OS Used - all info (architecture, linux flavor, etc)
Kali 2017.3
And kali 2018.3

## How did you install Veil? (Apt, Clone from Github, etc.)
On both versions of kali, I apt-get git clone
And I downloaded via zip and gui extracted. 

## Did you run the setup script?
Yes on both veraions

## Pastebin link to error you are encountering (include console actions you took prior to error)
No matter what payload selected. Windows defender stops it.
The delivery method is via kali web server. And I also tried USB

## Expected behavior
Up till a week ago. I was getting reverse callbacks 
Not anymore. Powershell has stopped working. 

## Any additional info you want to tell me
I can get a reverse connection from a mac OS 
But not a windows 10 1803 (updated Aug 4th 2018) OS
I have used empire powershell and same success/problem. 
Time frame. Everything was good uptill a fee days ago

**Comment by ChrisTruncer** [comment]
Hi,

I don't have the time or bandwidth to counter each individual detection a specific AV has. This project is currently being updated behind the scenes, but the best way forward for now would be to take advice provided in past github issues. Modify default values, change how the payload is working slightly, etc.

**Comment by 8L4NK** [comment]
Will do. I have altered values. Tried different methods. I suppose I'll
wait till dev push out a update. i have tried about 11 different payloads
all caught by windows defender. I'll have a eye out for the update. Any ETA
on that?  Week, month,  year?

**Comment by iklobato** [comment]
@zu3s Hello, did you find a qiuck solution to modify the av bypass?
