### ISSUE TITLE
Need improvement in PAYLOADS of veil

### ISSUE THREAD

**Issue by duckkar** [Veil-Framework/Veil#233]
## Veil version 3.1.11
This is not an issue on working of veil. I just want to inform the developers that the payloads generated using veil are detected by almost all anti virus scanners... Recently i have used **Phantom-Evasion** to create some test payloads and they are unbelievably working too good. They are almost undetectable by scanners... I don't know what they have use to build them but they are very much undetectable. 
I am a _big fan of veil_ and constantly keeps updating it to the latest version...
I very much liked the _Ordnance tool introduced in veil_... 
I just opened this issue to let the developers know there's a need of improvement in veil... I don't want to leave veil just because some new tools came...
I thereby request developers to amend veil and make its payloads overrun those created by Phantom-Evasion like tools ..
THANKS

**Comment by azamet90** [comment]
when was the last update of weil? 6 months? 1 year? it is detectable from everything :D
