### ISSUE TITLE
Veil 3.1X;Kali linux 2108.2; Clone from Github; yes i ran the setup; Can't install on Kali linux.[ERROR] Failed with installing dependencies (5).. Waited for a long time for unpacking packages and after that said error.Installing can't finish.how can i fix this?

### ISSUE THREAD

**Issue by waihankan** [Veil-Framework/Veil#235]
## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
You didn't provide any of the information that I asked for when creating an issue, and unfortunately I can't troubleshoot based off of what you gave me. I also tested last night the install on Kali and it successfully installs. If you have more information, please open a new issue and provide all the information requested.
