### ISSUE TITLE
Whole system crash afer install Veil

### ISSUE THREAD

**Issue by leiferdjango** [Veil-Framework/Veil#236]
Hello,

Thats embarsing, but there must be a solution, I hope you can help me.

Im using Debian 9
happens when I install Veil, everything is goin great but when goes to python-windows part, it crash. 

Now the system just boot in text mode tty. Im affraid I lost all my stuffs.

**Comment by ChrisTruncer** [comment]
Veil won’t cause your system to crash. I also am personally using Debian, so I can validate that it does work on that distro.

**Comment by ChrisTruncer** [comment]
If you have any additional details, please let me know. But At this point this isn't something I can recreate.
