### ISSUE TITLE
Good evening to all, in fact I can not laner ./Veil.py

### ISSUE THREAD

**Issue by pamela77** [Veil-Framework/Veil#237]
## Veil version
 ==========================================================================
                 Veil (Setup Script) | [Updated]: 2018-05-08
 ==========================================================================
     [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
 ==========================================================================

                 os = kali
          osversion = 2018.3
       osmajversion = 2018
               arch = x86_64
           trueuser = root
   userprimarygroup = root
        userhomedir = /root
            rootdir = /root/Veil
            veildir = /var/lib/veil
          outputdir = /var/lib/veil/output
    dependenciesdir = /var/lib/veil/setup-dependencies
            winedir = /var/lib/veil/wine
          winedrive = /var/lib/veil/wine/drive_c
            gempath = Z:\var\lib\veil\wine\drive_c\Ruby187\bin\gem

 [I] Kali Linux 2018.3 x86_64 detected...

 [I] Silent Mode: Enabled
 [I]  Force Mode: Enabled
 [?] Are you sure you wish to install Veil?

     Continue with installation? ([y]es/[s]ilent/[N]o): S

## OS Used - all info (architecture, linux flavor, etc)
I use Kali linux2.0 2018 64bits DD 60G install in dual boot.
Gnome version 3.28.2
processor Core I3,
Name of the Kali GNU / Linux Rolling OS

## How did you install Veil? (Apt, Clone from Github, etc.)
I install Veil from official github
https://github.com/Veil-Framework/Veil

## Did you run the setup script?
I have installed Veil using the default instructions and all it is to run without problem I think.
sudo apt-get -y install git
git clone https://github.com/Veil-Framework/Veil.git
cd Veil /
./config/setup.sh --force --silent

## Pastebin link to error you are encountering (include console actions you took prior to error)
1386/5000
Langue source : Anglais
During the installation there are zones where it is to mark errors I think. Here they are.
1 - [*] Initializing Veil's Wine environment ...

0012: err: ole: marshal_object could not get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0012: err: ole: marshal_object could not get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
0012: err: ole: StdMarshalImpl_MarshalInterface Failed to create ifstub, hres = 0x80004002
0012: err: ole: CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0012: err: ole: get_local_server_stream Failed: 80004002
0014: err: ole: marshal_object could not get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0014: err: ole: marshal_object could not get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
0014: err: ole: StdMarshalImpl_MarshalInterface Failed to create ifstub, hres = 0x80004002
0014: err: ole: CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0014: err: ole: get_local_server_stream Failed: 80004002
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/ var / lib / veil / wine' has been updated.
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/ var / lib / veil / wine' has been updated.
 [*] Veil Wine environment successfully created!

2-[*] Installing (Wine) Python...

 [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)

0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
002a:err:clipboard:convert_selection Timed out waiting for SelectionNotify event
002a:err:clipboard:convert_selection Timed out waiting for SelectionNotify event
Ignoring indexes: https://pypi.python.org/simple
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-7.1.2 setuptools-18.2

3-[*] Installing (Wine) Python's pywin32-220.win32-py3.4.exe...

 [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)

warning [pywin32-220.win32-py3.4.exe]:  192288 extra bytes at beginning or within zipfile
  (attempting to process anyway)
0009:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.

 [*] Installing (Wine) Python's pycrypto-2.6.1.win32-py3.4.exe...

 [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)

warning [pycrypto-2.6.1.win32-py3.4.exe]:  191515 extra bytes at beginning or within zipfile
  (attempting to process anyway)

4-[*] Finished environment checks

 [I] If you have any errors running Veil, run: './Veil.py --setup' and select the nuke the wine folder option

 [I] Done!
Everything is fine except those places where I get errors while running the config script.
After installing, here is the error message I get when I run ./Veil.py
root@Pamela:~/Veil# ./Veil.py
Traceback (most recent call last):
   File "./Veil.py", line 10, in <module>
     from lib.common import orchestra
   File "/root/Veil/lib/common/orchestra.py", line 8, in <module>
     import readline
ModuleNotFoundError: No module named 'readline'

## Expected behavior
$ ./Veil.py
===============================================================================
                             Veil | [Version]: 3.1.6
===============================================================================
      [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
===============================================================================

Main Menu

  2 tools loaded

Available Tools:

  1)  Evasion
  2)  Ordnance

Available Commands:

  exit      Completely exit Veil
  info      Information on a specific tool
  list      List available tools
  options     Show Veil configuration
  update      Update Veil
  use     Use a specific tool

Veil>:

## Any additional info you want to tell me
I delete the veil folder and install wine and install Veil-Evasion earlier version but I also get an error message. I beg you to help me because I have been in circles for days.
Thank you in advance. cordially

**Comment by ChrisTruncer** [comment]
Are you able to just install the readline library?

**Comment by pamela77** [comment]
Hello @ChrisTruncer Thank you very much for your help, I have to install the readline library from github depot or it is on another site?
Thank you again and I'm waiting for an answer.
cordially

**Comment by pamela77** [comment]
I found the library Readline.7.0.tar.gz on this site
http://git.savannah.gnu.org/cgit/readline.git?h=devel
Is this the right version for me?
cordially

**Comment by pamela77** [comment]
I just installed the readline library that I found on the official site but the same error appears tjrs pouffffff.
I do not know what to do anymore.

**Comment by ChrisTruncer** [comment]
Hi,

This sounds like something isolated to your system and/or the repos you are using. The setup process installs all dependencies needed, so there shouldn’t be a problem.

**Comment by pamela77** [comment]
I think so too but it still does not work. I install the readline library via the site depot, also via apt-get but always the same error message. I think I will admit to being defeated because I have the head that heats ................. Thank you anyway.
