### ISSUE TITLE
ModuleNotFoundError: No module named 'context_locals'

### ISSUE THREAD

**Issue by shaolinint** [Veil-Framework/Veil#238]
## Veil version
3.1.11

## OS Used - all info (architecture, linux flavor, etc)
Linux 4.15.0-32-generic #35-Ubuntu SMP Fri Aug 10 17:58:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

ubuntu 18.04

## How did you install Veil? (Apt, Clone from Github, etc.)
sudo apt-get -y install git
git clone https://github.com/Veil-Framework/Veil.git
cd Veil/
./config/setup.sh --force --silent

## Did you run the setup script?
yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
https://pastebin.com/LmwigapN

## Expected behavior
Veil successfully executed

## Any additional info you want to tell me
Python 3.6.5

**Comment by ChrisTruncer** [comment]
Ubuntu it appears changes some package names. I will have to review the setup process on it

**Comment by ChrisTruncer** [comment]
Can you try this again now? I just downloaded Ubuntu 18.04.1 LTS and installed Veil, and it installed successfully. I also tested by creating a Veil payload and it worked as well. Something might be fixed on Ubuntu's end now.

**Comment by ChrisTruncer** [comment]
I'm going to close due to no response. Please post if you have any additional methods to recreate this.

**Comment by shaolinint** [comment]
same error. may I know what is your python version? - thanks

**Comment by ChrisTruncer** [comment]
I’m running python 3
