### ISSUE TITLE
Veil unable to run. 

### ISSUE THREAD

**Issue by dela-dee** [Veil-Framework/Veil#239]
## OS Used - all info (architecture, linux flavor, etc)
kali linux

## How did you install Veil? (Apt, Clone from Github, etc.)
git clone

## Did you run the setup script?
yes i did 

## Pastebin link to error you are encountering (include console actions you took prior to error)
https://pastebin.com/2zRnueBD

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
Can you try running the setup script again as it shows how to in the Readme? The script will set the golang path. Worst case, you could always manually create it.

**Comment by ChrisTruncer** [comment]
Closing due to no response
