### ISSUE TITLE
[ERROR] Your architecture armv7l is not supported!

### ISSUE THREAD

**Issue by mohamed-soubhi** [Veil-Framework/Veil#240]
## Veil version
Veil (Setup Script) | [Updated]: 2018-05-08

## OS Used - all info (architecture, linux flavor, etc)
ka

## How did you install Veil? (Apt, Clone from Github, etc.)
clone from Githup

## Did you run the setup script?
yes put it didnt complete the setup 
this error appeared 
 [ERROR] Your architecture armv7l is not supported

## Pastebin link to error you are encountering (include console actions you took prior to error)
 ==========================================================================
                 Veil (Setup Script) | [Updated]: 2018-05-08
 ==========================================================================
     [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
 ==========================================================================

                 os = kali
          osversion = 2018.1
       osmajversion = 2018
               arch = armv7l
           trueuser = root
   userprimarygroup = 0
        userhomedir = /root
            rootdir = /root/Veil
            veildir = /var/lib/veil
          outputdir = /var/lib/veil/output
    dependenciesdir = /var/lib/veil/setup-dependencies
            winedir = /var/lib/veil/wine
          winedrive = /var/lib/veil/wine/drive_c
            gempath = Z:\var\lib\veil\wine\drive_c\Ruby187\bin\gem

 [ERROR] Your architecture armv7l is not supported!

## Expected behavior
it should complete the instillation 

## Any additional info you want to tell me
yes , i am using raspbery pi with kali linux

**Comment by ChrisTruncer** [comment]
Sorry,

It looks like right now that architecture isn’t supported.

**Comment by mohamed-soubhi** [comment]
so how it can be supported  also is there any other tool do the same task ?

**Comment by ChrisTruncer** [comment]
As of now, there aren't any plans to support this myself. If you would like to add support in, I would welcome it and would be happy to review a pull request.
