### ISSUE TITLE
[HELP] How to completely uninstall veil?

### ISSUE THREAD

**Issue by clancrate** [Veil-Framework/Veil#242]
## Veil version
veil 3.1.11
## OS Used - all info (architecture, linux flavor, etc)
Kali GNU/Linux rolling
## How did you install Veil? (Apt, Clone from Github, etc.)
https://null-byte.wonderhowto.com/how-to/hack-like-pro-evade-av-detection-with-veil-evasion-0162363/
## Did you run the setup script?
Yes
## Any additional info you want to tell me
How to completely uninstall veil-evasion? Its taking up alot of space in my hard drive and I want to uninstall it including the wine directories.

**Comment by clancrate** [comment]
Not sure how I did install veil, can't remember. I think I git cloned it.

**Comment by ChrisTruncer** [comment]
Just delete the Veil folder and the wine folder for Veil. Those are the two largest file locations.

**Comment by clancrate** [comment]
Where are can I exactly find those directories? I don't want to delete the wrong directory. I also have the preinstalled version of veil for Kali Linux (I think) so it might be different.

**Comment by ChrisTruncer** [comment]
I can’t help if you don’t know how you installed it. Please look at the setup script as it documents where everything is.

**Comment by clancrate** [comment]
Thanks. :)

**Comment by clancrate** [comment]
here are the install directories for veil(credits to u/rschulze at reddit): 
    veildir="/var/lib/veil"
    outputdir="${veildir}/output"
    dependenciesdir="${veildir}/setup-dependencies"
    rootdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd )
    winedir="${veildir}/wine"
    winedrive="${winedir}/drive_c"
    gempath="${winedir}\drive_c\Ruby187\bin\gem"
    replace="\"
    prefix="Z:"
    gempath="${gempath////$replace}"
    gempath="${prefix}${gempath}"

I'd start with /var/lib/veil and then check stuff flike /etc/ or /var/log

that is what u/rschulze said on my post (https://www.reddit.com/r/bash/comments/9d5q8w/can_someone_read_this_bash_file_to_tell_me_where/) at r/bash on reddit. I though someone might find it helpful so I posted it here. :)

**Comment by clancrate** [comment]
Also you might want to remove the application icons of wine and veil, this might help you as I used it to remove mine: https://askubuntu.com/questions/568258/how-to-remove-icons-from-all-applications
