### ISSUE TITLE
Failed to run wine

### ISSUE THREAD

**Issue by kaivan-s** [Veil-Framework/Veil#244]
#104  with installing wine (2): 0
Failed to run (wine) Python pip... Exit code: 193
Failed to run (wine) Python pip future... Exit code: 193
Failed to run (wine) Python pip pefile... Exit code: 193
Failed to install (Wine) Ruby.exe... Exit code: 193
Failed to run (wine) Ruby OCRA.. Exit code: 49
Failed to run (wine) AutoIT.. Exit code: 193

**Comment by ChrisTruncer** [comment]
Please provide all information requested when making an issue
