### ISSUE TITLE
Failure to install wine for python

### ISSUE THREAD

**Issue by kaivan-s** [Veil-Framework/Veil#245]
## Veil version
Version 3.1.6

## OS Used - all info (architecture, linux flavor, etc)
Kali linux 2018.3

## How did you install Veil? (Apt, Clone from Github, etc.)
Clone from Github

## Did you run the setup script?

Yes. The setup.sh script

## Pastebin link to error you are encountering (include console actions you took prior to error)
1) ran the ./setup.sh --silent --force command to install
2) dependencies are installed but fails to install wine for python.

Failed with installing wine (2): 0
Failed to run (wine) Python pip... Exit code: 193
Failed to run (wine) Python pip future... Exit code: 193
Failed to run (wine) Python pip pefile... Exit code: 193
Failed to install (Wine) Ruby.exe... Exit code: 193
Failed to run (wine) Ruby OCRA.. Exit code: 49
Failed to run (wine) AutoIT.. Exit code: 193

## Expected behavior
Complete Installation of all packages.

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
Can you provide any additional details? I’m testing this on a clean Kali VM with nothing else installed, and it is able to install and run Veil.

Can you also try different mirrors for your apt sources?

**Comment by kedllango** [comment]
re-install it using an interface and not while ssh-ing to it.

**Comment by kaivan-s** [comment]
Solved, Thank You !! I tried reinstalling it with nothing in Kali linux and it worked.

**Comment by adada111** [comment]
how to sloved?
