### ISSUE TITLE
MSE Catches Everything

### ISSUE THREAD

**Issue by Snowman418** [Veil-Framework/Veil#247]
## Veil version
3.1.11

## OS Used - all info (architecture, linux flavor, etc) 
kali 2018.3.2

## How did you install Veil? (Apt, Clone from Github, etc.)
apt

## Did you run the setup script?
yes

## Any additional info you want to tell me
Are there more encoders available? MSE catches everything Veil spits out. Not very effective.

**Comment by ChrisTruncer** [comment]
If you leave everything to the defaults, you can’t act surprised if it is caught. I have tested Veil without the default values and it does bypass detection. Encoders do not make something bypass AV.

Please do a little research into bypassing AV, and the different options that Veil allows you to specify. If you don’t do that, and just ask for more modules without changing anything, it doesn’t result in a useful Github issue

**Comment by Snowman418** [comment]
What other values could you possibly set? Every single payload in this package is detected. What magical tests have you performed that aren't detected?

Maybe you should head over to unicorn and see how they did it...

**Comment by ChrisTruncer** [comment]
There are numerous blog posts about this from myself, and others that have used Veil. Please feel free to review them, but if you’re not willing to take the time to do so, then I feel it’s reasonable for me to not re-explain it.
