### ISSUE TITLE
dlll sorunu

### ISSUE THREAD

**Issue by afyok003** [Veil-Framework/Veil#251]
## Veil version
Veil 3.1.

## OS Used - all info (architecture, linux flavor, etc)
linuxx2.6/3.x/4.x(64-bit)

## How did you install Veil? (Apt, Clone from Github, etc.)
sudo apt-get -y install git
git clone https://github.com/Veil-Framework/Veil.git
cd Veil/
bash setup.sh

## Did you run the setup script?
yes 
bash setup.sh

## Pastebin link to error you are encountering (include console actions you took prior to error)

0030:err:msi:ACTİON_CALLDLLFunction failed to load dll L"C:\users\root\Temp\msie025.tmp" (193) Bu durum ile karşılaşıyorum ???

## Expected behavior

sorunun çözümlenmesi

## Any additional info you want to tell me

acil yardım edin !

**Comment by ChrisTruncer** [comment]
Hi, I'm sorry, but I am unable to recreate this error.

Please try running the setup script how we tell you to run it in the readme:

./setup.sh --force --silent
