### ISSUE TITLE
Questions - About using payloads coded in another language than Python.

### ISSUE THREAD

**Issue by Dagdelo** [Veil-Framework/Veil#252]
Hi! I'm new with Veil and trying to understand how can I use Veil with a payload wrote in C++, for e.g. Or any other language. I was looking in the Veil/tools/evasion/payloads/ there have various folders with dif languages but all the payloads are coded in Python. 

So my question is: I have to translate my payloads to Python to use this Framework?

**Comment by ChrisTruncer** [comment]
The shell which contains the payload code is indeed written in python, that is so the framework can access each module, identify required options for each module, etc. But if you look at the code itself within each module, they are in their own respective language. There is golang code within the python module within the go folder.

This is an older blog post, but it has some good info - https://www.veil-framework.com/tutorial-veil-payload-development/

All payloads modules containing your code will need to be python 3 compliant, but obviously the underlying code itself can be in its own language. If you are writing a module for an already supported language, just add it into its respective folder and the framework will auto pick it up. If it's a currently unsupported language, you would need to let me know and we can look into adding support for it.

I'll close this issue, but if you have any questions, try googling for what info we already have available, and then feel free to ask for anything not covered

**Comment by Dagdelo** [comment]
@ChrisTruncer Thx for the useful information! I looked carefully the code in py and spotted the pieces of another's languages. Now my question is if a want to veil [this ](https://raw.githubusercontent.com/nettitude/PoshC2/master/Modules/Get-Keystrokes.ps1)payload in PowerShell whats steps should I take to do it? Do I have to mime the steps of obfuscation as it did in the other payloads to accomplish that? Or it exists a 'more automated' way to do so? If so, what are the steps, I mean, the commands?
