### ISSUE TITLE
Veil installation halts and freezes

### ISSUE THREAD

**Issue by anao00** [Veil-Framework/Veil#254]
## Veil version
Unknown since I wasn't able to install it. But it is the most up to date one as of October 24th, 2018.

## OS Used - all info (architecture, linux flavor, etc)
64 bit Linux Mint 18.1, kernel 4.13.0-17-generic.

## How did you install Veil? (Apt, Clone from Github, etc.)
I didn't, but I tried to by cloning it from github and running the setup.sh --force --silent as root, inside the config folder.

## Did you run the setup script?
With --force and --silent arguments enabled and as root.

## Pastebin link to error you are encountering (include console actions you took prior to error)
https://pastebin.com/hWgAWJE2
After 40 minutes without any activity I had to CTRL C it.

## Expected behavior
Installing without halting and not telling me reason why.

## Any additional info you want to tell me
None.

**Comment by ChrisTruncer** [comment]
Are you able to attempt this again? I’ve (fortunately/unfortunately) never experienced a freeze during the install process, so I don’t really have a way to debug that. If there was an error of some sort then I could look into it, but the freeze is something I can’t.

**Comment by ChrisTruncer** [comment]
Any info?

**Comment by ChrisTruncer** [comment]
closing since I haven't had a response.
