### ISSUE TITLE
installatione Error

### ISSUE THREAD

**Issue by arashex** [Veil-Framework/Veil#255]
Hi 
![screenshot 106](https://user-images.githubusercontent.com/36920707/47936587-60f6b400-def3-11e8-8274-6940dff9a6cc.png)
I downloaded the version3.1.X but I got to the following Error .
please guide me

**Comment by ChrisTruncer** [comment]
You didn't provide any of the information that was requested when you were creating the issue. Please provide the requested information.

Additionally, you can see from the screenshot that the git clone failed, so nothing else would be able to install. Please try running the setup script as shown in the readme. If you need to open another issue, please provide all information.
