### ISSUE TITLE
is it a wine issue or a kali repo issue?

### ISSUE THREAD

**Issue by Rogue899** [Veil-Framework/Veil#257]
[*] Installing Wine 32-bit and 64-bit binaries (via APT)

E: Failed to fetch http://kali.download/kali/pool/main/l/llvm-toolchain-6.0/libclang-common-6.0-dev_6.0.1-9.2_amd64.deb  503  Service Unavailable [IP: 104.18.247.114 80]
E: Failed to fetch http://kali.download/kali/pool/main/m/mesa/libgl1-mesa-dri_18.1.9-1_i386.deb  Connection failed [IP: 104.18.246.114 80]
E: Failed to fetch http://kali.download/kali/pool/main/w/wine/libwine_3.0.3-2_i386.deb  Connection timed out [IP: 104.18.244.114 80]
E: Failed to fetch http://kali.download/kali/pool/main/m/mesa/mesa-va-drivers_18.1.9-1_i386.deb  Connection failed [IP: 104.18.243.114 80]
E: Failed to fetch http://kali.download/kali/pool/main/m/mesa/mesa-vdpau-drivers_18.1.9-1_amd64.deb  Connection failed [IP: 104.18.245.114 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
 [ERROR] Failed with installing wine (2): 0

## OS Used - all info (architecture, linux flavor, etc)
using kali rolling 2018.3

## How did you install Veil? (Apt, Clone from Github, etc.)
installed veil through github

## Did you run the setup script?
yes

**Comment by ChrisTruncer** [comment]
That’s going to be a Kali, and more likely your specific VM issue. If you can’t hit the repos, then you can’t download required files.
