### ISSUE TITLE
regular user support

### ISSUE THREAD

**Issue by blshkv** [Veil-Framework/Veil#259]
It would be very helpful if it could be possible to specify user home directory in ```settings.py``` for all outputs, for example:

```
PAYLOAD_SOURCE_PATH="~/.veil/output/source/"
PAYLOAD_COMPILED_PATH="~/.veil/output/compiled/"
HANDLER_PATH="~/.veil/output/handlers/"
HASH_LIST="~/.veil/output/hashes.txt"
```

I have tried it, but the tool failed with the following message:
```
 [>] Please enter the base name for output files (default is payload): test
Traceback (most recent call last):
  File "./Veil.py", line 135, in <module>
    the_conductor.main_menu()
  File "/usr/lib64/veil/lib/common/orchestra.py", line 138, in main_menu
    tool_object.tool_main_menu()
  File "tools/evasion/tool.py", line 370, in tool_main_menu
    self.use_payload(selected_payload_module)
  File "tools/evasion/tool.py", line 403, in use_payload
    if outfile.compiler(selected_payload):
  File "/usr/lib64/veil/tools/evasion/evasion_common/outfile.py", line 53, in compiler
    with open(source_code_filepath, 'w') as source_file:
FileNotFoundError: [Errno 2] No such file or directory: '~/.veil/output/source/test.py'
```

**Comment by ChrisTruncer** [comment]
Veil will use the current settings set with the installer. However, you can feel free to edit them. The above error looks like Veil isn't able to find the file/folder that you are specifying. It won't auto-create folders, so make sure everything exists before you change the values in the settings.py file.

**Comment by blshkv** [comment]
This is not correct, the directory exists:

```
 [>] Please enter the base name for output files (default is payload): 
Traceback (most recent call last):
  File "./Veil.py", line 135, in <module>
    the_conductor.main_menu()
  File "/usr/lib64/veil/lib/common/orchestra.py", line 129, in main_menu
    tool_object.tool_main_menu()
  File "tools/evasion/tool.py", line 370, in tool_main_menu
    self.use_payload(selected_payload_module)
  File "tools/evasion/tool.py", line 403, in use_payload
    if outfile.compiler(selected_payload):
  File "/usr/lib64/veil/tools/evasion/evasion_common/outfile.py", line 53, in compiler
    with open(source_code_filepath, 'w') as source_file:
FileNotFoundError: [Errno 2] No such file or directory: '~/.veil/output/source/payload.py'

bash ~ $ ls -al ~/.veil/output/source/
total 8
drwxr-xr-x 2  4096 Nov 14 16:19 .
drwxr-xr-x 5  4096 Nov 23 07:37 ..

```

It would be also logical if tool could create the required directory structure. I'm not able to create it for each user (~)

I'm unable to re-open the bug so please do it.

**Comment by blshkv** [comment]
https://github.com/Veil-Framework/Veil/blob/master/tools/evasion/evasion_common/outfile.py#L53

The quick fix (just for the line 53) is to add the following:
``` with open(os.path.expanduser(source_code_filepath), 'w') as source_file:```

Please add it for all output variables

**Comment by ChrisTruncer** [comment]
I just tested this on my system with Debian. I modified the settings file to point to a folder in my home directory, and it was able to write the source code, handler, and compiled binary to the modified path.

![modifiedpath](https://user-images.githubusercontent.com/1674822/48986280-3520b580-f0d0-11e8-936e-9a107b9987a7.png)

**Comment by blshkv** [comment]
That's not exactly what I'm asking. It has to be a generic ```~/.vail/output``` (notice on the ~ tilde). 
As a workaround, I came out with the following silly workaround:
```
# Path to output the source of payloads
PAYLOAD_SOURCE_PATH=os.path.expanduser("~/.veil/output/source/")

# Path to output compiled payloads
PAYLOAD_COMPILED_PATH=os.path.expanduser("~/.veil/output/compiled/")

# Where to generate a msf handler script
HANDLER_PATH=os.path.expanduser("~/.veil/output/handlers/")

# Running hash list of all payloads generated
HASH_LIST=os.path.expanduser("~/.veil/output/hashes.txt")
```
