### ISSUE TITLE
Veil Framework Won't Install Correctly 

### ISSUE THREAD

**Issue by mh10280** [Veil-Framework/Veil#260]
## Veil version
3.1.X

## OS Used - all info (architecture, linux flavor, etc)
Kali2018.4 x86_64

## How did you install Veil? (Apt, Clone from Github, etc.)
Clone

## Did you run the setup script?
Yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
Failed with installing dependencies (1): 0
Failed with installing wine (2): 0
Failed to run (wine) Python pip... Exit code: 193
Failed to run (wine) Python pip future... Exit code: 193
Failed to run (wine) Python pip pefile... Exit code: 193
Failed to install (Wine) Ruby.exe... Exit code: 193
Failed to run (wine) Ruby OCRA.. Exit code: 49
Failed to run (wine) AutoIT.. Exit code: 193

## Expected behavior
NA

## Any additional info you want to tell me
This is a clean Kali install and every time I try to run the setup Wine doesn't want to function correctly and I keep getting this error on both my Macbook and my Desktop. If I need to include more please let me know.

**Comment by ChrisTruncer** [comment]
I actually just tested with the latest version of Veil on the latest version of Kali yesterday, and it installed correctly. Please follow the README's directions on how to install Veil, or provide a repeatable manner to recreate the issue.

**Comment by ChrisTruncer** [comment]
I'm just unfortunately able to recreate this, since my test yesterday did have everything install correctly.

**Comment by mh10280** [comment]
I’ll screen record me installing Veil and the errors I get and I’ll send them to you. Hopefully you can tell me where I went wrong, I really want to test with Veil so hopefully it’s just something simple.
