### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by llsoll** [Veil-Framework/Veil#261]
## Veil version
3.1.X

## OS Used - all info (architecture, linux flavor, etc)
Tried on Debian 9, Ubuntu 18.10 and kali linux 2018.4 (all x86_64)
All of them gave the same errors.
## How did you install Veil? (Apt, Clone from Github, etc.)
Ubuntu and Debian - clone
Kali linux - apt

## Did you run the setup script?
yes (it fails)

## Pastebin link to error you are encountering (include console actions you took prior to error)
https://pastebin.com/aUDCFE7n

## Expected behavior
What?

## Any additional info you want to tell me
There aren't any issues in the VMs.

**Comment by ChrisTruncer** [comment]
You have no internet, or it is related to your system/network. If you look at your log, it shows it can't even perform an apt-get update. Please follow the readme to see how to install Veil
