### ISSUE TITLE
How do I unset a payload option?

### ISSUE THREAD

**Issue by cm0s2** [Veil-Framework/Veil#269]
## Veil version
3.1.11

## OS Used - all info (architecture, linux flavor, etc)
Kali Linux 2018.2

## How did you install Veil? (Apt, Clone from Github, etc.)
Clone from github

## Did you run the setup script?
Yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
https://pastebin.com/Tsn2Fp1K

## Expected behavior
Trying to unset SLEEP (so it's set to "X")

I've tried:
set SLEEP X
set SLEEP x
unset SLEEP
etc

No matter what I try, Veil still thinks SLEEP is set, giving me this error when I run generate:
[*] If using SLEEP check with Ruby, you must also provide an additional check (like HOSTNAME)!

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
For certain payloads the framework won’t let you since there are additional things you must also set (like a hostname with sleep when using Ruby). Likely, the easiest way is to just close Veil and start again.

**Comment by cm0s2** [comment]
Okay, I'll simply exit out of Veil and start it again to reset my options. Thanks for the swift reply!
