### ISSUE TITLE
Issue running veil.py 

### ISSUE THREAD

**Issue by ajay340** [Veil-Framework/Veil#27]
## Veil version
3.0

## OS Used - all info (architecture, linux flavor, etc)
Debian 8 64 bit

## Pastebin link to error you are encountering (include console actions you took prior to error)
python Veil.py
Traceback (most recent call last):
  File "Veil.py", line 5, in <module>
    from lib.common import helpers
ImportError: No module named lib.common

## Expected behavior
Veil doesn't run

## Any additional info you want to tell me
I ran setup.sh -c but I still have the issue

**Comment by ChrisTruncer** [comment]
Just call ./Veil.py

You're trying to use Python 2 to run a py3 script
