### ISSUE TITLE
Sorry Doing this, THanks for help But...

### ISSUE THREAD

**Issue by r3x07** [Veil-Framework/Veil#270]
Thanks For Helping me!
I hope you update your screen soon, i reinstalled my linux and its working now
but my Anti-Virus found it (Mircosoft Security Essentials)
and Yes my **Anti-Virus** was updated
hope you update your script soon!

Thanks!
Sincerely Adam

**Comment by matrunchyk** [comment]
Yeah, the detection rate [is pretty high](https://spyralscanner.net/result.php?id=PRF3sHxBYu), unfortunately.


But great tool anyways!

**Comment by r3x07** [comment]
ye  i wish it was undetectable

**Comment by ChrisTruncer** [comment]
There are multiple options for you all to set. Do not use the default settings, or try changing the templates that make up the executable
