### ISSUE TITLE
Metasploit not found

### ISSUE THREAD

**Issue by r3x07** [Veil-Framework/Veil#272]
root@fbi~#  veil

 [!] ERROR #2-3: Can't find the Metasploit Framework (/usr/share/metasploit-framework/).   Run: /usr/share/veil/config/setup.sh --force --silent

i want to install it on other pc but it wont work saying that, and metasploit is installed why does it say that?

**Comment by ChrisTruncer** [comment]
Hi, it means that your settings file isn’t pointing to the proper directory. Please follow the directions that the error message is giving you.

**Comment by r3x07** [comment]
I did it still says the same thing
