### ISSUE TITLE
Stop closing my issue, just listen to me and reply

### ISSUE THREAD

**Issue by r3x07** [Veil-Framework/Veil#273]
root@fbi~# veil

[!] ERROR #2-3: Can't find the Metasploit Framework (/usr/share/metasploit-framework/). Run: /usr/share/veil/config/setup.sh --force --silent

**I did it 5 times already and it keeps saying metasploit not found**

**Comment by b4cktr4ck2** [comment]
@deadfishhackers I had the same issue, I know how to fix it. 

@ChrisTruncer  I'm not sure why it can't be reproduced, best way to reproduce is to just move the metasploit-framework elsewhere that's not in METASPLOIT_PATH.

To fix:
1. Find the location of Metasploit on your system (whereis metasploit-framework). Copy the folder path (I.e /usr/share/metasploit-framework)
2. Open /etc/veil/settings.py in an editor.
3. Scroll down to METASPLOIT_PATH and paste the path in to replace the default.
4. Re-run veil.

Hopefully this can help some other people who land here when trying to find a fix.
