### ISSUE TITLE
Update documentation to mention x server in requirements?

### ISSUE THREAD

**Issue by Pernat1y** [Veil-Framework/Veil#274]
## Veil version
3.1.11 (git)

## OS Used - all info (architecture, linux flavor, etc)
Kali 2018.4
Linux kali 4.18.0-kali3-amd64 #1 SMP Debian 4.18.20-2kali2 (2018-11-30) x86_64 GNU/Linux

## How did you install Veil? (Apt, Clone from Github, etc.)
Clone from git

## Did you run the setup script?
Yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
https://pastebin.com/JUtzX4zk
(see errors in "Installing (Wine) ..." sections)

## Expected behavior
To successfully install

## Any additional info you want to tell me
So, I have tried to install Veil on remote server via ssh and it failed (looks like because of errors while installing Wine modules).
Then I tried to run same installation directly on host (Gnome, default UI on Kali) and it was installed just fine.
If it is expected behavior and not a bug, we need to update documentation to mention it and/or add check for x server (e.g. with "xset q" command).

**Comment by ChrisTruncer** [comment]
I might need to look into this a little more. For some reason I had thought that this would be able to be installed headlessly, but I just encountered the same error you did. For the time being, it might help to update the docs to say it needs an x server unless it is possible to install headlessly


________________________________

**Comment by ChrisTruncer** [comment]
this has been added in, thanks!
