### ISSUE TITLE
Unable to determine OS Information

### ISSUE THREAD

**Issue by glides** [Veil-Framework/Veil#277]
## Veil version
3.1.11

## OS Used - all info (architecture, linux flavor, etc)
Elementary OS 5.0

## How did you install Veil? (Apt, Clone from Github, etc.)
github

## Did you run the setup script?
Trying ;)

## Pastebin link to error you are encountering (include console actions you took prior to error)
```
glides@x-ops:~/Code/Veil$ ./config/setup.sh 
 ==========================================================================
                 Veil (Setup Script) | [Updated]: 2018-05-08
 ==========================================================================
     [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
 ==========================================================================

                 os = elementary
          osversion = 5.0
       osmajversion = 5
               arch = x86_64
           trueuser = glides
   userprimarygroup = glides
        userhomedir = /home/glides
            rootdir = /home/glides/Code/Veil
            veildir = /var/lib/veil
          outputdir = /var/lib/veil/output
    dependenciesdir = /var/lib/veil/setup-dependencies
            winedir = /var/lib/veil/wine
          winedrive = /var/lib/veil/wine/drive_c
            gempath = Z:\var\lib\veil\wine\drive_c\Ruby187\bin\gem

 [ERROR] Unable to determine OS information. Exiting...
```

## Expected behavior
Well, it detects the OS - so...not that?

## Any additional info you want to tell me
The setup.sh script has '"Elementary"' instead of just 'Elementary' in the IF/THEN OS detection logic.
Removing a set of the quotes will fix the issue.

**Comment by ChrisTruncer** [comment]
Thanks for sending this report along with a fix, that makes it a lot easier. Just curious, do you have any interest in submitting a pull request with the fix? If so, it would show you having credit with the fix in the codebase. I figured I would ask first, thanks!


________________________________

**Comment by glides** [comment]
Sure, I'll do a pull and get it in there later tonight if you've not done it yet.

**Comment by ChrisTruncer** [comment]
This has been merged in, thanks!

**Comment by azrahel98** [comment]
nano ./setup.sh  --- ctrol+w elementary   borrar las comillas ("") y cambiar por ('')
