### ISSUE TITLE
Jumping back to main menu

### ISSUE THREAD

**Issue by JoeNibe** [Veil-Framework/Veil#28]
## Veil version
3.0

## OS Used - all info (architecture, linux flavor, etc)
Kali 2.0

## Pastebin link to error you are encountering (include console actions you took prior to error)
I installed Veil and ran it. It shows 

Main Menu

	2 tools loaded

Available Commands:

	exit			Exit Veil
	info			Information on a specific tool
	list			List available tools
	update			Update Veil
	use			Use a specific tool

Main menu choice: 

#then i used use
[*] Available Tools:

	1)	Evasion
	2)	Ordnance

Main menu choice: 
#When i try to select 1 it jumps back to main menu.

## Expected behavior
It should be showing modules in Evasion

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
Please show the exact command you are trying to run, might be easiest to link to pastebin

**Comment by ChrisTruncer** [comment]
I'm assuming you're typing the number "1". Please type "use 1".

**Comment by JoeNibe** [comment]
Thanks a lot it worked.
