### ISSUE TITLE
Wine error compiling payload .py to exe.

### ISSUE THREAD

**Issue by josu22** [Veil-Framework/Veil#281]
## Veil version
3.1.11

## OS Used - all info (architecture, linux flavor, etc)
Kali 2019.1 x86_64

## How did you install Veil? (Apt, Clone from Github, etc.)
apt and clone (both)

## Did you run the setup script?
Yes, with --silence --force, all time the same error.

## Pastebin link to error you are encountering (include console actions you took prior to error)

veil
use 1
use 27
set 1.1.1.1
generate

[?] How would you like to create your payload executable?

     1 - PyInstaller (default)
     2 - Py2Exe

 [>] Please enter the number of your choice: 1
0009:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
174 INFO: PyInstaller: 3.2.1
174 INFO: Python: 3.4.4
175 INFO: Platform: Windows-7-6.1.7601-SP1
Traceback (most recent call last):
  File "/var/lib/veil/PyInstaller-3.2.1//pyinstaller.py", line 15, in <module>
    run()
  File "Z:\var\lib\veil\PyInstaller-3.2.1\PyInstaller\__main__.py", line 88, in run
    spec_file = run_makespec(**vars(args))
  File "Z:\var\lib\veil\PyInstaller-3.2.1\PyInstaller\__main__.py", line 40, in run_makespec
    spec_file = PyInstaller.building.makespec.main(filenames, **opts)
  File "Z:\var\lib\veil\PyInstaller-3.2.1\PyInstaller\building\makespec.py", line 372, in main
    specfile = open(specfnm, 'w')
PermissionError: [Errno 13] Permission denied: 'Z:\\usr\\share\\veil\\asdads.spec'
===============================================================================
                                   Veil-Evasion
===============================================================================
      [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
===============================================================================

 [!] ERROR: Unable to create output file.
 [*] Source code written to: /var/lib/veil/output/source/asdads.py
 [*] Metasploit Resource file written to: /var/lib/veil/output/handlers/asdads.rc

Hit enter to continue...

## Expected behavior
Payload .exe generated

## Any additional info you want to tell me

Actually i tried 

unninstall veil, dpkg --add-architecture i386, install veil via apt and git clone.
chmod -R 777 to /var/lib/veil/wine

Same error all times.

**Comment by josu22** [comment]
News! i fix something. I dont know what.

but now i have this error:

 [>] Please enter the number of your choice: 1
wine: /var/lib/veil/wine is not owned by you
===============================================================================
                                   Veil-Evasion
===============================================================================
      [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
===============================================================================

 [!] ERROR: Unable to create output file.
 [*] Source code written to: /var/lib/veil/output/source/asdasdasd.py
 [*] Metasploit Resource file written to: /var/lib/veil/output/handlers/asdasdasd.rc

Hit enter to continue...

**Comment by ChrisTruncer** [comment]
So I believe this is something with your VM. I tested the latest Kali build and ran Veil's setup process. I was able to receive the output from Veil once I installed in, so I think it might be worth testing on a clean VM on your end (or modify the directory permissions of your existing VM).

**Comment by josu22** [comment]
> 
> 
> So I believe this is something with your VM. I tested the latest Kali build and ran Veil's setup process. I was able to receive the output from Veil once I installed in, so I think it might be worth testing on a clean VM on your end (or modify the directory permissions of your existing VM).

This is not a VM, i dont know why you close the issue, if you dont want fix it, keep the community helps.

Thanks for your repply
