### ISSUE TITLE
setup.sh requires sudo even as root

### ISSUE THREAD

**Issue by tmsteen** [Veil-Framework/Veil#282]
## Veil version
3.1.11

## OS Used - all info (architecture, linux flavor, etc)
Docker Ubuntu 18.04

## How did you install Veil? (Apt, Clone from Github, etc.)
Clone from GitHub

## Did you run the setup script?
Yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
https://pastebin.com/aa0nV2HT

## Expected behavior
The Ubuntu Docker base image runs as root, I expect that this would be enough to run the setup script but the script explicitly checks for `sudo` which is not part of the base image. 

## Any additional info you want to tell me
Not a  show stopping issue, more an annoyance if anything. Running `apt install sudo` during image build (in the Dockerfile) solves the issue.

**Comment by ChrisTruncer** [comment]
Thanks for the submission, and while it might be a small annoyance, that's how we're currently tracking and maintaining the user account that in doing the install (in the event they don't have root/admin privs).

I don't believe I'm going to change this in the short term, but if everything else is done (ha), then this is something I can look to in the future (or I'd be happy to review/test a pull request).
