### ISSUE TITLE
Add Parrot Security OS to setup script

### ISSUE THREAD

**Issue by dmknght** [Veil-Framework/Veil#284]
## Veil version
`Veil | [Version]: 3.1.11` (apt version: `Version: 3.1.11-0kali1`)

## OS Used - all info (architecture, linux flavor, etc)
Parrot Security OS 4.5 amd64

## How did you install Veil? (Apt, Clone from Github, etc.)
`sudo apt install veil && veil`

## Did you run the setup script?
Yes

## Error message
`[!] ERROR #2-3: Can’t find the Metasploit Framework (/opt/metasploit-framework/embedded/framework/). Run: /usr/share/veil/config/setup.sh --force --silent`

## Expected behavior

Veil should detect metasploit-framework path on Parrot Security OS
## Any additional info you want to tell me
By default, veil has hard-coded metasploit-framework path. Parrot OS as same as path.
![screenshot from 2019-02-08 21-12-56](https://user-images.githubusercontent.com/29118926/52483728-32216580-2be7-11e9-8e49-5ce74c9a2bf1.png)
But, veil detects Parrot Security OS as regular Linux distribution, which caused "can't find path" issue
![screenshot from 2019-02-08 21-11-18](https://user-images.githubusercontent.com/29118926/52483948-acea8080-2be7-11e9-8f74-c264c60e3e52.png)

Forum issue URL `https://community.parrotsec.org/t/veil-evasion-doesnt-install/5626/12`
## Suggestion: Add Parrot to `line 196`

**Comment by ChrisTruncer** [comment]
I can’t control how Veil is packaged in apt, so that’s not something that I can change.

I personally don’t have Parrot, but since you do, would you like to test the fix and then submit a pull request? I can review it then and get it merged in.


________________________________

**Comment by dmknght** [comment]
I believe if you update script and release next version, Kali and Parrot repository will update it and problem will be solved in next version. I am testing setup script. I will create pull request as soon as possible
