### ISSUE TITLE
Veil Installation Failure

### ISSUE THREAD

**Issue by amith1108** [Veil-Framework/Veil#287]
## Veil version
3.1.X

## OS Used - all info (architecture, linux flavor, etc)

Linux kali 4.19.0-kali1-amd64 
#1 SMP Debian 4.19.13-1kali1 (2019-01-03) x86_64 GNU/Linux

## How did you install Veil? (Apt, Clone from Github, etc.)
Tried both the methods(apt and Clone from Github), got the same error on both.

## Did you run the setup script?
Yes, I did.
I followed all the instructions in README.md.

## Pastebin link to error you are encountering (include console actions you took prior to error)
https://pastebin.com/8VhjkDkD

## Expected behavior
I think the expected behavior would have been to install Veil with no errors

## Any additional info you want to tell me
Before using the --force and --silent arguments on setup.sh files I got an error saying PyInstaller directory missing.

PS: Before creating a new issue, I did try to through all the other issues, related to installation failure. But none of the solutions there helped me. The most common solution I found was to edit  /etc/apt/sources.list. I edited it to default and also try to install all the dependencies separately. But none of them seemed to work, as the dependencies (like wine etc) were already installed.

**Comment by ChrisTruncer** [comment]
This looks to be an issue from your system/connection to the internet. If you look at line 45, you should have pulled down the Veil dependencies, but it didn’t happen. You can try manually cloning them and then restarting, or try to run the setup script again.

**Comment by amith1108** [comment]
Hey

> This looks to be an issue from your system/connection to the internet. If you look at line 45, you should have pulled down the Veil dependencies, but it didn’t happen. You can try manually cloning them and then restarting, or try to run the setup script again.
> […](#)
> ________________________________ From: Amith S <notifications@github.com> Sent: Tuesday, February 26, 2019 3:27 AM To: Veil-Framework/Veil Cc: Subscribed Subject: [EXTERNAL E-MAIL]: [Veil-Framework/Veil] Veil Instalation not complete (#287) Veil version 3.1.X OS Used - all info (architecture, linux flavor, etc) Linux kali 4.19.0-kali1-amd64 #1<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FVeil-Framework%2FVeil%2Fissues%2F1&data=02%7C01%7CChris%40fortynorthsecurity.com%7C38a5d3cb5c114b068f4208d69bd5137d%7C13e7061fe89b41a78b92ac403c961ded%7C1%7C0%7C636867736788164827&sdata=me4J4llGgjphg2SAZV9JQsSFYAjlHwU69%2F6vk4Xu%2Bs8%3D&reserved=0> SMP Debian 4.19.13-1kali1 (2019-01-03) x86_64 GNU/Linux How did you install Veil? (Apt, Clone from Github, etc.) Tried both the methods(apt and Clone from Github), got the same error on both. Did you run the setup script? Yes, I did. I followed all the instructions in README.md. Pastebin link to error you are encountering (include console actions you took prior to error) https://pastebin.com/8VhjkDkD<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpastebin.com%2F8VhjkDkD&data=02%7C01%7CChris%40fortynorthsecurity.com%7C38a5d3cb5c114b068f4208d69bd5137d%7C13e7061fe89b41a78b92ac403c961ded%7C1%7C0%7C636867736788174832&sdata=%2B%2Fx02IyR7FVQp8MWghbGMc8BWi%2FgFF67aexNQYTfjbU%3D&reserved=0> Expected behavior I think the expected behavior would have been to install Veil with no errors Any additional info you want to tell me Before using the --force and --silent arguments on setup.sh files I got an error saying PyInstaller directory missing. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FVeil-Framework%2FVeil%2Fissues%2F287&data=02%7C01%7CChris%40fortynorthsecurity.com%7C38a5d3cb5c114b068f4208d69bd5137d%7C13e7061fe89b41a78b92ac403c961ded%7C1%7C0%7C636867736788174832&sdata=znOV2v17LsmsES1Pv6GVkT3mYbk6nYcKU8qFaHsPksc%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABmORuBUNRxPA-Ibld25cLRY8BirjBPBks5vRQwsgaJpZM4bR2Cg&data=02%7C01%7CChris%40fortynorthsecurity.com%7C38a5d3cb5c114b068f4208d69bd5137d%7C13e7061fe89b41a78b92ac403c961ded%7C1%7C0%7C636867736788184841&sdata=RR3Wa8fsC8ZaXaVkOP%2F3J3KrnpciITdHIsy3V3WrQWc%3D&reserved=0>. [EXTERNAL E-MAIL] - ATTENTION: This e-mail was sent from an external source!
Hey Chris, 
Thnk for your reply. I'll try to manually clone Veil and install it again.

**Comment by amith1108** [comment]
Hey Chris,
Thank you for your reply, ill try to clone Veil manually and install it again.

**Comment by amith1108** [comment]
Hey Chris,
I've solved my issue and successfully installed Veil.
Thank you for help in pointing  out the issue.

As you suggested i tried to manually clone the Veil repo, I successfully cloned it but when I ran the 'sudo ./config/setup.sh --force --silent' command it gave me the same error.
After failing multiple times trying to install it, I started to dig around the internet.

I wandered on the Stack Exchange sites trying to solve my issues. 
I read some some comments where people suggested to increase the buffer size of git etc.

# Solution

I solved my issue by installing  the package 'gnutls-bin':

## Command to install gnutls-bin:  sudo apt install gnutls-bin

Here is the complete installation process:
https://pastebin.com/c7eQQvWW

Thank You, 
amith
