### ISSUE TITLE
Wont Load Please Please Help

### ISSUE THREAD

**Issue by computer00776** [Veil-Framework/Veil#29]
After install this error when trying to run

Traceback (most recent call last):
  File "Veil.py", line 5, in <module>
    from lib.common import helpers
ImportError: No module named lib.common

**Comment by computer00776** [comment]
Additional errors when installing

rr:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot

**Comment by ChrisTruncer** [comment]
Please clone Veil down, and just run it with ./Veil.py. It will auto-run python 3

**Comment by SChahtelln** [comment]
I have this problen too. Can you hellp me. I open neu issue hier. https://github.com/SChahtelln/mann/issues/1
