### ISSUE TITLE
veil install fail

### ISSUE THREAD

**Issue by gearcapitan** [Veil-Framework/Veil#290]
## Veil version
lastest

## OS Used - all info (architecture, linux flavor, etc)
linux

## How did you install Veil? (Apt, Clone from Github, etc.)
git

## Did you run the setup script?
yes

## Pastebin link to error you are encountering (include console actions you took prior to error)

![imagen](https://user-images.githubusercontent.com/13740942/54477523-4fd98000-47ce-11e9-974e-d5b3e806be60.png)

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
You didn’t provide enough information for me to debug this. I am asking for the version of Linux you are running so I can test on it (assuming it is supported). Can you provide that information?

**Comment by ChrisTruncer** [comment]
closing since I haven't heard any additional information. Feel free to add the info if you can
