### ISSUE TITLE
install python modules fail

### ISSUE THREAD

**Issue by Any3ite** [Veil-Framework/Veil#291]
# Linux kali 4.19.0-kali3-amd64 #1 SMP Debian 4.19.20-1kali1 (2019-02-14) x86_64 GNU/Linux

**Comment by ChrisTruncer** [comment]
Are you installing this on a system with an X server running? Veil won’t install headlessly, but should install otherwise.


________________________________

**Comment by ghost** [comment]
hello i have one error after the installation i 'm on parrotsec
 [!] ERROR #2-3: Can't find the Metasploit Framework (/opt/metasploit-framework/embedded
/framework/).   Run: /usr/share/veil/config/setup.sh --force --silent
and /usr/share/veil/config/setup.sh --force --silent no fix
please how fix this error?

**Comment by ChrisTruncer** [comment]
closing due to no response
