### ISSUE TITLE
Python3.7 compatibility: Veil Imports do not use explicit import syntax

### ISSUE THREAD

**Issue by Script-Nomad** [Veil-Framework/Veil#292]
## Veil version
3.1.X

## OS Used - all info (architecture, linux flavor, etc)
Fedora 29 (Linux abyss 4.19.15-300.fc29.x86_64) 

## How did you install Veil? (Apt, Clone from Github, etc.)
git clone method

## Did you run the setup script?
`sudo ./setup.sh --force --silent`

## The Issue
I realized after some repeated attempts to get Veil running that I was attempting to run via Python3.7 and this was causing some annoying import errors. Veil uses _implicit_ imports for its local directories which works in Python <= 3.6 but has been deprecated after Python 3.7, which enforces _explicit_ imports.

```
# Implicit
from lib.common import helpers

# Explicit
from .lib.common import helpers
```

However, the cleaner solution is to add an `__init__.py` file with the `__all__ = ['modules']` syntax for a more cross-compatible solution. I will submit a pull request to address this issue, but I am leaving it here in hopes that other people who are having import issues will be helped by it.

**Comment by kel12345678** [comment]
hello i have one error after the installation i 'm on parrotsec
 [!] ERROR #2-3: Can't find the Metasploit Framework (/opt/metasploit-framework/embedded
/framework/).   Run: /usr/share/veil/config/setup.sh --force --silent
and /usr/share/veil/config/setup.sh --force --silent no fix
please how fix this error?

**Comment by ChrisTruncer** [comment]
Hi @True-Demon, thank you for sending this over. I will review this shortly and look to get it merged in

**Comment by ChrisTruncer** [comment]
This should now be fixed. Thanks!
