### ISSUE TITLE
error installation

### ISSUE THREAD

**Issue by ghost** [Veil-Framework/Veil#295]
hello i have some errors 
[!] ERROR #2-3: Can't find the Metasploit Framework (/opt/metasploit-framework/embedded/framework/)
My os is parrot and i have metasploit but nothing in /opt how fix the path please?

**Comment by ChrisTruncer** [comment]
Hi, all you need to do is provide Veil the path to your metasploit install on the local system in the settings file (within /etc/veil/settings.py)

**Comment by ChrisTruncer** [comment]
Closing because of no response.
