### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by vendforce** [Veil-Framework/Veil#297]
## Pastebin link to error you are encountering (include console actions you took prior to error)
https://pastebin.com/M6T33MaD

## Any additional info you want to tell me
It was working then upgraded some python modules with pip and the now its not working
```
pip list | grep py3compat
py3compat             0.4
```

**Comment by ChrisTruncer** [comment]
Hi, I unfortunately don't support arch, I'm not certain why you would be getting that error. Please be sure to post if you find the answer in case anyone else encounters the same issue.
