### ISSUE TITLE
Veil.py is not running a

### ISSUE THREAD

**Issue by saumyabhatnagar1** [Veil-Framework/Veil#299]
## Veil version
3.1.6

## OS Used - all info (architecture, linux flavor, etc)

KAli Linux
## How did you install Veil? (Apt, Clone from Github, etc.)
Clone from Github

## Did you run the setup script?
yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
On running ./Veil.py it gives error
[!] ERROR #1-3: Can't import /etc/veil/settings.py.   Run: /opt/Veil/config/update-config.py

 And on running update-config.py it gives 
i] Can't find PyInstaller?   Run: /opt/Veil/config/config/setup.sh --force --silent
 [>] Please enter the directory of PyInstaller (e.g. /var/lib/veil/PyInstaller-3.2.1/): 

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
Can you try running setup script? I just installed Veil on a clean version of Kali and did not run into this issue.

**Comment by ChrisTruncer** [comment]
closing due to no response

**Comment by Cisco7** [comment]
Mine still doesn`t work
