### ISSUE TITLE
Broken links to sub-projects

### ISSUE THREAD

**Issue by mjmaley** [Veil-Framework/Veil#3]
Cloning the super project does not pull the current versions of the associated tools and does not contain all Veil-Framework toolsets. The linked tools direct to specific commits in the tool tree but are not on the current master version.

**Comment by ChrisTruncer** [comment]
Thanks for letting us know, we'll get checking this out.  In the meantime, we always accept pull requests too! :)

**Comment by ChrisTruncer** [comment]
Fixed
