### ISSUE TITLE
Cannot go back from Veil-ordnance payloads

### ISSUE THREAD

**Issue by tfriesen** [Veil-Framework/Veil#30]
## Veil version
3.0

## OS Used - all info (architecture, linux flavor, etc)
Kali-rolling amd64, up-to-date

## Pastebin link to error you are encountering (include console actions you took prior to error)
(no pastebin because this is short):

./Veil.py
use 2
payload \<any\>
back -> does not go back

## Expected behavior
goes back to veil-ordnance menu, allowing me to select another payload

## Any additional info you want to tell me
This an awesome tool and I love it and you are amazing. *mancrush*

**Comment by ChrisTruncer** [comment]
Yup, I just validated this. Thanks for reporting it and I'll look into fixing this!

**Comment by ChrisTruncer** [comment]
This should be merged in now, thanks!
