### ISSUE TITLE
The imp package deprecation in favor of importlib.

### ISSUE THREAD

**Issue by sebastian-mora** [Veil-Framework/Veil#301]
## Veil version
3.1.12

[https://docs.python.org/3.7/library/imp.html](url)

**Comment by ChrisTruncer** [comment]
Have you by chance modified the code to use the new library?

**Comment by sebastian-mora** [comment]
Sorry haven't had time to work on it. Planning on helping out more after Defcon!

**Comment by ChrisTruncer** [comment]
closing since this is merged!
