### ISSUE TITLE
i was waiting about 1 hour 

### ISSUE THREAD

**Issue by Imikeeee** [Veil-Framework/Veil#306]
## Veil version
newest

## OS Used - all info (architecture, linux flavor, etc)
Linux parrot 5.1.0-parrot1-3t-amd64 #1 SMP Parrot 5.1.3-1parrot1.3t (2019-05-20) x86_64 GNU/Linux

## How did you install Veil? (Apt, Clone from Github, etc.)

apt says: 
apt-get install veil
Reading package lists... Done
Building dependency tree       
Reading state information... Done
veil is already the newest version (3.1.11-0kali1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

github....

## Did you run the setup script?

yes...

## Pastebin link to error you are encountering (include console actions you took prior to error)

https://pastebin.com/ppqagdrE

## Any additional info you want to tell me
i was waiting about 1 hour 

 [*] Pulling down binary dependencies

 [*] Empty folder... git cloning

Cloning into '/var/lib/veil/setup-dependencies'...
remote: Enumerating objects: 12, done.
Unpacking objects:  33% (4/12)

**Comment by xinranxi** [comment]
I have encountered the same problem

**Comment by xinranxi** [comment]
sudo git clone https://github.com/Veil-Framework/VeilDependencies.git "${dependenciesdir}"
This is the dependency on downloading veil
But I don't know why.
Its download is very slow, so go to the download page and download the zip
Then put it in the folder

github.com/Veil-Framework/VeilDependencies.git 
github.com/Veil-Framework/VeilDependencies.git 
github.com/Veil-Framework/VeilDependencies.git

**Comment by ChrisTruncer** [comment]
This is 100% reliant on your local system and internet connection speed. All that is happening in the setup process is a git clone of the repo.

https://github.com/Veil-Framework/Veil/blob/master/config/setup.sh#L477

There's nothing done that programmatically that is slowing your computer down, this is your computer cloning the repo.

**Comment by vamshi1712** [comment]
I have the same issue,
do this,
apt-get update
apt-get install wine32
./setup.sh ( without silent and force )
It worked for me.
