### ISSUE TITLE
installation failed [ERROR] Failed with git clone: 0

### ISSUE THREAD

**Issue by formessingup** [Veil-Framework/Veil#309]
## Veil version
Latest on date 07/07/2019

## OS Used - all info (architecture, linux flavor, etc)
Kali Linux tried on both versions 32 and 64 bit in Virtual box Laptop OS is window 7 64 bit 
Latest versions 2019.2 both
## How did you install Veil? (Apt, Clone from Github, etc.)
I tried both method Apt and Clone from Github

## Did you run the setup script?
Yes 

## Pastebin link to error you are encountering (include console actions you took prior to error)
![error](https://user-images.githubusercontent.com/52130824/60772536-c38df880-a0ef-11e9-9c9d-6793d371af63.PNG)
![error2](https://user-images.githubusercontent.com/52130824/60772522-a9ecb100-a0ef-11e9-8698-79ecce0dc5f9.PNG)
![error3](https://user-images.githubusercontent.com/52130824/60772523-a9ecb100-a0ef-11e9-955d-2c4760744cb7.PNG)
![error4](https://user-images.githubusercontent.com/52130824/60772524-aa854780-a0ef-11e9-8d1d-838ad74d9932.PNG)
![error5](https://user-images.githubusercontent.com/52130824/60772525-aa854780-a0ef-11e9-8a45-f8eb0fb332d0.PNG)
[error.docx](https://github.com/Veil-Framework/Veil/files/3365994/error.docx)

## Expected behavior
should have installed

## Any additional info you want to tell me
I have been facing this issue from almost a month I have tried many solution i can find online but nothing worked i have tried upgrading Kali Linux both version before installing Veil. I tried installing in both version with out upgrading. I have followed the tutorials to install but still get these errors I followed the method shown in git hub but still no luck. Aldo i have tried clean installation many times again no luck not even once I was able to install successfully every single time same errorI am new to Linux so I have no idea what wrong here

**Comment by ChrisTruncer** [comment]
Unfortunately, this is going to be an issue on your side (either with your internet connection, or somehow losing internet access). All that is happening is Veil is trying to clone the repo with a git clone. You can manually clone the repo if you would like and then do the install too. But this isn't an issue with the setup script itself.

**Comment by AlNuman5** [comment]
Please help
![Screenshot from 2019-07-31 17-35-29](https://user-images.githubusercontent.com/44569464/62172707-0771c780-b355-11e9-825c-edcd6b24fa1c.png)

**Comment by KedarJoshi11** [comment]
> Please help
> ![Screenshot from 2019-07-31 17-35-29](https://user-images.githubusercontent.com/44569464/62172707-0771c780-b355-11e9-825c-edcd6b24fa1c.png)

![image](https://user-images.githubusercontent.com/43803843/84052191-daa72b80-a9cd-11ea-84a0-de962d15586b.png)

I have a similar issue. It is not getting installed.

**Comment by Great-Thanos** [comment]
Same problem

**Comment by ChrisTruncer** [comment]
I'm going to lock this issue. If you receive this, first, please try on a clean Kali system. As of the time of this post, I tested on a clean Kali, i **cloned the repo down and installed via the setup script instead of using apt** and everything installed successfully.
