### ISSUE TITLE
wine32 install error

### ISSUE THREAD

**Issue by tengocharly12** [Veil-Framework/Veil#310]
[!] ERROR #2-3: Can't find the WINE profile for AuotIT v3 (/var/lib/veil/wine//drive_c/Program Files/AutoIt3/Aut2Exe/Aut2exe.exe).   Run: /root/Veil/config/setup.sh --force --silent

i have some isue in ./setup.sh in wine32 
.

**Comment by stealthcopter** [comment]
`dpkg --add-architecture i386 && apt-get update && apt-get install wine32`

**Comment by ChrisTruncer** [comment]
Did this fix the issue @tengocharly12 ?

**Comment by d4t4king** [comment]
> Did this fix the issue @tengocharly12 ?

I am getting wine32 errors as well, although during setup.  I'm not sure if this is another Issue, or can be tacked on to this one.

**Here is the output of setup.py for me:**
```
==========================================================================
                 Veil (Setup Script) | [Updated]: 2018-05-08
 ==========================================================================
     [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
 ==========================================================================

                 os = kali
          osversion = 2019.2
       osmajversion = 2019
               arch = x86_64
           trueuser = root
   userprimarygroup = root
        userhomedir = /root
            rootdir = /root/Veil
            veildir = /var/lib/veil
          outputdir = /var/lib/veil/output
    dependenciesdir = /var/lib/veil/setup-dependencies
            winedir = /var/lib/veil/wine
          winedrive = /var/lib/veil/wine/drive_c
            gempath = Z:\var\lib\veil\wine\drive_c\Ruby187\bin\gem

 [I] Kali Linux 2019.2 x86_64 detected...

 [I] Silent Mode: Enabled
 [I]  Force Mode: Enabled


 [?] Are you sure you wish to install Veil?

     Continue with installation? ([y]es/[s]ilent/[N]o): S



 [*] Initializing package installation



 [*] Installing dependencies

 [*] Updating APT

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package mingw-w64
E: Unable to locate package mono-mcs
 [ERROR] Failed with installing dependencies (1): 0



 [*] Installing Python's pycrypto (via apt)...

Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-crypto is already the newest version (2.6.1-9+b1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
metasploit-framework is already the newest version (5.0.20-0kali1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.


 [*] Pulling down binary dependencies

 [*] Empty folder... git cloning

Cloning into '/var/lib/veil/setup-dependencies'...
remote: Enumerating objects: 12, done.
remote: Total 12 (delta 0), reused 0 (delta 0), pack-reused 12
Unpacking objects: 100% (12/12), done.


 [*] Installing Wine

 [*] Already have x86 architecture added...



 [*] Installing Wine 32-bit and 64-bit binaries (via APT)

E: Package 'wine32' has no installation candidate
 [ERROR] Failed with installing wine (2): 0



 [*] [ALERT]: Existing Veil Wine environment detected at: /var/lib/veil/wine

     Do you want to nuke it? ([y]es/[N]o): Y

 [*] Deleting existing Veil Wine environment...

 [*] Creating new Veil Wine environment in: /var/lib/veil/wine

 [*] Initializing Veil's Wine environment...

it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
wine: '/var/lib/veil/wine' is a 32-bit installation, it cannot support 64-bit applications.
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
wine: '/var/lib/veil/wine' is a 32-bit installation, it cannot support 64-bit applications.
 [*] Veil Wine environment successfully created!



 [*] Finished package installation



 [*] Initializing (OS + Wine) Python dependencies installation...



 [*] Installing (Wine) Python...

 [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)

it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
0012:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0012:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0012:err:ole:get_local_server_stream Failed: 80004002
0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
0014:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0014:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0014:err:ole:get_local_server_stream Failed: 80004002
Could not load wine-gecko. HTML rendering will be disabled.
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/var/lib/veil/wine' has been updated.
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
002f:err:msiexec:custom_action_server Failed to create custom action server pipe: 2
```
It appears to just hang here.  If I run it without the --silent option, a windows dialog pops up to install Python for Windows 3.4, and hangs if I click "Next".


**Contents of /etc/os-release**
```
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2019.2"
VERSION_ID="2019.2"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
```

Let me know if you need any other info.

**Comment by Usama79** [comment]
> > Did this fix the issue @tengocharly12 ?
> 
> I am getting wine32 errors as well, although during setup. I'm not sure if this is another Issue, or can be tacked on to this one.
> 
> **Here is the output of setup.py for me:**
> 
> ```
> ==========================================================================
>                  Veil (Setup Script) | [Updated]: 2018-05-08
>  ==========================================================================
>      [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
>  ==========================================================================
> 
>                  os = kali
>           osversion = 2019.2
>        osmajversion = 2019
>                arch = x86_64
>            trueuser = root
>    userprimarygroup = root
>         userhomedir = /root
>             rootdir = /root/Veil
>             veildir = /var/lib/veil
>           outputdir = /var/lib/veil/output
>     dependenciesdir = /var/lib/veil/setup-dependencies
>             winedir = /var/lib/veil/wine
>           winedrive = /var/lib/veil/wine/drive_c
>             gempath = Z:\var\lib\veil\wine\drive_c\Ruby187\bin\gem
> 
>  [I] Kali Linux 2019.2 x86_64 detected...
> 
>  [I] Silent Mode: Enabled
>  [I]  Force Mode: Enabled
> 
> 
>  [?] Are you sure you wish to install Veil?
> 
>      Continue with installation? ([y]es/[s]ilent/[N]o): S
> 
> 
> 
>  [*] Initializing package installation
> 
> 
> 
>  [*] Installing dependencies
> 
>  [*] Updating APT
> 
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package mingw-w64
> E: Unable to locate package mono-mcs
>  [ERROR] Failed with installing dependencies (1): 0
> 
> 
> 
>  [*] Installing Python's pycrypto (via apt)...
> 
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> python3-crypto is already the newest version (2.6.1-9+b1).
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> metasploit-framework is already the newest version (5.0.20-0kali1).
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> 
> 
>  [*] Pulling down binary dependencies
> 
>  [*] Empty folder... git cloning
> 
> Cloning into '/var/lib/veil/setup-dependencies'...
> remote: Enumerating objects: 12, done.
> remote: Total 12 (delta 0), reused 0 (delta 0), pack-reused 12
> Unpacking objects: 100% (12/12), done.
> 
> 
>  [*] Installing Wine
> 
>  [*] Already have x86 architecture added...
> 
> 
> 
>  [*] Installing Wine 32-bit and 64-bit binaries (via APT)
> 
> E: Package 'wine32' has no installation candidate
>  [ERROR] Failed with installing wine (2): 0
> 
> 
> 
>  [*] [ALERT]: Existing Veil Wine environment detected at: /var/lib/veil/wine
> 
>      Do you want to nuke it? ([y]es/[N]o): Y
> 
>  [*] Deleting existing Veil Wine environment...
> 
>  [*] Creating new Veil Wine environment in: /var/lib/veil/wine
> 
>  [*] Initializing Veil's Wine environment...
> 
> it looks like wine32 is missing, you should install it.
> as root, please execute "apt-get install wine32"
> wine: '/var/lib/veil/wine' is a 32-bit installation, it cannot support 64-bit applications.
> it looks like wine32 is missing, you should install it.
> as root, please execute "apt-get install wine32"
> wine: '/var/lib/veil/wine' is a 32-bit installation, it cannot support 64-bit applications.
>  [*] Veil Wine environment successfully created!
> 
> 
> 
>  [*] Finished package installation
> 
> 
> 
>  [*] Initializing (OS + Wine) Python dependencies installation...
> 
> 
> 
>  [*] Installing (Wine) Python...
> 
>  [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)
> 
> it looks like wine32 is missing, you should install it.
> as root, please execute "apt-get install wine32"
> 0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
> 0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
> 0012:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
> 0012:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
> 0012:err:ole:get_local_server_stream Failed: 80004002
> 0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
> 0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
> 0014:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
> 0014:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
> 0014:err:ole:get_local_server_stream Failed: 80004002
> Could not load wine-gecko. HTML rendering will be disabled.
> it looks like wine32 is missing, you should install it.
> as root, please execute "apt-get install wine32"
> Could not load wine-gecko. HTML rendering will be disabled.
> wine: configuration in '/var/lib/veil/wine' has been updated.
> 0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
> 0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
> 0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
> 0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
> it looks like wine32 is missing, you should install it.
> as root, please execute "apt-get install wine32"
> 002f:err:msiexec:custom_action_server Failed to create custom action server pipe: 2
> ```
> 
> It appears to just hang here. If I run it without the --silent option, a windows dialog pops up to install Python for Windows 3.4, and hangs if I click "Next".
> 
> **Contents of /etc/os-release**
> 
> ```
> PRETTY_NAME="Kali GNU/Linux Rolling"
> NAME="Kali GNU/Linux"
> ID=kali
> VERSION="2019.2"
> VERSION_ID="2019.2"
> ID_LIKE=debian
> ANSI_COLOR="1;31"
> HOME_URL="https://www.kali.org/"
> SUPPORT_URL="https://forums.kali.org/"
> BUG_REPORT_URL="https://bugs.kali.org/"
> ```
> 
> Let me know if you need any other info.

Did you find any solution?

**Comment by Usama79** [comment]
> > Did this fix the issue @tengocharly12 ?
> 
> I am getting wine32 errors as well, although during setup. I'm not sure if this is another Issue, or can be tacked on to this one.
> 
> **Here is the output of setup.py for me:**
> 
> ```
> ==========================================================================
>                  Veil (Setup Script) | [Updated]: 2018-05-08
>  ==========================================================================
>      [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
>  ==========================================================================
> 
>                  os = kali
>           osversion = 2019.2
>        osmajversion = 2019
>                arch = x86_64
>            trueuser = root
>    userprimarygroup = root
>         userhomedir = /root
>             rootdir = /root/Veil
>             veildir = /var/lib/veil
>           outputdir = /var/lib/veil/output
>     dependenciesdir = /var/lib/veil/setup-dependencies
>             winedir = /var/lib/veil/wine
>           winedrive = /var/lib/veil/wine/drive_c
>             gempath = Z:\var\lib\veil\wine\drive_c\Ruby187\bin\gem
> 
>  [I] Kali Linux 2019.2 x86_64 detected...
> 
>  [I] Silent Mode: Enabled
>  [I]  Force Mode: Enabled
> 
> 
>  [?] Are you sure you wish to install Veil?
> 
>      Continue with installation? ([y]es/[s]ilent/[N]o): S
> 
> 
> 
>  [*] Initializing package installation
> 
> 
> 
>  [*] Installing dependencies
> 
>  [*] Updating APT
> 
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package mingw-w64
> E: Unable to locate package mono-mcs
>  [ERROR] Failed with installing dependencies (1): 0
> 
> 
> 
>  [*] Installing Python's pycrypto (via apt)...
> 
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> python3-crypto is already the newest version (2.6.1-9+b1).
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> metasploit-framework is already the newest version (5.0.20-0kali1).
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> 
> 
>  [*] Pulling down binary dependencies
> 
>  [*] Empty folder... git cloning
> 
> Cloning into '/var/lib/veil/setup-dependencies'...
> remote: Enumerating objects: 12, done.
> remote: Total 12 (delta 0), reused 0 (delta 0), pack-reused 12
> Unpacking objects: 100% (12/12), done.
> 
> 
>  [*] Installing Wine
> 
>  [*] Already have x86 architecture added...
> 
> 
> 
>  [*] Installing Wine 32-bit and 64-bit binaries (via APT)
> 
> E: Package 'wine32' has no installation candidate
>  [ERROR] Failed with installing wine (2): 0
> 
> 
> 
>  [*] [ALERT]: Existing Veil Wine environment detected at: /var/lib/veil/wine
> 
>      Do you want to nuke it? ([y]es/[N]o): Y
> 
>  [*] Deleting existing Veil Wine environment...
> 
>  [*] Creating new Veil Wine environment in: /var/lib/veil/wine
> 
>  [*] Initializing Veil's Wine environment...
> 
> it looks like wine32 is missing, you should install it.
> as root, please execute "apt-get install wine32"
> wine: '/var/lib/veil/wine' is a 32-bit installation, it cannot support 64-bit applications.
> it looks like wine32 is missing, you should install it.
> as root, please execute "apt-get install wine32"
> wine: '/var/lib/veil/wine' is a 32-bit installation, it cannot support 64-bit applications.
>  [*] Veil Wine environment successfully created!
> 
> 
> 
>  [*] Finished package installation
> 
> 
> 
>  [*] Initializing (OS + Wine) Python dependencies installation...
> 
> 
> 
>  [*] Installing (Wine) Python...
> 
>  [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)
> 
> it looks like wine32 is missing, you should install it.
> as root, please execute "apt-get install wine32"
> 0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
> 0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
> 0012:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
> 0012:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
> 0012:err:ole:get_local_server_stream Failed: 80004002
> 0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
> 0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
> 0014:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
> 0014:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
> 0014:err:ole:get_local_server_stream Failed: 80004002
> Could not load wine-gecko. HTML rendering will be disabled.
> it looks like wine32 is missing, you should install it.
> as root, please execute "apt-get install wine32"
> Could not load wine-gecko. HTML rendering will be disabled.
> wine: configuration in '/var/lib/veil/wine' has been updated.
> 0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
> 0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
> 0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
> 0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
> it looks like wine32 is missing, you should install it.
> as root, please execute "apt-get install wine32"
> 002f:err:msiexec:custom_action_server Failed to create custom action server pipe: 2
> ```
> 
> It appears to just hang here. If I run it without the --silent option, a windows dialog pops up to install Python for Windows 3.4, and hangs if I click "Next".
> 
> **Contents of /etc/os-release**
> 
> ```
> PRETTY_NAME="Kali GNU/Linux Rolling"
> NAME="Kali GNU/Linux"
> ID=kali
> VERSION="2019.2"
> VERSION_ID="2019.2"
> ID_LIKE=debian
> ANSI_COLOR="1;31"
> HOME_URL="https://www.kali.org/"
> SUPPORT_URL="https://forums.kali.org/"
> BUG_REPORT_URL="https://bugs.kali.org/"
> ```
> 
> Let me know if you need any other info.

@d4t4king Did you find any solution?

**Comment by Gokhularamanan** [comment]
[!] ERROR #2-3: Can't find the WINE profile for AuotIT v3 (/var/lib/veil/wine//drive_c/Program Files/AutoIt3/Aut2Exe/Aut2exe.exe

**Comment by valtsr** [comment]
Hi Team,

I am having the same issue with the WINE Profile for Ruby and OCRA, does anyone have solutions/suggestions? I am very new to this.

**Comment by codedbymalik** [comment]
Same issue Please Provide Guidance!

**Comment by shaman9955** [comment]
@stealthcopter I works for after running
`dpkg --add-architecture i386 && apt-get update && apt-get install wine32`
And then I run
`./setup.sh`
without --silent and --force

**Comment by codedbymalik** [comment]
Yeah my issue got resolved! Thanks!

**Comment by praveenmoyili** [comment]
Failed to install (Wine) Ruby.exe... Exit code: 1
Failed to run (wine) Ruby OCRA.. Exit code: 49
Failed to run (wine) AutoIT.. Exit code: 255

i did the same but no sloution so far .

**Comment by codedbymalik** [comment]
Hey Praveen can you shae error screen or error logs?

**Comment by vamshi1712** [comment]
I have the same issue,
do this,
apt-get update
apt-get install wine32
./setup.sh ( without silent and force )
It worked for me.

**Comment by praveenmoyili** [comment]
> Hey Praveen can you shae error screen or error logs?

Thanks for replying , i don't know why - but issue got resolved after doing the same process after 2 days .

**Comment by Hemanathk** [comment]
apt-get insall wine32 not working dependence problem is coming

**Comment by schizophrene246** [comment]
I have the same problem, can anyone help?
