### ISSUE TITLE
hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0

### ISSUE THREAD

**Issue by jepunband** [Veil-Framework/Veil#313]
## Veil version
Veil | [Version]: 3.1.12

## OS Used - all info (architecture, linux flavor, etc)
5.1.0-parrot1-3t-amd64

## How did you install Veil? (Apt, Clone from Github, etc.)
github

## Did you run the setup script?
yes.

## Pastebin link to error you are encountering (include console actions you took prior to error)

 [?] How would you like to create your payload executable?

     1 - PyInstaller (default)
     2 - Py2Exe

 [>] Please enter the number of your choice: 1
0026:err:hid:PNP_AddDevice Cannot parse Report Descriptor
0026:err:plugplay:handle_bus_relations AddDevice failed for driver L"WineHID"
0026:err:hid:PNP_AddDevice Cannot parse Report Descriptor
0026:err:plugplay:handle_bus_relations AddDevice failed for driver L"WineHID"
0026:err:hid:PNP_AddDevice Cannot parse Report Descriptor
0026:err:plugplay:handle_bus_relations AddDevice failed for driver L"WineHID"
0026:err:hid:PNP_AddDevice Cannot parse Report Descriptor
0026:err:plugplay:handle_bus_relations AddDevice failed for driver L"WineHID"
0026:err:hid:PNP_AddDevice Cannot parse Report Descriptor
0026:err:plugplay:handle_bus_relations AddDevice failed for driver L"WineHID"
0026:err:hid:PNP_AddDevice Cannot parse Report Descriptor
0026:err:plugplay:handle_bus_relations AddDevice failed for driver L"WineHID"
0026:err:hid:PNP_AddDevice Cannot parse Report Descriptor
0026:err:plugplay:handle_bus_relations AddDevice failed for driver L"WineHID"
0026:err:hid:PNP_AddDevice Cannot parse Report Descriptor
0026:err:plugplay:handle_bus_relations AddDevice failed for driver L"WineHID"
0026:err:hid:PNP_AddDevice Cannot parse Report Descriptor
0026:err:plugplay:handle_bus_relations AddDevice failed for driver L"WineHID"
0026:err:hid:PNP_AddDevice Cannot parse Report Descriptor
0026:err:plugplay:handle_bus_relations AddDevice failed for driver L"WineHID"
0026:err:hid:parse_descriptor Unknown (bTag: 0x5, bType: 0x3)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x5, bType: 0x3)
0026:err:plugplay:try_add_device Building report descriptor failed, removing device
0026:err:hid:parse_descriptor Unknown (bTag: 0xd, bType: 0x2)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x1, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0xc, bType: 0x2)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x1, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0xe, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0xd, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x8, bType: 0x3)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0xe, bType: 0x1)
0026:err:hid:PNP_AddDevice Cannot parse Report Descriptor
0026:err:plugplay:handle_bus_relations AddDevice failed for driver L"WineHID"
0026:err:hid:PNP_AddDevice Cannot parse Report Descriptor
0026:err:plugplay:handle_bus_relations AddDevice failed for driver L"WineHID"
0026:err:hid:PNP_AddDevice Cannot parse Report Descriptor
0026:err:plugplay:handle_bus_relations AddDevice failed for driver L"WineHID"
0026:err:hid:PNP_AddDevice Cannot parse Report Descriptor
0026:err:plugplay:handle_bus_relations AddDevice failed for driver L"WineHID"
0026:err:hid:parse_descriptor Unknown (bTag: 0x5, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x5, bType: 0x3)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x3, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x4, bType: 0x3)
0026:err:hid:parse_descriptor Unknown (bTag: 0x5, bType: 0x3)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x3, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x3, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x3, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x3, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x3, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0026:err:plugplay:try_add_device Building report descriptor failed, removing device
0026:err:hid:PNP_AddDevice Cannot parse Report Descriptor
0026:err:plugplay:handle_bus_relations AddDevice failed for driver L"WineHID"
0026:err:plugplay:try_add_device Building report descriptor failed, removing device
0009:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.

## Any additional info you want to tell me

how to solve this error?

**Comment by ChrisTruncer** [comment]
did it create the file?

**Comment by ChrisTruncer** [comment]
Closing due to no response
