### ISSUE TITLE
Wine and Python Error, I think...

### ISSUE THREAD

**Issue by k1epto** [Veil-Framework/Veil#315]
## Veil version 
latest 3.1.x

## OS Used - all info (architecture, linux flavor, etc)
kali and parrot - was trying on both

## How did you install Veil? (Apt, Clone from Github, etc.)
apt

## Did you run the setup script?
yes, I even tried the setup with the nuke wine option... didn't help.

## Pastebin link to error you are encountering (include console actions you took prior to error)
` [ERROR] There was issues installing the following:

Failed to install (Wine) Python 3.4.4... Exit code: 2
Failed to install pywin32-220.win32-py3.4.exe... Exit code: 2
Failed to install pycrypto-2.6.1.win32-py3.4.exe... Exit code: 2
Failed to run (wine) Python pip... Exit code: 2
Failed to run (wine) Python pip future... Exit code: 2
Failed to run (wine) Python pip pefile... Exit code: 2
Failed to install (Wine) Ruby.exe... Exit code: 2
Failed to run (wine) Ruby OCRA.. Exit code: 2
Failed to run (wine) AutoIT.. Exit code: 2`

ALSO:

/usr/bin/wine: 40: exec: /usr/lib/wine/wine: Exec format error

## Expected behavior
I expected it to install wine, especially after I tried nuking it ... but no luck.

## Any additional info you want to tell me
I think it has something to do with python versions ... your script looks for python3.4 and I have python3.7 ... is there a way to downgrade my python maybe? or can you update your installer to allow for the difference??

**Comment by ChrisTruncer** [comment]
this is a mirror issue, the mirror you are using doesn't have the proper packages. Please try a different mirror

**Comment by k1epto** [comment]
what other mirrors can i use? - Nevermind, I have since updated my Parrot OS and it seems to be installing properly now. Thank you for your advice.
