### ISSUE TITLE
Powershell code don't work with msf

### ISSUE THREAD

**Issue by jcardonne** [Veil-Framework/Veil#316]
## Veil version
3.1.12

## OS Used - all info (architecture, linux flavor, etc)
kali linux

## How did you install Veil? (Apt, Clone from Github, etc.)
apt

## Did you run the setup script?
yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
msfconsol : https://pastebin.com/YDkbcPfa
script : https://pastebin.com/P7R4huNv

## Expected behavior
The script doesn't work, I don't have any feedback on msf. All other scripts work except powerhells

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
Does this issue still exist? I had an issue with powershell code, but it seems to now be fixed?
