### ISSUE TITLE
/Veil.py Line 8 & Line 10 error import readline

### ISSUE THREAD

**Issue by jianchen21** [Veil-Framework/Veil#317]
Traceback (most recent call last):
  File "./Veil.py", line 10, in <module>
    from lib.common import orchestra
  File "/root/Veil/lib/common/orchestra.py", line 8, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'

how to fix this ? change line 10 to ( from lib.common import orchestra) ? and the line 8 how to fix ?

**Comment by sebastian-mora** [comment]
If you are on windows the package readline does not come preinstalled with python. You will need to do `pip install pyreadline`

**Comment by ChrisTruncer** [comment]
closing because this is standard
