### ISSUE TITLE
Veil is not being executed

### ISSUE THREAD

**Issue by thecowmilk** [Veil-Framework/Veil#319]
## Veil version
I think the latest version of Veil-Evasion.

## OS Used - all info (architecture, linux flavor, etc)
I'm using Kali Linux machine x86_64bit architecture, latest release (2019.2)

## How did you install Veil? (Apt, Clone from Github, etc.)
I installed from git clone.

## Did you run the setup script?
Not as a superuser, actually I ran ./Veil.py first and then it came up with two suggested commands, the configuration and the setup.

## Pastebin link to error you are encountering (include console actions you took prior to error)
https://pastebin.com/QLBZBwpt so this is what error I'm getting.

## Expected behavior
I expected Veil to actually start.

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
Please follow the readme as it tells you how to install the tool.
