### ISSUE TITLE
mingw-64 and mono-mcs not available for install on Kali 2019.2

### ISSUE THREAD

**Issue by d4t4king** [Veil-Framework/Veil#320]
## Veil version
Cloned on 8/30/2019

## OS Used - all info (architecture, linux flavor, etc)
Kali 

```Linux kali 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux```

## How did you install Veil? (Apt, Clone from Github, etc.)
Cloned from github

## Did you run the setup script?
Yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
https://pastebin.com/3G4tPSLE

No actions prior to install

## Expected behavior
Install successful.

## Any additional info you want to tell me
Let me know what you need and I am happy to gather.

**Comment by ChrisTruncer** [comment]
This is likely to be a mirror issue, you should be able to see those packages

**Comment by d4t4king** [comment]
OK.  I'm not sure what the mirror(s) should be.  Everything in ```/etc/apt/sources.list``` is commented out.

`apt search mono-mcs` returns nothing.

**Comment by d4t4king** [comment]
Update: I added the repo as defined by this doc (https://docs.kali.org/general-use/kali-linux-sources-list-repositories) and there were ~1500 or so updates.  I will have to check if those packages are now available.

If they are, then I will close the issue.

Thanks.

**Comment by ChrisTruncer** [comment]
good to close?

**Comment by d4t4king** [comment]
> good to close?

Yup.  After adding the repository `config/setup.py` worked as expected.

Thanks.
