### ISSUE TITLE
Failed to install (Wine) Ruby.exe... Exit code: 1  Failed to run (wine) Ruby OCRA.. Exit code: 49

### ISSUE THREAD

**Issue by M0dred** [Veil-Framework/Veil#322]
uname -a 
5.2.0-kali2-amd64 #1 SMP Debian 5.2.9-2kali1 (2019-08-22) x86_64 GNU/Linux

wine is already the newest version (4.0.2-1)
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]

 [ERROR] There was issues installing the following:

Failed to install (Wine) Ruby.exe... Exit code: 1
Failed to run (wine) Ruby OCRA.. Exit code: 49

## How did you install Veil? (Apt, Clone from Github, etc.)
apt-get install veil -y
bash setup.sh --force --silent

**Comment by ChrisTruncer** [comment]
The readme states that you'll need/want to install Veil by cloning from github and then running the setup script. I would recommend that you follow that process rather than using apt.

**Comment by SarmadBytes** [comment]
Face error on the latest version of kali. I have tried apt as well as git method but showing this errors.

 [ERROR] There were issues installing the following:


Failed to install (Wine) Ruby.exe... Exit code: 1
Failed to run (wine) Ruby OCRA. Exit code: 49

Any solution.
Thanks

**Comment by Lou456op** [comment]
Someone have a solution ?
