### ISSUE TITLE
Nothing FUD anymore...

### ISSUE THREAD

**Issue by m0t420** [Veil-Framework/Veil#325]
Veil is not Fud anymore since long time...
Is there an update in the near future?
thanks

**Comment by ChrisTruncer** [comment]
It can bypass AV when not used in the default settings. You are also able to provide different modules which you can submit that will be new.

**Comment by m0t420** [comment]
Which settings? I tried everything and nothing worked against windows defender

look: https://imgur.com/C2YZu7Y

1 year ago there was maybe 1 or 2 av detection with this settings.  I don't know what im doing wrong
