### ISSUE TITLE
setup return an error: Your architecture armv7l is not supported!

### ISSUE THREAD

**Issue by lasyka** [Veil-Framework/Veil#326]
when i run ./setup.sh 
get an error:[ERROR] Your architecture armv7l is not supported!
How to build and install it on arm platform? 

## Veil version
git head

## OS Used - all info (architecture, linux flavor, etc)
os = kali
osversion = 2019.4
osmajversion = 2019
arch = armv7l

## How did you install Veil? (Apt, Clone from Github, etc.)
clone from github,and ./config/setup.sh

## Did you run the setup script?
yes

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
We've not tested this platform at all, so I can't confirm that it would work. Would you be willing to try editing the setup script and seeing if it works?
