### ISSUE TITLE
Setup script gives many wine errors. 

### ISSUE THREAD

**Issue by greyjedimaster** [Veil-Framework/Veil#327]
## Veil version
3.1

## OS Used - all info (architecture, linux flavor, etc)
os = ubuntu
osversion = 18.04
osmajversion = 18
arch = x86_64

## How did you install Veil? (Apt, Clone from Github, etc.)
git method

## Did you run the setup script?
Yes

## Any additional info you want to tell me
Appears to be an issue running the wine environment during the setup. I even tried completely removing wine and allowing it to be installed by the script. The errors are preventing wine from creating the necessary windows and icons to run the setup scripts.

**Comment by ChrisTruncer** [comment]
Without any error information, there's not really an easy way to understand what you are seeing. Please provide the actual error information
