### ISSUE TITLE
Installing failure 

### ISSUE THREAD

**Issue by ccelikanil** [Veil-Framework/Veil#328]
## Veil version
3.1.12

## OS Used - all info (architecture, linux flavor, etc)
Kali Linux

## How did you install Veil? (Apt, Clone from Github, etc.)
Clone from GitHub

## Did you run the setup script?
Yes,  
./config/setup.sh --force --silent

## Pastebin link to error you are encountering (include console actions you took prior to error)
`root@kali:/opt/Veil# ./config/setup.sh --silent
 ==========================================================================
                 Veil (Setup Script) | [Updated]: 2018-05-08
 ==========================================================================
     [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
 ==========================================================================

                 os = kali
          osversion = 2018.2
       osmajversion = 2018
               arch = x86_64
           trueuser = root
   userprimarygroup = root
        userhomedir = /root
            rootdir = /opt/Veil
            veildir = /var/lib/veil
          outputdir = /var/lib/veil/output
    dependenciesdir = /var/lib/veil/setup-dependencies
            winedir = /var/lib/veil/wine
          winedrive = /var/lib/veil/wine/drive_c
            gempath = Z:\var\lib\veil\wine\drive_c\Ruby187\bin\gem

 [I] Kali Linux 2018.2 x86_64 detected...

 [I] Silent Mode: Enabled

 [?] Are you sure you wish to install Veil?

     Continue with installation? ([y]es/[s]ilent/[N]o): S

 [*] Initializing package installation

 [*] Installing dependencies

 [*] Updating APT

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package mingw-w64
E: Unable to locate package mono-mcs
 [ERROR] Failed with installing dependencies (1): 0

 [*] Installing Python's pycrypto (via apt)...

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python3-crypto
 [ERROR] Failed with installing dependencies (6): 0

Reading package lists... Done
Building dependency tree       
Reading state information... Done
metasploit-framework is already the newest version (5.0.61-0kali1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

 [*] Pulling down binary dependencies

 [*] Empty folder... git cloning

Cloning into '/var/lib/veil/setup-dependencies'...
remote: Enumerating objects: 12, done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: unpack-objects failed
 [ERROR] Failed with git clone: 0

 [*] Installing Wine

 [*] Already have x86 architecture added...

 [*] Installing Wine 32-bit and 64-bit binaries (via APT)

 [*] [ALERT]: Existing Veil Wine environment detected at: /var/lib/veil/wine

     Do you want to nuke it? ([y]es/[N]o): Y

 [*] Deleting existing Veil Wine environment...

 [*] Creating new Veil Wine environment in: /var/lib/veil/wine

 [*] Initializing Veil's Wine environment...

0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
0014:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0014:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0014:err:ole:get_local_server_stream Failed: 80004002
0012:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0012:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0012:err:ole:get_local_server_stream Failed: 80004002
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/var/lib/veil/wine' has been updated.
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/var/lib/veil/wine' has been updated.
 [*] Veil Wine environment successfully created!

 [*] Finished package installation

 [*] Initializing (OS + Wine) Python dependencies installation...

 [*] Installing (Wine) Python...

 [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)

 [ERROR] Failed to install (Wine) Python 3.4.4... Exit code: 2

 [*] Installing (Wine) Python dependencies...

./config/setup.sh: line 725: pushd: /var/lib/veil/setup-dependencies/: No such file or directory

 [*] Installing (Wine) Python's pywin32-220.win32-py3.4.exe...

 [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)

unzip:  cannot find or open pywin32-220.win32-py3.4.exe, pywin32-220.win32-py3.4.exe.zip or pywin32-220.win32-py3.4.exe.ZIP.

 [*] Installing (Wine) Python's pycrypto-2.6.1.win32-py3.4.exe...

 [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)

unzip:  cannot find or open pycrypto-2.6.1.win32-py3.4.exe, pycrypto-2.6.1.win32-py3.4.exe.zip or pycrypto-2.6.1.win32-py3.4.exe.ZIP.
./config/setup.sh: line 763: popd: directory stack empty

 [*] Installing (OS) Python's PyInstaller (via TAR)

 [*] PyInstaller v3.2 is already installed... Skipping...

 [*] Installing (Wine) Python's PIP pefile

wine: cannot find '/var/lib/veil/wine/drive_c/Python34/python.exe'
 [ERROR] Failed to run (wine) Python pip... Exit code: 2

wine: cannot find '/var/lib/veil/wine/drive_c/Python34/python.exe'
 [ERROR] Failed to run (wine) Python pip future... Exit code: 2

wine: cannot find '/var/lib/veil/wine/drive_c/Python34/python.exe'
 [ERROR] Failed to run (wine) Python pip pefile... Exit code: 2

 [*] Finished (Wine + OS) Python dependencies installation

 [*] Initializing (Wine) Ruby installation...

./config/setup.sh: line 899: pushd: /var/lib/veil/setup-dependencies/: No such file or directory

 [*] Installing (Wine) Ruby & dependencies

 [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)

wine: cannot find '/var/lib/veil/setup-dependencies/rubyinstaller-1.8.7-p371.exe'
 [ERROR] Failed to install (Wine) Ruby.exe... Exit code: 2

 [*] Installing (Wine) Ruby OCRA gem...

Z:\opt\Veil>Z:\var\lib\veil\wine\drive_c\Ruby187\bin\gem install --force --local ocra-1.3.6.gem 
Can't recognize 'Z:\var\lib\veil\wine\drive_c\Ruby187\bin\gem install --force --local ocra-1.3.6.gem' as an internal or external command, or batch script.
 [ERROR] Failed to run (wine) Ruby OCRA.. Exit code: 49

 [*] Extracting (Wine) Ruby dependencies...

unzip:  cannot find or open /var/lib/veil/setup-dependencies/ruby_gems-1.8.zip, /var/lib/veil/setup-dependencies/ruby_gems-1.8.zip.zip or /var/lib/veil/setup-dependencies/ruby_gems-1.8.zip.ZIP.
./config/setup.sh: line 935: popd: directory stack empty

 [*] Finished Ruby installation

 [*] Initializing Go installation...

 [*] Installing Go x86_64 (via TAR)

/var/lib/veil/setup-dependencies/go1.7.5.linux-amd64.tar.gz: No such file or directory
 [ERROR] Bad hash for /var/lib/veil/setup-dependencies/go1.7.5.linux-amd64.tar.gz!

 [*] Finished Go installation

 [*] Initializing AutoIT installation...

 [*] Installing (Wine) AutoIT

 [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)

wine: cannot find '/var/lib/veil/setup-dependencies/autoit-v3-setup.exe'
 [ERROR] Failed to run (wine) AutoIT.. Exit code: 2

 [*] Finished AutoIT installation

 [*] Settings already detected... Skipping...

 [*] Finished environment checks

 [ERROR] There was issues installing the following:

 
Failed with installing dependencies (1): 0
Failed with installing dependencies (6): 0
Failed with git clone: 0
Failed to install (Wine) Python 3.4.4... Exit code: 2
Failed to run (wine) Python pip... Exit code: 2
Failed to run (wine) Python pip future... Exit code: 2
Failed to run (wine) Python pip pefile... Exit code: 2
Failed to install (Wine) Ruby.exe... Exit code: 2
Failed to run (wine) Ruby OCRA.. Exit code: 49
Bad hash for /var/lib/veil/setup-dependencies/go1.7.5.linux-amd64.tar.gz!
Failed to run (wine) AutoIT.. Exit code: 2

 [I] If you have any errors running Veil, run: './Veil.py --setup' and select the nuke the wine folder option

 [I] Done!

root@kali:/opt/Veil# ./Veil.py

 [!] ERROR #2-3: Can't find the WINE profile for Python v3.4 (/var/lib/veil/wine//drive_c/Python34/python.exe).   Run: /opt/Veil/config/setup.sh --force --silent

## Expected behavior
I was expecting it to be installed properly but it's not working.

## Any additional info you want to tell me
I am trying to install Veil from git clone for like 7-8 times but everytime im having an error. First, I was struggling with "Crypto Module Not Found" error, I tried to install Crypto module but I couldn't fix it. I deleted entire folder by "rm -rf Veil" and tried to clone it again and install it. This time I paid attention to logs and I saw that I'm getting lots of "Failed with installing dependencies" errors, please help me.

**PS: U might be telling me u should be using --force option in your triggering command also but I tried that either, I'm getting same error**

**Comment by ChrisTruncer** [comment]
Please review the directions when creating an issue and don't post a giant copy/paste of your console to this. It's easiest to use a pastebin link for readability.

This looks to be an issue with your local internet, where it didn't properly clone the repo down containing the dependencies for the project. Please try this again?

**Comment by ccelikanil** [comment]
Sorry this was my first issue submission. I'm trying it again but im ending up with same issue.

![11](https://user-images.githubusercontent.com/25687355/69664285-1bc29880-1099-11ea-8e1b-bb25862c5170.PNG)

And i can assure you there is nothing wrong with my internet but this keep happening..

**Comment by ChrisTruncer** [comment]
I just did an install of Veil on a Kali virtual machine that I have and it worked. Please try on a different VM, or manually make sure that you did indeed clone down the dependencies

**Comment by ccelikanil** [comment]
I think something weird is going on with my virtual machine. After I made the previous comment, I went to try to check updates of my kali but I was neither able to open my control center nor my software updater module.. I dont know what's going on but I uninstalled my VM image & just downloaded Kali again and will try to install Veil again.

**Comment by ccelikanil** [comment]
Update: I have installed Kali 2019.4 version and Veil successfully installed. Thanks.
