### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by adada111** [Veil-Framework/Veil#329]
![image](https://user-images.githubusercontent.com/54429391/70612489-f52c6200-1c41-11ea-8399-a77ba62e50ee.png)
My tool is up to date, but it still prompts me to upgrade.how can i slove it ?

**Comment by adada111** [comment]
![image](https://user-images.githubusercontent.com/54429391/70613995-a502cf00-1c44-11ea-8ea4-c923a7ed2930.png)

**Comment by adada111** [comment]
![image](https://user-images.githubusercontent.com/54429391/70622328-ab01ab80-1c56-11ea-82d5-ab83ebbedf4d.png)
here is error, but i don't know how to slove it

**Comment by adada111** [comment]
who can help me ?I have been tangled for days,thanks

**Comment by ChrisTruncer** [comment]
@adada111 - I rarely do this, but the sheer amount of spam you have created on this and other issues is overwhelming enough that I need a reprieve from it temporarily.

Please review the error messages you are seeing, make sure you are using Python 3 (on Linux), and install the tool.
