### ISSUE TITLE
Veil-Catapult configuration in Veil-Framework configuration file

### ISSUE THREAD

**Issue by feralfenrir** [Veil-Framework/Veil#33]
## Veil version
3.0

## OS Used - all info (architecture, linux flavor, etc)
Linux 4.9.0-kali3-amd64 #1 SMP Debian 4.9.13-1kali3 (2017-03-13) x86_64 GNU/Linux

## Pastebin link to error you are encountering (include console actions you took prior to error)
 Veil-Framework configuration:

 [*] OPERATING_SYSTEM = Kali
 [*] TERMINAL_CLEAR = clear
 [*] WINEPREFIX = /root/.config/wine/veil/
 [*] TEMP_DIR = /tmp/
 [*] MSFVENOM_OPTIONS =
 [*] METASPLOIT_PATH = /usr/share/metasploit-framework/
 [*] MSFVENOM_PATH = /usr/bin/
 [*] PYINSTALLER_PATH = /opt/veil/PyInstaller-3.2.1/

 [*] VEIL_EVASION_PATH = /root/projects/Veil-dev/
 [*] PAYLOAD_SOURCE_PATH = /usr/share/veil-output/source/
 [*] PAYLOAD_COMPILED_PATH = /usr/share/veil-output/compiled/
 [*] GENERATE_HANDLER_SCRIPT = True
 [*] HANDLER_PATH = /usr/share/veil-output/handlers/
 [*] HASH_LIST = /usr/share/veil-output/hashes.txt

 [*] VEIL_CATAPULT_PATH = /root/projects/Veil-Catapult/
 [*] CATAPULT_RESOURCE_PATH = /usr/share/veil-output/catapult/

 Configuration File Written To '/etc/veil/settings.py'

## Expected behavior
In my understanding, Veil-Catapult has been deprecated in favor of Veil-Pillage. I noticed that the config file still has Veil-Catapult configuration and Veil-Pillage is still not a part of the Veil 3.0 superproject.

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
We're not overwriting it in case anyone else is still using it. It's just extraneous data, which is just one line with, and I'm fine leaving that in vs. causing issues for someone's install
