### ISSUE TITLE
Python 3.8

### ISSUE THREAD

**Issue by Jarnek** [Veil-Framework/Veil#330]
## Veil version
current repo

## OS Used - all info (architecture, linux flavor, etc)
blackarch linux x86_64

## How did you install Veil? (Apt, Clone from Github, etc.)
cloned the current repo

## Did you run the setup script?
yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
https://pastebin.com/79fj4gms

## Expected behavior
veil.py should start to main menu

## Any additional info you want to tell me

I suppose it is an error while importing the tool library in python3.8

**Comment by ChrisTruncer** [comment]
Did you run the setup script?

**Comment by ChrisTruncer** [comment]
Closing since I haven't heard back
