### ISSUE TITLE
Pip3 Not found

### ISSUE THREAD

**Issue by SnXe** [Veil-Framework/Veil#334]
## Veil version
 #3

## OS Used - all info (architecture, linux flavor, etc)

Ubuntu 18.04 x86
## How did you install Veil? (Apt, Clone from Github, etc.)

Github
## Did you run the setup script?

Yup
## Pastebin link to error you are encountering (include console actions you took prior to error)

Pip3 unable to be found or installed 
## Expected behavior

Runs fine so far but the pip3 thing
## Any additional info you want to tell me
I have python 3-pip but not pip3. What issues should I expect from this.

**Comment by ChrisTruncer** [comment]
Did the script install? Can you build python executables?
