### ISSUE TITLE
ImportError: No module named 'past'

### ISSUE THREAD

**Issue by init5-SF** [Veil-Framework/Veil#336]
Veil | [Version]: 3.1.12

Kali linux

Installed using: apt

Setup script automatically ran

Error: https://pastebin.com/raw/eKzshLgE

This happened when I chose payload #26 and tried to compile it to EXE

**Comment by whale3070** [comment]
the same as @sxplitfirex ,  From #25 to #36 Evasion payload based python, and all of this was unavailable.

pyinstaller /var/lib/veil/output/source/xx.py  #use this command to compile python script to executable file

**Comment by ChrisTruncer** [comment]
I just used the latest version of Veil on the latest version of Kali. Please try using a clean VM and you shouldn't have an issue. Also please do not install via apt, please install via github cloning and installing.
