### ISSUE TITLE
No more custom payloads?

### ISSUE THREAD

**Issue by chppppp** [Veil-Framework/Veil#337]
## Veil version
3.1.12

## OS Used - all info (architecture, linux flavor, etc)
Kali 2020.1

## How did you install Veil? (Apt, Clone from Github, etc.)
apt

## Did you run the setup script?
yes

## Pastebin link to error you are encountering (include console actions you took prior to error)

Is there no place to add custom payloads anymore????? I am trying to shove PoshC2 payloads into Veil but I cannot figure out how to do it?! I find screenshots of folks with custom payload options but I have nothing. 

Thank you

**Comment by ChrisTruncer** [comment]
You can easily add custom payloads into Veil. Please look at the payload template, or how any payload is created. If you have a specific question, I am more than happy to answer.
