### ISSUE TITLE
Ruby install does not work in wine

### ISSUE THREAD

**Issue by JonLittleIT** [Veil-Framework/Veil#338]
## Veil version
[2017-03-07]
     Released.: 3.0
     Modified.: This is Veil 3.0's initial release (with minor bug patches post-release). Ideally everything is working well! All mods (hopefully) will be tracked in this file so you know of any changes.

ec2-user@kali:~/Veil/Veil$ python Veil.py

 [!] ERROR #2-3: Can't find the WINE profile for Ruby v1.8.7 (/var/lib/veil/wine//drive_c/Ruby187/bin/ruby.exe).   Run: /home/ec2-user/Veil/Veil/config/setup.sh --force --silent

Failed to install (Wine) Ruby.exe... Exit code: 1
Failed to run (wine) Ruby OCRA.. Exit code: 49

**Comment by ChrisTruncer** [comment]
are you installing this headlessly? If so, Veil currently can't be installed headlessly until a way is found to install ruby without an X session. If you want to install a desktop environment, or forward an X session locally, it should work

**Comment by JonLittleIT** [comment]
ahh ok thanks.

**Comment by ChrisTruncer** [comment]
Closing this since I am assuming the issue was the headless install.
