### ISSUE TITLE
Additional dependency missing: winbind

### ISSUE THREAD

**Issue by feralfenrir** [Veil-Framework/Veil#34]
## Veil version
3.0

## OS Used - all info (architecture, linux flavor, etc)
Linux 4.9.0-kali3-amd64 #1 SMP Debian 4.9.13-1kali3 (2017-03-13) x86_64 GNU/Linux

## Pastebin link to error you are encountering (include console actions you took prior to error)
While the setup process, the following error comes up during the installation of PyWin32 and PyCrypto.

`err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.`

## Expected behavior
This error was resolved on installing winbind from apt:
`apt install winbind`

I'm not really sure if this is an important dependency. If it is, this could be included in the setup.sh script.

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
I can check this out, but this won't impact Veil's usage, you are still able to completely use Veil and PyCrypto within wine without this package.

Thanks for letting me know

**Comment by bkkkd** [comment]
thanks.
