### ISSUE TITLE
All payloads detected by most antiviruses (antiscan.me)

### ISSUE THREAD

**Issue by Pvpoe** [Veil-Framework/Veil#340]
## Veil version
3.1.12

## OS Used - all info (architecture, linux flavor, etc)
Kali Linux

## How did you install Veil? (Apt, Clone from Github, etc.)
Clone from Github

## Did you run the setup script?
Yes

## Error
All payloads I have generated using Veil for the past week have been detected by antivirus softwares according to antiscan.me

**Comment by ChrisTruncer** [comment]
Hi, unfortunately, you didn't really provide much in the way of actionable information. There are multiple payloads, all with a variety of options. I would suggest you explore them.

Also there are other issues with the same issue, and my response has always been the same. The payloads created are there to serve as options for people. We welcome others to submit payloads that we can add in that work for them. I think Veil largely accomplished what we intended it to do.
