### ISSUE TITLE
can't find pyinstaller?

### ISSUE THREAD

**Issue by NisarAloko** [Veil-Framework/Veil#343]
while i am installing for the first time it wants pyinstaller directory
./setup.sh --silent --force 
then stops in this message
Can't find PyInstaller?   Run: /root/Veil/config/config/setup.sh --force --silent
 [>] Please enter the directory of PyInstaller (e.g. ):

i externally installed pyinstaller 
pip install pyinstaller

but still it can't finds the directory.

**Comment by ChrisTruncer** [comment]
Please provide all the information requested when creating an issue, I can't debug it without it. I will close, but if this is still an issue please re-open one

**Comment by joseph224** [comment]
**can't find pyinstaller**
**am having same issue here too sir, kindly help to reslove**
while i am installing for the first time it wants pyinstaller directory
./setup.sh --silent --force
then stops in this message
Can't find PyInstaller? Run: /root/Veil/config/config/setup.sh --force --silent
[>] Please enter the directory of PyInstaller (e.g. ):

i externally installed pyinstaller
pip install pyinstaller

but still it can't finds the directory.
and i don't know what to do anymore
like am stuck 
[
![issue](https://user-images.githubusercontent.com/76873310/103459319-2f6a1500-4d17-11eb-9062-3f8c02bebd46.png)
