### ISSUE TITLE
Cannot import name 'Tool'

### ISSUE THREAD

**Issue by ghost** [Veil-Framework/Veil#35]
## Veil version
Veil 3.0

## OS Used - all info (architecture, linux flavor, etc)
Debian 8

## Pastebin link to error you are encountering (include console actions you took prior to error)
http://pastebin.com/zNWCRAiP

## Expected behavior
Veil to run after install 

## Any additional info you want to tell me
I have tried to reinstall and reconfigure without success. Ran install using both sudo and dirrectly as root.

**Comment by ChrisTruncer** [comment]
Can you provide resolution to this? What fixed your issue?

**Comment by ghost** [comment]
Not sure. I ended up creating a new debian vm and it installed without issues.

**Comment by flibustier** [comment]
Hi,
I have exactly the same issue with the same error…
(I'm on Debian 8)
Thanks !

**Comment by ChrisTruncer** [comment]
Please run the setup script and ensure all dependencies are installed. I am currently running on Debian 8 as well.

**Comment by flibustier** [comment]
The setup script works fine, no error or problem during install, just when run ./Veil.py …

**Comment by ChrisTruncer** [comment]
I really wish I could help, but I have no way to recreate this. Are you using python 3?

I am cloning this down and I am able to run Veil. If there's someway to recreate this, then I'll absolutely look into it, but I just can't seem to cause that same error to trigger.

**Comment by ChrisTruncer** [comment]
To give more info, the ONLY time I have had it reported where this issue was popping up, the user thought everything was installed from the setup script, but that wasn't the case. Once they discovered that not all dependencies were installed, and then they installed them, the tool worked.

**Comment by flibustier** [comment]
For my versions of Python :
```
$ python --version
Python 2.7.9
$ python3 --version
Python 3.4.2
```
How can I check if some dependencies are missing ?

Thanks !

**Comment by ChrisTruncer** [comment]
I think easiest thing will be to re-run the setup script and review the output

**Comment by ghost** [comment]
I started having the same issue again after installing other tools. I reran the setup script and saved the output to a text file to review. The script does not show any errors with the dependencies and everything looks to install correctly.

**Comment by flibustier** [comment]
I reran the setup, here is it : [![asciicast](https://asciinema.org/a/4xo3paojs0w76ff8i4d3bqyf9.png)](https://asciinema.org/a/4xo3paojs0w76ff8i4d3bqyf9)
(you can skip to 4:00)

**Comment by ChrisTruncer** [comment]
are you running this headlessly? I don't see any of the libraries pop up to install the python libs, autoit, etc.

**Comment by ghost** [comment]
Here is my install also. 
[Veil.txt](https://github.com/Veil-Framework/Veil/files/879646/Veil.txt)

**Comment by flibustier** [comment]
Asciinema only record the terminal output but pop up appear too !

**Comment by ChrisTruncer** [comment]
I literally just created a new Debian VM 8, cloned Veil, and ran the setup. It all ran successfully, and when I started Veil, it worked without an issue.

**Comment by ChrisTruncer** [comment]
If anyone can provide any additional information how to recreate it, I am more than happy to help. But like I mentioned, I did test this on a clean Debian VM and didn't encounter an issue.

**Comment by flibustier** [comment]
Hi !
Just create a clean Debian VM and it's work fine ! So I will compare the 2 systems to try finding the problem… Thanks !

**Comment by Callightman** [comment]
Having same issue. I had Veil-Evasion installed and when install Veil 3 i had this problem.

**Comment by ChrisTruncer** [comment]
So, this is an odd issue. I cannot recreate this on one of my VMs, but on another one (with same exact OS, etc.) I AM able to. I think I just found a fix, and I just merged it into the master branch. Could anyone here try pulling the latest version and running Veil?  Ideally this should now work for everyone.

**Comment by flibustier** [comment]
It's fixed! Congrats!!
