### ISSUE TITLE
[-] Error running command {command name} : Rex::TimeoutError Operation timed out.

### ISSUE THREAD

**Issue by ShigeoNomura** [Veil-Framework/Veil#350]
## Veil version
    Veil | [Version]: 3.1.13

## OS Used - all info (architecture, linux flavor, etc)

VBox - Kali 2020/2 Fresh installation with latest updates / Windows 10 x64 Testing Machine Clean installation

## How did you install Veil? (Apt, Clone from Github, etc.)

Clone from Github

## Did you run the setup script?
yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
I've tried to create different payloads
 go/meterpreter/rev_http.py
 go/meterpreter/rev_https.py
 go/meterpreter/rev_tcp.py

Then execute them on windows 10 virtual test machine, I've used both windows/x64/meterpreter/reverse_http(https,tcp) and windows/meterpreter/reverse_http(https,tcp) to listen for incoming sessions. Session opens, but in case of http and https after any command i get [-] Error running command dir: Rex::TimeoutError Operation timed out. If I'm using x64/meterpreter the session didn't opens. If i use reverse_tcp payload, session dies after establishing the connection. I've tried to reinstall Veil with "Kali installation" and "Cloining from github". Didn't work. I've tried to use different ports to listen for incoming connection.  

Some time `sysinfo` command works only if it is the first command that you type, but after that all other commands gives you:
`[-] Error running command {command name} : Rex::TimeoutError Operation timed out.`

## Expected behavior
I guess, it should open a working meterpreter session.

## Any additional info you want to tell me
![screen](https://user-images.githubusercontent.com/5535622/79316786-d5989500-7ed2-11ea-9759-6b7d68dc314d.png)
Example of simple https payload
![screen5](https://user-images.githubusercontent.com/5535622/79316978-1c868a80-7ed3-11ea-9d82-3a822cf7966d.png)

**Comment by ShigeoNomura** [comment]
OK after 3 days! Finally solved the problem! Re-installation of the Veil Framework using "Kali's Quick Install" helped:
```
    sudo apt -y install veil
    sudo /usr/share/veil/config/setup.sh --force --silent 
```

Looks like the dependencies weren't installed correctly during previous installation process. Anyway thank you everyone for your help. Important thing is using sudo command, because in the latest version of kali root is not the default type of account and using second command without sudo will not install Veil dependencies correctly. Open
[-] Error running command {command na

UPDATE: same problem again. 
```
sysinfo
screenshot
```
commands worked, and i though that everything is ok, but after that all the commands gave the same:
`[-] Error running command {command name} : Rex::TimeoutError Operation timed out.`

**Comment by ShigeoNomura** [comment]
![screen_1](https://user-images.githubusercontent.com/5535622/79327388-5d39d000-7ee2-11ea-9854-c53ab42303bb.png)

**Comment by ShigeoNomura** [comment]
So an interesting finding a lot of commands are working, but as soon as i use `dir` command, the session gives an error message
 `[-] Error running command dir: Rex::TimeoutError Operation timed out.`
and after that no other command working.
![screen2](https://user-images.githubusercontent.com/5535622/79343682-b57dcb80-7efc-11ea-8973-b65038765b4d.png)

**Comment by ShigeoNomura** [comment]
I have fight this problem for a week or two.. 
Here is the solution: to be short.. the first command you need to use after session is established should be ps, then check for explorer.exe process id, and type migrate 1104  **(where 1104 is process id in my case, in your case it could be different)** after that all the commands will work fine. **If you will try to use dir or ls, before migrating it will broke the pipe and all the other commands will not work anymore. =\** This is the bug of the latest Veil version I believe. =\ I could not find any other explanation.

**Comment by ChrisTruncer** [comment]
Veil would not impact how meterpreter loads

**Comment by ShigeoNomura** [comment]
> Veil would not impact how meterpreter loads

ok, so do you have any idea why this situation could happend? 
Fresh clean Kali installation, Fresh clean windows with disabled av/windows defender/firewall.
metasploit up to date and fresh Veil, please note I've tried to reinstall Veil and Kali and Windows several times, but i couldn't find the solution. Or maybe I'm wrong and it shouldn't work unless we migrate to explorer? But in that case why any other commands stop working after using "dir" or "ls"?
