### ISSUE TITLE
Can't create Python payload

### ISSUE THREAD

**Issue by ghost** [Veil-Framework/Veil#352]
## Veil version
3.1.13

## OS Used - all info (architecture, linux flavor, etc)
Kali-Linux-2020.1-vmware-amd64

## How did you install Veil? (Apt, Clone from Github, etc.)
clone from Github

## Did you run the setup script?
./config/setup.sh --force --silent

## Pastebin link to error you are encountering (include console actions you took prior to error)
these are the commands I use in order:
./Veil.py
use 28
set LHOST "myhostip"
generate
ola
1
And this is the error:
663 INFO: PyInstaller: 3.2.1
663 INFO: Python: 3.4.4
664 INFO: Platform: Windows-7-6.1.7601-SP1
Traceback (most recent call last):
  File "/var/lib/veil/PyInstaller-3.2.1//pyinstaller.py", line 15, in <module>
    run()
  File "Z:\var\lib\veil\PyInstaller-3.2.1\PyInstaller\__main__.py", line 88, in run
    spec_file = run_makespec(**vars(args))
  File "Z:\var\lib\veil\PyInstaller-3.2.1\PyInstaller\__main__.py", line 40, in run_makespec
    spec_file = PyInstaller.building.makespec.main(filenames, **opts)
  File "Z:\var\lib\veil\PyInstaller-3.2.1\PyInstaller\building\makespec.py", line 372, in main
    specfile = open(specfnm, 'w')
PermissionError: [Errno 13] Permission denied: 'Z:\\home\\kali\\Veil\\ola2.spec'
===============================================================================
                                   Veil-Evasion
===============================================================================
      [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
===============================================================================

 [!] ERROR: Unable to create output file.
 [*] Source code written to: /var/lib/veil/output/source/ola2.py
 [*] Metasploit Resource file written to: /var/lib/veil/output/handlers/ola2.rc

Hit enter to continue...

## Expected behavior
generate the payload

## Any additional info you want to tell me

**Comment by ghost** [comment]
I solved it using root access, but now I have the following error:

wine: /var/lib/veil/wine is not owned by you

I don't know how to change the ownership of this directory

**Comment by ChrisTruncer** [comment]
try running in sudo, but you should be able to change the ownership of the folder on your system

**Comment by ghost** [comment]
I used the sudo command and give me other error, also I tried to change the permission of that folder but I still get the same error. I don't know how to solve that.
