### ISSUE TITLE
error in wine installation process .

### ISSUE THREAD

**Issue by praveenmoyili** [Veil-Framework/Veil#353]
## Did you run the setup ----------yes

Failed to install (Wine) Ruby.exe... Exit code: 1
Failed to run (wine) Ruby OCRA.. Exit code: 49

 [I] If you have any errors running Veil, run: './Veil.py --setup' and select the nuke the wine folder option

 [I] Done!

root@kali:~/Veil/config# cd ..
root@kali:~/Veil# ./Veil.py --setup

 [!] ERROR #2-3: Can't find the WINE profile for Ruby v1.8.7 (/var/lib/veil/wine//drive_c/Ruby187/bin/ruby.exe).   Run: /root/Veil/config/setup.sh --force --silent

[  
             Actually i'm trying to install Veil since 1 weak , but i'm facing many problems.

              I changed Souces.list    to

deb http://http.kali.org/kali kali-rolling main non-free contrib
deb-src http://http.kali.org/kali kali-rolling main non-free contrib

]

**Comment by ChrisTruncer** [comment]
Please search github issues before creating a new one, this has been discussed a bit before. This is going to be because you can't currently install Veil on a headless environment. You either need a desktop, or need to forward your X session locally to install everything.
