### ISSUE TITLE
Error in Wine Installation

### ISSUE THREAD

**Issue by savageandlost21** [Veil-Framework/Veil#356]
## OS Used - all info (architecture, linux flavor, etc)
Kali Linux 2020

## How did you install Veil? (Apt, Clone from Github, etc.)
Clone from Github

## Did you run the setup script?
yes

## Pastebin link to error you are encountering (include console actions you took prior to error)

https://pastebin.com/Z4bje9sC
## Expected behavior
To install Veil

## Any additional info you want to tell me
He always keep asking to enter the location of PyInstaller

**Comment by ChrisTruncer** [comment]
Can you try installing on a new VM, or watching the python install? It IR sawpthere was an issue there.

**Comment by savageandlost21** [comment]
> Can you try installing on a new VM, or watching the python install? It IR sawpthere was an issue there.

I was using Virtual Box. I will try it using VMware... Do you have any VM recomendations?

**Comment by ChrisTruncer** [comment]
It should just work, it looks to be an issue with your system cloning down the requirements, I would just try it again.

**Comment by Mpineda199** [comment]
i uninstall Virtualbox and installed again, doesnt work, 5 days trying to install veil. nothing yet.

**Comment by ChrisTruncer** [comment]
I just confirmed that the install works. I just downloaded a clean version of Kali and installed Veil on it without an issue. If you can provide additional details on how to recreate this, I would be happy to look into it.
