### ISSUE TITLE
Import Error : No module named 'readline'

### ISSUE THREAD

**Issue by chris924** [Veil-Framework/Veil#36]
Veil 3.0

Kali linux 64bit

http://pastebin.com/fzNMVxCm

Veil to start

**Comment by JoeNibe** [comment]
Try running
`python3 ./Veil.py`

**Comment by ChrisTruncer** [comment]
Please try the latest version of Kali. A friend of mine just tested and said readline is installed by default on Kali. Please give that a shot, thanks!
