### ISSUE TITLE
Failed to install (Wine) Ruby.exe... Exit code: 1 Failed to run (wine) Ruby OCRA.. Exit code: 49

### ISSUE THREAD

**Issue by cptcharis** [Veil-Framework/Veil#360]
## Veil version
latest

## OS Used - all info (architecture, linux flavor, etc)
Kali 2020 amd64 inside virtual box 6.1 and qemu/kvm

## How did you install Veil? (Apt, Clone from Github, etc.)
both ways Apt and clone for Github

## Did you run the setup script?
yes as per intructions

## Pastebin link to error you are encountering (include console actions you took prior to error)
[*] Installing (Wine) Ruby & dependencies

 [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)

0009:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0009:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
002c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
002c:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
 [ERROR] Failed to install (Wine) Ruby.exe... Exit code: 1

 [*] Installing (Wine) Ruby OCRA gem...

Z:\var\lib\veil\setup-dependencies>Z:\var\lib\veil\wine\drive_c\Ruby187\bin\gem install --force --local ocra-1.3.6.gem 
Can't recognize 'Z:\var\lib\veil\wine\drive_c\Ruby187\bin\gem install --force --local ocra-1.3.6.gem' as an internal or external command, or batch script.
 [ERROR] Failed to run (wine) Ruby OCRA.. Exit code: 49

[ERROR] There was issues installing the following:

 
Failed to install (Wine) Ruby.exe... Exit code: 1
Failed to run (wine) Ruby OCRA.. Exit code: 49

## Expected behavior
no errors????

## Any additional info you want to tell me
In qemu/kvm no errors
in virtual box 6.1 appears the above errors

kali 2020 clean install

**Comment by ChrisTruncer** [comment]
Please try installing on the latest version of Kali in a clean VM, and use the command provided in the Readme. I just verified that it works without an issue.

If you still encounter a problem, feel free to re-open this

**Comment by honeyfairy** [comment]
Please remember to install via the **GUI** of your server. It will not work via SSH!

**Comment by ankush245** [comment]
have found any solution regarding this issue
