### ISSUE TITLE
Problem during Veli Framework installation

### ISSUE THREAD

**Issue by abhranil-manna** [Veil-Framework/Veil#361]
## Veil version
Veil 3.1.X
## OS Used
Ubuntu
## How did you install Veil?
Clone from Github but when I install it ask for username and password of github of this repository.How to solve it?

## Did you run the setup script?
yes

**Comment by Abhranil-Manna** [comment]
When I install the veli it ask for user name and password of github.com.How to solve it?

**Comment by ChrisTruncer** [comment]
Veil doesn't ask for your username and password from github. Just clone the repo normally by cloning the repo path. Worst case, you can just download the repo too
