### ISSUE TITLE
NoDistribute along with many other sites says PAYLOAD is empty file or uploading error. But only AntiScan could successfully scan it with almost all antiviruses able to detect it.

### ISSUE THREAD

**Issue by samarth19** [Veil-Framework/Veil#362]
## Veil version
Veil 3.1.X 

## OS Used - all info (architecture, linux flavor, etc)
Kali linux within VirtualBox, x64 os architecture

## How did you install Veil? (Apt, Clone from Github, etc.)
Clone from Github

## Did you run the setup script?
Yes

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
Please modify the default templates. Veil can't stay completely undetected with default configs forever.
