### ISSUE TITLE
Wine Installation problem

### ISSUE THREAD

**Issue by saziburrahman** [Veil-Framework/Veil#363]
## Veil version
Veil 3.1.X

## OS Used - all info (architecture, linux flavor, etc)
Lenux On virtual Box

## How did you install Veil? (Apt, Clone from Github, etc.)
- cd /opt
- git clone https://github.com/Veil-Framework/Veil.git
- cd Veil
- cd config
- ./setup.sh --silent --force

## Did you run the setup script?
Yes.Multiple Time

## Pastebin link to error you are encountering (include console actions you took prior to error)
https://github.com/Veil-Framework/Veil.git

## Expected behavior
- cd /opt
- git clone https://github.com/Veil-Framework/Veil.git
- cd Veil
- cd config
- ./setup.sh --silent --force

root@kali:~# cd /opt

root@kali:/opt# git clone https://github.com/Veil-Framework/Veil.git

fatal: destination path 'Veil' already exists and is not an empty directory.

root@kali:/opt# cd Veil/config

root@kali:/opt/Veil/config# ./setup.sh --silent --force

 ==========================================================================

                 Veil (Setup Script) | [Updated]: 2018-05-08

 ==========================================================================

     [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework

 ==========================================================================

                 os = kali

          osversion = 2020.1

       osmajversion = 2020

               arch = x86_64

           trueuser = root

   userprimarygroup = root

        userhomedir = /root

            rootdir = /opt/Veil

            veildir = /var/lib/veil

          outputdir = /var/lib/veil/output

    dependenciesdir = /var/lib/veil/setup-dependencies

            winedir = /var/lib/veil/wine

          winedrive = /var/lib/veil/wine/drive_c

            gempath = Z:\var\lib\veil\wine\drive_c\Ruby187\bin\gem

 [I] Kali Linux 2020.1 x86_64 detected...

 [I] Silent Mode: Enabled

 [I]  Force Mode: Enabled

 [?] Are you sure you wish to install Veil?

     Continue with installation? ([y]es/[s]ilent/[N]o): S

 [*] Initializing package installation

 [*] Installing dependencies

 [*] Updating APT

W: GPG error: https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/Debian_10 ./ InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY DFA175A75104960E

E: The repository 'https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/Debian_10 ./ InRelease' is not signed.

 [ERROR] Failed with apt-get update (1): 0

Reading package lists... Done

Building dependency tree       

Reading state information... Done

git is already the newest version (1:2.26.2-1).

ruby is already the newest version (1:2.7+1).

ruby set to manually installed.

unzip is already the newest version (6.0-25).

unzip set to manually installed.

Some packages could not be installed. This may mean that you have

requested an impossible situation or if you are using the unstable

distribution that some required packages have not yet been created

or been moved out of Incoming.

The following information may help to resolve the situation:

The following packages have unmet dependencies:

 libc6-dev : Breaks: libgcc-8-dev (< 8.4.0-2~) but 8.3.0-26 is to be installed

             Breaks: python3.7 (< 3.7.7-1+b1) but 3.7.6-1 is to be installed

E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

 [ERROR] Failed with installing dependencies (1): 0

 [*] Installing Python's pycrypto (via apt)...

Reading package lists... Done

Building dependency tree       

Reading state information... Done

python3-crypto is already the newest version (2.6.1-13).

The following package was automatically installed and is no longer required:

  ruby2.5

Use 'sudo apt autoremove' to remove it.

0 upgraded, 0 newly installed, 0 to remove and 1299 not upgraded.

Reading package lists... Done

Building dependency tree       

Reading state information... Done

metasploit-framework is already the newest version (5.0.89-0kali1).

The following package was automatically installed and is no longer required:

  ruby2.5

Use 'sudo apt autoremove' to remove it.

0 upgraded, 0 newly installed, 0 to remove and 1299 not upgraded.

 [*] Pulling down binary dependencies

 [*] Empty folder... git cloning

Cloning into '/var/lib/veil/setup-dependencies'...

remote: Enumerating objects: 12, done.

remote: Total 12 (delta 0), reused 0 (delta 0), pack-reused 12

Receiving objects: 100% (12/12), 207.29 MiB | 47.00 KiB/s, done.

 [*] Installing Wine

 [*] Already have x86 architecture added...

 [*] Installing Wine 32-bit and 64-bit binaries (via APT)

E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

 [ERROR] Failed with installing wine (2): 0

 [*] [ALERT]: Existing Veil Wine environment detected at: /var/lib/veil/wine

     Do you want to nuke it? ([y]es/[N]o): Y

 [*] Deleting existing Veil Wine environment...

 [*] Creating new Veil Wine environment in: /var/lib/veil/wine

 [*] Initializing Veil's Wine environment...

sudo: wine: command not found

 [ERROR] Veil Wine environment could not be found!

 [ERROR] Check for existence of /var/lib/veil/wine/drive_c

 [*] Finished package installation

 [*] Initializing (OS + Wine) Python dependencies installation...

 [*] Installing (Wine) Python...

 [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)

sudo: wine: command not found

 [ERROR] Failed to install (Wine) Python 3.4.4... Exit code: 1

 [*] Installing (Wine) Python dependencies...

 [*] Installing (Wine) Python's pywin32-220.win32-py3.4.exe...

 [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)

warning [pywin32-220.win32-py3.4.exe]:  192288 extra bytes at beginning or within zipfile

  (attempting to process anyway)

cp: target '/var/lib/veil/wine/drive_c/Python34/Lib/site-packages/' is not a directory

cp: target '/var/lib/veil/wine/drive_c/Python34/Scripts/' is not a directory

sudo: wine: command not found

 [*] Installing (Wine) Python's pycrypto-2.6.1.win32-py3.4.exe...

 [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)

warning [pycrypto-2.6.1.win32-py3.4.exe]:  191515 extra bytes at beginning or within zipfile

  (attempting to process anyway)

cp: target '/var/lib/veil/wine/drive_c/Python34/Lib/site-packages/' is not a directory

 [*] Installing (OS) Python's PyInstaller (via TAR)

 [*] Installing (Wine) Python's PIP pefile

sudo: wine: command not found

 [ERROR] Failed to run (wine) Python pip... Exit code: 1

sudo: wine: command not found

 [ERROR] Failed to run (wine) Python pip future... Exit code: 1

sudo: wine: command not found

 [ERROR] Failed to run (wine) Python pip pefile... Exit code: 1

 [*] Finished (Wine + OS) Python dependencies installation

 [*] Initializing (Wine) Ruby installation...

 [*] Installing (Wine) Ruby & dependencies

 [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)

sudo: wine: command not found

 [ERROR] Failed to install (Wine) Ruby.exe... Exit code: 1

 [*] Installing (Wine) Ruby OCRA gem...

sudo: wine: command not found

 [ERROR] Failed to run (wine) Ruby OCRA.. Exit code: 1

 [*] Extracting (Wine) Ruby dependencies...

 [*] Finished Ruby installation

 [*] Initializing Go installation...

 [*] Installing Go x86_64 (via TAR)

 [*] Finished Go installation

 [*] Initializing AutoIT installation...

 [*] Installing (Wine) AutoIT

 [*]  Next -> Next -> Next -> Finished! ...Overwrite if prompt (use default values)

sudo: wine: command not found

 [ERROR] Failed to run (wine) AutoIT.. Exit code: 1

 [*] Finished AutoIT installation

 [*] Updating Veil configuration...

 [*] Detected current Veil settings. Removing...

 Veil Configuration:

 [*] OPERATING_SYSTEM = Kali

 [*] TERMINAL_CLEAR = false

 [*] VEIL_PATH = /opt/Veil/

 [*] WINEPREFIX = /var/lib/veil/wine/

 [*] TEMP_PATH = /tmp/

 [*] METASPLOIT_PATH = /usr/share/metasploit-framework/

 [*] MSFVENOM_PATH = /usr/bin/

 [*] MSFVENOM_OPTIONS = 

 [*] PYINSTALLER_PATH = /var/lib/veil/PyInstaller-3.2.1/

 [*] GOLANG_PATH = /var/lib/veil/go/

 Veil-Evasion Configuration:

 [*] PAYLOAD_SOURCE_PATH = /var/lib/veil/output/source/

 [*] PAYLOAD_COMPILED_PATH = /var/lib/veil/output/compiled/

 [*] HANDLER_PATH = /var/lib/veil/output/handlers/

 [*] HASH_LIST = /var/lib/veil/output/hashes.txt

 [I] Path '/etc/veil/' Created

 [I] Configuration File Written To: '/etc/veil/settings.py'

 [*] Ensuring this account (root) owns veil output directory (/var/lib/veil/output)...

 [*] Ensuring this account (root) has correct ownership of /var/lib/veil/wine

 [*] Finished Veil configuration...

 [*] Finished environment checks

 [ERROR] There was issues installing the following:

 

Failed with apt-get update (1): 0

Failed with installing dependencies (1): 0

Failed with installing wine (2): 0

Veil Wine environment could not be found!

Check for existence of /var/lib/veil/wine/drive_c

Failed to install (Wine) Python 3.4.4... Exit code: 1

Failed to run (wine) Python pip... Exit code: 1

Failed to run (wine) Python pip future... Exit code: 1

Failed to run (wine) Python pip pefile... Exit code: 1

Failed to install (Wine) Ruby.exe... Exit code: 1

Failed to run (wine) Ruby OCRA.. Exit code: 1

Failed to run (wine) AutoIT.. Exit code: 1

 [I] If you have any errors running Veil, run: './Veil.py --setup' and select the nuke the wine folder option

 [I] Done!

## Any additional info you want to tell me
Can you fix my problem 
[veilsetup.txt](https://github.com/Veil-Framework/Veil/files/4695222/veilsetup.txt)

**Comment by ChrisTruncer** [comment]
Please fix the repos that you use

**Comment by saziburrahman** [comment]
> Please fix the repos that you use

what is repos? can you briefly clarify this?
