### ISSUE TITLE
setup install problrm in kali

### ISSUE THREAD

**Issue by choudhary805** [Veil-Framework/Veil#364]
[ERROR] Failed to run (wine) AutoIT.. Exit code: 1

 [ERROR] There was issues installing the following:

 
Failed with installing dependencies (1): 0
Failed with installing wine (2): 0
Veil Wine environment could not be found!
Check for existence of /var/lib/veil/wine/drive_c
Failed to install (Wine) Python 3.4.4... Exit code: 1
Failed to run (wine) Python pip... Exit code: 1
Failed to run (wine) Python pip future... Exit code: 1
Failed to run (wine) Python pip pefile... Exit code: 1
Failed to install (Wine) Ruby.exe... Exit code: 1
Failed to run (wine) Ruby OCRA.. Exit code: 1
Failed to run (wine) AutoIT.. Exit code: 1

**Comment by Mpineda199** [comment]
I have the same issue, if you solve it, share please.

**Comment by ChrisTruncer** [comment]
I can't tell what the issue is if you don't provide any of the basic info we request. Please try on a clean kali and clone from git, I just verified it is working as of the time of this comment.
