### ISSUE TITLE
Unable to Install 

### ISSUE THREAD

**Issue by OL-PenTester** [Veil-Framework/Veil#365]
## Veil version
Veil 3.1

## OS Used - all info (architecture, linux flavor, etc)
Kali Linux 2019.4
x86_64
Gnome

## How did you install Veil? (Apt, Clone from Github, etc.)
Tried once through apt and once through Github clone

## Did you run the setup script?
Yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
https://pastebin.com/52ek1Ruv

## Any additional info you want to tell me
I cannot install wine32 on Kali 2019.4

**Comment by ChrisTruncer** [comment]
Can you try on a clean kali install, and only install by cloning from this repo and not from apt? I just tested the latest version of Kali and it installed successfully.

If you are still running into issues, feel free to comment and re-open this issue
