### ISSUE TITLE
architecture aarch64 not supported

### ISSUE THREAD

**Issue by athul4554** [Veil-Framework/Veil#366]
## Did you run the setup script? yes

why veil is not supporting on raspberrypi 4?

**Comment by ChrisTruncer** [comment]
We can't control the packages that Veil uses if they support that.

**Comment by Sergiota04** [comment]
Your architecture aarch64 is not supported!
Who to fixed it?

**Comment by Tobils** [comment]
anyone solved the issue ?

**Comment by Srijal2008** [comment]
Please solve this error

**Comment by fire715** [comment]
Give me suggestions
