### ISSUE TITLE
Can't find WINE profile? 

### ISSUE THREAD

**Issue by wenirex129** [Veil-Framework/Veil#367]
ike@kali:~/Desktop/Veil$ ls
CHANGELOG  config  __init__.py  lib  LICENSE  README.md  tools  Veil.py
mike@kali:~/Desktop/Veil$ cd config
mike@kali:~/Desktop/Veil/config$ ls
setup.sh  update-config.py
mike@kali:~/Desktop/Veil/config$ ./config/update-config.py --force --silent
bash: ./config/update-config.py: No such file or directory
mike@kali:~/Desktop/Veil/config$ ../
bash: ../: Is a directory
mike@kali:~/Desktop/Veil/config$ cd -
/home/mike/Desktop/Veil
mike@kali:~/Desktop/Veil$ ./config/update-config.py --force --silent

 [!] ERROR: Not root. Requesting...

[sudo] password for mike: 

 [i] Can't find WINE profile?   Run: /home/mike/Desktop/Veil/config/setup.sh --force --silent
 [>] Please enter the directory of Veil's WINE profile (e.g. /var/lib/veil/wine/):

**Comment by ChrisTruncer** [comment]
please follow the readme
