### ISSUE TITLE
Can't Install Veil 

### ISSUE THREAD

**Issue by KedarJoshi11** [Veil-Framework/Veil#370]
## OS Used - all info (architecture, linux flavor, etc)
Kali Linux 2020.1

## How did you install Veil? (Apt, Clone from Github, etc.)
apt-get install veil

## Did you run the setup script?
Yes, after it asked me to do in the error message. 
ERROR #2-3: Can't find Go (/var/lib/veil/go/).   Run: /usr/share/veil/config/setup.sh --force --silent

## Expected behavior
Should have installed it because I had veil before on the same system. I just reinstalled Kali and it's not working now. 

## Any additional info you want to tell me
Here's a screenshot of the last error message. 

![image](https://user-images.githubusercontent.com/43803843/84059513-5efeac00-a9d8-11ea-9658-f77ce5815014.png)

**Comment by KedarJoshi11** [comment]
It does not run past this. 

![image](https://user-images.githubusercontent.com/43803843/84128764-a596e980-aa5e-11ea-8fca-22f2b5fe5c0f.png)

**Comment by ChrisTruncer** [comment]
Can you try installing on a clean system, and cloning and installing from git (instead of installing from apt)? I just tested on a clean Kali image and it installed without any issues.

If you still are encountering problems, feel free to re-open this issue and/or comment in this.
