### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by sathyablaze** [Veil-Framework/Veil#371]
## OS Used - kali linux 2020

 i downloaded the file from https://github.com/Veil-Framework/Veil-Evasion.git by using the command: git clone  https://github.com/Veil-Framework/Veil-Evasion.git
had a lot of issues , but solved many of those , but right now , i wasn't able to solve this one issue
here are the details:

  
awk: fatal: invalid regexp: Invalid range end: /[:-.]/

E: No packages found

./setup.sh: line 546: [: : integer expression expected

Reading package lists... Done

Building dependency tree       

Reading state information... Done

E: Unable to locate package gccgo-5

update-alternatives: error: no alternatives for go

 [*] Installing Go x86_64 (via TAR)

 [*] Setttings already detected... Skipping...

  There was issues installing the following:

 

Failed to install dependencies... Exit code: 100

 [I] If you have any errors running Veil-Evasion, delete the Veil Wine profile ('rm -rf /root/.config/wine/veil') and re-run: '/root/Veil-Evasion/setup/setup.sh -c'

 [I] Done!

can you guys help me with it?

**Comment by ChrisTruncer** [comment]
You are cloning the wrong repo. Please clone the Veil repo, you're literally in that repo right now when you made this issue.
