### ISSUE TITLE
Wine is not owned by you

### ISSUE THREAD

**Issue by darklight-oss** [Veil-Framework/Veil#373]
## Veil version
3.1.14

## OS Used - all info (architecture, linux flavor, etc)
Kali linux 2020.2
kernel: Linux kali 5.6.0-kali2-amd64 #1 SMP Debian 5.6.14-1kali1 (2020-05-25) x86_64 GNU/Linux

## How did you install Veil? (Apt, Clone from Github, etc.)
`sudo apt install veil`

## Did you run the setup script?
yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
```
[python/meterpreter/rev_tcp>>]: generate
===============================================================================
                                   Veil-Evasion
===============================================================================
      [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
===============================================================================

 [>] Please enter the base name for output files (default is payload): 
===============================================================================
                                   Veil-Evasion
===============================================================================
      [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
===============================================================================

 [?] How would you like to create your payload executable?

     1 - PyInstaller (default)
     2 - Py2Exe

 [>] Please enter the number of your choice: 
wine: /var/lib/veil/wine is not owned by you
===============================================================================
                                   Veil-Evasion
===============================================================================
      [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
===============================================================================

 [!] ERROR: Unable to create output file.
 [*] Source code written to: /var/lib/veil/output/source/payload.py
 [*] Metasploit Resource file written to: /var/lib/veil/output/handlers/payload.rc
```

## Any additional info you want to tell me

The main error is:
`wine: /var/lib/veil/wine is not owned by you`
Also I ran the command `chown kali /var/lib/veil/wine` but nothing happened

**Comment by ChrisTruncer** [comment]
You will need to change ownership of that directory so you (your account you use) owns it. This shouldn't be an issue from the installer script. I just verified this by downloading a clean version of Kali (latest build as of this writing) and Veil installed successfully. The only modification was uncommenting the deb-src repo.

**Comment by Keshav0543** [comment]
> You will need to change ownership of that directory so you (your account you use) owns it. This shouldn't be an issue from the installer script. I just verified this by downloading a clean version of Kali (latest build as of this writing) and Veil installed successfully. The only modification was uncommenting the deb-src repo.

where is deb-src rep is located

**Comment by bignath74** [comment]
chown root /var/lib/veil/wine

**Comment by bignath74** [comment]
it worked for me

**Comment by bidurp** [comment]
chmod +777 /var/lib/veil/wine 
I was having the same issue. This worked for me
![image](https://github.com/Veil-Framework/Veil/assets/142151239/129638ed-4052-41f7-9024-07de397e712c)
