### ISSUE TITLE
Failed with installing Wine

### ISSUE THREAD

**Issue by cipher135** [Veil-Framework/Veil#374]
Forget about using it, it is not even installing...

**1st,  Sign of Error**
The following packages have unmet dependencies:
libc6-dev : Breaks: libgcc-8-dev (< 8.4.0-2~) but 8.3.0-26 is to be installed
Breaks: libgcc-9-dev (< 9.3.0-5~) but 9.2.1-22 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
[ERROR] Failed with installing dependencies (1): 0
.
.
.
_after many lines_...
**2nd, Error starts from here**
 E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
[ERROR] Failed with installing wine (2): 0

and it keeps on happening with Python, Ruby and whatever the hell there is.

**Comment by ChrisTruncer** [comment]
Without providing any information at all about your system, it's not possible to troubleshoot this.

There shouldn't be an issue from the installer script. I just verified this by downloading a clean version of Kali (latest build as of this writing) and Veil installed successfully. The only modification was uncommenting the deb-src repo.

**Comment by cipher135** [comment]
I am a newbie at learning this. I don't know which information you require. But I really need to get it resolved. Just tell me what info your require and let me help.
Thanks
