### ISSUE TITLE
veil installation error failed to install these dependencies

### ISSUE THREAD

**Issue by aswingreeshmam** [Veil-Framework/Veil#375]
Veil Configuration:
 [*] OPERATING_SYSTEM = Kali
 [*] TERMINAL_CLEAR = false
 [*] VEIL_PATH = /root/Veil/
 [*] WINEPREFIX = /var/lib/veil/wine/
 [*] TEMP_PATH = /tmp/
 [*] METASPLOIT_PATH = /usr/share/metasploit-framework/
 [*] MSFVENOM_PATH = /usr/bin/
 [*] MSFVENOM_OPTIONS = 
 [*] PYINSTALLER_PATH = /var/lib/veil/PyInstaller-3.2.1/
 [*] GOLANG_PATH = /var/lib/veil/go/

 Veil-Evasion Configuration:
 [*] PAYLOAD_SOURCE_PATH = /var/lib/veil/output/source/
 [*] PAYLOAD_COMPILED_PATH = /var/lib/veil/output/compiled/
 [*] HANDLER_PATH = /var/lib/veil/output/handlers/
 [*] HASH_LIST = /var/lib/veil/output/hashes.txt
 [I] Path '/etc/veil/' Created
 [I] Configuration File Written To: '/etc/veil/settings.py'

 [*] Ensuring this account (root) owns veil output directory (/var/lib/veil/output)...

 [*] Ensuring this account (root) has correct ownership of /var/lib/veil/wine

 [*] Finished Veil configuration...

 [*] Finished environment checks

 [ERROR] There was issues installing the following:

 
Failed with installing dependencies (1): 0
Failed with installing wine (2): 0
Veil Wine environment could not be found!
Check for existence of /var/lib/veil/wine/drive_c
Failed to install (Wine) Python 3.4.4... Exit code: 1
Failed to run (wine) Python pip... Exit code: 1
Failed to run (wine) Python pip future... Exit code: 1
Failed to run (wine) Python pip pefile... Exit code: 1
Failed to install (Wine) Ruby.exe... Exit code: 1
Failed to run (wine) Ruby OCRA.. Exit code: 1
Failed to run (wine) AutoIT.. Exit code: 1

 [I] If you have any errors running Veil, run: './Veil.py --setup' and select the nuke the wine folder option

 [I] Done

root@kali:~/Veil# ./Veil.py --setup

 [!] ERROR #2-3: Can't find the WINE profile for Python v3.4 (/var/lib/veil/wine//drive_c/Python34/python.exe).   Run: /root/Veil/config/setup.sh --force --silent

**Comment by ChrisTruncer** [comment]
Please follow the readme and install on a system with an X server.
