### ISSUE TITLE
Please enter the directory of PyInstaller (e.g. /var/lib/veil/PyInstaller-3.2.1/):

### ISSUE THREAD

**Issue by poovtamil** [Veil-Framework/Veil#381]
## Any additional info you want to tell me

**Comment by poovtamil** [comment]
Please enter the directory of PyInstaller (e.g. /var/lib/veil/PyInstaller-3.2.1/):

**Comment by elgaeraw** [comment]
I am having the same issue while running the setup.sh script. I think it has something to do with **Bad Hash received** but I am not sure.

**Comment by babzansyed** [comment]
I am having the same issue while running the setup.sh script. how to resolve it?

**Comment by Akshat-23265** [comment]
Help !!
