### ISSUE TITLE
Setup return an error: Your architecture armv7l is not supported

### ISSUE THREAD

**Issue by WBP20** [Veil-Framework/Veil#387]
Hi,

No possible to run the setup file, and so install and use Veil. 

## Veil version

Latest

## OS Used - all info (architecture, linux flavor, etc)

os = Kali Linux
osversion = 2020.3
osmajversion = 2020
arch = armv7l

## How did you install Veil? (Apt, Clone from Github, etc.)

sudo apt-get -y install git
git clone https://github.com/Veil-Framework/Veil.git
cd Veil/
./config/setup.sh --force --silent

## Did you run the setup script?

Yes and it returns : [ERROR] Your architecture armv7l is not supported!

## Pastebin link to error you are encountering (include console actions you took prior to error)

Same as the 2 issues below : 

https://github.com/Veil-Framework/Veil/issues/240
https://github.com/Veil-Framework/Veil/issues/326

## Expected behavior

Should install Veil and dependencies

## Any additional info you want to tell me

Running Kali Linux on RPI4.
Yes I am willing to try to edit the setup file if you tell me what to do. 

Thank you in advance for your help.

**Comment by ChrisTruncer** [comment]
This is not currently supported, so this will not install. If you happen to add in support for RPI4, feel free to send it our way and we will get it merged in.
