### ISSUE TITLE
how to install on  centos 7

### ISSUE THREAD

**Issue by leezp** [Veil-Framework/Veil#388]
## How did you install Veil? (Apt, Clone from Github, etc.)
git clone https://github.com/Veil-Framework/Veil.git
./config/setup.sh --force --silent

## Pastebin link to error you are encountering (include console actions you took prior to error)

[ERROR] Unable to determine OS information. Exiting...
## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
We don't currently support this distro. In the event that you want to add in support, feel free to send it our way and we will be happy to merge it in.
