### ISSUE TITLE
Same issue with pop os

### ISSUE THREAD

**Issue by harmony-al** [Veil-Framework/Veil#390]
## Veil version
Latest version as of October , 2020

## OS Used - all info (architecture, linux flavor, etc)

Pop Os
## How did you install Veil? (Apt, Clone from Github, etc.)
git clone

## Did you run the setup script?
yes, I ran it but it is giving me ' [ERROR] Unable to determine OS information. Exiting... '

## Pastebin link to the error you are encountering (include console actions you took prior to error)
[ERROR] Unable to determine OS information. Exiting...

## Expected behavior
The problem is in the setup file as it does not include pop os 

## Any additional info you want to tell me
Help soon, I tried to replace all Elementary os mention with pop os but it did not work. I am new to Linux. Sorry, for the dumb question.

**Comment by ChrisTruncer** [comment]
We currently do not support this distro. In the event that you want to add in support, feel free to submit it over to us and we will be happy to get it merged in.

**Comment by lSANCHOl** [comment]
hi, any update on POP OS support. I don't know much about coding but I've heard POP OS is a clone of ubuntu with extra features so I reckon the current code used for ubuntu in setup.sh could be used for POP OS.  So would it be possible and pretty easy to just add an if statement to detect pop os and then make it run the same bits of code used to setup ubuntu?

**Comment by lSANCHOl** [comment]
I tried it myself by just replacing the if statements from "ubuntu" to "pop" and it got to the stage wheree I had to enter the directory for msfvenom and when entering it it would just ask me to enter it again infinitely.

**Comment by lSANCHOl** [comment]
I literally changed all the the if statements that check if the OS is "ubuntu" to "pop" in the setup.sh and now veil works for me. I am running POP OS 20.04. this doesn't suprise me as pop os is pretty much identical to ubuntu.
