### ISSUE TITLE
Encryption Errors

### ISSUE THREAD

**Issue by fisherstevens** [Veil-Framework/Veil#394]
## Veil version
3.1.14

## OS Used - all info (architecture, linux flavor, etc)
Kali 2020.3 x64

## How did you install Veil? (Apt, Clone from Github, etc.)
apt-get install veil
sudo /usr/share/veil/Veil.py

## Did you run the setup script?
I tried that as well

## Pastebin link to error you are encountering (include console actions you took prior to error)
https://pastebin.com/65xLNQiu

## Expected behavior
Generated final output

## Any additional info you want to tell me
It seems to tie back to how the key is generated. It doesn't like that it is a string.

**Comment by Ag0s** [comment]
Update line 21 on file:
/usr/share/veil/tools/evasion/evasion_common/encryption.py
to:
aes_cipher_object = AES.new(random_aes_key.encode('utf8'), AES.MODE_CBC, IV=iv.encode('utf8'))

**Comment by ChrisTruncer** [comment]
This is now merged in, thanks!
