### ISSUE TITLE
3 Errors while installing Veilt / Failed to install dependencies... Exit code: 100 / Failed to install Capstone... Exit code: 100 / Failed to install SymmetricJSONRPC... Exit code: 100

### ISSUE THREAD

**Issue by ghost** [Veil-Framework/Veil#396]
I'm running Kali on VirtualBox 2020.3
and i tried (for multiple hours) to download veil-evasion
I fixed some issues with downloading wine32 manuelly etc...
But i cant fix the last 3 Errors:

  There was issues installing the following:

///
 
Failed to install dependencies... Exit code: 100
Failed to install Capstone... Exit code: 100
Failed to install SymmetricJSONRPC... Exit code: 100

 [I] If you have any errors running Veil-Evasion, delete the Veil Wine profile ('rm -rf /root/.config/wine/veil') and re-run: '/root/Veil-Evasion/setup/setup.sh -c'

 [I] Done!

root@kali:~/Veil-Evasion/setup# Veil-Evasion
-bash: Veil-Evasion: command not found

///

## Did you run the setup script?
Yes

Can someone help me? I tried so hard haha...

**Comment by gabi8888767768** [comment]
oi, vc descobriu como corrigir o erro?
