### ISSUE TITLE
3 Errors while installing Veil / Failed to install dependencies... Exit code: 100 / Failed to install Capstone... Exit code: 100 / Failed to install SymmetricJSONRPC... Exit code: 100

### ISSUE THREAD

**Issue by ghost** [Veil-Framework/Veil#397]
I'm running Kali on VirtualBox 2020.3
and i tried (for multiple hours) to download veil-evasion
I fixed some issues with downloading wine32 manuelly etc...
But i cant fix the last 3 Errors:

There were issues installing the following:

///
 
Failed to install dependencies... Exit code: 100
Failed to install Capstone... Exit code: 100
Failed to install SymmetricJSONRPC... Exit code: 100

 [I] If you have any errors running Veil-Evasion, delete the Veil Wine profile ('rm -rf /root/.config/wine/veil') and re-run: '/root/Veil-Evasion/setup/setup.sh -c'

 [I] Done!

root@kali:~/Veil-Evasion/setup# Veil-Evasion
-bash: Veil-Evasion: command not found

///

Did you run the setup script?
Yes

Can someone help me? I tried so hard haha...

**Comment by paragonexcite** [comment]
Same here.

Running:
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2020.4
Codename:       kali-rolling

Through Oracle VM Virtual Box

This is the error code:

Failed to install dependencies... Exit code: 100
Failed to install Capstone... Exit code: 100
Failed to install SymmetricJSONRPC... Exit code: 100

Any help would be appreciated.

**Comment by ChrisTruncer** [comment]
Please provide all of the information requested when creating a Github issue. We're not able to troubleshoot the problem with the limited information we have. Feel free to go ahead and respond to this issue with all of the information requested and we can better help try to find the problem.
