### ISSUE TITLE
error python/meterpreter/rev_http

### ISSUE THREAD

**Issue by jackson5sec** [Veil-Framework/Veil#4]
Getting Invalid Syntax on Pyinstaller3 compile of payload.py for python/meterpreter/rev_http payload.

There's an extra % sign `%% 0x100` on line 145 [here](https://github.com/Veil-Framework/Veil/blob/master/Tools/Evasion/payloads/python/meterpreter/rev_http.py#L145)

Also one [here](https://github.com/Veil-Framework/Veil/blob/master/Tools/Evasion/payloads/python/meterpreter/rev_http.py#L159) `%%(" + hostName + ", " + portName + ", " + checkinMethodName + "())` on line 159

Both of these cause syntax errors when trying to compile the generated payload.py.

**Comment by jackson5sec** [comment]
Fixed it by either removing % or formatting it the same as python/meterpreter/rev_https

**Comment by ChrisTruncer** [comment]
Yup, I can reproduce this.  I'll get a fix pushed shortly

**Comment by ChrisTruncer** [comment]
This is merged in now, thanks!
