### ISSUE TITLE
Cant set advanced settings for payloads

### ISSUE THREAD

**Issue by JoeNibe** [Veil-Framework/Veil#40]
## Veil version
3.0

## OS Used - all info (architecture, linux flavor, etc)
Kali 2.0

Is it possible to set the advanced options available for payloads,

For example the payload meterpreter/reverse_http have the following advanced options:

msf > use windows/meterpreter/reverse_http
msf payload(reverse_http) > advanced

Module advanced options (payload/windows/meterpreter/reverse_http):

   Name                         Current Setting                                                Required  Description
   ----                         ---------------                                                --------  -----------
   AutoLoadStdapi               true                                                           yes       Automatically load the Stdapi extension
   AutoRunScript                                                                               no        A script to run automatically on session creation.
   AutoSystemInfo               true                                                           yes       Automatically capture system information on initialization.
   AutoVerifySession            true                                                           yes       Automatically verify and drop invalid sessions
   AutoVerifySessionTimeout     30                                                             no        Timeout period to wait for session validation to occur, in seconds
 etc..

So is it possible to set value for any of the above values.

**Comment by ChrisTruncer** [comment]
Yes, you can set this. Veil asks if there are any advanced options you would like to set. That would be where you input it.

![advanced options](https://cloud.githubusercontent.com/assets/1674822/24668036/b17cd8d4-1922-11e7-9b89-0c20026eef8a.png)
