### ISSUE TITLE
everytime the install of python 3.4.4,my kali always get stuck 。。how to fix it？

### ISSUE THREAD

**Issue by telnetyourheart** [Veil-Framework/Veil#405]
[!] ERROR #2-3: Can't find the WINE profile for Python v3.4 (/var/lib/veil/wine//drive_c/Python34/python.exe).   Run: /usr/share/veil/config/setup.sh --force --silent
 

then  i input  /usr/share/veil/config/setup.sh --force --silent 
it will get stuck when the appearance of the install of python 3.4.4

it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
0012:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0012:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0012:err:ole:get_local_server_stream Failed: 80004002
0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
0014:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0014:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0014:err:ole:get_local_server_stream Failed: 80004002
Could not find Wine Gecko. HTML rendering will be disabled.
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
Could not find Wine Gecko. HTML rendering will be disabled.
wine: configuration in L"/var/lib/veil/wine" has been updated.
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
0046:err:msiexec:custom_action_server Failed to create custom action server pipe: 2

**Comment by LiamKapeel** [comment]
you need to upgrade your perms to root. Do ""SUDO -S""
