### ISSUE TITLE
aarch64 not supported

### ISSUE THREAD

**Issue by haltosan** [Veil-Framework/Veil#408]
## Veil version
Updated 2018-05-08

## OS Used - all info (architecture, linux flavor, etc)
os = kali
osversion = 2020.4
osmajversion = 2020
arch = aarch64
I'm using the Raspberry Pi 3B+

## How did you install Veil? (Apt, Clone from Github, etc.)
Clone from Github on Jan 6, 2021

## Did you run the setup script?
Yes, the error appeared during the setup script.

## Any additional info you want to tell me
Is there a workaround that would work?
[edit]: I should probably clarify. Can Veil work on aarch64 with minimal tweaking on my end, or would it need major changes?

**Comment by ChrisTruncer** [comment]
I unfortunately do not believe it will work. It's due to the packages not all working on it. In the event that Veil's dependencies are all able to work on a Raspberry Pi, then that will change.
