### ISSUE TITLE
"this app cannot run on this pc, check with your software publisher"

### ISSUE THREAD

**Issue by Nj0n** [Veil-Framework/Veil#412]
hey.
i have installed Veil, created a backdoor, i have modifed it and even not , and it is was undetected and all was good.
but the problem is when i am trying to run it on my pc, or other pc (windows 10 x64) 
it is says " this app cannot run on this pc" the antivirus doesnt do anything, it is all goes clean until i am trying to open it up,

in metasploit it is looking like i got a shell, but it is not once i clicked on anyhing.

any idea how can i fix it ?

**Comment by ChrisTruncer** [comment]
Unfortunately, I don't have nearly enough information to troubleshoot this. If you can, please provide all of the information that is requested when opening a github issue so that we can begin to troubleshoot the problem. Feel free to respond with the information within this issue.
