### ISSUE TITLE
Veil Installation error Failed to run (wine) Python pip pefile... Exit code: 1

### ISSUE THREAD

**Issue by Ares-21** [Veil-Framework/Veil#428]
## Veil version
Veil 3.1

## OS Used - all info (architecture, linux flavor, etc)
Kali linux 2021.1 on VirtualBox on a Mac

## How did you install Veil? (Apt, Clone from Github, etc.)
git clone https://github.com/Veil-Framework/Veil.git

## Did you run the setup script?
yes i tried all of it 
./config/setup.sh --force --silent 
/usr/share/veil/config/setup.sh --force --silent
./Veil.py --setup

## Pastebin link to error you are encountering (include console actions you took prior to error)

[*] Installing (Wine) Python's PIP pefile

Collecting pip==19.1.*
  Downloading https://files.pythonhosted.org/packages/5c/e0/be401c003291b56efc55aeba6a80ab790d3d4cece2778288d65323009420/pip-19.1.1-py2.py3-none-any.whl (1.4MB)
    100% |################################| 1.4MB 285kB/s 
Installing collected packages: pip
  Found existing installation: pip 7.1.2
    Uninstalling pip-7.1.2:
      Successfully uninstalled pip-7.1.2
Successfully installed pip-19.1.1
You are using pip version 19.1.1, however version 21.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.             
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Collecting future
  Downloading https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz (829kB)
     |████████████████████████████████| 829kB 553kB/s eta 0:00:01
Installing collected packages: future
  Running setup.py install for future ... \0031:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
done
Successfully installed future-0.18.2
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Collecting pefile
  Downloading https://files.pythonhosted.org/packages/f9/1e/fc4fac0169d16a98577809400bbcfac8ad1900fa792184327b360ea51fc6/pefile-2021.5.13.tar.gz (66kB)
     |████████████████████████████████| 71kB 487kB/s eta 0:00:01
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\users\root\Temp\pip-install-u0tx4rya\pefile\setup.py", line 86, in <module>
        long_description = "\n".join(_read_doc().split('\n')),
      File "C:\users\root\Temp\pip-install-u0tx4rya\pefile\setup.py", line 33, in _read_doc
        tree = ast.parse(f.read())
      File "C:\Python34\lib\ast.py", line 35, in parse
        return compile(source, filename, mode, PyCF_ONLY_AST)
      File "<unknown>", line 3789
        f'Export directory contains more than 10 repeated entries '
                                                                  ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\users\root\Temp\pip-install-u0tx4rya\pefile\
 [ERROR] Failed to run (wine) Python pip pefile... Exit code: 1

[*] Finished environment checks

 [ERROR] There was issues installing the following:

 
Failed to run (wine) Python pip pefile... Exit code: 1

 [I] If you have any errors running Veil, run: './Veil.py --setup' and select the nuke the wine folder option

## Any additional info you want to tell me
Ive been trying to solve this issue for a few days now but none of the methods are working i even tried to download on a new kali virtual machine but it still shows this one error again if anyone has a solution please help me solve this.

**Comment by autumn-cpt** [comment]
@aakash272002 - The f strings were introduced in 3.6, so you need to restrict the pip load of pefile to an older version (had the same problem, this is how I'm solving it, with the use of csmake/csmake-providers PypiFacade), or you can move to python 3.6.

**Comment by autumn-cpt** [comment]
csmake isn't really production ready and is still running on python2 so I don't have packages available for it on GH, but I can make packages available for you to use if necessary.  Also, I just used PypiFacade for a different project with wine and while it's not set up to work with windows or wine, I found a way to get it to work well.  My advise is to move to python 3.6 though.

**Comment by srpape** [comment]
@autumn-cpt Do you happen to know the last version of pefile that supports Python 3.4?

**Comment by Ares-21** [comment]
@autumn-cpt i am currently using python 3.9.2 how can i change the version to 3.6 any idea please help me out here 
Thank you

**Comment by Ares-21** [comment]
@autumn-cpt also were you referring to csmake or cmake in the comment above I was a bit confused

**Comment by autumn-cpt** [comment]
@srpape The version of pefile that I'm using I know works for python 2: 2019.4.18

@aakash272002 I was basing the Python 3.4 comment from the log that was posted:
```
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
```
I was definitely referring to csmake:
https://github.com/devops-csmake

**Comment by Ares-21** [comment]
![scrnst](https://user-images.githubusercontent.com/63418316/119668178-ff4b1c00-be47-11eb-8fc8-2f91447b1f88.jpg)

I have downloaded the file pls could u help me what to do next @autumn-cpt

**Comment by autumn-cpt** [comment]
@aakash272002 you could do it all from source yourself.  But, it would be easier if you had some packages to install.  Do you need .deb files or .rpm. ?

**Comment by sploit-cloud** [comment]
Yo please need a step by step procedure in other to overcome the challenge "Veil Installation error Failed to run (wine) Python pip pefile... Exit code: 1"

**Comment by ashr** [comment]
![image](https://user-images.githubusercontent.com/171286/122740462-44664080-d284-11eb-9132-1805dd50deab.png)

Seems to do the trick for python 3.4

**Comment by pr0b3r7** [comment]
I am having this same issue - even with @ashr fix....
@autumn-cpt  - thank you for all the help you have been kindly providing so far. Could you please do a small writeup on how to overcome this 
![image](https://user-images.githubusercontent.com/14915771/124929550-9a4e1e80-dfce-11eb-96e8-32fb60db2f9e.png)
Thank you,

**Comment by dancyuser** [comment]
Hoping for an answer as I encountered this problem too

**Comment by DesmondKong** [comment]
> ![image](https://user-images.githubusercontent.com/171286/122740462-44664080-d284-11eb-9132-1805dd50deab.png)
> 
> Seems to do the trick for python 3.4

As per @ashr comment, changing the installed pefile version fixed the issue.

`# vi /usr/share/veil/config/setup.sh`

Change line 587 to:
`sudo -u "${trueuser}" WINEPREFIX="${winedir}" wine "${winedir}/drive_c/Python34/python.exe" "-m" "pip" "install" "-Iv" "pefile==2019.4.18"`

Then, run `# veil --setup` again.

Hope it helps.

**Comment by amithinfini** [comment]
@DesmondKong, it worked thanks

And folks, if unable to generate the payload file at last, run "sudo chown root:root -R /var/lib/veil/wine"

**Comment by amithinfini** [comment]
> > ![image](https://user-images.githubusercontent.com/171286/122740462-44664080-d284-11eb-9132-1805dd50deab.png)
> > Seems to do the trick for python 3.4
> 
> As per @ashr comment, changing the installed pefile version fixed the issue.
> 
> `# vi /usr/share/veil/config/setup.sh`
> 
> Change line 587 to:
> `sudo -u "${trueuser}" WINEPREFIX="${winedir}" wine "${winedir}/drive_c/Python34/python.exe" "-m" "pip" "install" "-Iv" "pefile==2019.4.18"`
> 
> Then, run `# veil --setup` again.
> 
> Hope it helps.



@DesmondKong, this worked thanks
And folks, if unable to generate the payload file at last, run "sudo chown root:root -R /var/lib/veil/wine"

**Comment by Ares-21** [comment]
thank you so much it works

**Comment by cyberxploithausa** [comment]
> > ![image](https://user-images.githubusercontent.com/171286/122740462-44664080-d284-11eb-9132-1805dd50deab.png)
> > Seems to do the trick for python 3.4
> 
> As per @ashr comment, changing the installed pefile version fixed the issue.
> 
> `# vi /usr/share/veil/config/setup.sh`
> 
> Change line 587 to:
> `sudo -u "${trueuser}" WINEPREFIX="${winedir}" wine "${winedir}/drive_c/Python34/python.exe" "-m" "pip" "install" "-Iv" "pefile==2019.4.18"`
> 
> Then, run `# veil --setup` again.
> 
> Hope it helps.

Hell yeah! i've spent about 10 days trying to solve veil installation problems, python pip pefile happens to be the last error. and thank God to your help. it works just fine.

**Comment by hasnainmshabbir** [comment]
can anyone explain me this i didnot understand .. how i fixed the Veil installation i see screen shot but i dont know where to copy paste this line of code

**Comment by hasnainmshabbir** [comment]
I do this but this is not working for me what should i do anyone please help

**Comment by MAAYTHM** [comment]
**(For all linux distributions which use 'apt' as their package handler)**
try editing the setup file like this:- 

**file location :-** `/usr/share/veil/config/setup.sh`

**Comment out lines which install wine in your system , You can find these lines somewhere from 302 line to 406 line. or you can search** `wine install` **in file for finding lines**

**and change these to :-**
`sudo ${arg} apt-get -y install --install-recommends winehq-stable`

**I highlighted some lines which need to comment out with red color and highlight those lines also which i added.**
![1](https://user-images.githubusercontent.com/86392841/148685377-7a4086d7-d3c8-4019-8c4b-221951083b41.png)
![2](https://user-images.githubusercontent.com/86392841/148685949-1bcb183f-6519-42fa-84f6-ab0b77e634a8.png)

**Comment by afastars** [comment]
Hi all,

I've used Veil-Framework Version 3.1.6 and I received error as follows, which similar to others, and I tried to change the code to  sudo -u "${trueuser}" WINEPREFIX="${winedir}" wine "${winedir}/drive_c/Python34/python.exe" "-m" "pip" "install" "-Iv" "pefile==2019.4.18"but it wasn't work for me...Please help me to resolve this problem.

![Capture_Error](https://user-images.githubusercontent.com/73839122/170531134-d1df0eb7-88c0-4d25-b389-83cf19e2ab0f.JPG)

**Comment by reddick7** [comment]
solved by install
sudo apt install winehq-staging
sudo apt install winehq-devel

**Comment by JhonCola** [comment]
AL GENERAR LA CARGA UTIL ME SALE ESTO SI ALGUIN ME PUEDE AYUDAR
[python/meterpreter/rev_tcp>>]: generate
Traceback (most recent call last):
  File "/usr/share/veil/./Veil.py", line 145, in <module>
    the_conductor.main_menu()
  File "/usr/share/veil/lib/common/orchestra.py", line 136, in main_menu
    tool_object.tool_main_menu()
  File "/usr/share/veil/tools/evasion/tool.py", line 368, in tool_main_menu
    self.use_payload(selected_payload_module)
  File "/usr/share/veil/tools/evasion/tool.py", line 400, in use_payload
    selected_payload.generate()
  File "/usr/share/veil/tools/evasion/payloads/python/meterpreter/rev_tcp.py", line 145, in generate
    payload_code = encryption.pyherion(payload_code)
  File "/usr/share/veil/tools/evasion/evasion_common/encryption.py", line 209, in pyherion
    encrypted_code, key, iv = aes_encryption("\n".join(codebase), encryption_pad='{')
  File "/usr/share/veil/tools/evasion/evasion_common/encryption.py", line 21, in aes_encryption
    aes_cipher_object = AES.new(random_aes_key, AES.MODE_CBC, iv)
  File "/usr/lib/python3/dist-packages/Cryptodome/Cipher/AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/Cryptodome/Cipher/__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/usr/lib/python3/dist-packages/Cryptodome/Cipher/_mode_cbc.py", line 274, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "/usr/lib/python3/dist-packages/Cryptodome/Cipher/AES.py", line 103, in _create_base_cipher
    result = start_operation(c_uint8_ptr(key),
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 143, in c_uint8_ptr
    raise TypeError("Object type %s cannot be passed to C code" % type(data))
TypeError: Object type <class 'str'> cannot be passed to C code
