### ISSUE TITLE
Powershell payloads enhancement

### ISSUE THREAD

**Issue by qgrosperrin** [Veil-Framework/Veil#43]
https://github.com/Veil-Framework/Veil/blob/master/Tools/Evasion/payloads/powershell/
All Powershell payloads (located under the path mentioned above) make use of the following arguments to launch the Powershell process: `powershell.exe -NoP -NonI -W Hidden -Exec Bypass -Command "..."`. 

The use of `-Exec Bypass` with `-Command` is redundant.  The use of `-Command` only should suffice to bypass the execution policy restrictions [1] so `-Exec Bypass` shouldn't be required.. 

I have confirmed the above with Veil generated payloads on my machine: with and without `-Exec Bypass` the result is the same (albeit my machine Execution Policy is set to 'Restricted'.)

Because some security products are triggering signatures on "-Exec Bypass" (and variations) for Powershell payloads, this redundancy may actually lead to some attacks being detected (don't have any source to support that I'm afraid).

As an aside, people should consider adding additional obfuscation if they want to (e.g. to obfuscate the launcher itself using https://github.com/danielbohannon/Invoke-Obfuscation).

[1] https://blog.netspi.com/15-ways-to-bypass-the-powershell-execution-policy/

**Comment by ChrisTruncer** [comment]
you're right, updated the payloads, thanks!
