### ISSUE TITLE
Freezing on Autoit.

### ISSUE THREAD

**Issue by ghost** [Veil-Framework/Veil#44]
## Veil version
3.0
## OS Used - all info (architecture, linux flavor, etc)
Kali 2017.1 Rolling
## Expected behavior
When installing Veil the script starts Autoit v3.3.14.2 but then freezes as it reaches GDIPlus_GraphicsSetClipRect.au3
It's done this 3 times now. Is there anything I can do. I have to restart my computer ever time and try again.

**Comment by ChrisTruncer** [comment]
Can you provide any info? You closed this without letting anyone know what fixed it for you?

With that said, I have never encountered this issue on any system I've tested, so I'm also interested in knowing.
