### ISSUE TITLE
 [ERROR] Failed with installing dependencies (6): 0

### ISSUE THREAD

**Issue by pranshushakya123** [Veil-Framework/Veil#449]
![Capture](https://user-images.githubusercontent.com/92092121/136686703-61ec4e94-0035-4164-82db-8e5125e5788d.PNG)

**Comment by aliali926** [comment]
In config file change python3-crypto to python3-cryptography. Then update

**Comment by pranshushakya123** [comment]
There is no such file

**Comment by caraidenome** [comment]
how did you solved ?
