### ISSUE TITLE
ImportError: No module named lib.common

### ISSUE THREAD

**Issue by oguzhanf** [Veil-Framework/Veil#45]
## Veil version
3.0

## OS Used - all info (architecture, linux flavor, etc)
Kali x64 running in VMWare up-to-date as of 13th April 2017

## Pastebin link to error you are encountering (include console actions you took prior to error)
https://pastebin.com/6ULTt8a7

## Expected behavior
To be presented with the menu options.

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
You're using Python 2. This tool is Python 3

**Comment by Evro123** [comment]
I have this problem too. What schuld I do??

**Comment by Evro123** [comment]
I have lib.common on python2 and python3install but have alredy this problem. Can you hellp me?Pleas!!

**Comment by ChrisTruncer** [comment]
Grab the latest version of Veil, start a new github issue, and give me all the info that I ask for to try to help troubleshoot.

**Comment by Evro123** [comment]
https://github.com/Evro123/dogs/issues/1#thread-subscription-status

**Comment by beyefendi** [comment]
python3 Veil.py rather than python Veil.py

**Comment by MarcusHolloway007** [comment]
Thanks brother helping may you live keep thanks your generosity and supportive nature helped a lot #Oguzhan Filizlibay

**Comment by rnbaidya** [comment]
Traceback (most recent call last):
  File "./Veil.py", line 7, in <module>
    from lib.common import orchestra
  File "/opt/Veil/lib/common/orchestra.py", line 10, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'
