### ISSUE TITLE
All Payload Get Detected

### ISSUE THREAD

**Issue by pranshushakya123** [Veil-Framework/Veil#452]
## Veil version
3.1.14

## OS Used - all info (architecture, linux flavor, etc)
Kali Linux

## How did you install Veil? (Apt, Clone from Github, etc.)
I used both then I am able to install veil

## Did you run the setup script?
Yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
**My all Payloads detected by Antivirus Programs** 

## Expected behavior
Payload Not Detected

## Any additional info you want to tell me
I want to know is there any issue in my veil that's why  my **payload get detected** or its something  else

**Comment by alekzandr** [comment]
I think this is to be expected now since the Framework has been public for so long.

**Comment by Idlefase** [comment]
@alekzandr is likely to be correct since av vendors collect all sorts of data bout payloads. Most payloads share commonly used tactics and code. A signature can cover lots of payloads. And as far as im aware, this program has a limited set of evading tactics.

**Comment by AdonisPro** [comment]
@ChrisTruncer , Request your input on this please as i am also facing the same. All the payloads are getting detected. And don;t want to loose this super excellent tool. 
Your suggestion is highly solicited. Earnest request. Please help.

**Comment by ChrisTruncer** [comment]
Veil wasn't a project designed for me to continuously fight against each AV for any person that uses the tool. It has the foundation of code (each base template) and then examples of modifications that can be done (checks on username, number of processors, etc.). People using the tool should by all means look at the code and use that as a base (if you want) and modify it to your needs.

Some areas I would recommend are keying the payloads. Veil right now does an if/else check and continues on. If you aren't setting these optional attributes, you need to start there. If you are, then you should modify the code so it actually is keyed based on the environment it is operating in vs. just an if/else check.

I would also encourage everyone to submit their modifications to Veil in the form of a pull request.
