### ISSUE TITLE
Debian 5.0???

### ISSUE THREAD

**Issue by R3GNUM** [Veil-Framework/Veil#458]
## Veil version
3.1 (latest)

## OS Used - all info (architecture, linux flavor, etc)
Parrot OS (security edition) 64bit.

## How did you install Veil? (Apt, Clone from Github, etc.)
tried both ways apt and git clone ... didn't work.

## Did you run the setup script?
yes, I did with --force and --silent.

## Pastebin link to error you are encountering (include console actions you took prior to error)
 ==========================================================================
                 Veil (Setup Script) | [Updated]: 2018-05-08
 ==========================================================================
     [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
 ==========================================================================

                 os = debian
          osversion = 5.0
       osmajversion = 5
               arch = x86_64
           trueuser = regnum
   userprimarygroup = regnum
        userhomedir = /home/regnum
            rootdir = /usr/share/veil
            veildir = /var/lib/veil
          outputdir = /var/lib/veil/output
    dependenciesdir = /var/lib/veil/setup-dependencies
            winedir = /var/lib/veil/wine
          winedrive = /var/lib/veil/wine/drive_c
            gempath = Z:\var\lib\veil\wine\drive_c\Ruby187\bin\gem

 [ERROR]: Veil is only supported on Debian 8 (Jessie) or higher!

 ==========================================================================
                 Veil (Setup Script) | [Updated]: 2018-05-08
 ==========================================================================
     [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
 ==========================================================================

                 os = debian
          osversion = 5.0
       osmajversion = 5
               arch = x86_64
           trueuser = regnum
   userprimarygroup = regnum
        userhomedir = /home/regnum
            rootdir = /usr/share/veil
            veildir = /var/lib/veil
          outputdir = /var/lib/veil/output
    dependenciesdir = /var/lib/veil/setup-dependencies
            winedir = /var/lib/veil/wine
          winedrive = /var/lib/veil/wine/drive_c
            gempath = Z:\var\lib\veil\wine\drive_c\Ruby187\bin\gem

 [ERROR]: Veil is only supported on Debian 8 (Jessie) or higher!

 [!] ERROR #2-3: Can't find Go (/var/lib/veil/go/).   Run: /usr/share/veil/config/setup.sh --force --silent

## Expected behavior
does not run anymore while I have the latest version of debian.

## Any additional info you want to tell me

Would love if you helped and showed how to resolve this error!

Thanks in advance!

**Comment by Ivoripuion** [comment]
same problems.
my parrot version is considered as debian’s.
I fix it like this:
```bash
if [ "$( awk -F '=' '/^NAME=/ {print $2}' /etc/os-release 2>&- )" == "\"Parrot OS\"" ]; then
  os="parrot"
else
  os="$( awk -F '=' '/^ID=/ {print $2}' /etc/os-release 2>&- )"
fi
```

**Comment by R3GNUM** [comment]
> same problems. my parrot version is considered as debian’s. I fix it like this:
> 
> ```shell
> if [ "$( awk -F '=' '/^NAME=/ {print $2}' /etc/os-release 2>&- )" == "\"Parrot OS\"" ]; then
>   os="parrot"
> else
>   os="$( awk -F '=' '/^ID=/ {print $2}' /etc/os-release 2>&- )"
> fi
> ```

Frist of all Hope your doing well! and second sorry for the late reply .
I really wanted to know how do I make it work?
can I ?
Drop these commands in the terminal ?
Make a .sh script and run these commands ?
Edit a config file?


Thank you in advance!
regards! R3GNUM!

**Comment by R3GNUM** [comment]
Found the solution!
Open up a terminal  and write : 
`cat /etc/os-release`
then you will see the os version details if **VERSION_ID="5.0"** change it to **VERSION_ID="8.0"** and enjoy!!

**Comment by Akshat-23265** [comment]
help i am also having the same issue-



 ==========================================================================
                 Veil (Setup Script) | [Updated]: 2018-05-08
 ==========================================================================
     [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
 ==========================================================================

                 os = debian
          osversion = 6.0
       osmajversion = 6
               arch = x86_64
           trueuser = _fusionmasterx
   userprimarygroup = _fusionmasterx
        userhomedir = /home/_fusionmasterx
            rootdir = /usr/share/veil
            veildir = /var/lib/veil
          outputdir = /var/lib/veil/output
    dependenciesdir = /var/lib/veil/setup-dependencies
            winedir = /var/lib/veil/wine
          winedrive = /var/lib/veil/wine/drive_c
            gempath = Z:\var\lib\veil\wine\drive_c\Ruby187\bin\gem

 [ERROR]: Veil is only supported on Debian 8 (Jessie) or higher!
