### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by AmandeepMinz** [Veil-Framework/Veil#465]
## Any additional info you want to tell m
![Screenshot_2022-03-26_17_26_15](https://user-images.githubusercontent.com/100037111/160238292-8a9d65ed-9c89-4684-924a-5f4bd6a6294d.png)
e

**Comment by Nouf0** [comment]
I have the same ;(

**Comment by Nouf0** [comment]
I  have the same

**Comment by elaserus** [comment]
anyboody is can answer this quest ?

**Comment by SYC-00** [comment]
there is a simple commad you have to type;;

pip install pycrypto

and done everything will be fine.

**Comment by kwame-adepa** [comment]
> I have the same

fix it with this simple cmd
pip install pycrypto

**Comment by AmandeepMinz** [comment]
> there is a simple commad you have to type;;
> 
> pip install pycrypto
> 
> and done everything will be fine.

THANK YOU

**Comment by AmandeepMinz** [comment]
> there is a simple commad you have to type;;
> 
> pip install pycrypto
> 
> and done everything will be fine.

THANK YOU
