### ISSUE TITLE
error compile with ordance

### ISSUE THREAD

**Issue by gearcapitan** [Veil-Framework/Veil#51]
## Veil version

last
## OS Used - all info (architecture, linux flavor, etc)
kali linux x64

## Any additional info you want to tell me
![kali linux-2017-04-24-17-14-26](https://cloud.githubusercontent.com/assets/13740942/25361037/9a01b220-2911-11e7-97e6-99ff1a5714bf.png)

**Comment by ChrisTruncer** [comment]
Did you run the setup script?

**Comment by ChrisTruncer** [comment]
?

**Comment by gearcapitan** [comment]
yes, sorry sorry, the issue is fixed
