### ISSUE TITLE
Veil Install Error

### ISSUE THREAD

**Issue by sharkmoos** [Veil-Framework/Veil#53]
## Expected behavior
So the problem occurs here 
 [*] Adding x86 architecture to x86_64 system for Wine

W: The repository 'http://http.kali.org/kali kali Release' does not have a Release file.
W: The repository 'http://security.kali.org/kali-security kali/updates Release' does not have a Release file.
E: Failed to fetch http://http.kali.org/kali/dists/kali/non-free/source/Sources  404  Not Found
E: Failed to fetch http://security.kali.org/kali-security/dists/kali/updates/main/source/Sources  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
 [*] Installing Wine 32-bit and 64-bit binaries
E: Package 'wine32' has no installation candidate
 [ERROR] Failed to install Wine... Exit code: 100

Which it then moves on from to unpack objects

Then fails to install dependencies 
 [*] Installing dependencies
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package mingw-w64
E: Unable to locate package monodoc-browser
E: Unable to locate package monodevelop
E: Unable to locate package mono-mcs
E: Unable to locate package golang
E: Unable to locate package python3-pip
 [ERROR] Failed to install dependencies... Exit code: 100

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
Can you try a different mirror? I don't have anyone else reporting that issue, and this is a fairly standard package, so I believe it should work.

Chris

**Comment by ChrisTruncer** [comment]
Closing due to not hearing back
