### ISSUE TITLE
Veil Install error

### ISSUE THREAD

**Issue by dmcxbluecoder** [Veil-Framework/Veil#54]
Failed to install (Wine) Python 3.4.4... Exit code: 3
Bad hash for PyInstaller.tar.gz!
Failed to install (Wine) Ruby.exe... Exit code: 2
Bad hash for go153x64.tar.gz!

**Comment by ChrisTruncer** [comment]
Can you delete the veil cloned repo and recline down? This is likely an issue with something happening while you cloned the required files to your system.

**Comment by ChrisTruncer** [comment]
Closing due to not hearing back
