### ISSUE TITLE
native/backdoor_factory payload missing in Veil 3.0

### ISSUE THREAD

**Issue by james-88** [Veil-Framework/Veil#55]
Hello,

Just wanted to ask if there are any plans on adding native/backdoor_factory payload to veil 3.0, cause at the moment it is only available in Veil 2.X not in Veil 3.0.

Thanks

**Comment by ChrisTruncer** [comment]
Hi there,

Backdoor Factory is an awesome tool, and Veil is only able to leverage a very small piece of it. Due to this, I don't have any plans on adding it in. I recommend using the full tool itself.
