### ISSUE TITLE
Error while installing Veil 3.0

### ISSUE THREAD

**Issue by Burch909** [Veil-Framework/Veil#57]
Hi everybody, 
i was installing veil 3.0 in my kali linux operating system(x64, last version) and such as it happens with the veil-evasion installations i can't install python 'cause if i click on next button in the python installer session nothing happens. I don't know why it happens(or more correctly it not happens), if someone knows why please tell me. 
Here's all the input that gives me 

root@Burch:~/Desktop/Veil-master(1)/Veil-master/setup# sudo ./setup.sh -c
 ==========================================================================
                  Veil (Setup Script) | [Updated]: 2017-01-24
 ==========================================================================
  [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
 ==========================================================================

 [I] Kali Linux "2017.1" x86_64 detected...

 [*] Initializing package installation

 [*] Adding x86 architecture to x86_64 system for Wine

 [*] Installing Wine 32-bit and 64-bit binaries
E: Package 'wine32' has no installation candidate
 [ERROR] Failed to install Wine... Exit code: 100

Cloning into 'VeilDependencies'...
remote: Counting objects: 12, done.
remote: Total 12 (delta 0), reused 0 (delta 0), pack-reused 12
Unpacking objects: 100% (12/12), done.

 [*] ALERT: Existing Veil Wine environment detected at /root/.config/wine/veil

     Do you want to nuke it? (recommended) [Y/n]: y

 [*] Deleting existing Veil Wine environment...

 [*] Creating new Veil Wine environment in: /root/.config/wine/veil
 [*] Initializing Veil's Wine environment...
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
wine: '/root/.config/wine/veil' is a 32-bit installation, it cannot support 64-bit applications.
 [*] Veil Wine environment successfully created!

 [*] Installing dependencies
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package mingw-w64
E: Unable to locate package monodoc-browser
E: Unable to locate package monodevelop
E: Unable to locate package mono-mcs
E: Unable to locate package golang
E: Unable to locate package python3-pip
 [ERROR] Failed to install dependencies... Exit code: 100

Reading package lists... Done
Building dependency tree       
Reading state information... Done
metasploit-framework is already the newest version (4.14.10-0kali1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

 [*] Initializing Python dependencies installation...

 [*] Installing (Wine) Python...
 [*] Next -> Next -> Next -> Finished! ...Overwrite if prompt. Use default values.
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
err:ole:get_local_server_stream Failed: 80004002
err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
err:ole:get_local_server_stream Failed: 80004002
Could not load wine-gecko. HTML rendering will be disabled.
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/root/.config/wine/veil' has been updated.
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installr
![screenshot from 2017-05-13 15-51-58](https://cloud.githubusercontent.com/assets/28673834/26026504/421eb0f2-37f4-11e7-90d3-e776a6c30e22.png)

**Comment by Burch909** [comment]
If i click next button here it goes but then in the next frame nothing happens if i click the next button.

**Comment by ChrisTruncer** [comment]
Sorry, I'm really not sure what would cause that, but there wouldn't be anything in Veil's code which does that.

Please let me know if you are able to determine an issue, but my best advice would be to retry it.

**Comment by Burch909** [comment]
@ChrisTruncer I-ve tryed this a lot of times and thinking it was a system problem i-ve tried to reinstall kali.

**Comment by sigmax4** [comment]
Did u reinstall the Kali? I'm whit the same error.

**Comment by kiteruuneras** [comment]
why I have this problem.It can't finish
![image](https://user-images.githubusercontent.com/24788134/33200597-40f94d56-d130-11e7-9094-42be673a36a8.png)

**Comment by laser007** [comment]
Hi,
I too had the same issue. When i click next its not responding. Anyone got any fix for this.

thank you

**Comment by 1qa23** [comment]
Failed to install dependencies... Exit code: 100
 how to fix ?

**Comment by dcliss** [comment]
same error tried to install using fresh installation of  [https://imgur.com/a/riEDI](url)

Couldnt go past this 
Im using Kali Linux 64 bit VMware VM
ANy help wouold be much appreciated

**Comment by 4RP3ggIO** [comment]
I'm having the same problem on a fresh instance of Kali...

**Comment by rohanraju1** [comment]
I'm Having the same problem as if the installation never goes further and anybody does know a solution
Thank you for taking your time to read this!!!!!

**Comment by dzwiener** [comment]
I am having this same issue as well.

**Comment by dzwiener** [comment]
It is due to the OS being 64x. You require a 32-bit OS in order to install wine32. I tried this, but still encounter a few issues, but down from 7 to 2!

**Comment by IzranShaikh** [comment]
Same Error while Veil tries to install Python 
`001d:err:msi:ACTION_CallDllFunction failed to load dll L"C:\\users\\root\\Temp\\msi52c2.tmp" (193)`
I mean this Error must occur just see that path i'm using Kali in a VBox and Kali doesn't have partitions like windows C,D,etc it just have the most outer directory "/" which contains everything and see the error i've pasted i see while installing it founds for a path C:/Program Files/Python3 
how is Kali supposed to access C:Program Files this is not Windows then why the Python which Veil install tries to download Python which is for Windows not for Linux

**Comment by waihankan** [comment]
same problem,, unpacking objects cant finish and  says early EOF fatal: unpack-objects failed

**Comment by rx13** [comment]
The reason they're failing (for me at least) is because /run/user/0 does not exist.
`sudo mkdir /run/user/0` and then re-run `./config/setup.sh --force --silent`
resolved the issue on ParrotOS

**Comment by yessinemaalej** [comment]
Already up to date.


 [*] Installing Wine

 [*] Already have x86 architecture added...



 [*] Installing Wine 32-bit and 64-bit binaries (via APT)
it has stopped here and not progressing, what should I do ?

**Comment by praveenmoyili** [comment]
> Already up to date.
> 
> [*] Installing Wine
> 
> [*] Already have x86 architecture added...
> 
> [*] Installing Wine 32-bit and 64-bit binaries (via APT)
> it has stopped here and not progressing, what should I do ?

im aslo having the same problem trying since 1 weak ,pls help me .

**Comment by lonerdnsujsb** [comment]
![15893172439313683184423926176464](https://user-images.githubusercontent.com/65256043/81745106-d0266e80-94c1-11ea-95e1-c756600aa4ed.jpg)
It stuck on [*Installing Wine 32-bit and 64-bit binaries (via APT)*] i need some help bro what can i do after this i have tried to installed so many times but same error happened i have 64-bit windows 10 and i used virtualbox for installing kali linux

**Comment by kks12** [comment]
> 
> 
> ![15893172439313683184423926176464](https://user-images.githubusercontent.com/65256043/81745106-d0266e80-94c1-11ea-95e1-c756600aa4ed.jpg)
> It stuck on [_Installing Wine 32-bit and 64-bit binaries (via APT)_] i need some help bro what can i do after this i have tried to installed so many times but same error happened i have 64-bit windows 10 and i used virtualbox for installing kali linux

Bro I have also same problem did u got any solution to that

**Comment by lonerdnsujsb** [comment]
Bro install win first then run update then run veil without silent and force
