### ISSUE TITLE
Readline module missing

### ISSUE THREAD

**Issue by miguelkennedy** [Veil-Framework/Veil#58]
## Veil version
Latest (13th May, 2017)

## OS Used - all info (architecture, linux flavor, etc)
Kali Linux 2017.1 x64

## Pastebin link to error you are encountering (include console actions you took prior to error)
After running setup.sh -c successfully, when I try to run ./Veil.py I get the following error:
Traceback (most recent call last):
File "./Veil.py", line 7, in 
from lib.common import orchestra
File "/root/github/PayloadsGenerators/Veil/lib/common/orchestra.py", line 10, in 
import readline
ImportError: No module named 'readline'

## Any additional info you want to tell me

I posted this issue in https://github.com/Veil-Framework/Veil-Evasion by mistake. This is happening with Veil V3.

Thanks!

**Comment by ChrisTruncer** [comment]
Can you give any additional information on how you encountered this?

I just installed Veil 3 on Kali and can't seem to trigger this error.

**Comment by darryllane** [comment]
The import error `ImportError: No module named readline` seems to suggest the readline package isnt installed (oddly). May be as simple as `sudo pip install readline`

**Comment by ChrisTruncer** [comment]
That should do it @darryllane. However, I literally just re-downloaded Kali's latest ISO and built a VM and can't trigger this issue.

Additionally, when importing readline in python3 in default Kali, it works without error.

**Comment by ChrisTruncer** [comment]
Closing this due to testing on Kali out of the box, before Veil is installed, and seeing readline is installed by default.

Please make sure you are using Python 3.

**Comment by rnbaidya** [comment]
Traceback (most recent call last):
  File "./Veil.py", line 7, in <module>
    from lib.common import orchestra
  File "/opt/Veil/lib/common/orchestra.py", line 10, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'

got this issue how to solve it?

**Comment by jianchen21** [comment]
> Traceback (most recent call last):
> File "./Veil.py", line 7, in
> from lib.common import orchestra
> File "/opt/Veil/lib/common/orchestra.py", line 10, in
> import readline
> ModuleNotFoundError: No module named 'readline'
> 
> got this issue how to solve it?

I have same issue have you solve it yet ?

**Comment by heegong** [comment]
tes I have same issue how solve it?

**Comment by pavanbandla** [comment]
Traceback (most recent call last):
  File "./ghost", line 27, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'




this is the error i am getting can  u help me to fix this!!!!!!!

**Comment by NRTnarathip** [comment]
how fix that
use sudo pip3 install readline
not use pip install readline
because we run script python ghost version python3
we Should install readline at python3=pip3

**Comment by satishshsrma** [comment]
I saw one issue " Traceback (most recent call last):
File "./ghost", line 27, in
import readline
ModuleNotFoundError: No module named 'readline'

this is the error i am getting can u help me to fix this!!!!!!!" "

I solve this issue permanantly fix..
Solution :

First you opened your terminal in linux , and type this code " nano ./ghost "
Then from line number 27, delete import readline , but not row delete.
Again type " ./ghost "
Then one error show again which related from line number 37.
Then similarly delete all matter of line number 37, but not delete row.
Then type again " ./ghost "
Finaly u get ghost framwork clearly..
If your problem solve then 1 comment reply me  , and follow me.. 
Thanks..

**Comment by Aniket-malware** [comment]
> Traceback (most recent call last):
> File "./ghost", line 27, in
> import readline
> ModuleNotFoundError: No module named 'readline'
> 
> this is the error i am getting can u help me to fix this!!!!!!!

use command : pip install readline
