### ISSUE TITLE
Install script wants to install python for windows

### ISSUE THREAD

**Issue by binarymist** [Veil-Framework/Veil#6]
In running the install script, I get a pop up... Python for Windows: Select Destination Directory. Wants to install to C:\Python27\ I thought I was on kali, but oh well. I select Yes cos I have no idea where you intend this to go. Then I get: C:\Python27\ exists. Are you sure you want to overwrite existing files? WTF? I don't have C:\Python27\

Just agreed to it anyway.
Now I've got:
[\*] Downloading Python Setup Files From http://www.veil-framework.com
[\*] Uncompressing Setup Archive
Archive: requiredfiles.zip
replace distutils/spawn.py? [y]yes, [n]o, [A]ll, [N]one, [r]ename: 

What is the correct response?
Went with A.

Possibly a little more insight around what to expect on the install, what's actually going down and what responses should be and why may be helpful for others in the future?
I'm happy to read some source, but reading the entire thing just to get through an install can get a bit cumbersome.

Thanks.

**Comment by binarymist** [comment]
Any response other than just closed?

**Comment by ChrisTruncer** [comment]
We've already created a significant number of big posts, and videos, on how to install veil-evasion and use it. Please review them.  If you don't understand why you have c:\python27, please do some searching and look it up.

**Comment by binarymist** [comment]
Ah, cool! Cheers for that. A we typo possibly: "And when you his this screen, click Yes" should be "And when you hit this screen, click Yes"?

Thanks.
