### ISSUE TITLE
autoit error compile with reverse_https

### ISSUE THREAD

**Issue by gearcapitan** [Veil-Framework/Veil#60]
## Veil version
last

## OS Used - all info (architecture, linux flavor, etc)

kali linux last
![kali linux-2017-05-16-18-36-09](https://cloud.githubusercontent.com/assets/13740942/26132594/04975f0c-3a67-11e7-8e30-e6eab0227cf7.png)
![kali linux-2017-05-16-18-36-20](https://cloud.githubusercontent.com/assets/13740942/26132596/0498dda0-3a67-11e7-8e9c-b8d5c45f5fb0.png)
![kali linux-2017-05-16-18-36-34](https://cloud.githubusercontent.com/assets/13740942/26132597/049ba62a-3a67-11e7-8869-341bc1d2976a.png)
![kali linux-2017-05-16-18-36-52](https://cloud.githubusercontent.com/assets/13740942/26132595/0498033a-3a67-11e7-82ca-4b6b0110e998.png)

**Comment by ChrisTruncer** [comment]
Thanks for submitting this, I'll check it out

**Comment by ChrisTruncer** [comment]
This is a line length limitation with AutoIt. For the team being, you won't be able to use that specific payload with AutoIt. I would suggest using a different language.

**Comment by ChrisTruncer** [comment]
Just pushed a fix, this should now be good for you!
