### ISSUE TITLE
Missing Package on Ubuntu (mono-mcs)

### ISSUE THREAD

**Issue by leesoh** [Veil-Framework/Veil#61]
## Veil version
3

## OS Used - all info (architecture, linux flavor, etc)
Ubuntu 16.10 x64

## Pastebin link to error you are encountering (include console actions you took prior to error)
Error generating CS payload

## Expected behavior
Payload generates successfully

## Any additional info you want to tell me
CS payload generation depends on `mono-mcs` package, which is not installed either by `setup.sh` or present by default. Will submit a PR when I get cycles. Opening an issue in case you beat me to it.

**Comment by leesoh** [comment]
Hmmm. Digging into `setup.sh` it looks like this should have been installed (https://github.com/Veil-Framework/Veil/blob/master/setup/setup.sh#L288). I'll do a bit more digging.

**Comment by ChrisTruncer** [comment]
Find anything else about this?

**Comment by ChrisTruncer** [comment]
closing since it is in setup script. Let me know if you discover an issue and this can be re-opened
