### ISSUE TITLE
Invalid Package on Ubuntu (wine)

### ISSUE THREAD

**Issue by leesoh** [Veil-Framework/Veil#62]
## Veil version
3

## OS Used - all info (architecture, linux flavor, etc)
Ubuntu 16.10

## Pastebin link to error you are encountering (include console actions you took prior to error)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package wine is a virtual package provided by:
  wine-stable 1.8.5-1ubuntu2
  wine-development 1.9.20-1ubuntu2
You should explicitly select one to install.

E: Package 'wine' has no installation candidate

## Expected behavior
Wine installs like a champ.

## Any additional info you want to tell me
Simple fix - replace `wine` with `wine-stable` (https://github.com/Veil-Framework/Veil/blob/master/setup/setup.sh#L159).

**Comment by ChrisTruncer** [comment]
I need to check, but I believe the reason it isn't there is because I am specifically supporting LTS, vs the latest version. This should work on LTS

**Comment by leesoh** [comment]
You're right: https://packages.ubuntu.com/xenial/wine

Sorry about that!
