### ISSUE TITLE
i have successfully installed veil3.0 but cant get it to work. i cant find the list of payloads. i have tried many commands but still cant select use either ordnance or evasion in kali linux

### ISSUE THREAD

**Issue by JuliRash** [Veil-Framework/Veil#74]
## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
Please fill out the required info

**Comment by JuliRash** [comment]
Veil Version 3.0
os and Architecture: Kali Rolling linux x86_64
installed from github by running the command  sudo ./setup.sh -c
i am not getting any error except i cannot select any of the options i will get redirected to the first part https://pastebin.com/kEbsfVQH would like to know what i am doing wrong. Thank you

**Comment by ChrisTruncer** [comment]
There needs no bug, the tool is running.

**Comment by JuliRash** [comment]
so how do i get all the payloads is there any official documentation thanks
