### ISSUE TITLE
Veil Evasion 0 Tools Loaded !! 

### ISSUE THREAD

**Issue by drspyro1911** [Veil-Framework/Veil#76]
## OS Used - Kali Linux 2.0

After Cloning Veil 3.0 from Github and Finishing setup script and update configuration 
i started the Veil.py it gives me :

===============================================================================
                             Veil | [Version]: 3.1.2
===============================================================================
      [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
===============================================================================

Main Menu

	0 tools loaded

**Comment by ChrisTruncer** [comment]
Can you use Kali rolling? This shouldn't occur

**Comment by ChrisTruncer** [comment]
closing due to no response
