### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Captain05** [Veil-Framework/Veil#78]
## OS Used - all info (architecture, linux flavor, etc)
parrot

## How did you install Veil? (Apt, Clone from Github, etc.)
github

## Did you run the setup script?
yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
python Veil.py
Traceback (most recent call last):
  File "Veil.py", line 5, in <module>
    from lib.common import helpers
ImportError: No module named lib.common

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
Sorry, but I don't support parrot
