### ISSUE TITLE
Kali Linux 64 bit error creating executables with Evasion

### ISSUE THREAD

**Issue by thricegr8est** [Veil-Framework/Veil#8]
When trying to create any payload so far tested (~10), immediately after selecting Pyinstaller as compilation method, I get a several - "err:module:import_dll Library pywintypes27.dll (which is needed by L"C:\\Python27\\lib\\site-packages\\win32\\win32api.pyd") not found" errors, followed by complaints of missing pywin32. 

I am on 64bit Kali inside VM Workstation 11.0 using Evasion Version 2.21.3. I am unable to create any payloads with the most updated version of Kali. (updated and upgraded)

uname -a: Linux kali 3.18.0-kali3-amd64 #1 SMP Debian 3.18.6-1~kali2 (2015-03-02) x86_64 GNU/Linux

See Pastebin for full output:
http://pastebin.com/GvD6AnDh

**Comment by ChrisTruncer** [comment]
Could you try reinstalling this again?  I just tested on a fresh/clean Kali install, and everything appears to install correctly.  I just generated a python based payload and it worked.

Try doing a git pull, and potentially reinstalling the dependencies (or testing on a different VM).

**Comment by Skycrazy** [comment]
Also having the same issue, exact same errors. 
and recieve
 [!] Internal error #2. Please run /Veil-Evasion-master/config/update.py manually

which when run results in 0 payloads loaded in Veil

Running on 32 bit fresh install of kali, fully updated.

**Comment by ChrisTruncer** [comment]
Again, can you try to test on a different VM?  I had just tested the install on a freshly downloaded Kali VM, and I was able to install and generate a payload without a problem.

**Comment by Skycrazy** [comment]
Hi, thanks for replying. I'm not running on a Vm. I actually had this problem a couple of days ago and managed to fix the issue. However today decided it was time for a reinstall of kali as i was getting cluttered up. Ive hit a brick wall as to how i fixed it a few days ago, i just have no payloads loaded in veil after the update.py.

**Comment by thricegr8est** [comment]
Everything is good to go. Thank you. Close issue :) I just ended up downloading entire new image.

**Comment by thricegr8est** [comment]
@Skycrazy I was getting those errors as well. I did check and there is a new VMware image for Kali, version "C". Even after a dist-upgrade on my previous version nothing was working. I downloaded the new image and updated and now everything is working.

**Comment by thricegr8est** [comment]
I believe there are compiler issues haunting somewhere in the most recent versions of Kali. I am now having trouble using hyperion. Getting the same errors when trying to access Wine complaining about missing dlls. I tried to statically link them but to no avail.
