### ISSUE TITLE
"generate " command doesn't work while "generate" does

### ISSUE THREAD

**Issue by BaraSec** [Veil-Framework/Veil#8]
## Veil-Evasion version

Vel 3.0

## OS Used - all info (architecture, linux flavor, etc)

Kali Linux 64-bit

## Pastebin link to error you are encountering (include console actions you took prior to error)

"generate " command doesn't work while "generate" does, same with "options " and "options", this happened after choosing a payload (use 28).

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
While this is a fairly minor issue, I did get a fix pushed, so it is now in master.

Thanks

**Comment by BaraSec** [comment]
Thanks.

Can you tell me how issues like this gets fixed in the code perspective ?
