### ISSUE TITLE
Can't get past menu screen.

### ISSUE THREAD

**Issue by Bry-fi** [Veil-Framework/Veil#80]
## Veil version
3.1.2
## OS Used - all info (architecture, linux flavor, etc)
Kali linux rolling amd64
## How did you install Veil? (Apt, Clone from Github, etc.)
Git clone

## Did you run the setup script?

 ./setup.sh -c
## Pastebin link to error you are encountering (include console actions you took prior to error)
https://pastebin.com/T40BKXCZ

## Expected behavior
Listing of payloads

## Any additional info you want to tell me
It worked flawlessly before but ever since the update, I haven't tested it and I think it silently broke.

**Comment by ChrisTruncer** [comment]
There is a wiki for this
