### ISSUE TITLE
Wont work properly. Not loading Payloads

### ISSUE THREAD

**Issue by boutzamat** [Veil-Framework/Veil#81]
## Veil version
Latest version. Cloned today

## OS Used - all info (architecture, linux flavor, etc)
Kali Linux (latest version, updated today)

## How did you install Veil? (Apt, Clone from Github, etc.)
Clone

## Did you run the setup script?
Yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
When running Veil, i select "list" -> "Evasion". Still shows "2 items" instead of payloads.
Same happens if i type "use" -> "Evasion" instead of showing payloads, it still says "2 items".

## Expected behavior
Expected to load Payloads.

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
Can you please do this in your console and put that on pastebin so I can review it?

Thanks

**Comment by ChrisTruncer** [comment]
?

**Comment by boutzamat** [comment]
Sure, i will do it when i come home later tonight.

**Comment by boutzamat** [comment]
Im home again. What do you want me to type in the console?

**Comment by ChrisTruncer** [comment]
I don't have the time to provide the exact commands. Please just do exactly what you did to run into an issue in the first place

**Comment by boutzamat** [comment]
I got it working. I simply didnt specify which tool to use. The method is suppose to be "use 1/2" - i thought that i should just input "use" then select 1 or 2 by pressing one of the keys.

Feeling pretty stupid here.

Thank you for your time, and sorry for the stupid question.
Marking as closed.

**Comment by leiferdjango** [comment]
@boutzamat dont feel stupid Im searching for hours trying to get all the payloads, but there are all the time in 1 and 2 options
