### ISSUE TITLE
Option to use a SSL cert for meterpreter/rev_https

### ISSUE THREAD

**Issue by drale2k** [Veil-Framework/Veil#82]
## Veil version
3.1.2

## OS Used - all info (architecture, linux flavor, etc)
Kali

## How did you install Veil? (Apt, Clone from Github, etc.)
Clone from github

## Did you run the setup script?
yes

## Expected behavior
powershell/meterpreter/rev_https.py to support a custom SSL cert 

## Any additional info you want to tell me

Is it possible to supply a self generated SSL cert to "powershell/meterpreter/rev_https.py" ? Msfvenom allows this for example. It is very useful to bypass AVs

**Comment by ChrisTruncer** [comment]
Does this require the cert to be embedded into the powershell script, or just set on the handler side?

**Comment by drale2k** [comment]
When generating the payload with MSfvenom, i use the cert on the handler side as well as when generating the payload, using the "HandlerSSLCert=cert.pem" option from Msfvenom

**Comment by ChrisTruncer** [comment]
So i just tested and reviewed the code output from MSFVenom when providing the HandlerSSLCert parameter, and it looks like it is actually the same code when you both provide that flag and when you don't. This leads me to believe that it doesn't need to be embedded in the payload, it's only required server side.

If you try to use a veil payload with a metasploit handler where you specify the SSL cert, does it work?

**Comment by ChrisTruncer** [comment]
Checking in again?
