### ISSUE TITLE
0 tools loaded

### ISSUE THREAD

**Issue by Fireplop** [Veil-Framework/Veil#83]
## Veil version
3.1.2

## OS Used - all info (architecture, linux flavor, etc)
Linux kali 4.9.0-kali4-amd64 #1 SMP Debian 4.9.30-2kali1 (2017-06-22) x86_64 GNU/Linux

## How did you install Veil? (Apt, Clone from Github, etc.)
Clone from Github

## Did you run the setup script?
Of course

## Pastebin link to error you are encountering (include console actions you took prior to error)
./Veil/Veil.py
Having 0 tools loaded
This is not happening when launched from Veil directory directly (./Veil.py instead of ./Veil/Veil.py) 
## Expected behavior
Having 2 tools loaded successfully

## Any additional info you want to tell me
Thanks for this framework. Hope you have a solution on this issue ;)

**Comment by ChrisTruncer** [comment]
You just need to run it from the Veil directory, thanks

**Comment by Fireplop** [comment]
That's obvious, but I'm running it from my own script which is not located on the Veil directory ... :/

**Comment by ChrisTruncer** [comment]
Sorry, but this response from you does not make me want to provide any help. Considering I work on this on my own time, I'd prefer to not help individuals who can't respond respectfully.
