### ISSUE TITLE
GO payload can't rub

### ISSUE THREAD

**Issue by myasir2** [Veil-Framework/Veil#84]
## Veil version 3.0

So i generated a go/meterpreter/rev_https payload but when i try to run it on my Windows 8/10 machines, i get an error saying that the app can't run. I know that in msfvenom you can specify if you want to generate a x64 payload and that fixed my problem when i used msfvenom to generate a backdoor but i can't get it to work with veil. I was successfully able to generate and run a python payload however but that one kept getting blocked by Windows defender. Any tips? I'm fairly new to all of this

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
There's odd issues with Golang on Windows 10, and I think that is where your issues is. Go DOES work on Windows 7, but when moving the same exact payload to a windows 10 system, it encounters an issue.

I don't know the exact reason for this unfortunately, but I think that is likely the issue.

**Comment by myasir2** [comment]
Oh i see, is there any difference between using a GO payload compared to the python? Any functionality or processing speed or anything like that type of difference?

**Comment by ChrisTruncer** [comment]
Not that I know of. I am really unsure why this happens, and I've talked with a couple people about it and no one else seems to know the issue either.

**Comment by myasir2** [comment]
Ah, well its good to know that you're aware of it. Thanks for the help!

**Comment by ChrisTruncer** [comment]
No problem. Sorry that at the moment I don't have more information, but it's stumping a couple different minds right now too :)
