### ISSUE TITLE
Need some tips

### ISSUE THREAD

**Issue by myasir2** [Veil-Framework/Veil#86]
## Veil version
3.0

## OS Used - all info (architecture, linux flavor, etc)
Windows 8/10
Kali Linux

## How did you install Veil? (Apt, Clone from Github, etc.)
GitHub

## Any additional info you want to tell me

Every single payload i generate is getting detected by windows defender unfortunately. Is there any tips or resources you can provide to generate a much more hidden or encrypted backdoor so that it doesn't get detected by Windows Defender? I am doing research myself but i thought i could get some more tips

**Comment by ChrisTruncer** [comment]
I'm using defender and am not running into the same issues. Please also use non-default values.
