### ISSUE TITLE
Running Veil.py fails due to issues with gamemaker.py

### ISSUE THREAD

**Issue by funkychicken1** [Veil-Framework/Veil#88]
## Veil version
3.1.2 (pulled 20170726)

## OS Used - all info (architecture, linux flavor, etc)
kali2

## How did you install Veil? (Apt, Clone from Github, etc.)
clone from github

## Did you run the setup script?
yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
running Veil.py fails
gamemaker.py, lines 715 - 720 need indenting

## Expected behavior
once fixed, Veil ran fine.

**Comment by ChrisTruncer** [comment]
fix is pushed, thanks!
