### ISSUE TITLE
manjaro error :\

### ISSUE THREAD

**Issue by ghost** [Veil-Framework/Veil#9]
## OS Used - all info (architecture, linux flavor, etc)
manjaro 16.10.3 
kernel: Linux 4.10

# Error:

└> sudo ./setup/setup.sh 
[sudo] password di manjaro: 
 ==========================================================================
                  Veil (Setup Script) | [Updated]: 2017-01-24
 ==========================================================================
  [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
 ==========================================================================

 [ERROR] Unable to determine OS information. Exiting...

**Comment by ChrisTruncer** [comment]
Sorry, but I don't support manjero. Please use Debian in order to use Veil. However, Kali and Ubuntu should also work.

**Comment by ghost** [comment]
I made some corrections for working veil on manjaro.
Just change this file in Veil/config/setup.sh
[setup.txt](https://github.com/Veil-Framework/Veil/files/2198905/setup.txt)
