### ISSUE TITLE
Arch Linux problems with python

### ISSUE THREAD

**Issue by alexej-okelloj** [Veil-Framework/Veil#9]
I've tried to install Veil Framework on Arch Linux, however ./Install.sh -c ended up with quite a few syntax errors and later I realised the installer used python 3.5 and its libraries. So, the question is has anyone encountered such problem? Is there a way to uninstall the framework?

**Comment by ChrisTruncer** [comment]
This doesn't use python 3.5.  Also, this really shouldn't impact you since the script is apt based.

**Comment by p403nix** [comment]
Please is there a solution for this, we arch linux users can't seem to install this framework without hitch...

**Comment by byt3bl33d3r** [comment]
@p403nix use virtualenvs & virtualenvwrapper. You can find good docs on how to use them just a google away. (I use Arch Linux and got Veil to work pretty smoothly)
Cheers

**Comment by p403nix** [comment]
@byt3bl33d3r i have install them from AUR, thanks for the help i will google how to use them now, Am grateful

**Comment by p403nix** [comment]
@byt3bl33d3r i tried running the setup.sh -c on virtualenvs  but i still get the same error

**Comment by p403nix** [comment]
@byt3bl33d3r (venv) [adz@Adz ~]$ cd Veil-Evasion/
(venv) [adz@Adz Veil-Evasion]$ cd setup
(venv) [adz@Adz setup]$ setup.sh -c
bash: setup.sh: command not found

**Comment by ChrisTruncer** [comment]
I'm locking this due to Arch not being an officially supported OS.
