### ISSUE TITLE
"2tools are loaded

### ISSUE THREAD

**Issue by Anonymous1205** [Veil-Framework/Veil#90]
## Veil version
3.0

## OS Used - all info (architecture, linux flavor, etc)
Parrot 3.7 - JollyRoger x86_64

## How did you install Veil? (Apt, Clone from Github, etc.)
git clone from Github
cd Veil\
sudo ./setup.sh -c

## Did you run the setup script?
Yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
https://pastebin.com/NiZdRsf3

## Expected behavior
Maybe he can't find my Metasploit path...
I think that is because i copy past the wrong path of myMetasploit

## Any additional info you want to tell me
run the update.py 5 or 6 time wih different path of my Metasploit

**Comment by ChrisTruncer** [comment]
Please don't replace duplicates, and please just provide the correct path
