### ISSUE TITLE
cant generate pythoninstaller payload

### ISSUE THREAD

**Issue by barmaanb1383** [Veil-Framework/Veil#94]
## Veil version
3.1.2
## OS Used - all info (architecture, linux flavor, etc)
kali linux
## How did you install Veil? (Apt, Clone from Github, etc.)
git clone 

## Did you run the setup script?
yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
[?] How would you like to create your payload executable?

     1 - Pyinstaller (default)
     2 - Py2Exe

 [>] Please enter the number of your choice: 1
cp: cannot create regular file '/opt/veil/PyInstaller-3.2.1//PyInstaller/bootloader/Windows-32bit/runw.exe': No such file or directory

 [!] ERROR: Can't find python.exe in /root/.config/wine/veil/drive_c/Python34/
 [!] ERROR: Make sure the python.exe binary exists before using PyInstaller.

## Expected behavior
cant generate pythoninstaller payload

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
Can you see if you have that directory at all? Veil should check for that in the setup script to validate it exists

**Comment by ChrisTruncer** [comment]
can you?

**Comment by barmaanb1383** [comment]
Thabk you i re install veil
