### ISSUE TITLE
Veil 3 doesnt work after Veil 2

### ISSUE THREAD

**Issue by alcomic** [Veil-Framework/Veil#96]
## Veil version
Last from github (3.1.2?)

## OS Used - all info (architecture, linux flavor, etc)
Kali 2017.1

## How did you install Veil? (Apt, Clone from Github, etc.)
apt-get -y install git
git clone https://github.com/Veil-Framework/Veil.git
cd Veil/
cd setup
sudo ./setup.sh -c

## Did you run the setup script?
Yes (./setup.sh -c)

## Pastebin link to error you are encountering (include console actions you took prior to error)
https://pastebin.com/QCDPcwdc

## Any additional info you want to tell me
I installed last version of https://github.com/Veil-Framework/Veil-Evasion ( 2.28.2 ) and it worked well. After it I tried to install Veil 3 and after installing I cant run Veil 2 and Veil 3 (before installing Veil3, Veil 2 worked properly)

**Comment by ChrisTruncer** [comment]
Fix is merged, thanks!
