### ISSUE TITLE
can't Run Veil 3.0 

### ISSUE THREAD

**Issue by steam345** [Veil-Framework/Veil#97]
## Veil version
3.0

## OS Used - all info (architecture, linux flavor, etc)
Kali Linux 2017
## How did you install Veil? (Apt, Clone from Github, etc.)
git clone

## Did you run the setup script?
yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
https://pastebin.com/Dqnn3cpt

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
This is a duplicate issue, fix is merged
